import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';

const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
const enc=new TextEncoder(),dec=new TextDecoder();
const b64u=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const fromB64u=(value:string)=>Uint8Array.from(atob(value.replaceAll('-','+').replaceAll('_','/')+'='.repeat((4-value.length%4)%4)),c=>c.charCodeAt(0));
async function key(raw:string,usage:KeyUsage[]){const digest=await crypto.subtle.digest('SHA-256',enc.encode(raw));return crypto.subtle.importKey('raw',digest,'AES-GCM',false,usage)}
async function decrypt(ciphertext:string,iv:string,secret:string){const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromB64u(iv)},await key(secret,['decrypt']),fromB64u(ciphertext));return JSON.parse(dec.decode(plain))}
async function encrypt(tokens:unknown,secret:string){const iv=crypto.getRandomValues(new Uint8Array(12));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(secret,['encrypt']),enc.encode(JSON.stringify(tokens)));return{ciphertext:b64u(new Uint8Array(cipher)),iv:b64u(iv)}}

Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed.'},405);
 const url=Deno.env.get('SUPABASE_URL')??'',publishable=Deno.env.get('SUPABASE_ANON_KEY')??Deno.env.get('SUPABASE_PUBLISHABLE_KEY')??'',secretKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')??Deno.env.get('SUPABASE_SECRET_KEY')??'',tokenSecret=Deno.env.get('INTEGRATION_TOKEN_ENCRYPTION_KEY')??'';
 if(!url||!publishable||!secretKey||!tokenSecret)return json({error:'Calendar sync service is not configured.'},503);
 const authorization=req.headers.get('Authorization')??'',userClient=createClient(url,publishable,{global:{headers:{Authorization:authorization}},auth:{persistSession:false}}),admin=createClient(url,secretKey,{auth:{persistSession:false}});const {data:{user}}=await userClient.auth.getUser();if(!user)return json({error:'Authentication required.'},401);
 const body=await req.json().catch(()=>({})),businessId=String(body.businessId??''),connectionId=String(body.connectionId??'');const {data:membership}=await userClient.from('business_members').select('business_id').eq('business_id',businessId).eq('user_id',user.id).maybeSingle();if(!membership)return json({error:'Business access unavailable.'},403);
 const {data:connection}=await admin.from('calendar_connections').select('*,integration_connections!inner(status)').eq('id',connectionId).eq('business_id',businessId).maybeSingle();if(!connection||connection.integration_connections.status!=='CONNECTED'||!connection.sync_enabled)return json({error:'Active calendar connection not found.'},404);if(connection.provider!=='GOOGLE_CALENDAR')return json({error:'Microsoft calendar sync is not activated in this release.'},501);
 const {data:credential}=await admin.from('integration_oauth_credentials').select('token_ciphertext,token_iv,token_expires_at').eq('connection_id',connectionId).eq('business_id',businessId).maybeSingle();if(!credential)return json({error:'Calendar credentials need reconnection.'},409);
 let tokens=await decrypt(credential.token_ciphertext,credential.token_iv,tokenSecret);let accessToken=String(tokens.access_token??'');
 if(!accessToken||!credential.token_expires_at||new Date(credential.token_expires_at).getTime()<Date.now()+60_000){const clientId=Deno.env.get('GOOGLE_CLIENT_ID')??'',clientSecret=Deno.env.get('GOOGLE_CLIENT_SECRET')??'';if(!tokens.refresh_token||!clientId||!clientSecret)return json({error:'Calendar credentials need reconnection.'},409);const refresh=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:clientId,client_secret:clientSecret,refresh_token:String(tokens.refresh_token),grant_type:'refresh_token'})});if(!refresh.ok){await admin.from('integration_connections').update({status:'NEEDS_ATTENTION',last_error_code:'TOKEN_REFRESH_FAILED'}).eq('id',connectionId);return json({error:'Calendar authorization expired. Reconnect it.'},409)}const next=await refresh.json();tokens={...tokens,...next,refresh_token:tokens.refresh_token};accessToken=String(next.access_token);const encrypted=await encrypt(tokens,tokenSecret);await admin.from('integration_oauth_credentials').update({token_ciphertext:encrypted.ciphertext,token_iv:encrypted.iv,token_expires_at:new Date(Date.now()+Number(next.expires_in??3600)*1000).toISOString(),updated_at:new Date().toISOString()}).eq('connection_id',connectionId)}
 const headers={Authorization:'Bearer '+accessToken,'Content-Type':'application/json'},calendarId=encodeURIComponent(connection.provider_calendar_id||'primary');let imported=0,exported=0;
 if(connection.import_busy_time){const timeMin=new Date(Date.now()-30*86400000).toISOString(),timeMax=new Date(Date.now()+180*86400000).toISOString();const endpoint=`https://www.googleapis.com/calendar/v3/calendars/${calendarId}/events?singleEvents=true&showDeleted=true&timeMin=${encodeURIComponent(timeMin)}&timeMax=${encodeURIComponent(timeMax)}&maxResults=2500&fields=items(id,status,transparency,start,end,updated)`;const response=await fetch(endpoint,{headers});if(!response.ok)return json({error:'Google Calendar import failed.'},502);const payload=await response.json();for(const event of payload.items??[]){const start=event.start?.dateTime??(event.start?.date?event.start.date+'T00:00:00Z':null),end=event.end?.dateTime??(event.end?.date?event.end.date+'T00:00:00Z':null);if(!event.id||!start||!end)continue;const status=event.status==='cancelled'||event.transparency==='transparent'?'CANCELLED':'BUSY';await admin.from('external_calendar_busy_blocks').upsert({business_id:businessId,connection_id:connectionId,external_event_id:event.id,starts_at:start,ends_at:end,status,privacy:'OPAQUE',safe_label:'Busy',provider_updated_at:event.updated??null,synced_at:new Date().toISOString()},{onConflict:'business_id,connection_id,external_event_id'});imported++}}
 if(connection.export_crm_bookings){const {data:bookings}=await admin.from('crm_bookings').select('id,service_label,scheduled_start,scheduled_end,location_label,status,updated_at').eq('business_id',businessId).gte('scheduled_end',new Date(Date.now()-30*86400000).toISOString()).neq('status','NO_SHOW');for(const booking of bookings??[]){const {data:link}=await admin.from('calendar_event_links').select('id,external_event_id,last_synced_at').eq('business_id',businessId).eq('connection_id',connectionId).eq('crm_booking_id',booking.id).maybeSingle();const event={summary:booking.service_label||'Everest booking',start:{dateTime:booking.scheduled_start},end:{dateTime:booking.scheduled_end},location:booking.location_label??undefined,status:booking.status==='CANCELLED'?'cancelled':'confirmed',extendedProperties:{private:{everest_crm_booking_id:booking.id}}};let externalId=link?.external_event_id;if(link){if(new Date(link.last_synced_at).getTime()>=new Date(booking.updated_at).getTime())continue;const response=await fetch(`https://www.googleapis.com/calendar/v3/calendars/${calendarId}/events/${encodeURIComponent(externalId)}`,{method:'PATCH',headers,body:JSON.stringify(event)});if(!response.ok)continue}else{const response=await fetch(`https://www.googleapis.com/calendar/v3/calendars/${calendarId}/events`,{method:'POST',headers,body:JSON.stringify(event)});if(!response.ok)continue;externalId=(await response.json()).id}await admin.from('calendar_event_links').upsert({business_id:businessId,connection_id:connectionId,external_event_id:externalId,crm_booking_id:booking.id,sync_direction:'EXPORTED',last_external_updated_at:new Date().toISOString(),last_synced_at:new Date().toISOString()},{onConflict:'business_id,connection_id,external_event_id'});exported++}}
 await admin.from('calendar_connections').update({last_synced_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',connectionId).eq('business_id',businessId);return json({synced:true,importedBusyBlocks:imported,exportedCrmBookings:exported});
});
