import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import type { Profile } from '@/lib/types';

type AccountRoute = '/requests' | '/quotes' | '/bookings' | '/orders' | '/messages' | '/reviews' | '/notifications' | '/business-dashboard' | '/settings';
const links: ReadonlyArray<readonly [string, AccountRoute]> = [['Requests','/requests'],['Quotes','/quotes'],['Bookings','/bookings'],['Orders','/orders'],['Messages','/messages'],['Reviews','/reviews'],['Notifications','/notifications'],['Business dashboard','/business-dashboard'],['Settings','/settings']];

export default function Account() {
  const [profile,setProfile]=useState<Profile|null>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState('');
  useEffect(()=>{let active=true;(async()=>{try{const [{supabaseConfigured},{getProfile}]=await Promise.all([import('@/lib/supabase'),import('@/lib/marketplace')]);if(!active)return;if(!supabaseConfigured){setLoading(false);return;}const p=await getProfile();if(active)setProfile(p);}catch(e){if(active)setError(e instanceof Error?e.message:'Unable to load account.');}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[]);
  async function logout(){try{const {signOut}=await import('@/lib/auth');await signOut();setProfile(null);router.replace('/');}catch(e){setError(e instanceof Error?e.message:'Could not sign out. Please try again.');}}
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><View style={s.top}><Pressable onPress={()=>router.back()} accessibilityLabel="Go back"><Ionicons name="arrow-back" size={23}/></Pressable><Text style={s.topTitle}>Account</Text><View style={{width:23}}/></View>{loading?<ActivityIndicator style={{marginTop:50}}/>:profile?<><View style={s.profile}><View style={s.avatar}><Ionicons name="person-outline" size={27}/></View><Text style={s.name}>{profile.full_name||'Everest Local customer'}</Text><Text style={s.copy}>{profile.phone||profile.city?`${profile.suburb||''}${profile.city?`, ${profile.city}`:''}`:'Your account is ready.'}</Text></View>{links.map(([label,path])=><Pressable style={s.row} key={label} onPress={()=>router.push(path)}><Text style={s.rowText}>{label}</Text><Ionicons name="chevron-forward" size={18} color="#777"/></Pressable>)}<Pressable onPress={()=>void logout()} style={s.logout}><Text style={s.logoutText}>SIGN OUT</Text></Pressable></>:<View style={s.profile}><View style={s.avatar}><Ionicons name="person-outline" size={27}/></View><Text style={s.name}>Welcome to Everest Local</Text><Text style={s.copy}>{error||'Sign in or create an account to manage requests, bookings, orders and messages.'}</Text><Pressable onPress={()=>router.push('/auth')} style={s.button}><Text style={s.buttonText}>SIGN IN / CREATE ACCOUNT</Text></Pressable></View>}{!!error&&!!profile&&<Text style={s.error}>{error}</Text>}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:40},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},topTitle:{fontSize:17,fontWeight:'800'},profile:{marginTop:28,backgroundColor:'#151515',borderRadius:23,padding:24,alignItems:'center'},avatar:{width:64,height:64,borderRadius:32,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},name:{color:'#fff',fontSize:20,fontWeight:'800',marginTop:15,textAlign:'center'},copy:{color:'#aaa',fontSize:13,lineHeight:20,textAlign:'center',marginTop:7},button:{backgroundColor:'#fff',borderRadius:13,paddingVertical:13,paddingHorizontal:16,marginTop:18},buttonText:{fontSize:11,fontWeight:'800'},row:{height:58,borderBottomWidth:1,borderBottomColor:'#e4e1da',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},rowText:{fontSize:14,fontWeight:'700'},logout:{marginTop:22,height:50,borderRadius:14,borderWidth:1,borderColor:'#d8d3ca',alignItems:'center',justifyContent:'center'},logoutText:{fontSize:11,fontWeight:'900'},error:{color:'#b42318',fontSize:12,marginTop:12,textAlign:'center'}});