import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import type { Profile } from '@/lib/types';
import type { AccessContext } from '@/lib/access';

type AccountRoute='/requests'|'/quotes'|'/bookings'|'/orders'|'/messages'|'/reviews'|'/notifications'|'/settings';
const links:ReadonlyArray<readonly [string,AccountRoute]>=[['Requests','/requests'],['Quotes','/quotes'],['Bookings','/bookings'],['Orders','/orders'],['Messages','/messages'],['Reviews','/reviews'],['Notifications','/notifications'],['Settings','/settings']];

export default function Account(){
 const [profile,setProfile]=useState<Profile|null>(null);const [access,setAccess]=useState<AccessContext|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{let active=true;(async()=>{try{const {supabase,supabaseConfigured}=await import('@/lib/supabase');const {getProfile}=await import('@/lib/marketplace');const {getMyAccessContext}=await import('@/lib/access');if(!supabaseConfigured){if(active)setLoading(false);return;}const {data:{user}}=await supabase.auth.getUser();if(!user){if(active)setLoading(false);return;}const [p,a]=await Promise.all([getProfile(),getMyAccessContext()]);if(active){setProfile(p);setAccess(a);}}catch(e){if(active)setError(e instanceof Error?e.message:'We could not load your account right now.')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
 async function logout(){try{const {signOut}=await import('@/lib/auth');await signOut();setProfile(null);router.replace('/')}catch{setError('Could not sign out. Please try again.')}}
 const businessReady=access?.is_verified_business===true;const businessPending=access?.is_business_member===true&&!businessReady;const driverActive=access?.is_active_driver===true;const driverPending=access?.driver_application_status==='PENDING'||access?.driver_application_status==='APPROVED';
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><View style={s.top}><Pressable onPress={()=>router.back()} accessibilityLabel="Go back"><Ionicons name="arrow-back" size={23}/></Pressable><Text style={s.topTitle}>Account</Text><View style={{width:23}}/></View>{loading?<ActivityIndicator style={{marginTop:50}}/>:profile?<><View style={s.profile}><View style={s.avatar}><Ionicons name="person-outline" size={27}/></View><Text style={s.name}>{profile.full_name||'Everest Local account'}</Text><Text style={s.copy}>{profile.phone||profile.city?(profile.suburb||'')+(profile.city?', '+profile.city:''):'Your account is ready.'}</Text><View style={s.roles}><Text style={s.rolesLabel}>YOU'RE USING EVEREST LOCAL AS</Text><Text style={s.rolesText}>{driverActive?'Delivery Driver':businessReady?'Business':'Customer'}</Text></View></View>
 <Text style={s.section}>Switch mode</Text>
 <Pressable style={s.roleCard} onPress={()=>router.push('/')}><View><Text style={s.roleTitle}>Customer</Text><Text style={s.roleCopy}>Find services, hire local businesses and buy products.</Text></View><Ionicons name="arrow-forward" size={18}/></Pressable>
 {access?.is_business_member&&<Pressable style={s.roleCard} onPress={()=>router.push('/business-dashboard')}><View><Text style={s.roleTitle}>Business</Text><Text style={s.roleCopy}>{businessReady?'Manage your verified business.':'Verification: '+(access.business_verification_status??'UNVERIFIED')+'.'}</Text></View><Ionicons name="arrow-forward" size={18}/></Pressable>}
 {driverActive&&<Pressable style={s.roleCard} onPress={()=>router.push('/delivery')}><View><Text style={s.roleTitle}>Delivery Driver</Text><Text style={s.roleCopy}>View assigned deliveries and update authorized delivery jobs.</Text></View><Ionicons name="arrow-forward" size={18}/></Pressable>}
 <Text style={s.section}>Build with Everest Local</Text>
 {!access?.is_business_member&&<Pressable style={s.roleCard} onPress={()=>router.push('/business-onboarding')}><View><Text style={s.roleTitle}>Create a Business</Text><Text style={s.roleCopy}>Create your business profile and enter verification.</Text></View><Ionicons name="arrow-forward" size={18}/></Pressable>}
 {businessPending&&<View style={s.noticeCard}><Text style={s.noticeTitle}>Business verification pending</Text><Text style={s.roleCopy}>Your business profile exists. Submit or review verification before marketplace publication.</Text><Pressable onPress={()=>router.push('/business-verification')}><Text style={s.link}>OPEN VERIFICATION →</Text></Pressable></View>}
 {!driverActive&&!driverPending&&<Pressable style={s.roleCard} onPress={()=>router.push('/driver-onboarding')}><View><Text style={s.roleTitle}>Become a Delivery Driver</Text><Text style={s.roleCopy}>Apply to deliver real Everest orders. Approval is server-controlled.</Text></View><Ionicons name="arrow-forward" size={18}/></Pressable>}
 {driverPending&&<View style={s.noticeCard}><Text style={s.noticeTitle}>Driver application {access?.driver_application_status?.toLowerCase()}</Text><Text style={s.roleCopy}>You cannot access delivery jobs until an authorized admin activates your driver account.</Text><Pressable onPress={()=>router.push('/driver-onboarding')}><Text style={s.link}>VIEW APPLICATION →</Text></Pressable></View>}
 {links.map(([label,path])=><Pressable style={s.row} key={label} onPress={()=>router.push(path)}><Text style={s.rowText}>{label}</Text><Ionicons name="chevron-forward" size={18} color="#777"/></Pressable>)}
 {error&&<Text style={s.error}>{error}</Text>}<Pressable onPress={()=>void logout()} style={s.logout}><Text style={s.logoutText}>SIGN OUT</Text></Pressable></>:<View style={s.profile}><View style={s.avatar}><Ionicons name="person-outline" size={27}/></View><Text style={s.name}>Welcome to Everest Local</Text><Text style={s.copy}>{error||'Sign in or create an account to manage requests, bookings, orders and messages.'}</Text><Pressable onPress={()=>router.push('/auth')} style={s.button}><Text style={s.buttonText}>SIGN IN / CREATE ACCOUNT</Text></Pressable></View>}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:40},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},topTitle:{fontSize:17,fontWeight:'800'},profile:{marginTop:28,backgroundColor:'#151515',borderRadius:23,padding:24,alignItems:'center'},avatar:{width:64,height:64,borderRadius:32,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},name:{color:'#fff',fontSize:20,fontWeight:'800',marginTop:15,textAlign:'center'},copy:{color:'#aaa',fontSize:13,lineHeight:20,textAlign:'center',marginTop:7},roles:{marginTop:16,paddingTop:13,borderTopWidth:1,borderTopColor:'#333',width:'100%',alignItems:'center'},rolesLabel:{fontSize:8,fontWeight:'900',letterSpacing:1.2,color:'#888'},rolesText:{fontSize:12,fontWeight:'800',color:'#fff',marginTop:5},section:{fontSize:19,fontWeight:'800',marginTop:25,marginBottom:9},roleCard:{backgroundColor:'#fff',borderRadius:16,borderWidth:1,borderColor:'#e5e2dc',padding:16,marginTop:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},roleTitle:{fontSize:14,fontWeight:'800'},roleCopy:{fontSize:11,lineHeight:17,color:'#777',marginTop:4,maxWidth:285},noticeCard:{backgroundColor:'#eeece7',borderRadius:16,padding:16,marginTop:8},noticeTitle:{fontSize:14,fontWeight:'900'},link:{fontSize:10,fontWeight:'900',letterSpacing:.7,marginTop:12},button:{backgroundColor:'#fff',borderRadius:13,paddingVertical:13,paddingHorizontal:16,marginTop:18},buttonText:{fontSize:11,fontWeight:'800'},row:{height:58,borderBottomWidth:1,borderBottomColor:'#e4e1da',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},rowText:{fontSize:14,fontWeight:'700'},logout:{marginTop:22,height:50,borderRadius:14,borderWidth:1,borderColor:'#d8d3ca',alignItems:'center',justifyContent:'center'},logoutText:{fontSize:11,fontWeight:'900'},error:{color:'#b42318',fontSize:12,marginTop:12,textAlign:'center'}});
