import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { getAdminMfaState } from '@/lib/admin-mfa';
import { ADMIN_RESOURCES, getAdminResource, getAdminResourcePage, getAdminResourceCount, type AdminResourceKey, type AdminResource } from '@/lib/admin-operations';

const PAGE_SIZE=25;
const dedicatedRoutes:Partial<Record<AdminResourceKey,string>>={business_verifications:'/business-verification',driver_applications:'/driver-verification',deliveries:'/delivery',delivery_assignments:'/delivery'};

function formatValue(value:unknown){if(value===null||value===undefined||value==='')return '—';if(typeof value==='object'){try{return JSON.stringify(value)}catch{return '[data]'}}return String(value)}
function ResourceTable({resource}:{resource:AdminResource}){
 const [rows,setRows]=useState<Record<string,unknown>[]>([]),[count,setCount]=useState(0),[page,setPage]=useState(0),[search,setSearch]=useState(''),[draft,setDraft]=useState(''),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState('');
 const load=useCallback(async(p=page,s=search,refresh=false)=>{refresh?setRefreshing(true):setLoading(true);setError('');try{const result=await getAdminResourcePage(resource,p,PAGE_SIZE,s);setRows(result.rows);setCount(result.count);setPage(p)}catch(e){setError(e instanceof Error?e.message:'The admin data could not be loaded.')}finally{setLoading(false);setRefreshing(false)}},[page,resource,search]);
 useEffect(()=>{void load(0,'')},[resource.key]);
 const columns=useMemo(()=>resource.select.split(',').slice(0,6),[resource.select]),totalPages=Math.max(1,Math.ceil(count/PAGE_SIZE));
 return <View><View style={styles.searchRow}><TextInput value={draft} onChangeText={setDraft} placeholder={`Search ${resource.label.toLowerCase()}…`} placeholderTextColor="#999" style={styles.search} returnKeyType="search" onSubmitEditing={()=>{setSearch(draft.trim());void load(0,draft.trim())}}/><Pressable onPress={()=>{setSearch(draft.trim());void load(0,draft.trim())}} style={styles.smallButton}><Text style={styles.smallButtonText}>SEARCH</Text></Pressable></View>
 {loading&&!rows.length?<View style={styles.state}><ActivityIndicator/><Text style={styles.muted}>Loading real database records…</Text></View>:error?<View style={styles.state}><Text style={styles.error}>{error}</Text><Pressable onPress={()=>void load(page,search)} style={styles.outline}><Text style={styles.outlineText}>RETRY</Text></Pressable></View>:!rows.length?<View style={styles.state}><Text style={styles.stateTitle}>No records found</Text><Text style={styles.muted}>{search?'Try a different search.':'There are currently no records in this resource.'}</Text></View>:<ScrollView horizontal refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(page,search,true)}/>}><View style={styles.table}><View style={styles.header}>{columns.map(c=><Text key={c} style={styles.headerText}>{c.replaceAll('_',' ').toUpperCase()}</Text>)}</View>{rows.map((row,index)=><View key={String(row.id??row.product_id??index)} style={styles.row}>{columns.map(c=><Text selectable key={c} style={styles.cell} numberOfLines={3}>{formatValue(row[c])}</Text>)}</View>)}</View></ScrollView>}
 {count>0&&<View style={styles.pagination}><Pressable disabled={page===0||loading} onPress={()=>void load(page-1,search)} style={styles.outline}><Text style={styles.outlineText}>PREVIOUS</Text></Pressable><Text style={styles.pageText}>Page {page+1} of {totalPages} · {count} total</Text><Pressable disabled={page>=totalPages-1||loading} onPress={()=>void load(page+1,search)} style={styles.outline}><Text style={styles.outlineText}>NEXT</Text></Pressable></View>}</View>
}
function CommandCard({resource,count}:{resource:AdminResource;count:number|null}){return <Pressable accessibilityRole="button" accessibilityLabel={`Open ${resource.label}`} onPress={()=>router.push({pathname:'/admin-operations',params:{resource:resource.key}})} style={({pressed})=>[styles.card,pressed&&styles.cardPressed]}><Text style={styles.cardNumber}>{count===null?'—':count}</Text><Text style={styles.cardLabel}>{resource.label}</Text><Text style={styles.cardDescription}>{resource.description}</Text></Pressable>}
export default function AdminOperations(){
 const params=useLocalSearchParams<{resource?:string}>(),[authorized,setAuthorized]=useState<boolean|null>(null),[counts,setCounts]=useState<Record<string,number|null>>({}),[selected,setSelected]=useState<AdminResource>(()=>getAdminResource(params.resource)),[error,setError]=useState('');
 useEffect(()=>{void getAdminMfaState().then(state=>setAuthorized(state.authorizedAdmin&&state.passwordAuthenticated&&state.aal==='aal2')).catch(()=>setAuthorized(false))},[]);
 useEffect(()=>{setSelected(getAdminResource(params.resource))},[params.resource]);
 const loadCounts=useCallback(async()=>{setError('');try{const pairs=await Promise.all(ADMIN_RESOURCES.map(async r=>[r.key,await getAdminResourceCount(r)] as const));setCounts(Object.fromEntries(pairs))}catch{setError('Some command-center metrics could not be loaded. Retry to refresh.')}},[]);
 useEffect(()=>{if(authorized)void loadCounts()},[authorized,loadCounts]);
 if(authorized===null)return <SafeAreaView style={styles.safe}><View style={styles.center}><ActivityIndicator/><Text style={styles.muted}>Verifying admin access…</Text></View></SafeAreaView>;
 if(!authorized)return <SafeAreaView style={styles.safe}><View style={styles.center}><Text style={styles.title}>Admin access required</Text><Text style={styles.muted}>Password authentication and AAL2 MFA are required before operational data is loaded.</Text><Pressable onPress={()=>router.replace('/admin')} style={styles.button}><Text style={styles.buttonText}>RETURN TO ADMIN</Text></Pressable></View></SafeAreaView>;
 const primary=ADMIN_RESOURCES.filter(r=>!['service_areas','service_matches','opportunities','post_media','admin_actions','stripe_events'].includes(r.key)),secondary=ADMIN_RESOURCES.filter(r=>!primary.includes(r));
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><View style={styles.top}><View><Text style={styles.eyebrow}>EVEREST LOCAL · PRIVATE ADMIN</Text><Text style={styles.title}>Command Center</Text><Text style={styles.subtitle}>Operational control plane backed by real Supabase data. Sensitive mutations remain behind server-authorized RPCs.</Text></View><Pressable onPress={()=>router.replace('/admin')} style={styles.outline}><Text style={styles.outlineText}>BACK</Text></Pressable></View>
 {!!error&&<View style={styles.banner}><Text style={styles.error}>{error}</Text><Pressable onPress={()=>void loadCounts()}><Text style={styles.retry}>RETRY</Text></Pressable></View>}
 <Text style={styles.section}>Platform operations</Text><View style={styles.grid}>{primary.map(r=><CommandCard key={r.key} resource={r} count={counts[r.key]??null}/>)}</View>
 <Text style={styles.section}>System / control plane</Text><View style={styles.grid}>{secondary.map(r=><CommandCard key={r.key} resource={r} count={counts[r.key]??null}/>)}</View>
 <View style={styles.detailHeader}><Text style={styles.section}>{selected.label}</Text><Text style={styles.muted}>{selected.sensitive?'Sensitive operational data is intentionally minimized and never exposes provider secrets.':selected.description}</Text></View>
 {dedicatedRoutes[selected.key]?<View style={styles.dedicated}><Text style={styles.stateTitle}>Dedicated operational workflow</Text><Text style={styles.muted}>Use the existing server-authorized workflow for this resource rather than duplicating its mutation logic.</Text><Pressable onPress={()=>router.push(dedicatedRoutes[selected.key] as never)} style={styles.button}><Text style={styles.buttonText}>OPEN {selected.label.toUpperCase()}</Text></Pressable></View>:<ResourceTable resource={selected}/>}
 </ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#f7f6f2'},page:{padding:20,paddingBottom:60,maxWidth:1200,width:'100%',alignSelf:'center'},center:{flex:1,justifyContent:'center',alignItems:'center',padding:30},top:{flexDirection:'row',justifyContent:'space-between',gap:16,alignItems:'flex-start'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:'#777'},title:{fontSize:31,fontWeight:'900',letterSpacing:-1,marginTop:6},subtitle:{fontSize:13,lineHeight:20,color:'#777',maxWidth:720,marginTop:8},section:{fontSize:19,fontWeight:'900',marginTop:28,marginBottom:12},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},card:{width:'31.5%',minWidth:220,backgroundColor:'#fff',borderRadius:18,borderWidth:1,borderColor:'#e4e0d8',padding:16,minHeight:142},cardPressed:{opacity:.72,transform:[{scale:.99}]},cardNumber:{fontSize:27,fontWeight:'900'},cardLabel:{fontSize:12,fontWeight:'900',marginTop:8},cardDescription:{fontSize:11,lineHeight:16,color:'#777',marginTop:6},detailHeader:{marginTop:10},searchRow:{flexDirection:'row',gap:8,marginTop:8,marginBottom:12},search:{flex:1,minWidth:220,height:44,borderWidth:1,borderColor:'#ddd8cf',borderRadius:12,backgroundColor:'#fff',paddingHorizontal:13,fontSize:13},smallButton:{height:44,borderRadius:12,backgroundColor:'#111',paddingHorizontal:15,alignItems:'center',justifyContent:'center'},smallButtonText:{color:'#fff',fontSize:10,fontWeight:'900'},table:{minWidth:900,backgroundColor:'#fff',borderRadius:16,borderWidth:1,borderColor:'#e4e0d8',overflow:'hidden'},header:{flexDirection:'row',backgroundColor:'#f0eee9',padding:11,gap:8},headerText:{width:150,fontSize:9,fontWeight:'900',color:'#666'},row:{flexDirection:'row',padding:11,borderTopWidth:1,borderTopColor:'#eeeae3',gap:8},cell:{width:150,fontSize:11,lineHeight:16,color:'#222'},pagination:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10,marginTop:12},pageText:{fontSize:11,color:'#777'},button:{height:42,borderRadius:12,backgroundColor:'#111',paddingHorizontal:15,alignItems:'center',justifyContent:'center',marginTop:14},buttonText:{color:'#fff',fontSize:10,fontWeight:'900'},outline:{height:40,borderRadius:11,borderWidth:1,borderColor:'#d9d5cc',paddingHorizontal:13,alignItems:'center',justifyContent:'center'},outlineText:{fontSize:9,fontWeight:'900'},state:{backgroundColor:'#fff',borderRadius:18,padding:30,alignItems:'center',justifyContent:'center',minHeight:150},stateTitle:{fontSize:15,fontWeight:'900'},muted:{fontSize:12,lineHeight:18,color:'#777',marginTop:7},error:{fontSize:12,color:'#b42318'},banner:{backgroundColor:'#fff1f0',borderRadius:12,padding:12,marginTop:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},retry:{fontSize:10,fontWeight:'900'},dedicated:{backgroundColor:'#fff',borderRadius:18,padding:20,borderWidth:1,borderColor:'#e4e0d8',marginTop:12}});
