import { useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { supabase } from '@/lib/supabase';
import type { VerificationStatus } from '@/lib/types';

type PendingBusiness={id:string;name:string;verification_status:VerificationStatus;abn:string|null;suburb:string|null;city:string|null;state:string|null};
type Counts=Record<string,number>;
export default function Admin(){const [loading,setLoading]=useState(true);const [allowed,setAllowed]=useState(false);const [counts,setCounts]=useState<Counts>({});const [pending,setPending]=useState<PendingBusiness[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function load(){try{const {data:user}=await supabase.auth.getUser();if(!user.user)throw new Error('Authentication required');const {data:profile,error:pError}=await supabase.from('profiles').select('role').eq('id',user.user.id).single();if(pError)throw pError;if(profile?.role!=='ADMIN')throw new Error('Admin authorization required');setAllowed(true);const tables=['businesses','profiles','service_requests','quotes','bookings','products','orders','reviews','audit_logs'];const results=await Promise.all(tables.map(t=>supabase.from(t).select('*',{count:'exact',head:true})));const failed=results.find(r=>r.error);if(failed?.error)throw new Error(failed.error.message);setCounts(Object.fromEntries(tables.map((t,i)=>[t,results[i].count??0])));const {data:businesses,error:bError}=await supabase.from('businesses').select('id,name,verification_status,abn,suburb,city,state').eq('verification_status','PENDING').order('created_at',{ascending:true}).limit(50);if(bError)throw bError;setPending((businesses??[]) as PendingBusiness[])}catch(e){setError(e instanceof Error?e.message:'Unable to load admin dashboard.')}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
 async function verify(id:string,status:VerificationStatus){setBusy(true);setError('');try{const {error:e}=await supabase.rpc('admin_set_verification',{p_business_id:id,p_status:status,p_notes:status==='VERIFIED'?'Verified by admin':'Admin review action'});if(e)throw e;await load()}catch(e){setError(e instanceof Error?e.message:'Verification action failed.')}finally{setBusy(false)}}
 if(loading)return <SafeAreaView style={s.safe}><ActivityIndicator style={{marginTop:60}}/></SafeAreaView>;if(!allowed)return <SafeAreaView style={s.safe}><View style={s.center}><Text style={s.title}>Restricted</Text><Text style={s.copy}>{error}</Text></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.eyebrow}>EVEREST LOCAL</Text><Text style={s.title}>Operations</Text><Text style={s.copy}>Admin-only marketplace operations. Sensitive state changes are server-authorized and audited.</Text><View style={s.grid}>{Object.entries(counts).map(([k,v])=><View style={s.card} key={k}><Text style={s.number}>{v}</Text><Text style={s.label}>{k.replaceAll('_',' ').toUpperCase()}</Text></View>)}</View><Text style={s.section}>Pending verification</Text>{pending.length?pending.map(b=><View style={s.business} key={b.id}><Text style={s.businessName}>{b.name}</Text><Text style={s.meta}>{b.abn?`ABN ${b.abn} · `:''}{[b.suburb,b.city,b.state].filter(Boolean).join(', ')}</Text><View style={s.actions}><Pressable disabled={busy} onPress={()=>void verify(b.id,'VERIFIED')} style={s.button}><Text style={s.buttonText}>VERIFY</Text></Pressable><Pressable disabled={busy} onPress={()=>void verify(b.id,'REJECTED')} style={s.outline}><Text style={s.outlineText}>REJECT</Text></Pressable><Pressable disabled={busy} onPress={()=>void verify(b.id,'SUSPENDED')} style={s.outline}><Text style={s.outlineText}>SUSPEND</Text></Pressable></View></View>):<View style={s.empty}><Text style={s.emptyTitle}>No pending business verifications.</Text><Text style={s.meta}>New submissions will appear here.</Text></View>}{!!error&&<Text style={s.error}>{error}</Text>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:40},center:{flex:1,padding:30,justifyContent:'center',alignItems:'center'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:'#777'},title:{fontSize:31,fontWeight:'900',letterSpacing:-1,marginTop:7},copy:{fontSize:13,lineHeight:20,color:'#777',marginTop:8,marginBottom:24},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},card:{width:'48%',minHeight:100,backgroundColor:'#fff',borderRadius:17,borderWidth:1,borderColor:'#e5e2dc',padding:16,justifyContent:'space-between'},number:{fontSize:29,fontWeight:'900'},label:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#777'},section:{fontSize:19,fontWeight:'800',marginTop:28,marginBottom:10},business:{backgroundColor:'#fff',borderRadius:17,borderWidth:1,borderColor:'#e5e2dc',padding:16,marginBottom:10},businessName:{fontSize:15,fontWeight:'800'},meta:{fontSize:11,color:'#777',marginTop:5},actions:{flexDirection:'row',gap:7,marginTop:14},button:{height:40,borderRadius:11,backgroundColor:'#111',paddingHorizontal:14,alignItems:'center',justifyContent:'center'},buttonText:{fontSize:9,fontWeight:'900',color:'#fff'},outline:{height:40,borderRadius:11,borderWidth:1,borderColor:'#ddd8cf',paddingHorizontal:12,alignItems:'center',justifyContent:'center'},outlineText:{fontSize:9,fontWeight:'900'},empty:{backgroundColor:'#fff',borderRadius:19,padding:25,alignItems:'center'},emptyTitle:{fontSize:15,fontWeight:'800'},error:{color:'#b42318',fontSize:12,marginTop:12}});