import {useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {router} from 'expo-router';
import {deletePost,listMyPosts,restorePost,type SocialPost} from '@/lib/social';
import {deleteStory,listMyStoryArchive,type Story} from '@/lib/social-expansion';
import {type ThemeColors,useAppTheme} from '@/lib/theme';
import {haptic} from '@/lib/haptics';

type Tab='POSTS'|'STORIES'|'CLIPS';
export default function Archive(){
 const {colors}=useAppTheme();const s=useMemo(()=>styles(colors),[colors]);
 const [tab,setTab]=useState<Tab>('POSTS');const [posts,setPosts]=useState<SocialPost[]>([]);const [stories,setStories]=useState<Story[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');
 async function load(){setError('');try{const [p,st]=await Promise.all([listMyPosts(80),listMyStoryArchive(100)]);setPosts(p.filter(x=>x.status==='HIDDEN'));setStories(st)}catch(e){setError(e instanceof Error?e.message:'Archive could not be loaded.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const shown=tab==='STORIES'?stories:posts.filter(x=>(x.content_format==='CLIP')===(tab==='CLIPS'));
 async function restore(post:SocialPost){if(busy)return;setBusy(post.id);try{await restorePost(post.id);setPosts(v=>v.filter(x=>x.id!==post.id));void haptic.success()}catch(e){setError(e instanceof Error?e.message:'Post could not be restored.')}finally{setBusy('')}}
 function removePost(post:SocialPost){Alert.alert('Delete permanently?','This removes the archived item from Everest Local.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{setBusy(post.id);try{await deletePost(post.id);setPosts(v=>v.filter(x=>x.id!==post.id))}catch(e){setError(e instanceof Error?e.message:'Post could not be deleted.')}finally{setBusy('')}}}])}
 function removeStory(story:Story){Alert.alert('Delete story?','This removes the story from your archive and any Highlight using it.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{setBusy(story.id);try{await deleteStory(story.id);setStories(v=>v.filter(x=>x.id!==story.id))}catch(e){setError(e instanceof Error?e.message:'Story could not be deleted.')}finally{setBusy('')}}}])}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
  <View style={s.header}><Pressable onPress={()=>router.back()} style={s.round}><Ionicons name="arrow-back" size={21} color={colors.text}/></Pressable><View style={{flex:1}}><Text style={s.kicker}>PRIVATE</Text><Text style={s.title}>Archive</Text></View><Pressable onPress={()=>router.push('/highlights')} style={s.highlight}><Text style={s.highlightText}>HIGHLIGHTS</Text></Pressable></View>
  <View style={s.note}><Ionicons name="archive-outline" size={18} color={colors.accent}/><Text style={s.noteText}>Only you can see this screen. Stories appear here after 24 hours. Archived Posts and Clips stay hidden until you restore them.</Text></View>
  <View style={s.tabs}>{(['POSTS','STORIES','CLIPS'] as Tab[]).map(x=><Pressable key={x} onPress={()=>setTab(x)} style={[s.tab,tab===x&&s.tabActive]}><Text style={[s.tabText,tab===x&&s.tabTextActive]}>{x[0]+x.slice(1).toLowerCase()}</Text></Pressable>)}</View>
  {loading?<ActivityIndicator color={colors.brand} style={{marginTop:60}}/>:error?<Text style={s.error}>{error}</Text>:shown.length===0?<View style={s.empty}><Ionicons name={tab==='STORIES'?'time-outline':tab==='CLIPS'?'play-circle-outline':'images-outline'} size={30} color={colors.muted}/><Text style={s.emptyTitle}>Nothing archived here</Text><Text style={s.emptyCopy}>{tab==='STORIES'?'Expired Stories will appear automatically.':'Archive something from your content menu and it will appear here.'}</Text></View>:tab==='STORIES'?(shown as Story[]).map(story=><View key={story.id} style={s.card}><View style={s.icon}><Ionicons name="ellipse-outline" size={20} color={colors.brand}/></View><View style={{flex:1}}><Text numberOfLines={2} style={s.cardTitle}>{story.caption||'Story'}</Text><Text style={s.meta}>{new Date(story.created_at).toLocaleDateString()} · expired</Text></View><Pressable disabled={busy===story.id} onPress={()=>removeStory(story)} style={s.delete}><Ionicons name="trash-outline" size={17} color={colors.danger}/></Pressable></View>):(shown as SocialPost[]).map(post=><View key={post.id} style={s.card}><View style={s.icon}><Ionicons name={post.content_format==='CLIP'?'play-outline':'images-outline'} size={20} color={colors.brand}/></View><View style={{flex:1}}><Text numberOfLines={2} style={s.cardTitle}>{post.caption|| (post.content_format==='CLIP'?'Clip':'Post')}</Text><Text style={s.meta}>{new Date(post.created_at).toLocaleDateString()} · archived</Text></View><Pressable disabled={busy===post.id} onPress={()=>void restore(post)} style={s.restore}><Ionicons name="arrow-undo-outline" size={16} color={colors.text}/><Text style={s.restoreText}>Restore</Text></Pressable><Pressable disabled={busy===post.id} onPress={()=>removePost(post)} style={s.delete}><Ionicons name="trash-outline" size={17} color={colors.danger}/></Pressable></View>)}
 </ScrollView></SafeAreaView>;
}
const styles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:18,paddingBottom:60,maxWidth:720,width:'100%',alignSelf:'center'},header:{minHeight:64,flexDirection:'row',alignItems:'center',gap:12},round:{width:42,height:42,borderRadius:21,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,alignItems:'center',justifyContent:'center'},kicker:{fontSize:8,fontWeight:'900',letterSpacing:1.5,color:c.accent},title:{fontSize:25,fontWeight:'900',color:c.text},highlight:{height:38,borderRadius:19,backgroundColor:c.soft,paddingHorizontal:12,alignItems:'center',justifyContent:'center'},highlightText:{fontSize:8,fontWeight:'900',letterSpacing:.6,color:c.text},note:{borderRadius:18,backgroundColor:c.elevated,borderWidth:1,borderColor:c.border,padding:14,marginTop:13,flexDirection:'row',gap:9},noteText:{flex:1,fontSize:10,lineHeight:16,color:c.textSecondary},tabs:{marginTop:16,borderRadius:17,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,padding:4,flexDirection:'row'},tab:{flex:1,height:39,borderRadius:13,alignItems:'center',justifyContent:'center'},tabActive:{backgroundColor:c.soft},tabText:{fontSize:10,fontWeight:'800',color:c.muted},tabTextActive:{fontWeight:'900',color:c.text},error:{fontSize:11,color:c.danger,marginTop:18},empty:{paddingVertical:70,alignItems:'center'},emptyTitle:{fontSize:17,fontWeight:'900',color:c.text,marginTop:12},emptyCopy:{fontSize:11,lineHeight:17,color:c.muted,textAlign:'center',marginTop:5,maxWidth:300},card:{minHeight:76,borderRadius:19,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,padding:12,marginTop:10,flexDirection:'row',alignItems:'center',gap:10},icon:{width:42,height:42,borderRadius:15,backgroundColor:c.soft,alignItems:'center',justifyContent:'center'},cardTitle:{fontSize:12,fontWeight:'900',color:c.text},meta:{fontSize:9,color:c.muted,marginTop:4},restore:{height:36,borderRadius:18,backgroundColor:c.soft,paddingHorizontal:10,flexDirection:'row',alignItems:'center',gap:5},restoreText:{fontSize:8,fontWeight:'900',color:c.text},delete:{width:36,height:36,borderRadius:18,alignItems:'center',justifyContent:'center'}});
