import { useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { supabase, supabaseConfigured } from '@/lib/supabase';

export default function Assistant(){
 const [input,setInput]=useState('');const [answer,setAnswer]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function ask(text=input){const message=text.trim();if(!message)return;setInput('');setAnswer('');setError('');setBusy(true);try{if(!supabaseConfigured)throw new Error('Ask Everest is not connected yet. Configure the marketplace backend first.');const {data,error:fnError}=await supabase.functions.invoke('assistant',{body:{message}});if(fnError)throw fnError;setAnswer(data?.message??'No answer is currently available.');}catch(e){setError(e instanceof Error?e.message:'Ask Everest is temporarily unavailable.');}finally{setBusy(false)}}
 return <SafeAreaView style={s.safe}><View style={s.page}><View style={s.top}><Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={23}/></Pressable><Text style={s.topTitle}>Ask Everest</Text><View style={{width:23}}/></View><ScrollView contentContainerStyle={{paddingBottom:100}} keyboardShouldPersistTaps="handled"><View style={s.hero}><View style={s.icon}><Ionicons name="sparkles" size={23} color="#fff"/></View><Text style={s.title}>How can I help?</Text><Text style={s.copy}>Ask about real marketplace businesses and products. Everest will not invent prices, reviews or availability.</Text></View><View style={s.examples}>{['I need a car detailer this weekend','Find a local cleaner','Help me create a service request','I want to buy detailing products'].map(x=><Pressable onPress={()=>ask(x)} style={s.chip} key={x}><Text style={s.chipText}>{x}</Text><Ionicons name="arrow-forward" size={15}/></Pressable>)}</View>{busy&&<ActivityIndicator style={{marginTop:24}}/>}{!!error&&<Text style={s.error}>{error}</Text>}{!!answer&&<View style={s.answer}><Text style={s.answerLabel}>EVEREST</Text><Text style={s.answerText}>{answer}</Text></View>}</ScrollView><View style={s.composer}><TextInput value={input} onChangeText={setInput} onSubmitEditing={()=>ask()} returnKeyType="send" placeholder="Tell Everest what you need..." placeholderTextColor="#888" style={s.input}/><Pressable disabled={busy} onPress={()=>ask()} style={s.send}><Ionicons name="arrow-up" color="#fff" size={18}/></Pressable></View></View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,flex:1},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},topTitle:{fontSize:17,fontWeight:'800'},hero:{backgroundColor:'#151515',borderRadius:23,padding:24,marginTop:30},icon:{width:48,height:48,borderRadius:16,backgroundColor:'#292929',alignItems:'center',justifyContent:'center'},title:{color:'#fff',fontSize:27,fontWeight:'800',marginTop:18},copy:{color:'#aaa',fontSize:13,lineHeight:20,marginTop:8},examples:{marginTop:18,gap:10},chip:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e5e2dc',borderRadius:15,padding:15,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},chipText:{fontSize:13,fontWeight:'600',flex:1},answer:{marginTop:20,backgroundColor:'#fff',borderRadius:18,borderWidth:1,borderColor:'#e5e2dc',padding:17},answerLabel:{fontSize:9,fontWeight:'900',letterSpacing:1.4,color:'#777'},answerText:{fontSize:14,lineHeight:21,marginTop:8},error:{color:'#b42318',fontSize:12,marginTop:20},composer:{position:'absolute',bottom:20,left:20,right:20,height:58,backgroundColor:'#fff',borderRadius:17,borderWidth:1,borderColor:'#e5e2dc',flexDirection:'row',alignItems:'center',paddingLeft:15,paddingRight:7},input:{flex:1,fontSize:14,color:'#111'},send:{width:44,height:44,borderRadius:14,backgroundColor:'#111',alignItems:'center',justifyContent:'center'}});