import { useEffect, useState } from 'react';
import { ActivityIndicator, Linking, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { supabase } from '@/lib/supabase';
import { updateBookingStatus } from '@/lib/marketplace';
import { createServiceCheckout } from '@/lib/service-payments';
import { getOrCreateConversation } from '@/lib/messaging';
import { userFacingError } from '@/lib/errors';
import type { BookingStatus } from '@/lib/types';

type Booking={id:string;business_id:string;request_id:string|null;price:number;scheduled_date:string|null;scheduled_time:string|null;status:BookingStatus;created_at:string};
export default function Bookings(){
 const [items,setItems]=useState<Booking[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [busy,setBusy]=useState<string|null>(null);const [confirmCancelId,setConfirmCancelId]=useState<string|null>(null);const [error,setError]=useState('');
 async function load(mode:'initial'|'refresh'='initial'){if(mode==='initial')setLoading(true);else setRefreshing(true);try{setError('');const {data:{user}}=await supabase.auth.getUser();if(!user){setItems([]);return;}const {data,error:e}=await supabase.from('bookings').select('id,business_id,request_id,price,scheduled_date,scheduled_time,status,created_at').eq('customer_id',user.id).order('created_at',{ascending:false});if(e)throw e;setItems((data??[]) as Booking[])}catch(e){setError(userFacingError(e,'Unable to load bookings. Please try again.'))}finally{setLoading(false);setRefreshing(false)}}
 useEffect(()=>{void load()},[]);
 async function cancel(id:string){setBusy(id);setError('');try{await updateBookingStatus(id,'CANCELLED');setConfirmCancelId(null);await load()}catch(e){setError(userFacingError(e,'Booking could not be cancelled. Please try again.'))}finally{setBusy(null)}}
 async function payDeposit(id:string){setBusy(id);setError('');try{const url=await createServiceCheckout(id);await Linking.openURL(url)}catch(e){setError(userFacingError(e,'Payment could not be started. Please try again.'))}finally{setBusy(null)}}
 async function messageBusiness(booking:Booking){setBusy(`message:${booking.id}`);setError('');try{if(!booking.request_id)throw new Error('This booking is not linked to a service request yet.');const id=await getOrCreateConversation({requestId:booking.request_id,businessId:booking.business_id,bookingId:booking.id});router.push({pathname:'/messages',params:{conversationId:id}})}catch(e){setError(userFacingError(e,'Conversation could not be opened. Please try again.'))}finally{setBusy(null)}}
 return <SafeAreaView style={s.safe}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load('refresh')}/>} contentContainerStyle={s.page}><Text style={s.eyebrow}>EVEREST LOCAL</Text><Text style={s.title}>Bookings</Text>{loading?<ActivityIndicator/>:items.length?items.map(b=>{const canCancel=['REQUESTED','PENDING_PAYMENT','CONFIRMED','UPCOMING'].includes(b.status);const confirming=confirmCancelId===b.id;return <View style={s.card} key={b.id}><View style={s.row}><Text style={s.status}>{b.status.replaceAll('_',' ')}</Text><Text style={s.amount}>${Number(b.price).toFixed(2)} AUD</Text></View><Text style={s.meta}>Scheduled: {b.scheduled_date??'Date pending'}{b.scheduled_time?` at ${b.scheduled_time}`:''}</Text><Pressable disabled={busy!==null} onPress={()=>void messageBusiness(b)} style={s.outline}><Text style={s.outlineText}>{busy===`message:${b.id}`?'OPENING…':'MESSAGE BUSINESS'}</Text></Pressable>{b.status==='PENDING_PAYMENT'&&<Pressable disabled={busy!==null} onPress={()=>void payDeposit(b.id)} style={s.button}><Text style={s.buttonText}>{busy===b.id?'OPENING PAYMENT…':'PAY BOOKING DEPOSIT'}</Text></Pressable>}{canCancel&&!confirming&&<Pressable disabled={busy!==null} onPress={()=>setConfirmCancelId(b.id)} style={s.cancel}><Text style={s.cancelText}>CANCEL BOOKING</Text></Pressable>}{canCancel&&confirming&&<View style={s.confirmBox}><Text style={s.confirmText}>Cancel this booking? The business will see the booking as cancelled.</Text><View style={s.confirmRow}><Pressable disabled={busy!==null} onPress={()=>setConfirmCancelId(null)} style={s.keep}><Text style={s.cancelText}>KEEP BOOKING</Text></Pressable><Pressable disabled={busy!==null} onPress={()=>void cancel(b.id)} style={s.confirmCancel}><Text style={s.confirmCancelText}>{busy===b.id?'CANCELLING…':'YES, CANCEL'}</Text></Pressable></View></View>}</View>}):<View style={s.empty}>{error?<><Text style={s.emptyTitle}>We couldn't load your bookings.</Text><Text style={s.meta}>Your booking data is safe. Try again.</Text><Pressable onPress={()=>void load()} style={s.button}><Text style={s.buttonText}>RETRY</Text></Pressable></>:<><Text style={s.emptyTitle}>No upcoming bookings.</Text><Text style={s.meta}>Accepted quotes become real bookings through the marketplace workflow.</Text></>}</View>}{!!error&&!!items.length&&<View style={s.recovery}><Text style={s.error}>{error}</Text><Pressable onPress={()=>void load()} style={s.retry}><Text style={s.retryText}>RETRY</Text></Pressable></View>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:50},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:'#777'},title:{fontSize:31,fontWeight:'900',marginTop:7,marginBottom:22},card:{backgroundColor:'#fff',borderRadius:17,borderWidth:1,borderColor:'#e5e2dc',padding:17,marginBottom:10},row:{flexDirection:'row',justifyContent:'space-between'},status:{fontSize:9,fontWeight:'900'},amount:{fontSize:20,fontWeight:'900'},meta:{fontSize:11,color:'#777',marginTop:7},button:{height:46,borderRadius:13,backgroundColor:'#111',alignItems:'center',justifyContent:'center',marginTop:13},buttonText:{color:'#fff',fontSize:9,fontWeight:'900'},outline:{height:43,borderRadius:12,borderWidth:1,borderColor:'#d8d3ca',alignItems:'center',justifyContent:'center',marginTop:11},outlineText:{fontSize:9,fontWeight:'900'},cancel:{height:43,borderRadius:12,borderWidth:1,borderColor:'#ddd8cf',alignItems:'center',justifyContent:'center',marginTop:10},cancelText:{fontSize:9,fontWeight:'900'},confirmBox:{marginTop:10,padding:12,borderRadius:12,backgroundColor:'#fff8e8',borderWidth:1,borderColor:'#ead8ae'},confirmText:{fontSize:11,lineHeight:16,color:'#6b5424'},confirmRow:{flexDirection:'row',gap:8,marginTop:10},keep:{flex:1,minHeight:42,borderRadius:10,borderWidth:1,borderColor:'#ddd8cf',alignItems:'center',justifyContent:'center',paddingHorizontal:8},confirmCancel:{flex:1,minHeight:42,borderRadius:10,backgroundColor:'#b42318',alignItems:'center',justifyContent:'center',paddingHorizontal:8},confirmCancelText:{fontSize:9,fontWeight:'900',color:'#fff'},empty:{backgroundColor:'#fff',borderRadius:19,padding:28,alignItems:'center'},emptyTitle:{fontSize:16,fontWeight:'800',textAlign:'center'},recovery:{marginTop:12,gap:9},error:{fontSize:12,color:'#b42318'},retry:{height:40,borderRadius:11,borderWidth:1,borderColor:'#d8d3ca',alignItems:'center',justifyContent:'center',alignSelf:'flex-start',paddingHorizontal:16},retryText:{fontSize:9,fontWeight:'900'}});