import { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Linking, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { supabase } from '@/lib/supabase';
import { updateBookingStatus } from '@/lib/marketplace';
import { createServiceCheckout } from '@/lib/service-payments';
import { getOrCreateConversation } from '@/lib/messaging';
import { type ThemeColors, useAppTheme } from '@/lib/theme';
import type { BookingStatus } from '@/lib/types';

type Booking={id:string;business_id:string;request_id:string|null;price:number;scheduled_date:string|null;scheduled_time:string|null;status:BookingStatus;created_at:string};
export default function Bookings(){
 const {colors}=useAppTheme();const s=useMemo(()=>createStyles(colors),[colors]);
 const [items,setItemsState]=useState<Booking[]>([]);const itemsRef=useRef<Booking[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [busy,setBusy]=useState<string|null>(null);const [confirmCancelId,setConfirmCancelId]=useState<string|null>(null);const [error,setError]=useState('');
 const loadActiveRef=useRef(false);const operationActiveRef=useRef(false);const operationActive=busy!==null||refreshing;
 function setItems(next:Booking[]){itemsRef.current=next;setItemsState(next)}
 async function load(mode:'initial'|'refresh'='initial'){
  if(loadActiveRef.current||operationActiveRef.current)return;loadActiveRef.current=true;
  if(mode==='initial'&&!itemsRef.current.length)setLoading(true);else setRefreshing(true);
  try{setError('');const {data:{user}}=await supabase.auth.getUser();if(!user){setItems([]);return;}const {data,error:e}=await supabase.from('bookings').select('id,business_id,request_id,price,scheduled_date,scheduled_time,status,created_at').eq('customer_id',user.id).order('created_at',{ascending:false});if(e)throw e;setItems((data??[]) as Booking[])}catch{setError(itemsRef.current.length?'Bookings could not be refreshed. Showing your last loaded bookings.':'Bookings could not be loaded. Please try again.')}finally{loadActiveRef.current=false;setLoading(false);setRefreshing(false)}
 }
 useEffect(()=>{void load()},[]); // eslint-disable-line react-hooks/exhaustive-deps
 async function runOperation(key:string,action:()=>Promise<void>){if(operationActiveRef.current||loadActiveRef.current)return;operationActiveRef.current=true;setBusy(key);setError('');try{await action()}finally{operationActiveRef.current=false;setBusy(null)}}
 async function cancel(id:string){await runOperation(id,async()=>{try{await updateBookingStatus(id,'CANCELLED');setConfirmCancelId(null);await load()}catch{setError('Booking could not be cancelled. Please try again.')}})}
 async function payDeposit(id:string){await runOperation(id,async()=>{try{const url=await createServiceCheckout(id);await Linking.openURL(url)}catch{setError('Payment could not be started. Please try again.')}})}
 async function messageBusiness(booking:Booking){await runOperation(`message:${booking.id}`,async()=>{try{if(!booking.request_id){setError('This booking is not linked to a service request yet.');return;}const id=await getOrCreateConversation({requestId:booking.request_id,businessId:booking.business_id,bookingId:booking.id});router.push({pathname:'/messages',params:{conversationId:id}})}catch{setError('Conversation could not be opened. Please try again.')}})}
 return <SafeAreaView style={s.safe}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load('refresh')} tintColor={colors.text}/>} contentContainerStyle={s.page}><Text style={s.eyebrow}>EVEREST LOCAL</Text><Text style={s.title}>Bookings</Text>{loading?<ActivityIndicator color={colors.text}/>:items.length?items.map(b=>{const canCancel=['REQUESTED','PENDING_PAYMENT','CONFIRMED','UPCOMING'].includes(b.status);const confirming=confirmCancelId===b.id;return <View style={s.card} key={b.id}><View style={s.row}><Text style={s.status}>{b.status.replaceAll('_',' ')}</Text><Text style={s.amount}>${Number(b.price).toFixed(2)} AUD</Text></View><Text style={s.meta}>Scheduled: {b.scheduled_date??'Date pending'}{b.scheduled_time?` at ${b.scheduled_time}`:''}</Text><Pressable disabled={operationActive} onPress={()=>void messageBusiness(b)} style={[s.outline,operationActive&&s.disabled]}><Text style={s.outlineText}>{busy===`message:${b.id}`?'OPENING…':'MESSAGE BUSINESS'}</Text></Pressable>{b.status==='PENDING_PAYMENT'&&<Pressable disabled={operationActive} onPress={()=>void payDeposit(b.id)} style={[s.button,operationActive&&s.disabled]}><Text style={s.buttonText}>{busy===b.id?'OPENING PAYMENT…':'PAY BOOKING DEPOSIT'}</Text></Pressable>}{canCancel&&!confirming&&<Pressable disabled={operationActive} onPress={()=>setConfirmCancelId(b.id)} style={[s.cancel,operationActive&&s.disabled]}><Text style={s.cancelText}>CANCEL BOOKING</Text></Pressable>}{canCancel&&confirming&&<View style={s.confirmBox}><Text style={s.confirmText}>Cancel this booking? The business will see the booking as cancelled.</Text><View style={s.confirmRow}><Pressable disabled={operationActive} onPress={()=>setConfirmCancelId(null)} style={s.keep}><Text style={s.cancelText}>KEEP BOOKING</Text></Pressable><Pressable disabled={operationActive} onPress={()=>void cancel(b.id)} style={s.confirmCancel}><Text style={s.confirmCancelText}>{busy===b.id?'CANCELLING…':'YES, CANCEL'}</Text></Pressable></View></View>}</View>}):<View style={s.empty}>{error?<><Text style={s.emptyTitle}>We couldn't load your bookings.</Text><Text style={s.meta}>Your booking data is safe. Try again.</Text><Pressable disabled={operationActive} onPress={()=>void load('refresh')} style={[s.button,operationActive&&s.disabled]}><Text style={s.buttonText}>{refreshing?'RETRYING…':'RETRY BOOKINGS'}</Text></Pressable></>:<><Text style={s.emptyTitle}>No upcoming bookings.</Text><Text style={s.meta}>Accepted quotes become real bookings through the marketplace workflow.</Text></>}</View>}{!!error&&!!items.length&&<View style={s.recovery}><Text style={s.error}>{error}</Text><Pressable disabled={operationActive} onPress={()=>void load('refresh')} style={[s.retry,operationActive&&s.disabled]}><Text style={s.retryText}>{refreshing?'RETRYING…':'RETRY BOOKINGS'}</Text></Pressable></View>}</ScrollView></SafeAreaView>}
const createStyles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:50,maxWidth:760,width:'100%',alignSelf:'center'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:c.muted},title:{fontSize:31,fontWeight:'900',marginTop:7,marginBottom:22,color:c.text},card:{backgroundColor:c.surface,borderRadius:17,borderWidth:1,borderColor:c.border,padding:17,marginBottom:10},row:{flexDirection:'row',justifyContent:'space-between',gap:12},status:{fontSize:9,fontWeight:'900',color:c.text},amount:{fontSize:20,fontWeight:'900',color:c.text},meta:{fontSize:11,color:c.muted,marginTop:7},button:{height:46,borderRadius:13,backgroundColor:c.brand,alignItems:'center',justifyContent:'center',marginTop:13},buttonText:{color:c.onBrand,fontSize:9,fontWeight:'900'},outline:{height:43,borderRadius:12,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center',marginTop:11},outlineText:{fontSize:9,fontWeight:'900',color:c.text},cancel:{height:43,borderRadius:12,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center',marginTop:10},cancelText:{fontSize:9,fontWeight:'900',color:c.text},confirmBox:{marginTop:10,padding:12,borderRadius:12,backgroundColor:c.soft,borderWidth:1,borderColor:c.border},confirmText:{fontSize:11,lineHeight:16,color:c.text},confirmRow:{flexDirection:'row',gap:8,marginTop:10},keep:{flex:1,minHeight:42,borderRadius:10,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center',paddingHorizontal:8},confirmCancel:{flex:1,minHeight:42,borderRadius:10,backgroundColor:c.danger,alignItems:'center',justifyContent:'center',paddingHorizontal:8},confirmCancelText:{fontSize:9,fontWeight:'900',color:'#fff'},empty:{backgroundColor:c.surface,borderRadius:19,padding:28,alignItems:'center',borderWidth:1,borderColor:c.border},emptyTitle:{fontSize:16,fontWeight:'800',textAlign:'center',color:c.text},recovery:{marginTop:12,gap:9,backgroundColor:c.surface,borderRadius:14,borderWidth:1,borderColor:c.border,padding:14},error:{fontSize:12,color:c.danger},retry:{height:40,borderRadius:11,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center',alignSelf:'flex-start',paddingHorizontal:16},retryText:{fontSize:9,fontWeight:'900',color:c.text},disabled:{opacity:.5}});