import {useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {router,useLocalSearchParams} from 'expo-router';
import {addCrmNote,addCrmTask,type CrmActivity,type CrmContact,type CrmLeadStatus,type CrmTask,updateLeadStatus} from '@/lib/crm';
import {getWorkspaceContext,type BusinessWorkspace} from '@/lib/workspace';
import {supabase} from '@/lib/supabase';
import {type ThemeColors,useAppTheme} from '@/lib/theme';

const stages:CrmLeadStatus[]=['NEW_LEAD','CONTACTED','QUALIFIED','QUOTE_SENT','FOLLOW_UP','WON','LOST'];
type Note={id:string;body:string;created_at:string};
type ExtQuote={id:string;status:string;total:number;created_at:string};
type ExtBooking={id:string;service_label:string;scheduled_start:string;status:string;amount:number|null};
type MarketBooking={id:string;status:string;price:number|null;scheduled_date:string|null;completed_at:string|null};
type MarketQuote={id:string;status:string;total:number;created_at:string};

export default function BusinessCustomer(){
 const {id}=useLocalSearchParams<{id:string}>();const {colors}=useAppTheme();const st=useMemo(()=>styles(colors),[colors]);
 const [business,setBusiness]=useState<BusinessWorkspace|null>(null);const [contact,setContact]=useState<CrmContact|null>(null);const [notes,setNotes]=useState<Note[]>([]);const [tasks,setTasks]=useState<CrmTask[]>([]);const [activities,setActivities]=useState<CrmActivity[]>([]);
 const [externalQuotes,setExternalQuotes]=useState<ExtQuote[]>([]);const [externalBookings,setExternalBookings]=useState<ExtBooking[]>([]);const [marketBookings,setMarketBookings]=useState<MarketBooking[]>([]);const [marketQuotes,setMarketQuotes]=useState<MarketQuote[]>([]);
 const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [note,setNote]=useState('');const [task,setTask]=useState('');const [due,setDue]=useState('');
 const [quoteTotal,setQuoteTotal]=useState('');const [quoteNotes,setQuoteNotes]=useState('');const [bookingService,setBookingService]=useState('');const [bookingWhen,setBookingWhen]=useState('');const [bookingAmount,setBookingAmount]=useState('');
 async function load(){if(!id)return;setLoading(true);setError('');try{
  const ctx=await getWorkspaceContext();if(ctx.mode!=='BUSINESS'||!ctx.active_business_id){router.replace('/');return;}const current=ctx.businesses.find(b=>b.id===ctx.active_business_id);if(!current)throw new Error('Business access unavailable.');setBusiness(current);
  const contactR=await supabase.from('business_contacts').select('*').eq('business_id',current.id).eq('id',id).maybeSingle();if(contactR.error)throw contactR.error;if(!contactR.data)throw new Error('Customer not found.');const c=contactR.data as CrmContact;setContact(c);
  const [n,t,a,eq,eb]=await Promise.all([
   supabase.from('crm_notes').select('id,body,created_at').eq('business_id',current.id).eq('contact_id',id).order('created_at',{ascending:false}),
   supabase.from('crm_tasks').select('id,task,due_at,priority,status').eq('business_id',current.id).eq('contact_id',id).order('due_at',{ascending:true}),
   supabase.from('crm_activities').select('id,kind,title,detail,occurred_at,source_record_type,source_record_id').eq('business_id',current.id).eq('contact_id',id).order('occurred_at',{ascending:false}).limit(50),
   supabase.from('crm_external_quotes').select('id,status,total,created_at').eq('business_id',current.id).eq('contact_id',id).order('created_at',{ascending:false}),
   supabase.from('crm_external_bookings').select('id,service_label,scheduled_start,status,amount').eq('business_id',current.id).eq('contact_id',id).order('scheduled_start',{ascending:false}),
  ]);for(const r of [n,t,a,eq,eb])if(r.error)throw r.error;setNotes((n.data??[]) as Note[]);setTasks((t.data??[]) as CrmTask[]);setActivities((a.data??[]) as CrmActivity[]);setExternalQuotes((eq.data??[]) as ExtQuote[]);setExternalBookings((eb.data??[]) as ExtBooking[]);
  if(c.linked_everest_user_id){const [mb,mq]=await Promise.all([
   supabase.from('bookings').select('id,status,price,scheduled_date,completed_at').eq('business_id',current.id).eq('customer_id',c.linked_everest_user_id).order('created_at',{ascending:false}),
   supabase.from('quotes').select('id,status,total,created_at').eq('business_id',current.id).eq('customer_id',c.linked_everest_user_id).order('created_at',{ascending:false})
  ]);if(mb.error)throw mb.error;if(mq.error)throw mq.error;setMarketBookings((mb.data??[]) as MarketBooking[]);setMarketQuotes((mq.data??[]) as MarketQuote[]);}else{setMarketBookings([]);setMarketQuotes([]);}
 }catch(e){setError(e instanceof Error?e.message:'Customer could not be loaded.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[id]);
 const authoritativeRevenue=[...marketBookings.filter(b=>b.status==='COMPLETED').map(b=>Number(b.price||0)),...externalBookings.filter(b=>b.status==='COMPLETED'&&b.amount!=null).map(b=>Number(b.amount||0))].reduce((a,b)=>a+b,0);
 async function saveNote(){if(!business||!contact||!note.trim())return;try{await addCrmNote(business.id,contact.id,note);setNote('');await load();}catch(e){setError(e instanceof Error?e.message:'Note could not be saved.');}}
 async function saveTask(){if(!business||!contact||!task.trim()||!due.trim())return;const date=new Date(due);if(Number.isNaN(date.getTime())){setError('Use a valid follow-up date/time.');return;}try{await addCrmTask(business.id,contact.id,task,date.toISOString());setTask('');setDue('');await load();}catch(e){setError(e instanceof Error?e.message:'Follow-up could not be saved.');}}
 async function createQuote(){if(!business||!contact)return;const total=Number(quoteTotal);if(!Number.isFinite(total)||total<0){setError('Enter a valid quote total.');return;}const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data,error:e}=await supabase.from('crm_external_quotes').insert({business_id:business.id,contact_id:contact.id,total,subtotal:total,tax:0,notes:quoteNotes||null,created_by:user.id}).select('id').single();if(e){setError(e.message);return;}await supabase.from('crm_activities').insert({business_id:business.id,contact_id:contact.id,kind:'QUOTE_CREATED',title:'External quote created',detail:'$'+total.toFixed(2),source_record_type:'CRM_EXTERNAL_QUOTE',source_record_id:data.id,created_by:user.id});setQuoteTotal('');setQuoteNotes('');await load();}
 async function createBooking(){if(!business||!contact||!bookingService.trim()||!bookingWhen.trim())return;const when=new Date(bookingWhen);if(Number.isNaN(when.getTime())){setError('Use a valid booking date/time.');return;}const amount=bookingAmount.trim()?Number(bookingAmount):null;if(amount!==null&&(!Number.isFinite(amount)||amount<0)){setError('Enter a valid amount.');return;}const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data,error:e}=await supabase.from('crm_external_bookings').insert({business_id:business.id,contact_id:contact.id,service_label:bookingService.trim(),scheduled_start:when.toISOString(),amount,created_by:user.id}).select('id').single();if(e){setError(e.message);return;}await supabase.from('crm_activities').insert({business_id:business.id,contact_id:contact.id,kind:'BOOKING_CREATED',title:'External booking created',detail:bookingService.trim(),source_record_type:'CRM_EXTERNAL_BOOKING',source_record_id:data.id,created_by:user.id});setBookingService('');setBookingWhen('');setBookingAmount('');await load();}
 if(loading)return <SafeAreaView style={st.safe}><ActivityIndicator color={colors.brand} style={{marginTop:80}}/></SafeAreaView>;
 if(!contact)return <SafeAreaView style={st.safe}><Text style={st.error}>{error||'Customer not found.'}</Text></SafeAreaView>;
 return <SafeAreaView style={st.safe} edges={['top']}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={st.page}>
  <Pressable onPress={()=>router.back()} style={st.back}><Ionicons name="chevron-back" size={19} color={colors.text}/><Text style={st.backText}>Customers</Text></Pressable>
  <Text style={st.eyebrow}>CUSTOMER 360</Text><Text style={st.title}>{contact.display_name}</Text><Text style={st.meta}>{[contact.source.replaceAll('_',' '),contact.phone,contact.email].filter(Boolean).join(' · ')}</Text>
  <View style={st.metrics}><View><Text style={st.metric}>{'$'+authoritativeRevenue.toFixed(2)}</Text><Text style={st.metricL}>Recorded completed revenue</Text></View><View><Text style={st.metric}>{marketBookings.filter(b=>b.status==='COMPLETED').length+externalBookings.filter(b=>b.status==='COMPLETED').length}</Text><Text style={st.metricL}>Completed jobs</Text></View></View>
  <Text style={st.label}>LEAD STAGE</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={st.chips}>{stages.map(stage=><Pressable key={stage} onPress={()=>business&&void updateLeadStatus(business.id,contact.id,stage).then(load).catch(e=>setError(e.message))} style={[st.chip,contact.lead_status===stage&&st.chipOn]}><Text style={[st.chipText,contact.lead_status===stage&&st.chipTextOn]}>{stage.replaceAll('_',' ')}</Text></Pressable>)}</ScrollView>
  <Section title="Follow-up"><TextInput value={task} onChangeText={setTask} placeholder="What needs to happen?" placeholderTextColor={colors.muted} style={st.input}/><TextInput value={due} onChangeText={setDue} placeholder="Due date/time, e.g. 2026-09-26 14:00" placeholderTextColor={colors.muted} style={st.input}/><Pressable onPress={()=>void saveTask()} style={st.primary}><Text style={st.primaryText}>SCHEDULE FOLLOW-UP</Text></Pressable>{tasks.filter(t=>t.status==='OPEN').map(t=><Text key={t.id} style={st.line}>• {t.task} — {new Date(t.due_at).toLocaleString()}</Text>)}</Section>
  <Section title="Notes"><TextInput value={note} onChangeText={setNote} multiline placeholder="Add a private note" placeholderTextColor={colors.muted} style={[st.input,st.multiline]}/><Pressable onPress={()=>void saveNote()} style={st.secondary}><Text style={st.secondaryText}>ADD NOTE</Text></Pressable>{notes.slice(0,5).map(n=><View key={n.id} style={st.timeline}><Text style={st.timelineTitle}>{n.body}</Text><Text style={st.timelineTime}>{new Date(n.created_at).toLocaleString()}</Text></View>)}</Section>
  <Section title="External quote"><TextInput value={quoteTotal} onChangeText={setQuoteTotal} keyboardType="decimal-pad" placeholder="Total" placeholderTextColor={colors.muted} style={st.input}/><TextInput value={quoteNotes} onChangeText={setQuoteNotes} placeholder="Quote notes" placeholderTextColor={colors.muted} style={st.input}/><Pressable onPress={()=>void createQuote()} style={st.secondary}><Text style={st.secondaryText}>CREATE DRAFT QUOTE</Text></Pressable>{externalQuotes.slice(0,4).map(q=><Text key={q.id} style={st.line}>{q.status} · {'$'+Number(q.total).toFixed(2)}</Text>)}</Section>
  <Section title="External booking"><TextInput value={bookingService} onChangeText={setBookingService} placeholder="Service" placeholderTextColor={colors.muted} style={st.input}/><TextInput value={bookingWhen} onChangeText={setBookingWhen} placeholder="Date/time, e.g. 2026-09-27 09:00" placeholderTextColor={colors.muted} style={st.input}/><TextInput value={bookingAmount} onChangeText={setBookingAmount} keyboardType="decimal-pad" placeholder="Amount (optional)" placeholderTextColor={colors.muted} style={st.input}/><Pressable onPress={()=>void createBooking()} style={st.secondary}><Text style={st.secondaryText}>ADD BOOKING</Text></Pressable>{externalBookings.slice(0,4).map(b=><Text key={b.id} style={st.line}>{b.service_label} · {new Date(b.scheduled_start).toLocaleString()} · {b.status}</Text>)}</Section>
  <Section title="Everest activity">{contact.linked_everest_user_id?<><Text style={st.line}>{marketBookings.length} marketplace bookings · {marketQuotes.length} marketplace quotes</Text>{marketBookings.slice(0,4).map(b=><Text key={b.id} style={st.line}>{b.status} · {b.scheduled_date||'Date pending'}{b.price!=null?' · $'+Number(b.price).toFixed(2):''}</Text>)}</>:<Text style={st.muted}>No Everest account is linked to this CRM contact yet.</Text>}</Section>
  <Section title="Activity timeline">{activities.length?activities.map(a=><View key={a.id} style={st.timeline}><Text style={st.timelineTitle}>{a.title}</Text>{a.detail?<Text style={st.muted}>{a.detail}</Text>:null}<Text style={st.timelineTime}>{new Date(a.occurred_at).toLocaleString()}</Text></View>):<Text style={st.muted}>Activity will appear here as this customer moves through your business.</Text>}</Section>
  {error?<Text style={st.error}>{error}</Text>:null}
 </ScrollView></SafeAreaView>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){const {colors}=useAppTheme();return <View style={{marginTop:26}}><Text style={{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:colors.muted,marginBottom:8}}>{title.toUpperCase()}</Text>{children}</View>}
const styles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:80,maxWidth:760,width:'100%',alignSelf:'center'},back:{flexDirection:'row',alignItems:'center',gap:4,minHeight:40},backText:{fontSize:12,fontWeight:'800',color:c.text},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.4,color:c.brand,marginTop:14},title:{fontSize:32,fontWeight:'900',color:c.text,marginTop:5},meta:{fontSize:11,color:c.muted,marginTop:5},metrics:{flexDirection:'row',gap:28,borderRadius:19,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,padding:16,marginTop:18},metric:{fontSize:22,fontWeight:'900',color:c.text},metricL:{fontSize:9,color:c.muted,marginTop:3},label:{fontSize:9,fontWeight:'900',letterSpacing:1.1,color:c.muted,marginTop:22},chips:{gap:7,paddingTop:8},chip:{height:34,borderRadius:17,borderWidth:1,borderColor:c.border,paddingHorizontal:11,alignItems:'center',justifyContent:'center'},chipOn:{backgroundColor:c.brand,borderColor:c.brand},chipText:{fontSize:8,fontWeight:'900',color:c.text},chipTextOn:{color:c.onBrand},input:{minHeight:46,borderRadius:13,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,color:c.text,paddingHorizontal:13,marginTop:8},multiline:{minHeight:86,paddingTop:12,textAlignVertical:'top'},primary:{height:45,borderRadius:13,backgroundColor:c.brand,alignItems:'center',justifyContent:'center',marginTop:9},primaryText:{fontSize:9,fontWeight:'900',color:c.onBrand},secondary:{height:44,borderRadius:13,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,alignItems:'center',justifyContent:'center',marginTop:9},secondaryText:{fontSize:9,fontWeight:'900',color:c.text},line:{fontSize:11,lineHeight:18,color:c.textSecondary,marginTop:8},timeline:{borderLeftWidth:2,borderLeftColor:c.border,paddingLeft:11,paddingVertical:7,marginTop:4},timelineTitle:{fontSize:12,fontWeight:'800',color:c.text},timelineTime:{fontSize:9,color:c.muted,marginTop:3},muted:{fontSize:10,lineHeight:16,color:c.muted,marginTop:4},error:{fontSize:11,color:c.danger,marginTop:14}});
