import { useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { supabase } from '@/lib/supabase';
import { myBusiness } from '@/lib/catalog';
import type { Order,OrderStatus } from '@/lib/types';

type Delivery={order_id:string;status:string};
export default function BusinessOrders(){const [orders,setOrders]=useState<Order[]>([]);const [deliveries,setDeliveries]=useState<Record<string,string>>({});const [loading,setLoading]=useState(true);const [deliveryLoading,setDeliveryLoading]=useState(false);const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState('');const [deliveryError,setDeliveryError]=useState('');
 async function loadDeliveries(data:Order[]){if(!data.length){setDeliveries({});setDeliveryError('');return;}setDeliveryLoading(true);setDeliveryError('');try{const {data:ds,error:de}=await supabase.from('deliveries').select('order_id,status').in('order_id',data.map(o=>o.id));if(de)throw de;setDeliveries(Object.fromEntries(((ds??[]) as Delivery[]).map(d=>[d.order_id,d.status])));}catch{setDeliveryError('Delivery updates are temporarily unavailable. Your orders are still available below.');}finally{setDeliveryLoading(false)}}
 async function load(){setLoading(true);setError('');try{const b=await myBusiness();if(!b){setOrders([]);setDeliveries({});setDeliveryError('');return;}const {data,error:e}=await supabase.from('orders').select('id,order_number,status,payment_status,total,created_at,delivery_method').eq('business_id',b.id).order('created_at',{ascending:false});if(e)throw e;const nextOrders=(data??[]) as Order[];setOrders(nextOrders);await loadDeliveries(nextOrders);}catch{setError('Unable to load business orders right now. Please try again.');}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
 async function next(order:Order,status:OrderStatus){setBusy(order.id);setError('');try{const {error:e}=await supabase.rpc('update_order_status',{p_order_id:order.id,p_next:status});if(e)throw e;await load();}catch{setError('Unable to update this order right now. Please try again.');}finally{setBusy(null)}}
 async function requestDelivery(order:Order){setBusy(order.id);setError('');try{const {error:e}=await supabase.rpc('request_delivery_for_order',{p_order_id:order.id});if(e)throw e;await load();}catch{setError('Unable to request delivery right now. Please try again.');}finally{setBusy(null)}}
 function nextStatus(o:Order):OrderStatus|null{if(o.status==='PAYMENT_CONFIRMED')return 'ACCEPTED';if(o.status==='ACCEPTED')return 'PREPARING';if(o.status==='PREPARING')return 'READY_FOR_PICKUP';return null}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.eyebrow}>BUSINESS ORDERS</Text><Text style={s.title}>Orders</Text>{loading?<ActivityIndicator/>:error&&!orders.length?<View style={s.empty}><Text style={s.error}>{error}</Text><Pressable onPress={()=>void load()} style={s.retry}><Text style={s.retryText}>RETRY</Text></Pressable></View>:orders.length?<>{deliveryError?<View style={s.warning}><Text style={s.warningText}>{deliveryError}</Text><Pressable disabled={deliveryLoading} onPress={()=>void loadDeliveries(orders)} style={s.deliveryRetry}>{deliveryLoading?<ActivityIndicator/>:<Text style={s.retryText}>RETRY DELIVERY UPDATES</Text>}</Pressable></View>:null}{orders.map(o=>{const nextValue=nextStatus(o);const deliveryStatus=deliveries[o.id];const canRequestDelivery=o.status==='READY_FOR_PICKUP'&&(o.delivery_method==='EVEREST_DELIVERY'||o.delivery_method==='SAME_DAY')&&!deliveryStatus;return <View style={s.card} key={o.id}><View style={s.row}><Text style={s.number}>{o.order_number}</Text><Text style={s.status}>{o.status.replaceAll('_',' ')}</Text></View><Text style={s.amount}>${Number(o.total).toFixed(2)} AUD</Text><Text style={s.meta}>{o.delivery_method??'Pickup / local fulfilment'} · {o.payment_status}</Text>{deliveryStatus&&<Text style={s.delivery}>DELIVERY · {deliveryStatus.replaceAll('_',' ')}</Text>}{nextValue&&<Pressable disabled={busy!==null} style={s.button} onPress={()=>void next(o,nextValue)}><Text style={s.buttonText}>MOVE TO {nextValue.replaceAll('_',' ')}</Text></Pressable>}{canRequestDelivery&&!deliveryError&&<Pressable disabled={busy!==null} style={s.outline} onPress={()=>void requestDelivery(o)}><Text style={s.outlineText}>REQUEST EVEREST DELIVERY</Text></Pressable>}</View>})}{!!error&&<View style={s.warning}><Text style={s.warningText}>{error}</Text><Pressable onPress={()=>void load()} style={s.deliveryRetry}><Text style={s.retryText}>RETRY ORDERS</Text></Pressable></View>}</>:<View style={s.empty}><Text style={s.emptyTitle}>No orders yet.</Text><Text style={s.meta}>Real customer orders will appear here.</Text></View>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:50},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:'#777'},title:{fontSize:31,fontWeight:'900',marginTop:7,marginBottom:22},card:{backgroundColor:'#fff',borderRadius:17,borderWidth:1,borderColor:'#e5e2dc',padding:17,marginBottom:10},row:{flexDirection:'row',justifyContent:'space-between'},number:{fontSize:14,fontWeight:'900'},status:{fontSize:9,fontWeight:'900'},amount:{fontSize:22,fontWeight:'900',marginTop:12},meta:{fontSize:11,color:'#777',marginTop:5},delivery:{fontSize:9,fontWeight:'900',letterSpacing:.7,marginTop:10},button:{height:46,borderRadius:12,backgroundColor:'#111',alignItems:'center',justifyContent:'center',marginTop:13},buttonText:{color:'#fff',fontSize:9,fontWeight:'900'},outline:{height:46,borderRadius:12,borderWidth:1,borderColor:'#ddd8cf',alignItems:'center',justifyContent:'center',marginTop:8},outlineText:{fontSize:9,fontWeight:'900'},empty:{backgroundColor:'#fff',borderRadius:19,padding:28,alignItems:'center'},emptyTitle:{fontSize:16,fontWeight:'800'},error:{color:'#b42318',fontSize:12,textAlign:'center'},retry:{height:42,borderRadius:12,borderWidth:1,borderColor:'#ddd8cf',alignItems:'center',justifyContent:'center',marginTop:12,minWidth:120},retryText:{fontSize:9,fontWeight:'900',letterSpacing:.6},warning:{backgroundColor:'#fff8e8',borderRadius:14,padding:14,marginBottom:12,borderWidth:1,borderColor:'#ead8ae'},warningText:{fontSize:12,lineHeight:18,color:'#6b5424'},deliveryRetry:{minHeight:38,alignItems:'center',justifyContent:'center',marginTop:8}});
