import {useCallback,useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {router,useLocalSearchParams} from 'expo-router';
import {CrmDateTimeField} from '@/components/CrmDateTimeField';
import {BusinessTabBar} from '@/components/BusinessTabBar';
import {createCrmBooking,crmLabel,listBusinessContacts,listCrmBookings,listCrmOpportunities,listCrmQuotes,setCrmBookingStatus,type CrmBooking,type CrmBookingStatus,type CrmContact,type CrmOpportunity,type CrmQuote} from '@/lib/crm';
import {getWorkspaceContext,type BusinessWorkspace} from '@/lib/workspace';
import {supabase} from '@/lib/supabase';
import {type ThemeColors,useAppTheme} from '@/lib/theme';

const durationOptions=[30,45,60,90,120,180,240];
const statuses:CrmBookingStatus[]=['TENTATIVE','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED','NO_SHOW'];
const money=(n:number)=>new Intl.NumberFormat(undefined,{style:'currency',currency:'AUD'}).format(n);
function localDate(d:Date){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');}
function localTime(d:Date){return String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0');}

export default function BusinessCrmBooking(){
 const params=useLocalSearchParams<{id?:string;contactId?:string;opportunityId?:string;quoteId?:string}>();const {colors}=useAppTheme();const st=useMemo(()=>styles(colors),[colors]);
 const [business,setBusiness]=useState<BusinessWorkspace|null>(null);const [contacts,setContacts]=useState<CrmContact[]>([]);const [deals,setDeals]=useState<CrmOpportunity[]>([]);const [quotes,setQuotes]=useState<CrmQuote[]>([]);const [existing,setExisting]=useState<CrmBooking|null>(null);
 const [contactId,setContactId]=useState(params.contactId??'');const [opportunityId,setOpportunityId]=useState(params.opportunityId??'');const [quoteId,setQuoteId]=useState(params.quoteId??'');const [service,setService]=useState('');const [when,setWhen]=useState(()=>new Date(Date.now()+86400000));const [duration,setDuration]=useState(60);const [location,setLocation]=useState('');const [price,setPrice]=useState('');const [status,setStatus]=useState<'TENTATIVE'|'CONFIRMED'>('CONFIRMED');const [notes,setNotes]=useState('');
 const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [conflict,setConflict]=useState('');const [conflictAcknowledged,setConflictAcknowledged]=useState(false);

 const load=useCallback(async()=>{setLoading(true);setError('');try{
  const ctx=await getWorkspaceContext();if(ctx.mode!=='BUSINESS'||!ctx.active_business_id){router.replace('/');return;}const current=ctx.businesses.find(b=>b.id===ctx.active_business_id);if(!current)throw new Error('Business access unavailable.');setBusiness(current);
  const [contactRows,dealRows,quoteRows,bookingRows]=await Promise.all([listBusinessContacts(current.id),listCrmOpportunities(current.id),listCrmQuotes(current.id),listCrmBookings(current.id)]);setContacts(contactRows);setDeals(dealRows);setQuotes(quoteRows);
  if(params.id){const found=bookingRows.find(b=>b.id===params.id);if(!found)throw new Error('Booking not found.');setExisting(found);setContactId(found.contact_id);setOpportunityId(found.opportunity_id??'');setQuoteId(found.quote_id??'');}
  else if(params.quoteId){const quote=quoteRows.find(q=>q.id===params.quoteId);if(quote){setContactId(quote.contact_id);setOpportunityId(quote.opportunity_id??'');setPrice(String(quote.total));setQuoteId(quote.id);if(quote.title)setService(quote.title);}}
 }catch(e){setError(e instanceof Error?e.message:'Booking could not be loaded.');}finally{setLoading(false);}},[params.id,params.quoteId]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{if(opportunityId){const deal=deals.find(d=>d.id===opportunityId);if(deal){setContactId(deal.contact_id);if(!service)setService(deal.service_label||deal.title);}}},[opportunityId,deals,service]);
 useEffect(()=>{if(quoteId){const quote=quotes.find(q=>q.id===quoteId);if(quote){setContactId(quote.contact_id);setOpportunityId(quote.opportunity_id??opportunityId);if(!service)setService(quote.title||'Booked service');if(!price)setPrice(String(quote.total));}}},[quoteId,quotes,opportunityId,service,price]);

 async function checkNativeConflict(){if(!business)return null;const date=localDate(when),time=localTime(when);const {data,error:e}=await supabase.from('bookings').select('id,scheduled_date,scheduled_time,status').eq('business_id',business.id).eq('scheduled_date',date).in('status',['REQUESTED','PENDING_PAYMENT','CONFIRMED','UPCOMING','IN_PROGRESS']);if(e)throw e;const same=(data??[]).find(row=>row.scheduled_time&&String(row.scheduled_time).slice(0,5)===time);return same?'An Everest marketplace booking already starts at '+time+' on '+new Date(date+'T12:00:00').toLocaleDateString()+'.':null;}
 async function save(){if(!business||!contactId||!service.trim())return;const amount=price.trim()?Number(price):null;if(amount!==null&&(!Number.isFinite(amount)||amount<0)){setError('Enter a valid booking price.');return;}setBusy(true);setError('');
  try{const warning=await checkNativeConflict();if(warning&&!conflictAcknowledged){setConflict(warning);setBusy(false);return;}const id=await createCrmBooking({businessId:business.id,contactId,opportunityId:opportunityId||null,quoteId:quoteId||null,serviceLabel:service.trim(),scheduledStart:when.toISOString(),durationMinutes:duration,locationLabel:location,price:amount,status,notes});router.replace({pathname:'/business-crm-booking',params:{id}});}
  catch(e){setError(e instanceof Error?e.message:'Booking could not be created.');}finally{setBusy(false);}
 }
 async function changeStatus(next:CrmBookingStatus){if(!business||!existing)return;setBusy(true);try{await setCrmBookingStatus(business.id,existing.id,next);await load();}catch(e){setError(e instanceof Error?e.message:'Booking status could not be updated.');}finally{setBusy(false);}}
 if(loading)return <SafeAreaView style={st.safe}><ActivityIndicator color={colors.brand} style={{marginTop:80}}/></SafeAreaView>;
 const contact=contacts.find(c=>c.id===contactId),deal=deals.find(d=>d.id===opportunityId),quote=quotes.find(q=>q.id===quoteId);
 return <SafeAreaView style={st.safe} edges={['top']}><View style={{flex:1}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={st.page}>
  <View style={st.top}><Pressable onPress={()=>router.back()} style={st.back}><Ionicons name="chevron-back" size={19} color={colors.text}/></Pressable><View style={{flex:1}}><Text style={st.eyebrow}>CRM BOOKING</Text><Text style={st.topTitle}>{existing?'Booking details':'Schedule job'}</Text></View>{existing?<Text style={[st.status,{color:existing.status==='COMPLETED'?colors.brand:existing.status==='CANCELLED'||existing.status==='NO_SHOW'?colors.danger:colors.text}]}>{crmLabel(existing.status)}</Text>:null}</View>
  {existing?<><View style={st.hero}><Text style={st.service}>{existing.service_label}</Text><Text style={st.customer}>{contact?.display_name??'Customer'}</Text><View style={st.when}><Ionicons name="calendar-outline" size={18} color={colors.brand}/><View><Text style={st.whenMain}>{new Date(existing.scheduled_start).toLocaleString()}</Text><Text style={st.small}>{Math.round((new Date(existing.scheduled_end).getTime()-new Date(existing.scheduled_start).getTime())/60000)} minutes{existing.location_label?' · '+existing.location_label:''}</Text></View></View>{existing.price!=null?<Text style={st.amount}>{money(Number(existing.price))}</Text>:null}</View>
   <Section title="Linked records" colors={colors}><Detail label="Customer" value={contact?.display_name??'Unknown'} colors={colors}/><Detail label="Deal" value={deal?.title??'Not linked'} colors={colors}/><Detail label="Quote" value={quote?'#'+quote.quote_number+' · '+money(Number(quote.total)):'Not linked'} colors={colors}/></Section>
   <Section title="Booking status" colors={colors}><View style={st.statusWrap}>{statuses.map(next=><Pressable disabled={busy||next===existing.status} key={next} onPress={()=>void changeStatus(next)} style={[st.statusChoice,next===existing.status&&st.statusChoiceOn]}><Text style={[st.statusChoiceText,next===existing.status&&st.statusChoiceTextOn]}>{crmLabel(next)}</Text></Pressable>)}</View></Section>
   {existing.notes?<Section title="Notes" colors={colors}><Text style={st.note}>{existing.notes}</Text></Section>:null}
  </>:<>
   <Section title="Customer & deal" colors={colors}><Text style={st.label}>CONTACT</Text><ScrollView style={{maxHeight:180}}>{contacts.map(c=><Pressable key={c.id} onPress={()=>{setContactId(c.id);if(opportunityId&&!deals.some(d=>d.id===opportunityId&&d.contact_id===c.id))setOpportunityId('');if(quoteId&&!quotes.some(q=>q.id===quoteId&&q.contact_id===c.id))setQuoteId('');}} style={[st.choice,contactId===c.id&&st.choiceOn]}><View style={{flex:1}}><Text style={st.choiceTitle}>{c.display_name}</Text><Text style={st.small}>{[c.company,c.phone||c.email].filter(Boolean).join(' · ')||crmLabel(c.source)}</Text></View>{contactId===c.id?<Ionicons name="checkmark-circle" size={18} color={colors.brand}/>:null}</Pressable>)}</ScrollView><Text style={st.label}>DEAL</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={st.pills}><Pressable onPress={()=>setOpportunityId('')} style={[st.pill,!opportunityId&&st.pillOn]}><Text style={[st.pillText,!opportunityId&&st.pillTextOn]}>No deal</Text></Pressable>{deals.filter(d=>d.contact_id===contactId).map(d=><Pressable key={d.id} onPress={()=>setOpportunityId(d.id)} style={[st.pill,opportunityId===d.id&&st.pillOn]}><Text style={[st.pillText,opportunityId===d.id&&st.pillTextOn]}>{d.title}</Text></Pressable>)}</ScrollView><Text style={st.label}>QUOTE</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={st.pills}><Pressable onPress={()=>setQuoteId('')} style={[st.pill,!quoteId&&st.pillOn]}><Text style={[st.pillText,!quoteId&&st.pillTextOn]}>No quote</Text></Pressable>{quotes.filter(q=>q.contact_id===contactId&&q.status==='ACCEPTED').map(q=><Pressable key={q.id} onPress={()=>setQuoteId(q.id)} style={[st.pill,quoteId===q.id&&st.pillOn]}><Text style={[st.pillText,quoteId===q.id&&st.pillTextOn]}>#{q.quote_number} · {money(Number(q.total))}</Text></Pressable>)}</ScrollView></Section>
   <Section title="Job" colors={colors}><TextInput value={service} onChangeText={setService} placeholder="Service / job title" placeholderTextColor={colors.muted} style={st.input}/><CrmDateTimeField label="Date & start time" value={when} onChange={value=>{setWhen(value);setConflict('');setConflictAcknowledged(false);}} minimumDate={new Date()}/><Text style={st.label}>DURATION</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={st.pills}>{durationOptions.map(value=><Pressable key={value} onPress={()=>setDuration(value)} style={[st.pill,duration===value&&st.pillOn]}><Text style={[st.pillText,duration===value&&st.pillTextOn]}>{value<60?value+' min':value%60?Math.floor(value/60)+'h '+value%60+'m':value/60+'h'}</Text></Pressable>)}</ScrollView><TextInput value={location} onChangeText={setLocation} placeholder="Job address / location" placeholderTextColor={colors.muted} style={st.input}/><TextInput value={price} onChangeText={setPrice} keyboardType="decimal-pad" placeholder="Price (optional)" placeholderTextColor={colors.muted} style={st.input}/><TextInput value={notes} onChangeText={setNotes} multiline placeholder="Private booking notes" placeholderTextColor={colors.muted} style={[st.input,st.multiline]}/><Text style={st.label}>STATUS</Text><View style={st.pills}>{(['TENTATIVE','CONFIRMED'] as const).map(value=><Pressable key={value} onPress={()=>setStatus(value)} style={[st.pill,status===value&&st.pillOn]}><Text style={[st.pillText,status===value&&st.pillTextOn]}>{crmLabel(value)}</Text></Pressable>)}</View></Section>
   {conflict?<View style={st.warning}><View style={st.warningTop}><Ionicons name="warning-outline" size={19} color={colors.danger}/><Text style={st.warningTitle}>Possible double booking</Text></View><Text style={st.warningText}>{conflict}</Text><Text style={st.warningText}>CRM-to-CRM overlaps are blocked server-side. This Everest marketplace conflict requires acknowledgement.</Text><Pressable onPress={()=>{setConflictAcknowledged(true);setConflict('');}} style={st.ack}><Text style={st.ackText}>I CHECKED THIS SLOT — CONTINUE</Text></Pressable></View>:null}
   <Pressable disabled={busy||!contactId||!service.trim()} onPress={()=>void save()} style={[st.save,(busy||!contactId||!service.trim())&&{opacity:.45}]}><Text style={st.saveText}>{busy?'CHECKING…':'CREATE BOOKING'}</Text></Pressable>
  </>}
  {error?<Text style={st.error}>{error}</Text>:null}
 </ScrollView><BusinessTabBar active="/business-crm-booking"/></View></SafeAreaView>;
}
function Section({title,children,colors}:{title:string;children:React.ReactNode;colors:ThemeColors}){return <View style={sectionStyles.wrap}><Text style={[sectionStyles.label,{color:colors.muted}]}>{title.toUpperCase()}</Text><View style={[sectionStyles.body,{borderColor:colors.border,backgroundColor:colors.surface}]}>{children}</View></View>}
function Detail({label,value,colors}:{label:string;value:string;colors:ThemeColors}){return <View style={[sectionStyles.row,{borderBottomColor:colors.border}]}><Text style={[sectionStyles.key,{color:colors.muted}]}>{label}</Text><Text style={[sectionStyles.value,{color:colors.text}]}>{value}</Text></View>}
const sectionStyles=StyleSheet.create({wrap:{marginTop:20},label:{fontSize:8,fontWeight:'900',letterSpacing:1.1,marginBottom:7},body:{borderWidth:1,borderRadius:16,padding:14},row:{minHeight:43,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:12},key:{fontSize:10,flex:1},value:{fontSize:10,fontWeight:'800',textAlign:'right',flex:1.5}});
const styles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:18,paddingBottom:110,maxWidth:820,width:'100%',alignSelf:'center'},top:{flexDirection:'row',alignItems:'center',gap:10},back:{width:40,height:40,borderRadius:12,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:8,fontWeight:'900',letterSpacing:1.1,color:c.muted},topTitle:{fontSize:15,fontWeight:'900',color:c.text,marginTop:2},status:{fontSize:9,fontWeight:'900'},hero:{borderWidth:1,borderColor:c.border,borderRadius:18,backgroundColor:c.surface,padding:18,marginTop:20},service:{fontSize:24,fontWeight:'900',color:c.text},customer:{fontSize:11,color:c.muted,marginTop:4},when:{flexDirection:'row',alignItems:'center',gap:10,marginTop:18},whenMain:{fontSize:13,fontWeight:'800',color:c.text},small:{fontSize:9,lineHeight:14,color:c.muted,marginTop:3},amount:{fontSize:24,fontWeight:'900',color:c.text,marginTop:18},statusWrap:{flexDirection:'row',flexWrap:'wrap',gap:6},statusChoice:{height:34,borderWidth:1,borderColor:c.border,borderRadius:10,paddingHorizontal:10,justifyContent:'center'},statusChoiceOn:{backgroundColor:c.soft,borderColor:c.brand},statusChoiceText:{fontSize:8,fontWeight:'900',color:c.text},statusChoiceTextOn:{color:c.brand},note:{fontSize:11,lineHeight:18,color:c.text},label:{fontSize:8,fontWeight:'900',letterSpacing:1,color:c.muted,marginTop:13,marginBottom:6},choice:{minHeight:47,borderWidth:1,borderColor:c.border,borderRadius:11,paddingHorizontal:11,flexDirection:'row',alignItems:'center',gap:10,marginBottom:5},choiceOn:{backgroundColor:c.soft,borderColor:c.brand},choiceTitle:{fontSize:10,fontWeight:'900',color:c.text},pills:{flexDirection:'row',gap:6},pill:{height:32,borderRadius:10,borderWidth:1,borderColor:c.border,paddingHorizontal:10,justifyContent:'center'},pillOn:{backgroundColor:c.brand,borderColor:c.brand},pillText:{fontSize:8,fontWeight:'900',color:c.text},pillTextOn:{color:c.onBrand},input:{minHeight:48,borderWidth:1,borderColor:c.border,borderRadius:12,backgroundColor:c.elevated,color:c.text,paddingHorizontal:11,marginTop:8},multiline:{minHeight:86,paddingTop:11,textAlignVertical:'top'},warning:{borderWidth:1,borderColor:c.danger,borderRadius:16,padding:14,marginTop:16,backgroundColor:c.surface},warningTop:{flexDirection:'row',alignItems:'center',gap:7},warningTitle:{fontSize:13,fontWeight:'900',color:c.text},warningText:{fontSize:9,lineHeight:15,color:c.muted,marginTop:6},ack:{height:40,borderRadius:11,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center',marginTop:12},ackText:{fontSize:8,fontWeight:'900',color:c.text},save:{height:46,borderRadius:13,backgroundColor:c.brand,alignItems:'center',justifyContent:'center',marginTop:18},saveText:{fontSize:9,fontWeight:'900',color:c.onBrand},error:{fontSize:11,color:c.danger,marginTop:14}});
