import { useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { supabase } from '@/lib/supabase';

export default function Business(){
 const [name,setName]=useState('');const [description,setDescription]=useState('');const [abn,setAbn]=useState('');const [phone,setPhone]=useState('');const [email,setEmail]=useState('');const [suburb,setSuburb]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function create(){setMessage('');if(!name.trim()||!suburb.trim()){setMessage('Business name and suburb are required.');return;}setBusy(true);try{const {data,error}=await supabase.rpc('create_business_profile',{p_name:name,p_description:description,p_category_id:null,p_abn:abn,p_phone:phone,p_email:email,p_suburb:suburb,p_city:'Sydney',p_state:'NSW',p_postcode:null});if(error)throw error;setMessage(`Business created. ID: ${data}. Submit verification from your dashboard.`);}catch(e){setMessage(e instanceof Error?e.message:'Could not create business.')}finally{setBusy(false)}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><View style={s.top}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.topTitle}>Business setup</Text><View style={{width:28}}/></View><Text style={s.title}>Bring your business to Everest.</Text><Text style={s.copy}>Create a business profile first. Marketplace verification is controlled separately and cannot be self-assigned.</Text>
 {[['BUSINESS NAME',name,setName,'Your business name'],['DESCRIPTION',description,setDescription,'What do you offer?'],['ABN',abn,setAbn,'Optional until verification'],['PHONE',phone,setPhone,'Business phone'],['EMAIL',email,setEmail,'Business email'],['SUBURB',suburb,setSuburb,'Service area suburb']].map(([label,value,setter,placeholder])=><View key={String(label)}><Text style={s.label}>{label}</Text><TextInput value={value as string} onChangeText={setter as any} placeholder={String(placeholder)} style={[s.input,label==='DESCRIPTION'&&s.area]} multiline={label==='DESCRIPTION'}/></View>)}
 {!!message&&<Text style={s.message}>{message}</Text>}<Pressable disabled={busy} onPress={create} style={s.button}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>CREATE BUSINESS PROFILE</Text>}</Pressable></ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:50},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:25},back:{fontSize:34,fontWeight:'300'},topTitle:{fontSize:16,fontWeight:'800'},title:{fontSize:30,fontWeight:'900',letterSpacing:-1,marginTop:5},copy:{fontSize:13,lineHeight:20,color:'#777',marginTop:8,marginBottom:20},label:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:'#777',marginTop:14,marginBottom:7},input:{height:54,borderWidth:1,borderColor:'#dfdcd5',backgroundColor:'#fff',borderRadius:15,paddingHorizontal:15,fontSize:14},area:{height:110,paddingTop:14,textAlignVertical:'top'},button:{height:54,borderRadius:15,backgroundColor:'#111',alignItems:'center',justifyContent:'center',marginTop:24},buttonText:{color:'#fff',fontSize:11,fontWeight:'900',letterSpacing:.7},message:{marginTop:14,fontSize:12,color:'#333',lineHeight:18}});