import {useCallback,useEffect,useMemo,useState,type ComponentProps} from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {router,useLocalSearchParams} from 'expo-router';
import {BusinessTabBar} from '@/components/BusinessTabBar';
import {getBusinessContact,type CrmContact} from '@/lib/crm';
import {createBusinessMembershipPlan,createBusinessPackage,getBusinessGrowthMetrics,intervalLabel,inviteCustomerToMembership,listBusinessMembershipPlans,listBusinessPackages,type BillingUnit,type BusinessPackage,type GrowthMetrics,type MembershipPlan,type PlanVisibility} from '@/lib/growth';
import {getWorkspaceContext,type BusinessWorkspace} from '@/lib/workspace';
import {type ThemeColors,useAppTheme} from '@/lib/theme';

const presets:Array<{label:string;unit:BillingUnit;count:number}>=[
 {label:'Weekly',unit:'WEEK',count:1},{label:'Fortnightly',unit:'WEEK',count:2},{label:'Monthly',unit:'MONTH',count:1},{label:'Quarterly',unit:'MONTH',count:3},{label:'Annual',unit:'YEAR',count:1},
];
const money=(value:number)=>new Intl.NumberFormat(undefined,{style:'currency',currency:'AUD'}).format(value);

export default function BusinessGrowth(){
 const {contactId}=useLocalSearchParams<{contactId?:string}>();const {colors}=useAppTheme();const s=useMemo(()=>styles(colors),[colors]);
 const [business,setBusiness]=useState<BusinessWorkspace|null>(null);const [contact,setContact]=useState<CrmContact|null>(null);const [plans,setPlans]=useState<MembershipPlan[]>([]);const [packages,setPackages]=useState<BusinessPackage[]>([]);
 const [metrics,setMetrics]=useState<GrowthMetrics|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [success,setSuccess]=useState('');
 const [planName,setPlanName]=useState('');const [planDescription,setPlanDescription]=useState('');const [planPrice,setPlanPrice]=useState('');const [planCredits,setPlanCredits]=useState('0');const [planUnit,setPlanUnit]=useState<BillingUnit>('MONTH');const [planCount,setPlanCount]=useState(1);const [visibility,setVisibility]=useState<PlanVisibility>('PUBLIC');
 const [packageName,setPackageName]=useState('');const [packagePrice,setPackagePrice]=useState('');const [packageCredits,setPackageCredits]=useState('5');const [packageExpiry,setPackageExpiry]=useState('');
 const [selectedPlan,setSelectedPlan]=useState('');const [custom,setCustom]=useState(false);const [customTitle,setCustomTitle]=useState('');const [customPrice,setCustomPrice]=useState('');const [customUnit,setCustomUnit]=useState<BillingUnit>('MONTH');const [customCount,setCustomCount]=useState(1);const [customCredits,setCustomCredits]=useState('0');

 const load=useCallback(async()=>{setLoading(true);setError('');try{
  const ctx=await getWorkspaceContext();if(ctx.mode!=='BUSINESS'||!ctx.active_business_id){router.replace('/');return;}const current=ctx.businesses.find(x=>x.id===ctx.active_business_id);if(!current)throw new Error('Business access unavailable.');setBusiness(current);
  const [planRows,packageRows,growth]=await Promise.all([listBusinessMembershipPlans(current.id),listBusinessPackages(current.id),getBusinessGrowthMetrics(current.id)]);setPlans(planRows);setPackages(packageRows);setMetrics(growth);
  if(contactId){const c=await getBusinessContact(current.id,contactId);setContact(c);setSelectedPlan(value=>value||planRows.find(p=>p.active)?.id||'');}else setContact(null);
 }catch(e){setError(e instanceof Error?e.message:'Growth could not be loaded.')}finally{setLoading(false)}},[contactId]);
 useEffect(()=>{void load()},[load]);

 async function createPlan(){if(!business)return;const price=Number(planPrice),credits=Number(planCredits||0);if(!planName.trim()||!Number.isFinite(price)||price<=0||!Number.isInteger(credits)||credits<0){setError('Enter a plan name, valid price and whole-number credits.');return;}setBusy('plan');setError('');setSuccess('');try{
  await createBusinessMembershipPlan({businessId:business.id,name:planName.trim(),description:planDescription.trim(),visibility,price,intervalUnit:planUnit,intervalCount:planCount,includedCredits:credits});
  setPlanName('');setPlanDescription('');setPlanPrice('');setPlanCredits('0');setSuccess('Membership plan created.');await load();
 }catch(e){setError(e instanceof Error?e.message:'Plan could not be created.')}finally{setBusy('')}}
 async function createPackage(){if(!business)return;const price=Number(packagePrice),credits=Number(packageCredits),expiry=packageExpiry.trim()?Number(packageExpiry):null;if(!packageName.trim()||!Number.isFinite(price)||price<=0||!Number.isInteger(credits)||credits<1||(expiry!==null&&(!Number.isInteger(expiry)||expiry<1))){setError('Enter a package name, valid price, credits and optional expiry days.');return;}setBusy('package');setError('');setSuccess('');try{
  await createBusinessPackage({businessId:business.id,name:packageName.trim(),visibility:'PUBLIC',price,creditCount:credits,expiresAfterDays:expiry});
  setPackageName('');setPackagePrice('');setPackageCredits('5');setPackageExpiry('');setSuccess('Prepaid package created.');await load();
 }catch(e){setError(e instanceof Error?e.message:'Package could not be created.')}finally{setBusy('')}}
 async function invite(){if(!business||!contact)return;setBusy('invite');setError('');setSuccess('');try{
  if(custom){const price=Number(customPrice),credits=Number(customCredits||0);if(!customTitle.trim()||!Number.isFinite(price)||price<=0||!Number.isInteger(credits)||credits<0)throw new Error('Enter a custom plan title, price and valid credits.');
   await inviteCustomerToMembership({businessId:business.id,contactId:contact.id,customTitle:customTitle.trim(),customPrice:price,intervalUnit:customUnit,intervalCount:customCount,includedCredits:credits});
  }else{if(!selectedPlan)throw new Error('Choose a membership plan first.');await inviteCustomerToMembership({businessId:business.id,contactId:contact.id,planId:selectedPlan});}
  setSuccess('Approval request sent. Billing will not start unless the customer accepts in My Everest.');setCustomTitle('');setCustomPrice('');setCustomCredits('0');
 }catch(e){setError(e instanceof Error?e.message:'Membership invitation could not be sent.')}finally{setBusy('')}}

 return <SafeAreaView style={s.safe} edges={['top']}><View style={{flex:1}}><ScrollView contentContainerStyle={s.page}>
  <View style={s.head}><View><Text style={s.eyebrow}>BUSINESS MODE · GROWTH</Text><Text style={s.title}>Recurring revenue</Text><Text style={s.copy}>Memberships, prepaid service packages and customer retention controls. Metrics below come from real membership, booking and payment records.</Text></View></View>
  {error?<View style={s.alert}><Text style={s.error}>{error}</Text></View>:null}{success?<View style={s.success}><Text style={s.successText}>{success}</Text></View>:null}
  {loading?<ActivityIndicator color={colors.brand} style={{marginTop:50}}/>:<>
   <View style={s.metrics}>
    <Metric label="Active members" value={String(metrics?.active_members??0)} colors={colors}/><Metric label="MRR" value={money(Number(metrics?.mrr??0))} colors={colors}/><Metric label="Package revenue" value={money(Number(metrics?.package_revenue??0))} colors={colors}/><Metric label="Recurring series" value={String(metrics?.recurring_booking_series??0)} colors={colors}/><Metric label="Credits outstanding" value={String(metrics?.credits_outstanding??0)} colors={colors}/><Metric label="Failed payments · 30d" value={String(metrics?.failed_membership_payments_30d??0)} colors={colors}/>
   </View>
   {contact?<View style={s.enrol}><View style={s.sectionHead}><View><Text style={s.sectionTitle}>Make {contact.display_name} recurring</Text><Text style={s.sectionCopy}>{contact.linked_everest_user_id?'Choose an existing plan or create a negotiated customer-specific plan.':'This CRM contact is not linked to an Everest customer yet, so paid recurring billing cannot be requested.'}</Text></View><Ionicons name="repeat-outline" size={23} color={colors.brand}/></View>
    {contact.linked_everest_user_id?<><View style={s.modeRow}><Chip label="Existing plan" active={!custom} onPress={()=>setCustom(false)} colors={colors}/><Chip label="Custom plan" active={custom} onPress={()=>setCustom(true)} colors={colors}/></View>
     {!custom?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{plans.filter(p=>p.active).map(p=><Chip key={p.id} label={p.name+' · '+money(Number(p.price))} active={selectedPlan===p.id} onPress={()=>setSelectedPlan(p.id)} colors={colors}/>)}</ScrollView>:<View style={s.form}><Field label="Custom plan name" value={customTitle} onChangeText={setCustomTitle} placeholder="Fleet care" colors={colors}/><Field label="Price" value={customPrice} onChangeText={setCustomPrice} placeholder="600" keyboardType="decimal-pad" colors={colors}/><Field label="Credits per billing period" value={customCredits} onChangeText={setCustomCredits} placeholder="0" keyboardType="number-pad" colors={colors}/><Text style={s.label}>Billing frequency</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{presets.map(p=><Chip key={p.label} label={p.label} active={customUnit===p.unit&&customCount===p.count} onPress={()=>{setCustomUnit(p.unit);setCustomCount(p.count)}} colors={colors}/>)}</ScrollView></View>}
     <Pressable disabled={busy==='invite'} onPress={()=>void invite()} style={s.primary}><Text style={s.primaryText}>{busy==='invite'?'SENDING…':'SEND APPROVAL REQUEST'}</Text></Pressable><Text style={s.consent}>The customer must explicitly approve Stripe recurring billing. This action never charges them.</Text></>:null}
   </View>:null}

   <View style={s.section}><View style={s.sectionHead}><View><Text style={s.sectionTitle}>Membership plans</Text><Text style={s.sectionCopy}>Weekly, fortnightly, monthly, quarterly, annual and Stripe-supported custom intervals.</Text></View><Text style={s.count}>{plans.filter(p=>p.active).length} active</Text></View>
    <View style={s.form}><Field label="Plan name" value={planName} onChangeText={setPlanName} placeholder="Car Care" colors={colors}/><Field label="Description" value={planDescription} onChangeText={setPlanDescription} placeholder="Monthly maintenance membership" colors={colors}/><View style={s.two}><View style={{flex:1}}><Field label="Price" value={planPrice} onChangeText={setPlanPrice} placeholder="79" keyboardType="decimal-pad" colors={colors}/></View><View style={{flex:1}}><Field label="Credits / period" value={planCredits} onChangeText={setPlanCredits} placeholder="1" keyboardType="number-pad" colors={colors}/></View></View>
     <Text style={s.label}>Billing frequency</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{presets.map(p=><Chip key={p.label} label={p.label} active={planUnit===p.unit&&planCount===p.count} onPress={()=>{setPlanUnit(p.unit);setPlanCount(p.count)}} colors={colors}/>)}</ScrollView>
     <Text style={s.label}>Visibility</Text><View style={s.modeRow}>{(['PUBLIC','PRIVATE','INVITE_ONLY'] as PlanVisibility[]).map(v=><Chip key={v} label={v.replace('_',' ')} active={visibility===v} onPress={()=>setVisibility(v)} colors={colors}/>)}</View>
     <Pressable disabled={busy==='plan'} onPress={()=>void createPlan()} style={s.primary}><Text style={s.primaryText}>{busy==='plan'?'CREATING…':'CREATE MEMBERSHIP PLAN'}</Text></Pressable>
    </View>
    <View style={s.list}>{plans.map(p=><View key={p.id} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{p.name}</Text><Text style={s.rowMeta}>{money(Number(p.price))} / {intervalLabel(p.billing_interval_unit,p.billing_interval_count)} · {p.visibility.replace('_',' ')} · {p.included_credits} credits</Text></View><View style={[s.dot,{opacity:p.active?1:.25}]}/></View>)}</View>
   </View>

   <View style={s.section}><View style={s.sectionHead}><View><Text style={s.sectionTitle}>Prepaid packages</Text><Text style={s.sectionCopy}>Sell a fixed number of services without exposing a writable customer balance.</Text></View><Text style={s.count}>{packages.filter(p=>p.active).length} active</Text></View>
    <View style={s.form}><Field label="Package name" value={packageName} onChangeText={setPackageName} placeholder="5 Wash Pack" colors={colors}/><View style={s.two}><View style={{flex:1}}><Field label="Price" value={packagePrice} onChangeText={setPackagePrice} placeholder="199" keyboardType="decimal-pad" colors={colors}/></View><View style={{flex:1}}><Field label="Service credits" value={packageCredits} onChangeText={setPackageCredits} placeholder="5" keyboardType="number-pad" colors={colors}/></View></View><Field label="Expiry days (optional)" value={packageExpiry} onChangeText={setPackageExpiry} placeholder="365" keyboardType="number-pad" colors={colors}/><Pressable disabled={busy==='package'} onPress={()=>void createPackage()} style={s.primary}><Text style={s.primaryText}>{busy==='package'?'CREATING…':'CREATE PREPAID PACKAGE'}</Text></Pressable></View>
    <View style={s.list}>{packages.map(p=><View key={p.id} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{p.name}</Text><Text style={s.rowMeta}>{money(Number(p.price))} · {p.credit_count} credits{p.expires_after_days?' · expires '+p.expires_after_days+'d':''}</Text></View><View style={[s.dot,{opacity:p.active?1:.25}]}/></View>)}</View>
   </View>
   <View style={s.security}><Ionicons name="shield-checkmark-outline" size={20} color={colors.brand}/><View style={{flex:1}}><Text style={s.securityTitle}>Server-authoritative by design</Text><Text style={s.sectionCopy}>Customers cannot grant credits, edit prices or change billing state. Businesses cannot silently subscribe customers. Stripe events and validated RPCs own financial state.</Text></View></View>
  </>}
 </ScrollView><BusinessTabBar active="/business-control"/></View></SafeAreaView>;
}

function Metric({label,value,colors}:{label:string;value:string;colors:ThemeColors}){const s=styles(colors);return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>}
function Chip({label,active,onPress,colors}:{label:string;active:boolean;onPress:()=>void;colors:ThemeColors}){const s=styles(colors);return <Pressable onPress={onPress} style={[s.chip,active&&s.chipOn]}><Text style={[s.chipText,active&&s.chipTextOn]}>{label}</Text></Pressable>}
function Field({label,colors,...props}:{label:string;colors:ThemeColors}&ComponentProps<typeof TextInput>){const s=styles(colors);return <View style={{gap:5}}><Text style={s.label}>{label}</Text><TextInput {...props} placeholderTextColor={colors.muted} style={s.input}/></View>}

const styles=(c:ThemeColors)=>StyleSheet.create({
 safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:120,maxWidth:980,width:'100%',alignSelf:'center'},head:{maxWidth:720},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.4,color:c.accent},title:{fontSize:34,fontWeight:'900',letterSpacing:-.8,color:c.text,marginTop:5},copy:{fontSize:12,lineHeight:19,color:c.textSecondary,marginTop:7},metrics:{flexDirection:'row',flexWrap:'wrap',gap:9,marginTop:22},metric:{flexGrow:1,flexBasis:'30%',minWidth:145,borderRadius:17,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,padding:14},metricValue:{fontSize:21,fontWeight:'900',color:c.text},metricLabel:{fontSize:9,color:c.muted,marginTop:4},section:{marginTop:28},enrol:{marginTop:24,borderRadius:21,borderWidth:1,borderColor:c.border,backgroundColor:c.elevated,padding:17},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:12},sectionTitle:{fontSize:20,fontWeight:'900',color:c.text},sectionCopy:{fontSize:10,lineHeight:16,color:c.muted,marginTop:4,maxWidth:630},count:{fontSize:9,fontWeight:'900',color:c.brand},form:{marginTop:14,borderRadius:18,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,padding:15,gap:12},two:{flexDirection:'row',gap:10},label:{fontSize:9,fontWeight:'900',color:c.textSecondary},input:{height:45,borderRadius:12,borderWidth:1,borderColor:c.border,backgroundColor:c.elevated,paddingHorizontal:12,fontSize:12,color:c.text},chips:{gap:7,paddingRight:12},modeRow:{flexDirection:'row',gap:7,flexWrap:'wrap',marginTop:12},chip:{minHeight:34,borderRadius:999,borderWidth:1,borderColor:c.border,paddingHorizontal:12,alignItems:'center',justifyContent:'center',backgroundColor:c.elevated},chipOn:{backgroundColor:c.brand,borderColor:c.brand},chipText:{fontSize:9,fontWeight:'900',color:c.text},chipTextOn:{color:c.onBrand},primary:{height:46,borderRadius:13,backgroundColor:c.brand,alignItems:'center',justifyContent:'center',marginTop:3},primaryText:{fontSize:9,fontWeight:'900',letterSpacing:.4,color:c.onBrand},consent:{fontSize:9,lineHeight:14,color:c.muted,marginTop:8},list:{marginTop:10,gap:7},row:{minHeight:62,borderRadius:15,borderWidth:1,borderColor:c.border,backgroundColor:c.elevated,padding:13,flexDirection:'row',alignItems:'center',gap:10},rowTitle:{fontSize:13,fontWeight:'900',color:c.text},rowMeta:{fontSize:9,color:c.muted,marginTop:4},dot:{width:9,height:9,borderRadius:99,backgroundColor:c.brand},security:{marginTop:28,borderRadius:18,borderWidth:1,borderColor:c.border,backgroundColor:c.elevated,padding:15,flexDirection:'row',gap:10},securityTitle:{fontSize:12,fontWeight:'900',color:c.text},alert:{marginTop:14,borderRadius:13,borderWidth:1,borderColor:c.border,backgroundColor:c.elevated,padding:12},error:{fontSize:10,color:c.danger},success:{marginTop:14,borderRadius:13,borderWidth:1,borderColor:c.border,backgroundColor:c.soft,padding:12},successText:{fontSize:10,fontWeight:'800',color:c.text},
});