import { Ionicons } from '@expo/vector-icons';
import { router,useLocalSearchParams } from 'expo-router';
import { useCallback,useEffect,useMemo,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { BusinessTabBar } from '@/components/BusinessTabBar';
import { addChecklistItem,ensureJobWorkspace,getJobWorkspace,setChecklistItem,setJobProgress,type JobChecklistItem,type JobRecord } from '@/lib/job-operations';
import { getOrCreateBookingConversation,updateBookingStatus } from '@/lib/marketplace';
import { supabase } from '@/lib/supabase';
import { type ThemeColors,useAppTheme } from '@/lib/theme';
import type { BookingStatus } from '@/lib/types';

type Job={id:string;request_id:string|null;business_id:string;price:number;scheduled_date:string|null;scheduled_time:string|null;status:BookingStatus;created_at:string};
export default function BusinessJob(){
 const {id}=useLocalSearchParams<{id?:string}>();const jobId=typeof id==='string'?id:'';const {colors}=useAppTheme();const s=useMemo(()=>styles(colors),[colors]);
 const [job,setJob]=useState<Job|null>(null);const [record,setRecord]=useState<JobRecord|null>(null);const [checklist,setChecklist]=useState<JobChecklistItem[]>([]);const [item,setItem]=useState('');const [summary,setSummary]=useState('');const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [busy,setBusy]=useState('');const [error,setError]=useState('');
 const load=useCallback(async(refresh=false)=>{if(refresh)setRefreshing(true);else setLoading(true);setError('');try{const {data,error:jobError}=await supabase.from('bookings').select('id,request_id,business_id,price,scheduled_date,scheduled_time,status,created_at').eq('id',jobId).single();if(jobError)throw jobError;const workspace=await getJobWorkspace(jobId);setJob(data as Job);setRecord(workspace.record);setChecklist(workspace.checklist);setSummary(workspace.record?.completion_summary??'')}catch{setError('Job workspace could not be loaded.')}finally{setLoading(false);setRefreshing(false)}},[jobId]);
 useEffect(()=>{void load()},[load]);
 async function run(key:string,work:()=>Promise<void>){if(busy)return;setBusy(key);setError('');try{await work();await load(true)}catch(e){setError(e instanceof Error?e.message:'That update could not be completed.')}finally{setBusy('')}}
 async function progress(status:'ON_MY_WAY'|'ARRIVED'){await run(status,async()=>{if(!record)await ensureJobWorkspace(jobId);await setJobProgress(jobId,status)})}
 async function advance(){if(!job)return;if(job.status==='CONFIRMED'){await run('advance',async()=>{await updateBookingStatus(job.id,'UPCOMING');await ensureJobWorkspace(job.id)});return}if(job.status==='UPCOMING'){await run('advance',async()=>{await updateBookingStatus(job.id,'IN_PROGRESS');await setJobProgress(job.id,'IN_PROGRESS')});return}if(job.status==='IN_PROGRESS'){if(checklist.some(value=>!value.is_complete)){setError('Complete the work checklist before finishing this job.');return}await run('advance',async()=>{await updateBookingStatus(job.id,'COMPLETED');await setJobProgress(job.id,'COMPLETED',summary)})}}
 if(loading)return <SafeAreaView style={s.safe}><ActivityIndicator color={colors.brand} style={{marginTop:70}}/></SafeAreaView>;
 if(!job)return <SafeAreaView style={s.safe}><View style={s.center}><Text style={s.title}>Job unavailable</Text><Text style={s.copy}>{error}</Text></View></SafeAreaView>;
 const actionLabel=job.status==='CONFIRMED'?'MARK UPCOMING':job.status==='UPCOMING'?'START JOB':job.status==='IN_PROGRESS'?'COMPLETE JOB':'';
 return <SafeAreaView style={s.safe} edges={['top']}><View style={{flex:1}}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={colors.brand}/>} contentContainerStyle={s.page}>
  <Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color={colors.text}/></Pressable><Text style={s.eyebrow}>JOB WORKSPACE</Text><View style={s.heading}><View><Text style={s.title}>{job.scheduled_date??'Schedule pending'}</Text><Text style={s.copy}>{job.scheduled_time?.slice(0,5)??'Time pending'} · ${Number(job.price).toFixed(2)} · {job.status.replaceAll('_',' ')}</Text></View><View style={s.statusIcon}><Ionicons name={job.status==='COMPLETED'?'checkmark':'construct-outline'} size={23} color={colors.brand}/></View></View>
  {error?<View style={s.notice}><Text style={s.error}>{error}</Text></View>:null}
  {['CONFIRMED','UPCOMING','IN_PROGRESS'].includes(job.status)&&<View style={s.section}><Text style={s.kicker}>CUSTOMER ARRIVAL UPDATES</Text><Text style={s.sectionTitle}>Keep the customer informed</Text><Text style={s.copy}>Only choose a status when it is true. Customers see this immediately in their job portal.</Text><View style={s.actionRow}><Pressable disabled={!!busy} onPress={()=>void progress('ON_MY_WAY')} style={[s.choice,record?.arrival_status==='ON_MY_WAY'&&s.choiceOn]}><Ionicons name="navigate-outline" size={18} color={record?.arrival_status==='ON_MY_WAY'?colors.onBrand:colors.text}/><Text style={[s.choiceText,record?.arrival_status==='ON_MY_WAY'&&s.choiceTextOn]}>ON MY WAY</Text></Pressable><Pressable disabled={!!busy} onPress={()=>void progress('ARRIVED')} style={[s.choice,record?.arrival_status==='ARRIVED'&&s.choiceOn]}><Ionicons name="location-outline" size={18} color={record?.arrival_status==='ARRIVED'?colors.onBrand:colors.text}/><Text style={[s.choiceText,record?.arrival_status==='ARRIVED'&&s.choiceTextOn]}>ARRIVED</Text></Pressable></View></View>}
  <View style={s.section}><Text style={s.kicker}>WORK CHECKLIST</Text><Text style={s.sectionTitle}>Clear expectations, visible progress</Text>{checklist.map(entry=><Pressable disabled={!!busy||job.status==='COMPLETED'} key={entry.id} onPress={()=>void run('check:'+entry.id,async()=>setChecklistItem(entry.id,!entry.is_complete))} style={s.checkRow}><Ionicons name={entry.is_complete?'checkmark-circle':'ellipse-outline'} size={22} color={entry.is_complete?colors.brand:colors.muted}/><Text style={[s.checkLabel,entry.is_complete&&s.checkDone]}>{entry.label}</Text></Pressable>)}{job.status!=='COMPLETED'&&<View style={s.addRow}><TextInput value={item} onChangeText={setItem} placeholder="Add work item" placeholderTextColor={colors.muted} style={s.input} maxLength={160}/><Pressable disabled={!item.trim()||!!busy} onPress={()=>void run('add',async()=>{await addChecklistItem(job.id,item);setItem('')})} style={s.add}><Ionicons name="add" size={22} color={colors.onBrand}/></Pressable></View>}{!checklist.length&&<Text style={s.emptyText}>Add the agreed work so both sides know what completion means.</Text>}</View>
  {job.status==='IN_PROGRESS'&&<View style={s.section}><Text style={s.kicker}>COMPLETION NOTE</Text><Text style={s.sectionTitle}>Summarise the result</Text><TextInput value={summary} onChangeText={setSummary} multiline placeholder="What was completed? Add useful aftercare or next-step notes." placeholderTextColor={colors.muted} maxLength={2000} style={[s.input,s.summary]}/></View>}
  <View style={s.actions}>{job.request_id&&<Pressable disabled={!!busy} onPress={()=>void run('message',async()=>{const conversationId=await getOrCreateBookingConversation({requestId:job.request_id!,businessId:job.business_id,bookingId:job.id});router.push({pathname:'/messages',params:{conversationId,businessMode:'1',businessId:job.business_id}})})} style={s.secondary}><Ionicons name="chatbubble-outline" size={18} color={colors.text}/><Text style={s.secondaryText}>MESSAGE CUSTOMER</Text></Pressable>}{actionLabel&&<Pressable disabled={!!busy} onPress={()=>void advance()} style={s.primary}><Text style={s.primaryText}>{busy==='advance'?'UPDATING…':actionLabel}</Text></Pressable>}</View>
 </ScrollView><BusinessTabBar active="/business-job"/></View></SafeAreaView>;
}
const styles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:115,maxWidth:880,width:'100%',alignSelf:'center'},center:{flex:1,justifyContent:'center',alignItems:'center',padding:24},back:{width:42,height:42,borderRadius:21,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center',marginBottom:22},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.6,color:c.brand},heading:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{fontSize:30,lineHeight:37,fontWeight:'900',color:c.text,marginTop:6},copy:{fontSize:12,lineHeight:19,color:c.muted,marginTop:5},statusIcon:{width:50,height:50,borderRadius:16,backgroundColor:c.soft,alignItems:'center',justifyContent:'center'},section:{backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:19,padding:18,marginTop:13},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1.3,color:c.accent},sectionTitle:{fontSize:18,fontWeight:'900',color:c.text,marginTop:5},actionRow:{flexDirection:'row',gap:8,marginTop:15},choice:{flex:1,minHeight:48,borderWidth:1,borderColor:c.border,borderRadius:14,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:7},choiceOn:{backgroundColor:c.brand,borderColor:c.brand},choiceText:{fontSize:9,fontWeight:'900',color:c.text},choiceTextOn:{color:c.onBrand},checkRow:{minHeight:48,flexDirection:'row',alignItems:'center',gap:10,borderTopWidth:1,borderTopColor:c.border,marginTop:10,paddingTop:10},checkLabel:{fontSize:13,fontWeight:'700',color:c.text,flex:1},checkDone:{color:c.muted,textDecorationLine:'line-through'},addRow:{flexDirection:'row',gap:8,marginTop:13},input:{minHeight:48,borderRadius:13,borderWidth:1,borderColor:c.border,backgroundColor:c.canvas,color:c.text,paddingHorizontal:13,flex:1,fontSize:13},add:{width:48,height:48,borderRadius:13,backgroundColor:c.brand,alignItems:'center',justifyContent:'center'},summary:{minHeight:120,paddingTop:13,textAlignVertical:'top',marginTop:12},emptyText:{fontSize:12,lineHeight:18,color:c.muted,marginTop:12},actions:{flexDirection:'row',flexWrap:'wrap',gap:9,marginTop:14},primary:{minHeight:50,borderRadius:14,backgroundColor:c.brand,paddingHorizontal:18,alignItems:'center',justifyContent:'center',flexGrow:1},primaryText:{fontSize:10,fontWeight:'900',color:c.onBrand},secondary:{minHeight:50,borderRadius:14,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,paddingHorizontal:18,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,flexGrow:1},secondaryText:{fontSize:10,fontWeight:'900',color:c.text},notice:{backgroundColor:c.surface,borderWidth:1,borderColor:c.danger,borderRadius:14,padding:13,marginTop:13},error:{fontSize:12,color:c.danger}});
