import {useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {router} from 'expo-router';
import {BusinessTabBar} from '@/components/BusinessTabBar';
import {ModeSwitcher} from '@/components/ModeSwitcher';
import {setBusinessAvailability,type BusinessAvailability} from '@/lib/crm';
import {getWorkspaceContext,type BusinessWorkspace} from '@/lib/workspace';
import {supabase} from '@/lib/supabase';
import {type ThemeColors,useAppTheme} from '@/lib/theme';

const statuses:BusinessAvailability['status'][]=['AVAILABLE_NOW','AVAILABLE_LATER','BUSY','OFFLINE'];

export default function BusinessAvailabilityScreen(){
 const {colors}=useAppTheme();const st=useMemo(()=>styles(colors),[colors]);
 const [business,setBusiness]=useState<BusinessWorkspace|null>(null);const [status,setStatus]=useState<BusinessAvailability['status']>('OFFLINE');const [from,setFrom]=useState('');const [until,setUntil]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const ctx=await getWorkspaceContext();if(ctx.mode!=='BUSINESS'||!ctx.active_business_id){router.replace('/');return;}const current=ctx.businesses.find(b=>b.id===ctx.active_business_id);if(!current)throw new Error('Business access unavailable.');setBusiness(current);const {data,error:e}=await supabase.from('business_availability').select('*').eq('business_id',current.id).maybeSingle();if(e)throw e;if(data){setStatus(data.status);setFrom(data.available_from??'');setUntil(data.available_until??'');}}catch(e){setError(e instanceof Error?e.message:'Availability could not be loaded.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function save(){if(!business)return;setSaving(true);setError('');try{let start:string|null=null,end:string|null=null;if(status==='AVAILABLE_LATER'){const a=new Date(from);if(Number.isNaN(a.getTime()))throw new Error('Enter a valid available-from date/time.');start=a.toISOString();if(until.trim()){const b=new Date(until);if(Number.isNaN(b.getTime()))throw new Error('Enter a valid available-until date/time.');end=b.toISOString();}}else if(status==='AVAILABLE_NOW'&&until.trim()){const b=new Date(until);if(Number.isNaN(b.getTime()))throw new Error('Enter a valid available-until date/time.');end=b.toISOString();start=new Date().toISOString();}await setBusinessAvailability(business.id,status,start,end);await load();}catch(e){setError(e instanceof Error?e.message:'Availability could not be saved.');}finally{setSaving(false);}}
 return <SafeAreaView style={st.safe} edges={['top']}><View style={{flex:1}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={st.page}>
  <View style={st.header}><View><Text style={st.mode}>BUSINESS MODE</Text><Text style={st.name}>{business?.name??'Business'}</Text></View><ModeSwitcher compact/></View><Text style={st.title}>Availability</Text><Text style={st.copy}>Tell nearby customers when you can actually take work. Matching still applies verification, capability, location and marketplace eligibility.</Text>
  {loading?<ActivityIndicator color={colors.brand} style={{marginTop:50}}/>:<><View style={st.options}>{statuses.map(v=><Pressable key={v} onPress={()=>setStatus(v)} style={[st.option,status===v&&st.optionOn]}><View style={[st.dot,status===v&&st.dotOn]}/><View style={{flex:1}}><Text style={st.optionTitle}>{v.replaceAll('_',' ')}</Text><Text style={st.optionCopy}>{v==='AVAILABLE_NOW'?'Ready for new work now':v==='AVAILABLE_LATER'?'Set the next time you can take work':v==='BUSY'?'Temporarily exclude me from available-now results':'Do not show me as currently available'}</Text></View></Pressable>)}</View>
  {(status==='AVAILABLE_LATER'||status==='AVAILABLE_NOW')?<View style={st.window}><Text style={st.label}>{status==='AVAILABLE_LATER'?'AVAILABLE FROM':'AVAILABLE UNTIL (OPTIONAL)'}</Text>{status==='AVAILABLE_LATER'?<TextInput value={from} onChangeText={setFrom} placeholder="2026-09-26 15:00" placeholderTextColor={colors.muted} style={st.input}/>:null}<Text style={st.label}>AVAILABLE UNTIL (OPTIONAL)</Text><TextInput value={until} onChangeText={setUntil} placeholder="2026-09-26 18:00" placeholderTextColor={colors.muted} style={st.input}/></View>:null}
  <Pressable disabled={saving} onPress={()=>void save()} style={[st.primary,saving&&{opacity:.6}]}><Text style={st.primaryText}>{saving?'SAVING…':'SAVE AVAILABILITY'}</Text></Pressable></>}
  {error?<Text style={st.error}>{error}</Text>:null}
 </ScrollView><BusinessTabBar active="/business-control"/></View></SafeAreaView>;
}
const styles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:110,maxWidth:760,width:'100%',alignSelf:'center'},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},mode:{fontSize:9,fontWeight:'900',letterSpacing:1.3,color:c.muted},name:{fontSize:15,fontWeight:'900',color:c.text,marginTop:2},title:{fontSize:33,fontWeight:'900',color:c.text,marginTop:25},copy:{fontSize:12,lineHeight:18,color:c.muted,marginTop:5},options:{gap:9,marginTop:20},option:{minHeight:72,borderRadius:18,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,padding:14,flexDirection:'row',alignItems:'center',gap:12},optionOn:{borderColor:c.brand,backgroundColor:c.soft},dot:{width:12,height:12,borderRadius:6,borderWidth:2,borderColor:c.muted},dotOn:{borderColor:c.brand,backgroundColor:c.brand},optionTitle:{fontSize:13,fontWeight:'900',color:c.text},optionCopy:{fontSize:10,lineHeight:15,color:c.muted,marginTop:3},window:{borderRadius:18,borderWidth:1,borderColor:c.border,backgroundColor:c.elevated,padding:14,marginTop:16},label:{fontSize:9,fontWeight:'900',letterSpacing:1.1,color:c.muted,marginTop:8},input:{minHeight:46,borderRadius:13,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,color:c.text,paddingHorizontal:13,marginTop:7},primary:{height:48,borderRadius:14,backgroundColor:c.brand,alignItems:'center',justifyContent:'center',marginTop:16},primaryText:{fontSize:9,fontWeight:'900',color:c.onBrand},error:{fontSize:11,color:c.danger,marginTop:14}});
