import {useCallback,useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Linking,Pressable,ScrollView,StyleSheet,Text,useWindowDimensions,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {router} from 'expo-router';
import {BusinessTabBar} from '@/components/BusinessTabBar';
import {ModeSwitcher} from '@/components/ModeSwitcher';
import {beginIntegrationOAuth,listIntegrationConnections,type IntegrationConnection,type IntegrationProvider} from '@/lib/integrations';
import {getWorkspaceContext,type BusinessWorkspace} from '@/lib/workspace';
import {type ThemeColors,useAppTheme} from '@/lib/theme';

const catalog:Array<{category:string;provider:IntegrationProvider;title:string;copy:string;icon:keyof typeof Ionicons.glyphMap;available:boolean}>=[
 {category:'CALENDAR',provider:'GOOGLE_CALENDAR',title:'Google Calendar',copy:'Import private events as busy time and sync Everest bookings.',icon:'logo-google',available:true},
 {category:'CALENDAR',provider:'MICROSOFT_CALENDAR',title:'Microsoft Outlook',copy:'Microsoft 365 calendar connection via OAuth and Graph.',icon:'logo-microsoft',available:true},
 {category:'COMMUNICATION',provider:'GMAIL',title:'Gmail',copy:'Associate customer threads and send only after explicit confirmation.',icon:'mail-outline',available:true},
 {category:'AI',provider:'OPENAI',title:'Everest AI',copy:'CRM-aware summaries and drafts with business-scoped context.',icon:'sparkles-outline',available:false},
];

export default function BusinessIntegrations(){
 const {colors}=useAppTheme();const {width}=useWindowDimensions();const desktop=width>=1000;const st=useMemo(()=>styles(colors,desktop),[colors,desktop]);
 const [business,setBusiness]=useState<BusinessWorkspace|null>(null);const [connections,setConnections]=useState<IntegrationConnection[]>([]);const [loading,setLoading]=useState(true);const [working,setWorking]=useState('');const [error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const ctx=await getWorkspaceContext();if(ctx.mode!=='BUSINESS'||!ctx.active_business_id)throw new Error('Business Mode is not active.');const current=ctx.businesses.find(x=>x.id===ctx.active_business_id);if(!current)throw new Error('Business access unavailable.');setBusiness(current);setConnections(await listIntegrationConnections(current.id));}catch(e){setError(e instanceof Error?e.message:'Integrations could not be loaded.');}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function connect(provider:IntegrationProvider){if(!business||provider==='OPENAI')return;setWorking(provider);setError('');try{const url=await beginIntegrationOAuth(business.id,provider);await Linking.openURL(url);}catch(e){setError(e instanceof Error?e.message:'Connection could not be started.')}finally{setWorking('')}}
 const byProvider=new Map(connections.map(x=>[x.provider,x]));
 return <SafeAreaView style={st.safe} edges={['top']}><View style={{flex:1}}><ScrollView contentContainerStyle={st.page}>
  <View style={st.header}><Pressable onPress={()=>router.back()} style={st.back}><Ionicons name="arrow-back" size={20} color={colors.text}/></Pressable><View style={{flex:1}}><Text style={st.mode}>BUSINESS MODE</Text><Text style={st.name}>{business?.name??'Integrations'}</Text></View><ModeSwitcher compact/></View>
  <View style={st.hero}><Text style={st.title}>Integrations</Text><Text style={st.copy}>Connect the tools your business already uses. OAuth tokens stay on the server and private calendar details are reduced to busy windows by default.</Text></View>
  {loading?<ActivityIndicator color={colors.brand} style={{marginTop:42}}/>:catalog.map((item,index)=>{const connection=byProvider.get(item.provider);const status=connection?.status??'NOT_CONNECTED';return <View key={item.provider}>{index===0||catalog[index-1].category!==item.category?<Text style={st.category}>{item.category}</Text>:null}<View style={st.card}><View style={st.logo}><Ionicons name={item.icon} size={22} color={colors.text}/></View><View style={st.cardBody}><View style={st.titleRow}><Text style={st.cardTitle}>{item.title}</Text><View style={[st.badge,status==='CONNECTED'?st.connected:status==='NEEDS_ATTENTION'?st.warning:st.neutral]}><Text style={st.badgeText}>{status.replaceAll('_',' ')}</Text></View></View><Text style={st.cardCopy}>{item.copy}</Text>{connection?.account_label?<Text style={st.account}>{connection.account_label}</Text>:null}</View><Pressable disabled={working===item.provider||!item.available} onPress={()=>connection?.status==='CONNECTED'&&item.provider.includes('CALENDAR')?router.push('/business-calendar-integrations'):void connect(item.provider)} style={[st.action,!item.available&&{opacity:.45}]}><Text style={st.actionText}>{working===item.provider?'OPENING…':connection?.status==='CONNECTED'?'CONFIGURE':item.available?'CONNECT':'SET UP SERVER'}</Text></Pressable></View></View>})}
  <Text style={st.category}>AUTOMATION</Text><Pressable onPress={()=>router.push('/business-automations')} style={st.wideCard}><View><Text style={st.cardTitle}>Automations & webhooks</Text><Text style={st.cardCopy}>Build trigger → condition → action workflows and connect Zapier, Make or n8n through signed webhooks.</Text></View><Ionicons name="chevron-forward" size={19} color={colors.muted}/></Pressable>
  {error?<View style={st.errorBox}><Text style={st.error}>{error}</Text></View>:null}
 </ScrollView><BusinessTabBar active="/business-control"/></View></SafeAreaView>
}
const styles=(c:ThemeColors,desktop:boolean)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:desktop?26:18,paddingBottom:110,maxWidth:desktop?1120:760,width:'100%',alignSelf:'center'},header:{flexDirection:'row',alignItems:'center',gap:12},back:{width:40,height:40,borderWidth:1,borderColor:c.border,borderRadius:12,alignItems:'center',justifyContent:'center'},mode:{fontSize:8,fontWeight:'900',letterSpacing:1.2,color:c.muted},name:{fontSize:14,fontWeight:'900',color:c.text,marginTop:2},hero:{marginTop:25,maxWidth:700},title:{fontSize:desktop?36:31,fontWeight:'900',color:c.text},copy:{fontSize:12,lineHeight:19,color:c.muted,marginTop:6},category:{fontSize:9,fontWeight:'900',letterSpacing:1.25,color:c.muted,marginTop:27,marginBottom:7},card:{borderWidth:1,borderColor:c.border,backgroundColor:c.surface,minHeight:100,padding:15,flexDirection:desktop?'row':'column',alignItems:desktop?'center':'stretch',gap:13},logo:{width:45,height:45,borderRadius:13,backgroundColor:c.soft,alignItems:'center',justifyContent:'center'},cardBody:{flex:1},titleRow:{flexDirection:'row',gap:9,alignItems:'center',flexWrap:'wrap'},cardTitle:{fontSize:14,fontWeight:'900',color:c.text},cardCopy:{fontSize:10,lineHeight:16,color:c.muted,marginTop:4,maxWidth:640},account:{fontSize:9,fontWeight:'800',color:c.brand,marginTop:5},badge:{borderRadius:8,paddingHorizontal:7,paddingVertical:4},connected:{backgroundColor:c.soft},warning:{backgroundColor:c.elevated},neutral:{backgroundColor:c.canvas},badgeText:{fontSize:7,fontWeight:'900',color:c.muted},action:{height:38,borderWidth:1,borderColor:c.border,borderRadius:10,paddingHorizontal:13,alignItems:'center',justifyContent:'center'},actionText:{fontSize:8,fontWeight:'900',color:c.text},wideCard:{borderWidth:1,borderColor:c.border,backgroundColor:c.surface,borderRadius:15,padding:17,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},errorBox:{marginTop:16,borderWidth:1,borderColor:c.danger,borderRadius:12,padding:12},error:{fontSize:10,color:c.danger}});
