import {useCallback,useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,useWindowDimensions,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {router} from 'expo-router';
import {createCrmAutomation,listCrmAutomations,setCrmAutomationStatus,type CrmAutomation} from '@/lib/integrations';
import {getWorkspaceContext} from '@/lib/workspace';
import {type ThemeColors,useAppTheme} from '@/lib/theme';

const triggers=['DEAL_CREATED','DEAL_STAGE_CHANGED','QUOTE_VIEWED','QUOTE_ACCEPTED','BOOKING_COMPLETED','CUSTOMER_INACTIVE','EMAIL_RECEIVED'] as const;
const actions=['CREATE_FOLLOW_UP','CREATE_TASK','ADD_TAG','CREATE_INTERNAL_NOTE','CREATE_NOTIFICATION','CALL_WEBHOOK'] as const;
const label=(value:string)=>value.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,m=>m.toUpperCase());
export default function BusinessAutomations(){
 const {colors}=useAppTheme();const {width}=useWindowDimensions();const desktop=width>=1000;const st=useMemo(()=>styles(colors,desktop),[colors,desktop]);const [businessId,setBusinessId]=useState('');const [rows,setRows]=useState<CrmAutomation[]>([]);const [loading,setLoading]=useState(true);const [open,setOpen]=useState(false);const [name,setName]=useState('');const [trigger,setTrigger]=useState<string>('DEAL_CREATED');const [action,setAction]=useState<string>('CREATE_FOLLOW_UP');const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const ctx=await getWorkspaceContext();if(ctx.mode!=='BUSINESS'||!ctx.active_business_id)throw new Error('Business Mode is not active.');setBusinessId(ctx.active_business_id);setRows(await listCrmAutomations(ctx.active_business_id));}catch(e){setError(e instanceof Error?e.message:'Automations could not load.')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 async function save(){if(!name.trim())return;setSaving(true);try{await createCrmAutomation({businessId,name,triggerType:trigger,actionType:action,actionConfig:action==='CREATE_FOLLOW_UP'?{delay_minutes:15,title:'Follow up'}:{}});setOpen(false);setName('');await load()}catch(e){setError(e instanceof Error?e.message:'Automation could not be created.')}finally{setSaving(false)}}
 async function toggle(row:CrmAutomation){await setCrmAutomationStatus(businessId,row.id,row.status==='ACTIVE'?'PAUSED':'ACTIVE');await load()}
 return <SafeAreaView style={st.safe} edges={['top']}><ScrollView contentContainerStyle={st.page}><View style={st.header}><Pressable onPress={()=>router.back()} style={st.back}><Ionicons name="arrow-back" size={20} color={colors.text}/></Pressable><View style={{flex:1}}><Text style={st.eyebrow}>BUSINESS OPERATIONS</Text><Text style={st.title}>Automations</Text></View><Pressable onPress={()=>setOpen(true)} style={st.primary}><Ionicons name="add" size={17} color={colors.onBrand}/><Text style={st.primaryText}>NEW AUTOMATION</Text></Pressable></View><Text style={st.copy}>Build clear, auditable workflows without a fragile node canvas. Consequential communications still require a real connected provider and explicit confirmation.</Text>
 {loading?<ActivityIndicator color={colors.brand} style={{marginTop:40}}/>:<><View style={st.statusGrid}>{(['ACTIVE','PAUSED','DRAFT'] as const).map(status=><View key={status} style={st.metric}><Text style={st.metricN}>{rows.filter(x=>x.status===status).length}</Text><Text style={st.metricL}>{status}</Text></View>)}</View>{rows.length?<View style={st.table}><View style={st.tableHead}><Text style={[st.th,{flex:1.4}]}>AUTOMATION</Text>{desktop?<><Text style={[st.th,{flex:1}]}>TRIGGER</Text><Text style={[st.th,{flex:1}]}>ACTION</Text><Text style={[st.th,{width:110}]}>LAST RUN</Text></>:null}<Text style={[st.th,{width:92}]}>STATUS</Text></View>{rows.map(row=><View key={row.id} style={st.row}><View style={{flex:desktop?1.4:1}}><Text style={st.rowTitle}>{row.name}</Text>{!desktop?<Text style={st.rowMeta}>{label(row.trigger_type)} → {label(row.actions?.[0]?.action_type??'No action')}</Text>:null}</View>{desktop?<><Text style={[st.cell,{flex:1}]}>{label(row.trigger_type)}</Text><Text style={[st.cell,{flex:1}]}>{label(row.actions?.[0]?.action_type??'No action')}</Text><Text style={[st.cell,{width:110}]}>{row.last_run_at?new Date(row.last_run_at).toLocaleDateString():'Never'}</Text></>:null}<Pressable onPress={()=>void toggle(row)} style={[st.status,row.status==='ACTIVE'&&st.statusOn]}><Text style={st.statusText}>{row.status}</Text></Pressable></View>)}</View>:<View style={st.empty}><Ionicons name="flash-outline" size={25} color={colors.brand}/><Text style={st.emptyTitle}>No automations yet</Text><Text style={st.copy}>Start with a safe internal action such as creating a follow-up task when a deal is created.</Text></View>}</>}{error?<Text style={st.error}>{error}</Text>:null}</ScrollView>
 <Modal visible={open} transparent animationType="fade" onRequestClose={()=>setOpen(false)}><View style={st.backdrop}><View style={st.modal}><Text style={st.eyebrow}>SIMPLE BUILDER</Text><Text style={st.modalTitle}>New automation</Text><TextInput value={name} onChangeText={setName} placeholder="Automation name" placeholderTextColor={colors.muted} style={st.input}/><Picker label="WHEN THIS HAPPENS" values={triggers} selected={trigger} onSelect={setTrigger} colors={colors}/><View style={st.flowLine}/><Picker label="DO THIS" values={actions} selected={action} onSelect={setAction} colors={colors}/><Text style={st.safety}>This starts as a draft. Review it, then activate it from the list.</Text><View style={st.modalActions}><Pressable onPress={()=>setOpen(false)} style={st.secondary}><Text style={st.secondaryText}>CANCEL</Text></Pressable><Pressable disabled={!name.trim()||saving} onPress={()=>void save()} style={st.primary}><Text style={st.primaryText}>{saving?'SAVING…':'SAVE DRAFT'}</Text></Pressable></View></View></View></Modal></SafeAreaView>
}
function Picker({label:heading,values,selected,onSelect,colors}:{label:string;values:readonly string[];selected:string;onSelect:(value:string)=>void;colors:ThemeColors}){return <View><Text style={[pickerStyles.heading,{color:colors.muted}]}>{heading}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={pickerStyles.pills}>{values.map(value=><Pressable key={value} onPress={()=>onSelect(value)} style={[pickerStyles.pill,{borderColor:colors.border},selected===value&&{backgroundColor:colors.brand,borderColor:colors.brand}]}><Text style={[pickerStyles.text,{color:selected===value?colors.onBrand:colors.text}]}>{label(value)}</Text></Pressable>)}</ScrollView></View>}
const pickerStyles=StyleSheet.create({heading:{fontSize:8,fontWeight:'900',letterSpacing:1.1,marginTop:18,marginBottom:8},pills:{gap:6},pill:{height:34,borderWidth:1,borderRadius:10,paddingHorizontal:10,justifyContent:'center'},text:{fontSize:8,fontWeight:'900'}});
const styles=(c:ThemeColors,desktop:boolean)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:desktop?26:18,paddingBottom:80,maxWidth:1120,width:'100%',alignSelf:'center'},header:{flexDirection:'row',alignItems:'center',gap:12},back:{width:40,height:40,borderWidth:1,borderColor:c.border,borderRadius:12,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:8,fontWeight:'900',letterSpacing:1.2,color:c.muted},title:{fontSize:desktop?34:28,fontWeight:'900',color:c.text,marginTop:2},copy:{fontSize:11,lineHeight:18,color:c.muted,marginTop:12,maxWidth:720},primary:{height:42,borderRadius:11,backgroundColor:c.brand,paddingHorizontal:13,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:5},primaryText:{fontSize:8,fontWeight:'900',color:c.onBrand},statusGrid:{flexDirection:'row',gap:8,marginTop:22},metric:{flex:1,borderWidth:1,borderColor:c.border,borderRadius:13,backgroundColor:c.surface,padding:14},metricN:{fontSize:22,fontWeight:'900',color:c.text},metricL:{fontSize:8,fontWeight:'900',color:c.muted,marginTop:2},table:{borderWidth:1,borderColor:c.border,borderRadius:15,backgroundColor:c.surface,overflow:'hidden',marginTop:16},tableHead:{minHeight:38,backgroundColor:c.soft,flexDirection:'row',alignItems:'center',paddingHorizontal:13,gap:10},th:{fontSize:7,fontWeight:'900',color:c.muted},row:{minHeight:66,borderTopWidth:1,borderTopColor:c.border,flexDirection:'row',alignItems:'center',paddingHorizontal:13,gap:10},rowTitle:{fontSize:11,fontWeight:'900',color:c.text},rowMeta:{fontSize:8,color:c.muted,marginTop:3},cell:{fontSize:9,color:c.muted},status:{width:92,height:30,borderWidth:1,borderColor:c.border,borderRadius:9,alignItems:'center',justifyContent:'center'},statusOn:{backgroundColor:c.soft},statusText:{fontSize:7,fontWeight:'900',color:c.text},empty:{borderWidth:1,borderColor:c.border,borderRadius:16,backgroundColor:c.surface,padding:22,marginTop:16,alignItems:'flex-start'},emptyTitle:{fontSize:16,fontWeight:'900',color:c.text,marginTop:10},error:{fontSize:10,color:c.danger,marginTop:14},backdrop:{flex:1,backgroundColor:'rgba(0,0,0,.55)',justifyContent:'flex-end',alignItems:'center'},modal:{width:'100%',maxWidth:680,backgroundColor:c.elevated,borderTopLeftRadius:24,borderTopRightRadius:24,padding:20,paddingBottom:30},modalTitle:{fontSize:24,fontWeight:'900',color:c.text,marginTop:3},input:{height:48,borderWidth:1,borderColor:c.border,borderRadius:12,backgroundColor:c.surface,color:c.text,paddingHorizontal:12,marginTop:15},flowLine:{height:20,width:2,backgroundColor:c.border,marginLeft:16},safety:{fontSize:9,lineHeight:15,color:c.muted,marginTop:16},modalActions:{flexDirection:'row',justifyContent:'flex-end',gap:8,marginTop:18},secondary:{height:42,borderWidth:1,borderColor:c.border,borderRadius:11,paddingHorizontal:14,alignItems:'center',justifyContent:'center'},secondaryText:{fontSize:8,fontWeight:'900',color:c.text}});
