import {useCallback,useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Switch,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {router} from 'expo-router';
import {configureCalendarConnection,listCalendarConnections,syncCalendarConnection,type CalendarConnection} from '@/lib/integrations';
import {getWorkspaceContext} from '@/lib/workspace';
import {type ThemeColors,useAppTheme} from '@/lib/theme';

export default function CalendarIntegrations(){
 const {colors}=useAppTheme();const st=useMemo(()=>styles(colors),[colors]);const [businessId,setBusinessId]=useState('');const [rows,setRows]=useState<CalendarConnection[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState('');const [error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const ctx=await getWorkspaceContext();if(ctx.mode!=='BUSINESS'||!ctx.active_business_id)throw new Error('Business Mode is not active.');setBusinessId(ctx.active_business_id);setRows(await listCalendarConnections(ctx.active_business_id));}catch(e){setError(e instanceof Error?e.message:'Calendar settings could not load.')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 async function update(row:CalendarConnection,patch:Partial<CalendarConnection>){const next={...row,...patch};setRows(current=>current.map(x=>x.id===row.id?next:x));setSaving(row.id);setError('');try{await configureCalendarConnection({businessId,connectionId:row.id,importBusy:next.import_busy_time,exportMarketplace:next.export_marketplace_bookings,exportCrm:next.export_crm_bookings,exportTasks:next.export_tasks,syncDirection:next.sync_direction});}catch(e){setRows(current=>current.map(x=>x.id===row.id?row:x));setError(e instanceof Error?e.message:'Settings could not be saved.')}finally{setSaving('')}}
 async function sync(row:CalendarConnection){setSaving(row.id);setError('');try{await syncCalendarConnection(businessId,row.id);await load()}catch(e){setError(e instanceof Error?e.message:'Calendar could not sync.')}finally{setSaving('')}}
  return <SafeAreaView style={st.safe} edges={['top']}><ScrollView contentContainerStyle={st.page}><View style={st.header}><Pressable onPress={()=>router.back()} style={st.back}><Ionicons name="arrow-back" size={20} color={colors.text}/></Pressable><View><Text style={st.eyebrow}>INTEGRATIONS · CALENDAR</Text><Text style={st.title}>Calendar sync</Text></View></View><Text style={st.copy}>External events remain external. By default Everest stores only an opaque busy window—not private event titles or descriptions.</Text>{loading?<ActivityIndicator color={colors.brand} style={{marginTop:40}}/>:rows.length?rows.map(row=><View key={row.id} style={st.card}><View style={st.cardHead}><View style={{flex:1}}><Text style={st.cardTitle}>{row.provider==='GOOGLE_CALENDAR'?'Google Calendar':'Microsoft Outlook'}</Text><Text style={st.meta}>{row.calendar_label??'Primary calendar'}{row.last_synced_at?' · Last sync '+new Date(row.last_synced_at).toLocaleString():' · Awaiting first sync'}</Text></View>{saving===row.id?<ActivityIndicator color={colors.brand}/>:<View style={st.connected}><Text style={st.connectedText}>CONNECTED</Text></View>}</View><Setting title="Import busy times" copy="Prevent double-booking without importing private event details." value={row.import_busy_time} onChange={value=>void update(row,{import_busy_time:value})} colors={colors}/><Setting title="Export marketplace bookings" copy="Create linked events for confirmed Everest marketplace bookings." value={row.export_marketplace_bookings} onChange={value=>void update(row,{export_marketplace_bookings:value})} colors={colors}/><Setting title="Export CRM bookings" copy="Create linked events for CRM bookings and update them on reschedule." value={row.export_crm_bookings} onChange={value=>void update(row,{export_crm_bookings:value})} colors={colors}/><Setting title="Export tasks" copy="Add due tasks as calendar events." value={row.export_tasks} onChange={value=>void update(row,{export_tasks:value})} colors={colors}/><Pressable disabled={saving===row.id||row.provider!=='GOOGLE_CALENDAR'} onPress={()=>void sync(row)} style={[st.primary,row.provider!=='GOOGLE_CALENDAR'&&{opacity:.45}]}><Text style={st.primaryText}>{row.provider==='GOOGLE_CALENDAR'?'SYNC NOW':'MICROSOFT SYNC COMING NEXT'}</Text></Pressable></View>):<View style={st.empty}><Text style={st.cardTitle}>No calendar connected</Text><Text style={st.copy}>Connect Google Calendar or Microsoft Outlook from the Integrations Hub first.</Text><Pressable onPress={()=>router.replace('/business-integrations')} style={st.primary}><Text style={st.primaryText}>OPEN INTEGRATIONS</Text></Pressable></View>}{error?<Text style={st.error}>{error}</Text>:null}</ScrollView></SafeAreaView>
}
function Setting({title,copy,value,onChange,colors}:{title:string;copy:string;value:boolean;onChange:(value:boolean)=>void;colors:ThemeColors}){return <View style={[rowStyles.row,{borderTopColor:colors.border}]}><View style={{flex:1}}><Text style={[rowStyles.title,{color:colors.text}]}>{title}</Text><Text style={[rowStyles.copy,{color:colors.muted}]}>{copy}</Text></View><Switch value={value} onValueChange={onChange} trackColor={{false:colors.border,true:colors.brand}}/></View>}
const rowStyles=StyleSheet.create({row:{minHeight:72,borderTopWidth:1,flexDirection:'row',alignItems:'center',gap:14},title:{fontSize:12,fontWeight:'900'},copy:{fontSize:9,lineHeight:14,marginTop:3}});
const styles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:70,maxWidth:780,width:'100%',alignSelf:'center'},header:{flexDirection:'row',alignItems:'center',gap:12},back:{width:40,height:40,borderWidth:1,borderColor:c.border,borderRadius:12,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:8,fontWeight:'900',letterSpacing:1.1,color:c.muted},title:{fontSize:28,fontWeight:'900',color:c.text,marginTop:2},copy:{fontSize:11,lineHeight:18,color:c.muted,marginTop:12},card:{borderWidth:1,borderColor:c.border,borderRadius:16,backgroundColor:c.surface,padding:17,marginTop:22},cardHead:{flexDirection:'row',alignItems:'center',gap:12,paddingBottom:14},cardTitle:{fontSize:16,fontWeight:'900',color:c.text},meta:{fontSize:9,color:c.muted,marginTop:4},connected:{borderRadius:8,backgroundColor:c.soft,paddingHorizontal:8,paddingVertical:5},connectedText:{fontSize:7,fontWeight:'900',color:c.brand},empty:{borderWidth:1,borderColor:c.border,borderRadius:16,backgroundColor:c.surface,padding:20,marginTop:22},primary:{height:42,backgroundColor:c.brand,borderRadius:11,alignItems:'center',justifyContent:'center',marginTop:16,alignSelf:'flex-start',paddingHorizontal:14},primaryText:{fontSize:8,fontWeight:'900',color:c.onBrand},error:{fontSize:10,color:c.danger,marginTop:14}});
