import { useEffect,useMemo,useRef,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { myBusiness } from '@/lib/catalog';
import { supabase } from '@/lib/supabase';
import { getOrCreateBookingConversation, updateBookingStatus } from '@/lib/marketplace';
import { type ThemeColors,useAppTheme } from '@/lib/theme';
import type { BookingStatus } from '@/lib/types';

type Booking={id:string;request_id:string|null;business_id:string;price:number;scheduled_date:string|null;scheduled_time:string|null;status:BookingStatus;created_at:string};
const nextStatus=(status:BookingStatus):BookingStatus|null=>({CONFIRMED:'UPCOMING',UPCOMING:'IN_PROGRESS',IN_PROGRESS:'COMPLETED'} as Partial<Record<BookingStatus,BookingStatus>>)[status]??null;
export default function BusinessBookings(){
 const {colors}=useAppTheme();const s=useMemo(()=>createStyles(colors),[colors]);
 const [items,setItems]=useState<Booking[]>([]);const [businessId,setBusinessId]=useState('');const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [busy,setBusy]=useState<string|null>(null);const [confirmCancelId,setConfirmCancelId]=useState<string|null>(null);const [error,setError]=useState('');const loadRef=useRef(false);const operationRef=useRef(false);
 async function load(mode:'initial'|'refresh'|'background'='initial'){if(loadRef.current||operationRef.current)return;loadRef.current=true;if(mode==='initial'&&!items.length)setLoading(true);else if(mode==='refresh')setRefreshing(true);setError('');try{const business=await myBusiness();if(!business){setItems([]);setBusinessId('');return;}const {data,error:e}=await supabase.from('bookings').select('id,request_id,business_id,price,scheduled_date,scheduled_time,status,created_at').eq('business_id',business.id).order('created_at',{ascending:false});if(e)throw e;setBusinessId(business.id);setItems((data??[]) as Booking[]);}catch{setError(items.length?'We could not refresh your bookings. Showing the last successfully loaded booking information.':'Unable to load bookings right now. Please try again.');}finally{loadRef.current=false;setLoading(false);setRefreshing(false)}}useEffect(()=>{void load()},[]); // eslint-disable-line react-hooks/exhaustive-deps
 async function runOperation(key:string,action:()=>Promise<void>,failure:string){if(operationRef.current||loadRef.current||refreshing)return;operationRef.current=true;setBusy(key);setError('');try{await action();}catch{setError(failure);}finally{operationRef.current=false;setBusy(null)}}
 async function advance(id:string,status:BookingStatus){await runOperation(id,async()=>{await updateBookingStatus(id,status);setConfirmCancelId(null);const {data,error:e}=await supabase.from('bookings').select('id,request_id,business_id,price,scheduled_date,scheduled_time,status,created_at').eq('business_id',businessId).order('created_at',{ascending:false});if(e)throw e;setItems((data??[]) as Booking[]);},'Booking update failed. Please try again.');}
 async function openConversation(booking:Booking){if(!booking.request_id||!businessId)return;await runOperation(`message:${booking.id}`,async()=>{const conversationId=await getOrCreateBookingConversation({requestId:booking.request_id!,businessId,bookingId:booking.id});router.push({pathname:'/messages',params:{conversationId}});},'Unable to open booking conversation right now. Please try again.');}
 const controlsBusy=busy!==null||refreshing||loadRef.current;
 return <SafeAreaView style={s.safe}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} enabled={!controlsBusy||refreshing} tintColor={colors.text} onRefresh={()=>{if(!controlsBusy)void load('refresh')}}/>} contentContainerStyle={s.page}><Text style={s.eyebrow}>BUSINESS BOOKINGS</Text><Text style={s.title}>Bookings</Text>{loading?<ActivityIndicator color={colors.text}/>:error&&!items.length?<View style={s.empty}><Text style={s.error}>{error}</Text><Pressable disabled={controlsBusy} onPress={()=>void load('refresh')} style={[s.retry,controlsBusy&&s.disabled]}><Text style={s.retryText}>{refreshing?'RETRYING…':'RETRY'}</Text></Pressable></View>:items.length?<>{error?<View style={s.warning}><Text style={s.warningText}>{error}</Text><Pressable disabled={controlsBusy} onPress={()=>void load('refresh')} style={s.retry}><Text style={s.retryText}>{refreshing?'RETRYING…':'RETRY BOOKINGS'}</Text></Pressable></View>:null}{items.map(b=>{const next=nextStatus(b.status);const canCancel=['REQUESTED','PENDING_PAYMENT','CONFIRMED','UPCOMING'].includes(b.status);const confirming=confirmCancelId===b.id;return <View style={s.card} key={b.id}><View style={s.row}><Text style={s.status}>{b.status.replaceAll('_',' ')}</Text><Text style={s.amount}>${Number(b.price).toFixed(2)} AUD</Text></View><Text style={s.meta}>Scheduled: {b.scheduled_date??'Date pending'}{b.scheduled_time?` at ${b.scheduled_time}`:''}</Text><Text style={s.meta}>Booking {b.id.slice(0,8).toUpperCase()}</Text>{b.request_id&&<Pressable disabled={controlsBusy} onPress={()=>void openConversation(b)} style={[s.message,controlsBusy&&s.disabled]}><Text style={s.messageText}>{busy===`message:${b.id}`?'OPENING…':'MESSAGE CUSTOMER'}</Text></Pressable>}{next&&<Pressable disabled={controlsBusy} onPress={()=>void advance(b.id,next)} style={[s.button,controlsBusy&&s.disabled]}><Text style={s.buttonText}>{busy===b.id?'UPDATING…':`MOVE TO ${next.replaceAll('_',' ')}`}</Text></Pressable>}{canCancel&&!confirming&&<Pressable disabled={controlsBusy} onPress={()=>setConfirmCancelId(b.id)} style={[s.cancel,controlsBusy&&s.disabled]}><Text style={s.cancelText}>CANCEL BOOKING</Text></Pressable>}{canCancel&&confirming&&<View style={s.confirmBox}><Text style={s.confirmText}>Cancel this booking? This action changes the customer’s booking status.</Text><View style={s.confirmRow}><Pressable disabled={controlsBusy} onPress={()=>setConfirmCancelId(null)} style={[s.keep,controlsBusy&&s.disabled]}><Text style={s.cancelText}>KEEP BOOKING</Text></Pressable><Pressable disabled={controlsBusy} onPress={()=>void advance(b.id,'CANCELLED')} style={[s.confirmCancel,controlsBusy&&s.disabled]}><Text style={s.confirmCancelText}>{busy===b.id?'CANCELLING…':'YES, CANCEL'}</Text></Pressable></View></View>}</View>})}</>:<View style={s.empty}><Text style={s.emptyTitle}>No bookings yet.</Text><Text style={s.meta}>Accepted customer quotes will create real bookings here.</Text></View>}</ScrollView></SafeAreaView>}
const createStyles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:50,maxWidth:760,width:'100%',alignSelf:'center'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:c.muted},title:{fontSize:31,fontWeight:'900',marginTop:7,marginBottom:22,color:c.text},card:{backgroundColor:c.surface,borderRadius:17,borderWidth:1,borderColor:c.border,padding:17,marginBottom:10},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},status:{fontSize:9,fontWeight:'900',color:c.text},amount:{fontSize:20,fontWeight:'900',color:c.text},meta:{fontSize:11,color:c.muted,marginTop:7},message:{height:43,borderRadius:12,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center',marginTop:13},messageText:{fontSize:9,fontWeight:'900',color:c.text},button:{height:46,borderRadius:13,backgroundColor:c.text,alignItems:'center',justifyContent:'center',marginTop:9},buttonText:{color:c.canvas,fontSize:9,fontWeight:'900'},cancel:{height:43,borderRadius:12,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center',marginTop:9},cancelText:{fontSize:9,fontWeight:'900',color:c.text},confirmBox:{marginTop:9,padding:12,borderRadius:12,backgroundColor:c.soft,borderWidth:1,borderColor:c.border},confirmText:{fontSize:11,lineHeight:16,color:c.text},confirmRow:{flexDirection:'row',gap:8,marginTop:10},keep:{flex:1,minHeight:42,borderRadius:10,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center',paddingHorizontal:8},confirmCancel:{flex:1,minHeight:42,borderRadius:10,backgroundColor:c.danger,alignItems:'center',justifyContent:'center',paddingHorizontal:8},confirmCancelText:{fontSize:9,fontWeight:'900',color:'#fff'},empty:{backgroundColor:c.surface,borderRadius:19,padding:28,alignItems:'center',borderWidth:1,borderColor:c.border},emptyTitle:{fontSize:16,fontWeight:'800',color:c.text},error:{fontSize:12,color:c.danger,textAlign:'center'},retry:{minHeight:42,borderRadius:12,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center',marginTop:12,paddingHorizontal:16},retryText:{fontSize:9,fontWeight:'900',letterSpacing:.6,color:c.text},warning:{backgroundColor:c.soft,borderRadius:14,padding:14,marginBottom:12,borderWidth:1,borderColor:c.border},warningText:{fontSize:12,lineHeight:18,color:c.text},disabled:{opacity:.5}});