import {useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {router} from 'expo-router';
import {BusinessTabBar} from '@/components/BusinessTabBar';
import {ModeSwitcher} from '@/components/ModeSwitcher';
import {setBusinessAvailability,setBusinessBookingSettings,setServiceBookingSettings,type BusinessAvailability} from '@/lib/crm';
import {getWorkspaceContext,type BusinessWorkspace} from '@/lib/workspace';
import {supabase} from '@/lib/supabase';
import {type ThemeColors,useAppTheme} from '@/lib/theme';

const statuses:BusinessAvailability['status'][]=['AVAILABLE_NOW','AVAILABLE_LATER','BUSY','OFFLINE'];

export default function BusinessAvailabilityScreen(){
 const {colors}=useAppTheme();const st=useMemo(()=>styles(colors),[colors]);
 const [business,setBusiness]=useState<BusinessWorkspace|null>(null);const [status,setStatus]=useState<BusinessAvailability['status']>('OFFLINE');const [from,setFrom]=useState('');const [until,setUntil]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 const [instant,setInstant]=useState(false);const [capacity,setCapacity]=useState('1');const [workStart,setWorkStart]=useState('09:00');const [workEnd,setWorkEnd]=useState('17:00');const [services,setServices]=useState<Array<{id:string;name:string;service_booking_settings:{instant_booking_enabled:boolean}|{instant_booking_enabled:boolean}[]|null}>>([]);
 async function load(){setLoading(true);setError('');try{const ctx=await getWorkspaceContext();if(ctx.mode!=='BUSINESS'||!ctx.active_business_id){router.replace('/');return;}const current=ctx.businesses.find(b=>b.id===ctx.active_business_id);if(!current)throw new Error('Business access unavailable.');setBusiness(current);const [availability,settings,serviceRows]=await Promise.all([supabase.from('business_availability').select('*').eq('business_id',current.id).maybeSingle(),supabase.from('business_booking_settings').select('*').eq('business_id',current.id).maybeSingle(),supabase.from('services').select('id,name,service_booking_settings(instant_booking_enabled)').eq('business_id',current.id).eq('active',true).order('name')]);if(availability.error)throw availability.error;if(settings.error)throw settings.error;if(serviceRows.error)throw serviceRows.error;const data=availability.data;if(data){setStatus(data.status);setFrom(data.available_from??'');setUntil(data.available_until??'');}if(settings.data){setInstant(settings.data.instant_booking_enabled);setCapacity(String(settings.data.capacity));const first=(settings.data.weekly_hours as Record<string,Array<{start:string;end:string}>>)?.['1']?.[0];if(first){setWorkStart(first.start);setWorkEnd(first.end);}}setServices((serviceRows.data??[]) as typeof services);}catch(e){setError(e instanceof Error?e.message:'Availability could not be loaded.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function save(){if(!business)return;setSaving(true);setError('');try{let start:string|null=null,end:string|null=null;if(status==='AVAILABLE_LATER'){const a=new Date(from);if(Number.isNaN(a.getTime()))throw new Error('Enter a valid available-from date/time.');start=a.toISOString();if(until.trim()){const b=new Date(until);if(Number.isNaN(b.getTime()))throw new Error('Enter a valid available-until date/time.');end=b.toISOString();}}else if(status==='AVAILABLE_NOW'&&until.trim()){const b=new Date(until);if(Number.isNaN(b.getTime()))throw new Error('Enter a valid available-until date/time.');end=b.toISOString();start=new Date().toISOString();}const cap=Number(capacity);if(!Number.isInteger(cap)||cap<1||cap>100)throw new Error('Capacity must be between 1 and 100.');if(!/^\d\d:\d\d$/.test(workStart)||!/^\d\d:\d\d$/.test(workEnd)||workEnd<=workStart)throw new Error('Enter working hours like 09:00 to 17:00.');const schedule=Object.fromEntries([1,2,3,4,5,6,7].map(day=>[String(day),[{start:workStart,end:workEnd}]]));await Promise.all([setBusinessAvailability(business.id,status,start,end),setBusinessBookingSettings({businessId:business.id,weeklyHours:schedule,capacity:cap,instantBookingEnabled:instant})]);await load();}catch(e){setError(e instanceof Error?e.message:'Availability could not be saved.');}finally{setSaving(false);}}
 return <SafeAreaView style={st.safe} edges={['top']}><View style={{flex:1}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={st.page}>
  <View style={st.header}><View><Text style={st.mode}>BUSINESS MODE</Text><Text style={st.name}>{business?.name??'Business'}</Text></View><ModeSwitcher compact/></View><Text style={st.title}>Availability</Text><Text style={st.copy}>Tell nearby customers when you can actually take work. Matching still applies verification, capability, location and marketplace eligibility.</Text>
  {loading?<ActivityIndicator color={colors.brand} style={{marginTop:50}}/>:<><View style={st.options}>{statuses.map(v=><Pressable key={v} onPress={()=>setStatus(v)} style={[st.option,status===v&&st.optionOn]}><View style={[st.dot,status===v&&st.dotOn]}/><View style={{flex:1}}><Text style={st.optionTitle}>{v.replaceAll('_',' ')}</Text><Text style={st.optionCopy}>{v==='AVAILABLE_NOW'?'Ready for new work now':v==='AVAILABLE_LATER'?'Set the next time you can take work':v==='BUSY'?'Temporarily exclude me from available-now results':'Do not show me as currently available'}</Text></View></Pressable>)}</View>
  {(status==='AVAILABLE_LATER'||status==='AVAILABLE_NOW')?<View style={st.window}><Text style={st.label}>{status==='AVAILABLE_LATER'?'AVAILABLE FROM':'AVAILABLE UNTIL (OPTIONAL)'}</Text>{status==='AVAILABLE_LATER'?<TextInput value={from} onChangeText={setFrom} placeholder="2026-09-26 15:00" placeholderTextColor={colors.muted} style={st.input}/>:null}<Text style={st.label}>AVAILABLE UNTIL (OPTIONAL)</Text><TextInput value={until} onChangeText={setUntil} placeholder="2026-09-26 18:00" placeholderTextColor={colors.muted} style={st.input}/></View>:null}
  <View style={st.window}><Text style={st.label}>INSTANT BOOKING</Text><Pressable onPress={()=>setInstant(value=>!value)} style={[st.option,instant&&st.optionOn,{marginTop:7}]}><View style={[st.dot,instant&&st.dotOn]}/><View style={{flex:1}}><Text style={st.optionTitle}>Allow customers to book a real time slot</Text><Text style={st.optionCopy}>Only enabled services can be booked. Everest checks capacity and calendar conflicts again at checkout.</Text></View></Pressable><Text style={st.label}>EVERYDAY WORKING HOURS</Text><View style={{flexDirection:'row',gap:8}}><TextInput value={workStart} onChangeText={setWorkStart} placeholder="09:00" placeholderTextColor={colors.muted} style={[st.input,{flex:1}]}/><TextInput value={workEnd} onChangeText={setWorkEnd} placeholder="17:00" placeholderTextColor={colors.muted} style={[st.input,{flex:1}]}/></View><Text style={st.label}>MAXIMUM CONCURRENT JOBS</Text><TextInput value={capacity} onChangeText={setCapacity} keyboardType="number-pad" placeholder="1" placeholderTextColor={colors.muted} style={st.input}/></View>
  {services.length?<View style={st.window}><Text style={st.label}>SERVICE INSTANT BOOKING</Text>{services.map(service=>{const raw=service.service_booking_settings;const enabled=Array.isArray(raw)?raw[0]?.instant_booking_enabled:raw?.instant_booking_enabled;return <Pressable key={service.id} disabled={saving} onPress={()=>void setServiceBookingSettings(service.id,!enabled).then(load).catch(e=>setError(e instanceof Error?e.message:'Could not update service booking.'))} style={[st.option,enabled&&st.optionOn,{marginTop:8}]}><View style={[st.dot,enabled&&st.dotOn]}/><View style={{flex:1}}><Text style={st.optionTitle}>{service.name}</Text><Text style={st.optionCopy}>{enabled?'Instant Book enabled':'Quote requests only'}</Text></View></Pressable>})}</View>:null}
  <Pressable disabled={saving} onPress={()=>void save()} style={[st.primary,saving&&{opacity:.6}]}><Text style={st.primaryText}>{saving?'SAVING…':'SAVE AVAILABILITY'}</Text></Pressable></>}
  {error?<Text style={st.error}>{error}</Text>:null}
 </ScrollView><BusinessTabBar active="/business-control"/></View></SafeAreaView>;
}
const styles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:110,maxWidth:760,width:'100%',alignSelf:'center'},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},mode:{fontSize:9,fontWeight:'900',letterSpacing:1.3,color:c.muted},name:{fontSize:15,fontWeight:'900',color:c.text,marginTop:2},title:{fontSize:33,fontWeight:'900',color:c.text,marginTop:25},copy:{fontSize:12,lineHeight:18,color:c.muted,marginTop:5},options:{gap:9,marginTop:20},option:{minHeight:72,borderRadius:18,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,padding:14,flexDirection:'row',alignItems:'center',gap:12},optionOn:{borderColor:c.brand,backgroundColor:c.soft},dot:{width:12,height:12,borderRadius:6,borderWidth:2,borderColor:c.muted},dotOn:{borderColor:c.brand,backgroundColor:c.brand},optionTitle:{fontSize:13,fontWeight:'900',color:c.text},optionCopy:{fontSize:10,lineHeight:15,color:c.muted,marginTop:3},window:{borderRadius:18,borderWidth:1,borderColor:c.border,backgroundColor:c.elevated,padding:14,marginTop:16},label:{fontSize:9,fontWeight:'900',letterSpacing:1.1,color:c.muted,marginTop:8},input:{minHeight:46,borderRadius:13,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,color:c.text,paddingHorizontal:13,marginTop:7},primary:{height:48,borderRadius:14,backgroundColor:c.brand,alignItems:'center',justifyContent:'center',marginTop:16},primaryText:{fontSize:9,fontWeight:'900',color:c.onBrand},error:{fontSize:11,color:c.danger,marginTop:14}});
