import {useCallback,useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {router} from 'expo-router';
import {BusinessTabBar} from '@/components/BusinessTabBar';
import {ModeSwitcher} from '@/components/ModeSwitcher';
import {createBusinessContact,findPossibleDuplicates,listBusinessContacts,type CrmContact,type CrmLeadStatus} from '@/lib/crm';
import {getWorkspaceContext,type BusinessWorkspace} from '@/lib/workspace';
import {type ThemeColors,useAppTheme} from '@/lib/theme';

const stages:CrmLeadStatus[]=['NEW_LEAD','CONTACTED','QUALIFIED','QUOTE_SENT','FOLLOW_UP','WON','LOST'];
const sources=['MANUAL','PHONE','INSTAGRAM','FACEBOOK','WEBSITE','GOOGLE','REFERRAL','WALK_IN','EMAIL','OTHER'];

export default function BusinessCustomers(){
 const {colors}=useAppTheme();const st=useMemo(()=>styles(colors),[colors]);
 const [business,setBusiness]=useState<BusinessWorkspace|null>(null);const [contacts,setContacts]=useState<CrmContact[]>([]);
 const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState('');
 const [adding,setAdding]=useState(false);const [name,setName]=useState('');const [phone,setPhone]=useState('');const [email,setEmail]=useState('');const [source,setSource]=useState('MANUAL');const [value,setValue]=useState('');const [notes,setNotes]=useState('');const [duplicate,setDuplicate]=useState('');
 const load=useCallback(async(refresh=false)=>{if(refresh)setRefreshing(true);else setLoading(true);setError('');
  try{const ctx=await getWorkspaceContext();if(ctx.mode!=='BUSINESS'||!ctx.active_business_id){router.replace('/');return;}const current=ctx.businesses.find(b=>b.id===ctx.active_business_id);if(!current)throw new Error('Business access unavailable.');setBusiness(current);setContacts(await listBusinessContacts(current.id));}
  catch(e){setError(e instanceof Error?e.message:'CRM could not be loaded.');}finally{setLoading(false);setRefreshing(false);}
 },[]);
 useEffect(()=>{void load();},[load]);
 const counts=Object.fromEntries(stages.map(stage=>[stage,contacts.filter(c=>c.lead_status===stage).length]));
 async function add(){if(!business||!name.trim())return;setError('');setDuplicate('');
  try{const matches=await findPossibleDuplicates(business.id,email,phone);if(matches.length){setDuplicate('Possible duplicate customer: '+matches.map((m:{display_name:string})=>m.display_name).join(', ')+'. Review before creating another record.');return;}
   const estimated=value.trim()?Number(value):null;if(estimated!==null&&(!Number.isFinite(estimated)||estimated<0))throw new Error('Enter a valid estimated value.');
   const id=await createBusinessContact({businessId:business.id,name:name.trim(),phone,email,source,estimatedValue:estimated,notes});
   setAdding(false);setName('');setPhone('');setEmail('');setValue('');setNotes('');await load(true);router.push({pathname:'/business-customer',params:{id}});
  }catch(e){setError(e instanceof Error?e.message:'Customer could not be added.');}
 }
 return <SafeAreaView style={st.safe} edges={['top']}><View style={{flex:1}}><ScrollView keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={colors.brand}/>} contentContainerStyle={st.page}>
  <View style={st.header}><View><Text style={st.mode}>BUSINESS MODE</Text><Text style={st.name}>{business?.name??'Business'}</Text></View><ModeSwitcher compact/></View>
  <View style={st.titleRow}><View><Text style={st.title}>Customers</Text><Text style={st.copy}>Everest and outside-Everest customers in one private workspace.</Text></View><Pressable onPress={()=>setAdding(v=>!v)} style={st.add}><Ionicons name={adding?'close':'add'} size={20} color={colors.onBrand}/></Pressable></View>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={st.pipeline}>{stages.map(stage=><View key={stage} style={st.stage}><Text style={st.stageN}>{counts[stage]??0}</Text><Text style={st.stageL}>{stage.replaceAll('_',' ')}</Text></View>)}</ScrollView>
  {adding?<View style={st.form}><Text style={st.formTitle}>Add customer or lead</Text><TextInput value={name} onChangeText={setName} placeholder="Name" placeholderTextColor={colors.muted} style={st.input}/><View style={st.row}><TextInput value={phone} onChangeText={setPhone} placeholder="Phone" placeholderTextColor={colors.muted} style={[st.input,{flex:1}]}/><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Email" placeholderTextColor={colors.muted} style={[st.input,{flex:1}]}/></View><Text style={st.label}>SOURCE</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={st.chips}>{sources.map(v=><Pressable key={v} onPress={()=>setSource(v)} style={[st.chip,source===v&&st.chipOn]}><Text style={[st.chipText,source===v&&st.chipTextOn]}>{v.replaceAll('_',' ')}</Text></Pressable>)}</ScrollView><TextInput value={value} onChangeText={setValue} keyboardType="decimal-pad" placeholder="Estimated value (optional)" placeholderTextColor={colors.muted} style={st.input}/><TextInput value={notes} onChangeText={setNotes} multiline placeholder="Notes" placeholderTextColor={colors.muted} style={[st.input,st.notes]}/>{duplicate?<View style={st.warning}><Text style={st.warningText}>{duplicate}</Text><Text style={st.warningHint}>Open the existing customer or clear the matching email/phone if these are genuinely different people.</Text></View>:null}<Pressable onPress={()=>void add()} style={st.primary}><Text style={st.primaryText}>ADD TO CRM</Text></Pressable></View>:null}
  {loading?<ActivityIndicator color={colors.brand} style={{marginTop:40}}/>:contacts.length?contacts.map(c=><Pressable key={c.id} onPress={()=>router.push({pathname:'/business-customer',params:{id:c.id}})} style={({pressed})=>[st.card,pressed&&{opacity:.72}]}><View style={st.avatar}><Text style={st.avatarText}>{c.display_name.slice(0,2).toUpperCase()}</Text></View><View style={{flex:1}}><View style={st.cardTop}><Text numberOfLines={1} style={st.cardTitle}>{c.display_name}</Text><Text style={st.status}>{c.lead_status.replaceAll('_',' ')}</Text></View><Text style={st.meta}>{[c.source.replaceAll('_',' '),c.suburb||c.city].filter(Boolean).join(' · ')||'CRM customer'}</Text><Text numberOfLines={1} style={st.meta}>{c.phone||c.email||'No contact detail yet'}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted}/></Pressable>):<View style={st.empty}><Text style={st.emptyTitle}>Your CRM is ready.</Text><Text style={st.copy}>Add the first phone, Instagram, Google, referral or walk-in customer. Everest marketplace customers can be linked here too.</Text></View>}
  {error?<Text style={st.error}>{error}</Text>:null}
 </ScrollView><BusinessTabBar active="/business-customers"/></View></SafeAreaView>;
}
const styles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:110,maxWidth:760,width:'100%',alignSelf:'center'},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},mode:{fontSize:9,fontWeight:'900',letterSpacing:1.3,color:c.muted},name:{fontSize:15,fontWeight:'900',color:c.text,marginTop:2},titleRow:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',gap:16,marginTop:25},title:{fontSize:33,fontWeight:'900',color:c.text},copy:{fontSize:12,lineHeight:18,color:c.muted,marginTop:5},add:{width:44,height:44,borderRadius:15,backgroundColor:c.brand,alignItems:'center',justifyContent:'center'},pipeline:{gap:8,paddingVertical:18},stage:{minWidth:104,borderRadius:17,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,padding:13},stageN:{fontSize:22,fontWeight:'900',color:c.text},stageL:{fontSize:8,fontWeight:'900',color:c.muted,marginTop:3},form:{borderRadius:20,borderWidth:1,borderColor:c.border,backgroundColor:c.elevated,padding:16,marginBottom:14},formTitle:{fontSize:18,fontWeight:'900',color:c.text},input:{minHeight:48,borderRadius:13,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,color:c.text,paddingHorizontal:13,marginTop:10},row:{flexDirection:'row',gap:8},notes:{minHeight:86,paddingTop:12,textAlignVertical:'top'},label:{fontSize:9,fontWeight:'900',letterSpacing:1.1,color:c.muted,marginTop:14},chips:{gap:7,paddingTop:8},chip:{height:34,borderRadius:17,borderWidth:1,borderColor:c.border,paddingHorizontal:11,alignItems:'center',justifyContent:'center'},chipOn:{backgroundColor:c.brand,borderColor:c.brand},chipText:{fontSize:8,fontWeight:'900',color:c.text},chipTextOn:{color:c.onBrand},primary:{height:46,borderRadius:14,backgroundColor:c.brand,alignItems:'center',justifyContent:'center',marginTop:12},primaryText:{fontSize:9,fontWeight:'900',color:c.onBrand},warning:{borderRadius:14,backgroundColor:c.soft,padding:12,marginTop:10},warningText:{fontSize:11,fontWeight:'900',color:c.text},warningHint:{fontSize:10,lineHeight:15,color:c.muted,marginTop:3},card:{minHeight:82,borderBottomWidth:1,borderBottomColor:c.border,flexDirection:'row',alignItems:'center',gap:12},avatar:{width:44,height:44,borderRadius:15,backgroundColor:c.soft,alignItems:'center',justifyContent:'center'},avatarText:{fontSize:11,fontWeight:'900',color:c.brand},cardTop:{flexDirection:'row',alignItems:'center',gap:8},cardTitle:{fontSize:14,fontWeight:'900',color:c.text,flex:1},status:{fontSize:8,fontWeight:'900',color:c.brand},meta:{fontSize:10,color:c.muted,marginTop:3},empty:{borderRadius:18,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,padding:22},emptyTitle:{fontSize:17,fontWeight:'900',color:c.text},error:{fontSize:11,color:c.danger,marginTop:12}});
