import {useCallback,useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {router} from 'expo-router';
import {BusinessTabBar} from '@/components/BusinessTabBar';
import {ModeSwitcher} from '@/components/ModeSwitcher';
import {listCrmBookings,listCrmOpportunities,listCrmQuotes,listCrmTasks,type CrmOpportunity,type CrmTask} from '@/lib/crm';
import {getWorkspaceContext,type BusinessWorkspace} from '@/lib/workspace';
import {supabase} from '@/lib/supabase';
import {type ThemeColors,useAppTheme} from '@/lib/theme';

type Priority={kind:'OVERDUE'|'NEW_LEAD'|'QUOTE'|'JOB'|'STALE'|'MESSAGE';title:string;subtitle:string;action:string;run:()=>void};
type Snapshot={newLeads:number;openDeals:number;pipelineValue:number;overdue:number;quotesWaiting:number;jobsToday:number;unread:number;stale:number;orders:number;revenue:number|null;completed:number};
const dayStart=(date=new Date())=>new Date(date.getFullYear(),date.getMonth(),date.getDate());
const money=(n:number)=>new Intl.NumberFormat(undefined,{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(n);

export default function BusinessToday(){
 const {colors}=useAppTheme();const st=useMemo(()=>styles(colors),[colors]);const [business,setBusiness]=useState<BusinessWorkspace|null>(null);const [snap,setSnap]=useState<Snapshot>({newLeads:0,openDeals:0,pipelineValue:0,overdue:0,quotesWaiting:0,jobsToday:0,unread:0,stale:0,orders:0,revenue:null,completed:0});const [priority,setPriority]=useState<Priority[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState('');
 const load=useCallback(async(refresh=false)=>{if(refresh)setRefreshing(true);else setLoading(true);setError('');try{
  const ctx=await getWorkspaceContext();if(ctx.mode!=='BUSINESS'||!ctx.active_business_id){router.replace('/');return;}const current=ctx.businesses.find(item=>item.id===ctx.active_business_id);if(!current){router.replace('/');return;}setBusiness(current);
  if(current.verification_status!=='VERIFIED'){setSnap({newLeads:0,openDeals:0,pipelineValue:0,overdue:0,quotesWaiting:0,jobsToday:0,unread:0,stale:0,orders:0,revenue:null,completed:0});setPriority([]);return;}
  const id=current.id,today=dayStart(),tomorrow=new Date(today.getTime()+86400000),todayIso=[today.getFullYear(),String(today.getMonth()+1).padStart(2,'0'),String(today.getDate()).padStart(2,'0')].join('-'),weekAgo=new Date(Date.now()-7*86400000).toISOString();
  const [deals,tasks,crmQuotes,crmBookings,nativeQuotes,nativeJobs,orders,conversations,payouts,completed]=await Promise.all([
   listCrmOpportunities(id),listCrmTasks(id),listCrmQuotes(id),listCrmBookings(id),
   supabase.from('quotes').select('id,status,total,updated_at,description').eq('business_id',id).in('status',['SENT','VIEWED']),
   supabase.from('bookings').select('id,status,price,scheduled_date,scheduled_time,request_id').eq('business_id',id).eq('scheduled_date',todayIso).in('status',['CONFIRMED','UPCOMING','IN_PROGRESS']).order('scheduled_time'),
   supabase.from('orders').select('id,order_number,status',{count:'exact'}).eq('business_id',id).in('status',['PAYMENT_CONFIRMED','ACCEPTED','PREPARING','READY_FOR_PICKUP']).order('created_at').limit(1),
   supabase.from('conversations').select('id,messages(id,sender_id,read_at,body,created_at)').eq('business_id',id),
   supabase.from('payouts').select('net_amount,created_at').eq('business_id',id).gte('created_at',weekAgo),
   supabase.from('bookings').select('id',{count:'exact',head:true}).eq('business_id',id).eq('status','COMPLETED').gte('completed_at',weekAgo),
  ]);
  for(const r of [nativeQuotes,nativeJobs,orders,conversations,payouts,completed])if(r.error)throw r.error;
  const open=deals.filter(d=>d.status==='OPEN'),newLeads=open.filter(d=>d.stage?.stage_key==='NEW_LEAD'),overdue=tasks.filter(t=>t.status==='OPEN'&&new Date(t.due_at)<new Date()),waiting=crmQuotes.filter(q=>['SENT','VIEWED'].includes(q.status)),todayCrm=crmBookings.filter(b=>!['CANCELLED','NO_SHOW'].includes(b.status)&&new Date(b.scheduled_start)>=today&&new Date(b.scheduled_start)<tomorrow),stale=open.filter(d=>Date.now()-new Date(d.last_activity_at).getTime()>=3*86400000);
  const {data:{user}}=await supabase.auth.getUser();const unreadRows=(conversations.data??[]).flatMap(row=>(row.messages??[] as Array<{id:string;sender_id:string;read_at:string|null;body:string;created_at:string}>).filter(m=>m.sender_id!==user?.id&&!m.read_at).map(m=>({...m,conversationId:row.id}))).sort((a,b)=>b.created_at.localeCompare(a.created_at));
  const revenue=(payouts.data??[]).length?(payouts.data??[]).reduce((sum,row)=>sum+Number(row.net_amount||0),0):null;
  setSnap({newLeads:newLeads.length,openDeals:open.length,pipelineValue:open.reduce((s,d)=>s+Number(d.estimated_value||0),0),overdue:overdue.length,quotesWaiting:waiting.length+(nativeQuotes.data?.length??0),jobsToday:todayCrm.length+(nativeJobs.data?.length??0),unread:unreadRows.length,stale:stale.length,orders:orders.count??0,revenue,completed:completed.count??0});
  const priorities:Priority[]=[];const firstOverdue=[...overdue].sort((a,b)=>a.due_at.localeCompare(b.due_at))[0];if(firstOverdue)priorities.push(taskPriority(firstOverdue));const firstLead=newLeads[0];if(firstLead)priorities.push(dealPriority('NEW_LEAD',firstLead,'New lead needs a first response'));const viewed=crmQuotes.find(q=>q.status==='VIEWED');if(viewed)priorities.push({kind:'QUOTE',title:'Quote #'+viewed.quote_number+' was viewed',subtitle:'Waiting for a customer decision',action:'OPEN QUOTE',run:()=>router.push({pathname:'/business-crm-quote',params:{id:viewed.id}})});const job=todayCrm[0];if(job)priorities.push({kind:'JOB',title:job.service_label,subtitle:new Date(job.scheduled_start).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})+' · CRM booking',action:'OPEN BOOKING',run:()=>router.push({pathname:'/business-crm-booking',params:{id:job.id}})});else if(nativeJobs.data?.[0])priorities.push({kind:'JOB',title:'Everest job today',subtitle:String(nativeJobs.data[0].scheduled_time??'Time pending').slice(0,5)+' · '+String(nativeJobs.data[0].status).replaceAll('_',' '),action:'OPEN CALENDAR',run:()=>router.push('/business-calendar')});const staleDeal=stale.find(d=>!d.next_task);if(staleDeal)priorities.push(dealPriority('STALE',staleDeal,'No activity for 3+ days and no next task'));if(unreadRows[0])priorities.push({kind:'MESSAGE',title:'Unread customer message',subtitle:unreadRows[0].body||'Open the conversation',action:'OPEN INBOX',run:()=>router.push('/business-inbox')});setPriority(priorities.slice(0,6));
 }catch(e){setError(e instanceof Error?e.message:'Business activity could not be loaded right now.');}finally{setLoading(false);setRefreshing(false);}},[]);
 useEffect(()=>{void load();},[load]);
 function taskPriority(task:CrmTask):Priority{return{kind:'OVERDUE',title:task.task,subtitle:'Overdue since '+new Date(task.due_at).toLocaleString(),action:'OPEN TASKS',run:()=>router.push({pathname:'/business-crm',params:{view:'TASKS'}})}}
 function dealPriority(kind:'NEW_LEAD'|'STALE',deal:CrmOpportunity,subtitle:string):Priority{return{kind,title:deal.title,subtitle,action:'OPEN DEAL',run:()=>router.push({pathname:'/business-deal',params:{id:deal.id}})}}
 const verified=business?.verification_status==='VERIFIED';const cards:[string,number,keyof typeof Ionicons.glyphMap,()=>void][]=[['New leads',snap.newLeads,'person-add-outline',()=>router.push('/business-crm')],['Overdue',snap.overdue,'alarm-outline',()=>router.push({pathname:'/business-crm',params:{view:'TASKS'}})],['Quotes waiting',snap.quotesWaiting,'receipt-outline',()=>router.push('/business-crm')],['Jobs today',snap.jobsToday,'calendar-outline',()=>router.push('/business-calendar')],['Unread',snap.unread,'chatbubble-outline',()=>router.push('/business-inbox')],['Stale deals',snap.stale,'warning-outline',()=>router.push('/business-crm')]];
 return <SafeAreaView style={st.safe} edges={['top']}><View style={{flex:1}}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={colors.brand}/>} contentContainerStyle={st.page}>
  <View style={st.header}><View style={{flex:1}}><Text style={st.mode}>BUSINESS MODE</Text><Text style={st.name}>{business?.name??'Business'}</Text></View><ModeSwitcher compact/><Pressable onPress={()=>router.push('/notifications')} style={st.icon}><Ionicons name="notifications-outline" size={19} color={colors.text}/></Pressable></View>
  {loading?<ActivityIndicator color={colors.brand} style={{marginTop:60}}/>:<><Text style={st.title}>Today</Text><Text style={st.copy}>The work that needs attention—not a dashboard full of vanity metrics.</Text>
   {!verified&&business?<View style={st.setup}><Text style={st.setupTitle}>Finish setting up {business.name}</Text><Text style={st.copy}>Business operations stay restricted until verification is complete.</Text><Pressable onPress={()=>router.push('/business-verification')} style={st.primary}><Text style={st.primaryText}>OPEN VERIFICATION</Text></Pressable></View>:null}
   {verified?<><View style={st.hero}><View><Text style={st.heroLabel}>OPEN PIPELINE</Text><Text style={st.heroValue}>{money(snap.pipelineValue)}</Text><Text style={st.heroHint}>{snap.openDeals} open opportunities</Text></View><Pressable onPress={()=>router.push('/business-crm')} style={st.heroLink}><Text style={st.heroLinkText}>OPEN CRM →</Text></Pressable></View>
   <View style={st.strip}>{cards.map(([label,n,icon,run])=><Pressable key={label} onPress={run} style={st.stat}><Ionicons name={icon} size={17} color={n>0?colors.brand:colors.muted}/><Text style={st.statNumber}>{n}</Text><Text style={st.statLabel}>{label}</Text></Pressable>)}</View>
   <View style={st.section}><Text style={st.sectionLabel}>PRIORITIES</Text>{priority.length?priority.map((item,index)=><Pressable key={item.kind+index} onPress={item.run} style={[st.priority,{borderBottomColor:colors.border}]}><View style={[st.priorityIcon,{backgroundColor:item.kind==='OVERDUE'||item.kind==='STALE'?colors.soft:colors.surface}]}><Ionicons name={item.kind==='OVERDUE'?'alarm-outline':item.kind==='NEW_LEAD'?'person-add-outline':item.kind==='QUOTE'?'receipt-outline':item.kind==='JOB'?'calendar-outline':item.kind==='STALE'?'warning-outline':'chatbubble-outline'} size={18} color={item.kind==='OVERDUE'||item.kind==='STALE'?colors.danger:colors.brand}/></View><View style={{flex:1}}><Text style={st.priorityTitle}>{item.title}</Text><Text style={st.prioritySub}>{item.subtitle}</Text></View><Text style={st.priorityAction}>{item.action}</Text></Pressable>):<View style={st.clear}><Text style={st.clearTitle}>Nothing urgent right now.</Text><Text style={st.copy}>New leads, overdue follow-ups, viewed quotes and upcoming work will surface here.</Text></View>}</View>
   {(snap.revenue!==null||snap.completed>0)?<View style={st.section}><Text style={st.sectionLabel}>THIS WEEK</Text><View style={st.performance}>{snap.revenue!==null?<View><Text style={st.metric}>{money(snap.revenue)}</Text><Text style={st.metricLabel}>Net payouts</Text></View>:null}<View><Text style={st.metric}>{snap.completed}</Text><Text style={st.metricLabel}>Completed Everest jobs</Text></View></View></View>:null}
   <View style={st.section}><Text style={st.sectionLabel}>QUICK ACTIONS</Text><View style={st.actions}><Quick label="New contact" icon="person-add-outline" onPress={()=>router.push('/business-customers')} colors={colors}/><Quick label="New booking" icon="calendar-outline" onPress={()=>router.push('/business-crm-booking')} colors={colors}/><Quick label="CRM tasks" icon="checkmark-circle-outline" onPress={()=>router.push({pathname:'/business-crm',params:{view:'TASKS'}})} colors={colors}/><Quick label="Everest leads" icon="flash-outline" onPress={()=>router.push('/business-leads')} colors={colors}/><Quick label="Create post" icon="add-circle-outline" onPress={()=>router.push('/create-post')} colors={colors}/><Quick label="Business controls" icon="storefront-outline" onPress={()=>router.push('/business-control')} colors={colors}/></View></View></>:null}
   {error?<View style={st.notice}><Text style={st.noticeText}>{error}</Text></View>:null}
  </>}</ScrollView><BusinessTabBar active="/business-today"/></View></SafeAreaView>;
}
function Quick({label,icon,onPress,colors}:{label:string;icon:keyof typeof Ionicons.glyphMap;onPress:()=>void;colors:ThemeColors}){return <Pressable onPress={onPress} style={[quickStyles.quick,{borderColor:colors.border,backgroundColor:colors.surface}]}><Ionicons name={icon} size={17} color={colors.brand}/><Text style={[quickStyles.quickText,{color:colors.text}]}>{label}</Text></Pressable>}
const quickStyles=StyleSheet.create({quick:{minHeight:48,borderRadius:13,borderWidth:1,paddingHorizontal:13,flexDirection:'row',alignItems:'center',gap:8,flexBasis:'48%',flexGrow:1},quickText:{fontSize:10,fontWeight:'800'}});
const styles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:110,maxWidth:920,width:'100%',alignSelf:'center'},header:{flexDirection:'row',alignItems:'center',gap:10},mode:{fontSize:9,fontWeight:'900',letterSpacing:1.3,color:c.muted},name:{fontSize:15,fontWeight:'900',color:c.text,marginTop:2},icon:{width:40,height:40,borderRadius:12,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center'},title:{fontSize:34,fontWeight:'900',color:c.text,marginTop:25},copy:{fontSize:11,lineHeight:17,color:c.muted,marginTop:4},hero:{marginTop:18,borderWidth:1,borderColor:c.border,borderRadius:18,backgroundColor:c.elevated,padding:17,flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',gap:12},heroLabel:{fontSize:8,fontWeight:'900',letterSpacing:1.1,color:c.muted},heroValue:{fontSize:30,fontWeight:'900',color:c.text,marginTop:4},heroHint:{fontSize:9,color:c.muted,marginTop:3},heroLink:{height:36,borderRadius:10,borderWidth:1,borderColor:c.border,paddingHorizontal:10,justifyContent:'center'},heroLinkText:{fontSize:8,fontWeight:'900',color:c.text},strip:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:10},stat:{minWidth:115,flexGrow:1,flexBasis:120,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,borderRadius:14,padding:12},statNumber:{fontSize:21,fontWeight:'900',color:c.text,marginTop:6},statLabel:{fontSize:8,fontWeight:'800',color:c.muted,marginTop:3},section:{marginTop:25},sectionLabel:{fontSize:8,fontWeight:'900',letterSpacing:1.2,color:c.muted,marginBottom:7},priority:{minHeight:70,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:10},priorityIcon:{width:40,height:40,borderRadius:12,alignItems:'center',justifyContent:'center'},priorityTitle:{fontSize:11,fontWeight:'900',color:c.text},prioritySub:{fontSize:9,color:c.muted,marginTop:3},priorityAction:{fontSize:7,fontWeight:'900',color:c.brand},clear:{borderWidth:1,borderColor:c.border,backgroundColor:c.surface,borderRadius:16,padding:18},clearTitle:{fontSize:14,fontWeight:'900',color:c.text},performance:{flexDirection:'row',gap:30,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,borderRadius:16,padding:16},metric:{fontSize:22,fontWeight:'900',color:c.text},metricLabel:{fontSize:9,color:c.muted,marginTop:3},actions:{flexDirection:'row',flexWrap:'wrap',gap:8},notice:{backgroundColor:c.soft,borderRadius:13,padding:12,marginTop:14},noticeText:{fontSize:10,color:c.text},setup:{backgroundColor:c.elevated,borderRadius:18,borderWidth:1,borderColor:c.border,padding:18,marginTop:18},setupTitle:{fontSize:16,fontWeight:'900',color:c.text},primary:{height:44,borderRadius:12,backgroundColor:c.brand,alignItems:'center',justifyContent:'center',marginTop:13},primaryText:{fontSize:9,fontWeight:'900',color:c.onBrand}});
