import {Ionicons} from '@expo/vector-icons';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,RefreshControl,ScrollView,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {BusinessTabBar} from '@/components/BusinessTabBar';
import {Avatar,Empty,Field,JobCard,Metric,Section,Tag} from '@/components/BusinessOperationsPrimitives';
import {businessOperationsStyles as styles} from '@/components/BusinessOperationsStyles';
import {ModeSwitcher} from '@/components/ModeSwitcher';
import {
 BUSINESS_ROLES,assignBusinessJob,createBusinessLocation,createBusinessTeam,getOperationsDashboard,
 inviteBusinessMember,removeBusinessMember,revokeBusinessInvitation,setBusinessTeamMember,updateBusinessMember,
 type BusinessMember,type BusinessRole,type OperationsDashboard,type OperationsJob,
} from '@/lib/business-operations';
import {getWorkspaceContext,type BusinessWorkspace} from '@/lib/workspace';
import {useAppTheme} from '@/lib/theme';
import {haptic} from '@/lib/haptics';

type Tab='OVERVIEW'|'DISPATCH'|'TEAM'|'STRUCTURE';
const roleLabel=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const when=(value:string|null)=>value?new Date(value).toLocaleString(undefined,{weekday:'short',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}):'Schedule pending';

export default function BusinessOperations(){
 const {colors}=useAppTheme();const s=useMemo(()=>styles(colors),[colors]);
 const [business,setBusiness]=useState<BusinessWorkspace|null>(null);const [data,setData]=useState<OperationsDashboard|null>(null);const [tab,setTab]=useState<Tab>('OVERVIEW');
 const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [busy,setBusy]=useState('');const [error,setError]=useState('');
 const [email,setEmail]=useState('');const [name,setName]=useState('');const [title,setTitle]=useState('');const [role,setRole]=useState<BusinessRole>('TECHNICIAN');const [dispatchable,setDispatchable]=useState(true);
 const [locationName,setLocationName]=useState('');const [address,setAddress]=useState('');const [suburb,setSuburb]=useState('');const [postcode,setPostcode]=useState('');
 const [teamName,setTeamName]=useState('');const [teamDescription,setTeamDescription]=useState('');
 const [editing,setEditing]=useState<BusinessMember|null>(null);const [editRole,setEditRole]=useState<BusinessRole>('TECHNICIAN');const [editDispatch,setEditDispatch]=useState(false);

 const load=useCallback(async(refresh=false)=>{if(refresh)setRefreshing(true);else setLoading(true);setError('');try{
  const ctx=await getWorkspaceContext();if(ctx.mode!=='BUSINESS'||!ctx.active_business_id)throw new Error('Business Mode is not active.');
  const current=ctx.businesses.find(x=>x.id===ctx.active_business_id);if(!current)throw new Error('Business access unavailable.');setBusiness(current);setData(await getOperationsDashboard(current.id));
 }catch(e){setError(e instanceof Error?e.message:'Operations could not be loaded.');}finally{setLoading(false);setRefreshing(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function run(key:string,work:()=>Promise<void>){if(busy)return;setBusy(key);setError('');try{await work();void haptic.success();await load(true)}catch(e){setError(e instanceof Error?e.message:'That change could not be completed.')}finally{setBusy('')}}
 async function invite(){if(!business||!email.trim())return;await run('invite',async()=>{await inviteBusinessMember({businessId:business.id,email,role,displayName:name,jobTitle:title,isDispatchable:dispatchable});setEmail('');setName('');setTitle('')})}
 async function addLocation(){if(!business||!locationName.trim())return;await run('location',async()=>{await createBusinessLocation({businessId:business.id,name:locationName,addressLine:address,suburb,city:'Sydney',state:'NSW',postcode});setLocationName('');setAddress('');setSuburb('');setPostcode('')})}
 async function addTeam(){if(!business||!teamName.trim())return;await run('team',async()=>{await createBusinessTeam({businessId:business.id,name:teamName,description:teamDescription});setTeamName('');setTeamDescription('')})}
 async function saveMember(){if(!business||!editing)return;await run('member:'+editing.user_id,async()=>{await updateBusinessMember({businessId:business.id,userId:editing.user_id,role:editRole,jobTitle:editing.job_title??undefined,employeeNumber:editing.employee_number??undefined,locationId:editing.location_id,isDispatchable:editDispatch,status:editing.status==='SUSPENDED'?'SUSPENDED':'ACTIVE'});setEditing(null)})}
 async function assign(job:OperationsJob,target:{userId?:string;teamId?:string}){if(!business)return;await run('assign',async()=>{await assignBusinessJob({businessId:business.id,bookingId:job.booking_id,crmBookingId:job.crm_booking_id,assignedUserId:target.userId??null,teamId:target.teamId??null})})}
 if(loading)return <SafeAreaView style={s.safe}><ActivityIndicator color={colors.brand} style={{marginTop:80}}/></SafeAreaView>;
 const p=data?.permissions;const members=data?.members??[];const teams=data?.teams??[];const locations=data?.locations??[];const jobs=data?.unassigned_jobs??[];const assignments=data?.assignments??[];
 return <SafeAreaView style={s.safe} edges={['top']}><View style={{flex:1}}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={colors.brand}/>} contentContainerStyle={s.page} showsVerticalScrollIndicator={false}>
  <View style={s.header}><View><Text style={s.eyebrow}>EVEREST OPERATIONS</Text><Text style={s.business}>{business?.name??'Business'}</Text></View><ModeSwitcher compact/></View>
  <View style={s.hero}><View style={{flex:1}}><Text style={s.title}>Run the operation.</Text><Text style={s.copy}>People, crews, locations and real jobs stay under one business identity. Permissions are enforced by the backend.</Text></View><View style={s.heroIcon}><Ionicons name="git-network-outline" size={25} color={colors.brand}/></View></View>
  <View style={s.tabs}>{(['OVERVIEW','DISPATCH','TEAM','STRUCTURE'] as Tab[]).map(x=><Pressable key={x} onPress={()=>setTab(x)} style={[s.tab,tab===x&&s.tabOn]}><Text style={[s.tabText,tab===x&&s.tabTextOn]}>{x}</Text></Pressable>)}</View>
  {error?<View style={s.errorBox}><Ionicons name="alert-circle-outline" size={18} color={colors.danger}/><Text style={s.error}>{error}</Text></View>:null}

  {tab==='OVERVIEW'&&<>
   <View style={s.metrics}><Metric icon="people-outline" value={String(data?.stats.active_staff??0)} label="ACTIVE STAFF" colors={colors}/><Metric icon="flash-outline" value={String(data?.stats.dispatchable_staff??0)} label="DISPATCHABLE" colors={colors}/><Metric icon="people-circle-outline" value={String(data?.stats.teams??0)} label="TEAMS" colors={colors}/><Metric icon="briefcase-outline" value={String(data?.stats.active_assignments??0)} label="LIVE ASSIGNMENTS" colors={colors}/></View>
   <Section title="Live work" copy="Unassigned and currently dispatched work in one place." colors={colors}/>
   {jobs.length?jobs.slice(0,4).map(job=><JobCard key={(job.booking_id??job.crm_booking_id)!} job={job} canAssign={p?.job_assign===true} onAssign={()=>setTab('DISPATCH')} colors={colors}/>):<Empty icon="checkmark-done-outline" title="No unassigned work" copy="New Everest and CRM bookings will appear here when they need an owner." colors={colors}/>} 
   {!!assignments.length&&<><Section title="In motion" copy="Current staff and crew assignments." colors={colors}/>{assignments.slice(0,6).map(a=><View key={a.id} style={s.assignment}><View><Text style={s.cardTitle}>{a.assignee_name}</Text><Text style={s.meta}>{a.status.replaceAll('_',' ')} · {when(a.updated_at)}</Text></View><Ionicons name="pulse" size={18} color={colors.brand}/></View>)}</>}
  </>}

  {tab==='DISPATCH'&&<>
   <Section title="Dispatch board" copy={p?.job_assign?'Assign jobs to an individual or a crew.':'You have read-only visibility for dispatch.'} colors={colors}/>
   {jobs.length?jobs.map(job=><View key={(job.booking_id??job.crm_booking_id)!} style={s.card}><JobCard job={job} canAssign={false} colors={colors}/>{p?.job_assign?<><Text style={s.mini}>ASSIGN TO PERSON</Text><View style={s.chips}>{members.filter(m=>m.status==='ACTIVE'&&m.is_dispatchable).map(m=><Pressable disabled={!!busy} key={m.user_id} onPress={()=>void assign(job,{userId:m.user_id})} style={s.person}><Avatar name={m.name} colors={colors}/><View><Text style={s.chipStrong}>{m.name}</Text><Text style={s.chipSub}>{roleLabel(m.member_role)}</Text></View></Pressable>)}</View><Text style={s.mini}>OR CREW</Text><View style={s.chips}>{teams.map(t=><Pressable disabled={!!busy} key={t.id} onPress={()=>void assign(job,{teamId:t.id})} style={s.teamChip}><Ionicons name="people-outline" size={15} color={colors.text}/><Text style={s.chipStrong}>{t.name}</Text></Pressable>)}</View></>:null}</View>):<Empty icon="sparkles-outline" title="Dispatch is clear" copy="Every current job is assigned or there is no work waiting." colors={colors}/>} 
  </>}

  {tab==='TEAM'&&<>
   <View style={s.sectionRow}><Section title="People" copy="Roles define real server permissions, not cosmetic access." colors={colors}/>{p?.team_manage?<Pressable onPress={()=>{setEmail('');setName('')}} style={s.iconButton}><Ionicons name="person-add-outline" size={18} color={colors.text}/></Pressable>:null}</View>
   {p?.team_manage?<View style={s.form}><Text style={s.formTitle}>Invite employee</Text><Field label="EMAIL" value={email} setValue={setEmail} placeholder="name@company.com" colors={colors}/><View style={s.two}><View style={{flex:1}}><Field label="NAME" value={name} setValue={setName} placeholder="Optional" colors={colors}/></View><View style={{flex:1}}><Field label="JOB TITLE" value={title} setValue={setTitle} placeholder="Technician" colors={colors}/></View></View><Text style={s.mini}>ROLE</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.roleStrip}>{BUSINESS_ROLES.map(r=><Pressable key={r} onPress={()=>setRole(r)} style={[s.roleChip,role===r&&s.roleChipOn]}><Text style={[s.roleText,role===r&&s.roleTextOn]}>{roleLabel(r)}</Text></Pressable>)}</ScrollView><Pressable onPress={()=>setDispatchable(v=>!v)} style={s.toggle}><Text style={s.cardTitle}>Can receive dispatched jobs</Text><Ionicons name={dispatchable?'toggle':'toggle-outline'} size={31} color={dispatchable?colors.brand:colors.muted}/></Pressable><Pressable disabled={!!busy||!email.trim()} onPress={()=>void invite()} style={[s.primary,(!email.trim()||!!busy)&&s.disabled]}><Text style={s.primaryText}>{busy==='invite'?'INVITING…':'SEND INVITATION'}</Text></Pressable></View>:null}
   {(data?.invitations??[]).map(inv=><View key={inv.id} style={s.invite}><View style={{flex:1}}><Text style={s.cardTitle}>{inv.email}</Text><Text style={s.meta}>{roleLabel(inv.member_role)} · expires {new Date(inv.expires_at).toLocaleDateString()}</Text></View>{p?.team_manage?<Pressable disabled={!!busy} onPress={()=>void run('revoke:'+inv.id,()=>revokeBusinessInvitation(business!.id,inv.id))} style={s.smallButton}><Text style={s.smallText}>REVOKE</Text></Pressable>:null}</View>)}
   {members.map(m=><View key={m.user_id} style={s.member}><View style={s.memberTop}><Avatar name={m.name} colors={colors}/><View style={{flex:1}}><Text style={s.cardTitle}>{m.name}</Text><Text style={s.meta}>{m.job_title||roleLabel(m.member_role)} · {m.status}</Text></View><View style={[s.dot,{backgroundColor:m.status==='ACTIVE'?colors.success:colors.muted}]}/></View><View style={s.tags}><Tag text={roleLabel(m.member_role)} colors={colors}/>{m.is_dispatchable?<Tag text="DISPATCHABLE" colors={colors}/>:null}{m.location_id?<Tag text="LOCATION SET" colors={colors}/>:null}</View>{p?.team_manage&&m.member_role!=='OWNER'?<><Pressable onPress={()=>{setEditing(m);setEditRole((m.member_role==='MANAGER'?'OPERATIONS_MANAGER':m.member_role==='STAFF'?'TECHNICIAN':m.member_role) as BusinessRole);setEditDispatch(m.is_dispatchable)}} style={s.manage}><Text style={s.manageText}>MANAGE ACCESS</Text><Ionicons name="options-outline" size={16} color={colors.text}/></Pressable>{editing?.user_id===m.user_id?<View style={s.edit}><Text style={s.mini}>ROLE</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.roleStrip}>{BUSINESS_ROLES.map(r=><Pressable key={r} onPress={()=>setEditRole(r)} style={[s.roleChip,editRole===r&&s.roleChipOn]}><Text style={[s.roleText,editRole===r&&s.roleTextOn]}>{roleLabel(r)}</Text></Pressable>)}</ScrollView><Pressable onPress={()=>setEditDispatch(v=>!v)} style={s.toggle}><Text style={s.cardTitle}>Dispatchable</Text><Ionicons name={editDispatch?'toggle':'toggle-outline'} size={31} color={editDispatch?colors.brand:colors.muted}/></Pressable><View style={s.editActions}><Pressable disabled={!!busy} onPress={()=>void saveMember()} style={s.primarySmall}><Text style={s.primaryText}>SAVE</Text></Pressable><Pressable disabled={!!busy} onPress={()=>void run('remove:'+m.user_id,()=>removeBusinessMember(business!.id,m.user_id))} style={s.danger}><Text style={s.dangerText}>REMOVE</Text></Pressable></View></View>:null}</>:null}</View>)}
  </>}

  {tab==='STRUCTURE'&&<>
   <Section title="Locations" copy="Give branches and field teams a real operating base without changing the public business identity." colors={colors}/>
   {p?.team_manage?<View style={s.form}><Text style={s.formTitle}>Add location</Text><Field label="LOCATION NAME" value={locationName} setValue={setLocationName} placeholder="Western Sydney" colors={colors}/><Field label="ADDRESS" value={address} setValue={setAddress} placeholder="Street address" colors={colors}/><View style={s.two}><View style={{flex:1}}><Field label="SUBURB" value={suburb} setValue={setSuburb} placeholder="Rooty Hill" colors={colors}/></View><View style={{flex:1}}><Field label="POSTCODE" value={postcode} setValue={setPostcode} placeholder="2766" colors={colors}/></View></View><Pressable disabled={!!busy||!locationName.trim()} onPress={()=>void addLocation()} style={[s.primary,(!locationName.trim()||!!busy)&&s.disabled]}><Text style={s.primaryText}>ADD LOCATION</Text></Pressable></View>:null}
   <View style={s.grid}>{locations.map(l=><View key={l.id} style={s.structure}><View style={s.structureIcon}><Ionicons name="location-outline" size={18} color={colors.brand}/></View><Text style={s.cardTitle}>{l.name}</Text><Text style={s.meta}>{[l.address_line,l.suburb,l.postcode].filter(Boolean).join(', ')||'Address not set'}</Text>{l.is_primary?<Tag text="PRIMARY" colors={colors}/>:null}</View>)}</View>
   <Section title="Crews" copy="Teams let dispatch move a whole crew together while every member keeps their own identity and permissions." colors={colors}/>
   {p?.team_manage?<View style={s.form}><Text style={s.formTitle}>Create crew</Text><Field label="TEAM NAME" value={teamName} setValue={setTeamName} placeholder="Crew A" colors={colors}/><Field label="DESCRIPTION" value={teamDescription} setValue={setTeamDescription} placeholder="Mobile detailing crew" colors={colors}/><Pressable disabled={!!busy||!teamName.trim()} onPress={()=>void addTeam()} style={[s.primary,(!teamName.trim()||!!busy)&&s.disabled]}><Text style={s.primaryText}>CREATE CREW</Text></Pressable></View>:null}
   {teams.map(t=><View key={t.id} style={s.teamCard}><View style={s.row}><View><Text style={s.cardTitle}>{t.name}</Text><Text style={s.meta}>{t.description||'Operational team'} · {t.member_count} members</Text></View><View style={s.count}><Text style={s.countText}>{t.member_count}</Text></View></View>{p?.team_manage?<View style={s.chips}>{members.filter(m=>m.status==='ACTIVE'&&m.member_role!=='OWNER').map(m=>{const on=t.members.some(x=>x.user_id===m.user_id);return <Pressable disabled={!!busy} key={m.user_id} onPress={()=>void run('team-member',()=>setBusinessTeamMember({businessId:business!.id,teamId:t.id,userId:m.user_id,enabled:!on,teamRole:on?'MEMBER':'MEMBER'}))} style={[s.memberToggle,on&&s.memberToggleOn]}><Ionicons name={on?'checkmark':'add'} size={13} color={on?colors.onBrand:colors.text}/><Text style={[s.memberToggleText,on&&{color:colors.onBrand}]}>{m.name}</Text></Pressable>})}</View>:null}</View>)}
  </>}
 </ScrollView><BusinessTabBar active="/business-operations"/></View></SafeAreaView>;
}

