import { useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { myBusiness } from '@/lib/catalog';
import { supabase } from '@/lib/supabase';
import { getOrCreateBookingConversation, updateBookingStatus } from '@/lib/marketplace';
import type { BookingStatus } from '@/lib/types';

type Booking={id:string;request_id:string|null;business_id:string;price:number;scheduled_date:string|null;scheduled_time:string|null;status:BookingStatus;created_at:string};
const nextStatus=(status:BookingStatus):BookingStatus|null=>({CONFIRMED:'UPCOMING',UPCOMING:'IN_PROGRESS',IN_PROGRESS:'COMPLETED'} as Partial<Record<BookingStatus,BookingStatus>>)[status]??null;
export default function BusinessBookings(){const [items,setItems]=useState<Booking[]>([]);const [businessId,setBusinessId]=useState('');const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [busy,setBusy]=useState<string|null>(null);const [confirmCancelId,setConfirmCancelId]=useState<string|null>(null);const [error,setError]=useState('');
 async function load(mode:'initial'|'refresh'|'background'='initial'){if(mode==='initial')setLoading(true);if(mode==='refresh')setRefreshing(true);setError('');try{const business=await myBusiness();if(!business){setItems([]);setBusinessId('');return;}const {data,error:e}=await supabase.from('bookings').select('id,request_id,business_id,price,scheduled_date,scheduled_time,status,created_at').eq('business_id',business.id).order('created_at',{ascending:false});if(e)throw e;setBusinessId(business.id);setItems((data??[]) as Booking[])}catch{setError('Unable to load bookings right now. Please try again.')}finally{if(mode==='initial')setLoading(false);if(mode==='refresh')setRefreshing(false)}}useEffect(()=>{void load()},[]);
 async function advance(id:string,status:BookingStatus){setBusy(id);setError('');try{await updateBookingStatus(id,status);setConfirmCancelId(null);await load('background')}catch{setError('Booking update failed. Please try again.')}finally{setBusy(null)}}
 async function openConversation(booking:Booking){if(!booking.request_id||!businessId||busy!==null||refreshing)return;setBusy(`message:${booking.id}`);setError('');try{const conversationId=await getOrCreateBookingConversation({requestId:booking.request_id,businessId,bookingId:booking.id});router.push({pathname:'/messages',params:{conversationId}})}catch{setError('Unable to open booking conversation right now. Please try again.')}finally{setBusy(null)}}
 const controlsBusy=busy!==null||refreshing;
 return <SafeAreaView style={s.safe}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{if(!busy)void load('refresh')}} />} contentContainerStyle={s.page}><Text style={s.eyebrow}>BUSINESS BOOKINGS</Text><Text style={s.title}>Bookings</Text>{loading?<ActivityIndicator/>:error&&!items.length?<><Text style={s.error}>{error}</Text><Pressable disabled={refreshing||busy!==null} onPress={()=>void load('refresh')} style={s.retry}><Text>{refreshing?'RETRYING…':'RETRY'}</Text></Pressable></>:items.length?<>{error?<View style={s.warning}><Text style={s.warningText}>We could not refresh your bookings. Showing the last successfully loaded booking information.</Text><Pressable disabled={controlsBusy} onPress={()=>void load('refresh')} style={s.retry}><Text>{refreshing?'RETRYING…':'RETRY BOOKINGS'}</Text></Pressable></View>:null}{items.map(b=>{const next=nextStatus(b.status);const canCancel=['REQUESTED','PENDING_PAYMENT','CONFIRMED','UPCOMING'].includes(b.status);const confirming=confirmCancelId===b.id;return <View style={s.card} key={b.id}><View style={s.row}><Text style={s.status}>{b.status.replaceAll('_',' ')}</Text><Text style={s.amount}>${Number(b.price).toFixed(2)} AUD</Text></View><Text style={s.meta}>Scheduled: {b.scheduled_date??'Date pending'}{b.scheduled_time?` at ${b.scheduled_time}`:''}</Text><Text style={s.meta}>Booking {b.id.slice(0,8).toUpperCase()}</Text>{b.request_id&&<Pressable disabled={controlsBusy} onPress={()=>void openConversation(b)} style={s.message}><Text style={s.messageText}>{busy===`message:${b.id}`?'OPENING…':'MESSAGE CUSTOMER'}</Text></Pressable>}{next&&<Pressable disabled={controlsBusy} onPress={()=>void advance(b.id,next)} style={s.button}><Text style={s.buttonText}>{busy===b.id?'UPDATING…':`MOVE TO ${next.replaceAll('_',' ')}`}</Text></Pressable>}{canCancel&&!confirming&&<Pressable disabled={controlsBusy} onPress={()=>setConfirmCancelId(b.id)} style={s.cancel}><Text style={s.cancelText}>CANCEL BOOKING</Text></Pressable>}{canCancel&&confirming&&<View style={s.confirmBox}><Text style={s.confirmText}>Cancel this booking? This action changes the customer’s booking status.</Text><View style={s.confirmRow}><Pressable disabled={controlsBusy} onPress={()=>setConfirmCancelId(null)} style={s.keep}><Text style={s.cancelText}>KEEP BOOKING</Text></Pressable><Pressable disabled={controlsBusy} onPress={()=>void advance(b.id,'CANCELLED')} style={s.confirmCancel}><Text style={s.confirmCancelText}>{busy===b.id?'CANCELLING…':'YES, CANCEL'}</Text></Pressable></View></View>}</View>})}</>:<View style={s.empty}><Text style={s.emptyTitle}>No bookings yet.</Text><Text style={s.meta}>Accepted customer quotes will create real bookings here.</Text></View>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:50},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:'#777'},title:{fontSize:31,fontWeight:'900',marginTop:7,marginBottom:22},card:{backgroundColor:'#fff',borderRadius:17,borderWidth:1,borderColor:'#e5e2dc',padding:17,marginBottom:10},row:{flexDirection:'row',justifyContent:'space-between'},status:{fontSize:9,fontWeight:'900'},amount:{fontSize:20,fontWeight:'900'},meta:{fontSize:11,color:'#777',marginTop:7},message:{height:43,borderRadius:12,borderWidth:1,borderColor:'#ddd8cf',alignItems:'center',justifyContent:'center',marginTop:13},messageText:{fontSize:9,fontWeight:'900'},button:{height:46,borderRadius:13,backgroundColor:'#111',alignItems:'center',justifyContent:'center',marginTop:9},buttonText:{color:'#fff',fontSize:9,fontWeight:'900'},cancel:{height:43,borderRadius:12,borderWidth:1,borderColor:'#ddd8cf',alignItems:'center',justifyContent:'center',marginTop:9},cancelText:{fontSize:9,fontWeight:'900'},confirmBox:{marginTop:9,padding:12,borderRadius:12,backgroundColor:'#fff8e8',borderWidth:1,borderColor:'#ead8ae'},confirmText:{fontSize:11,lineHeight:16,color:'#6b5424'},confirmRow:{flexDirection:'row',gap:8,marginTop:10},keep:{flex:1,minHeight:42,borderRadius:10,borderWidth:1,borderColor:'#ddd8cf',alignItems:'center',justifyContent:'center',paddingHorizontal:8},confirmCancel:{flex:1,minHeight:42,borderRadius:10,backgroundColor:'#b42318',alignItems:'center',justifyContent:'center',paddingHorizontal:8},confirmCancelText:{fontSize:9,fontWeight:'900',color:'#fff'},empty:{backgroundColor:'#fff',borderRadius:19,padding:28,alignItems:'center'},emptyTitle:{fontSize:16,fontWeight:'800'},error:{fontSize:12,color:'#b42318',textAlign:'center'},retry:{height:44,borderRadius:12,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',marginTop:12},warning:{backgroundColor:'#fff8e8',borderRadius:14,padding:14,marginBottom:12,borderWidth:1,borderColor:'#ead8ae'},warningText:{fontSize:12,lineHeight:18,color:'#6b5424'}});
