import { useEffect,useMemo,useRef,useState } from 'react';
import { ActivityIndicator,Alert,Linking,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import {cartUnitPrice,checkout,getCart,removeFromCart,setCartQuantity} from '@/lib/commerce';
import type { CartItem,ProductDeliveryMethod } from '@/lib/commerce';
import { type ThemeColors,useAppTheme } from '@/lib/theme';

export default function Cart(){
 const {colors}=useAppTheme();const s=useMemo(()=>createStyles(colors),[colors]);
 const [items,setItems]=useState<CartItem[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [method,setMethod]=useState<ProductDeliveryMethod>('PICKUP');const [address,setAddress]=useState('');
 const checkoutKey=useRef(`cart-${Date.now()}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`);const operationRef=useRef(false);
 async function load(mode:'initial'|'refresh'|'silent'='initial'){if(operationRef.current)return;if(mode==='initial')setLoading(true);else if(mode==='refresh')setRefreshing(true);setError('');try{setItems(await getCart())}catch{setError(items.length?'Your cart could not be refreshed. Showing your last loaded cart.':'Your cart is unavailable right now. Please try again.')}finally{setLoading(false);setRefreshing(false)}}
 useEffect(()=>{void load()},[]); // eslint-disable-line react-hooks/exhaustive-deps
 async function mutate(action:()=>Promise<void>,message:string){if(operationRef.current||refreshing)return;operationRef.current=true;setBusy(true);setError('');try{await action();checkoutKey.current=`cart-${Date.now()}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;operationRef.current=false;setBusy(false);await load('silent')}catch{setError(message);operationRef.current=false;setBusy(false)}}
 async function remove(item:CartItem){await mutate(()=>removeFromCart(item.product_id,item.variant_id),'Could not remove that item. Please try again.')}
 async function change(item:CartItem,delta:number){const next=item.quantity+delta;if(next<1){await remove(item);return;}await mutate(()=>setCartQuantity(item.product_id,item.variant_id,next),'Could not update your cart. Check stock availability and try again.')}
 const hasUnavailableProduct=items.some(i=>!i.products||i.products.status!=='ACTIVE');const businessIds=new Set(items.map(i=>i.products?.business_id).filter(Boolean));const hasMultipleBusinesses=businessIds.size>1;const deliveryAvailable=items.length>0&&!hasUnavailableProduct&&!hasMultipleBusinesses&&items.every(i=>i.products?.delivery_eligible===true);const pickupAvailable=items.length>0&&!hasUnavailableProduct&&!hasMultipleBusinesses&&items.every(i=>i.products?.pickup_available!==false);const shippingAvailable=items.length>0&&!hasUnavailableProduct&&!hasMultipleBusinesses&&items.every(i=>i.products?.shipping_available===true);
 useEffect(()=>{if(method==='EVEREST_DELIVERY'&&!deliveryAvailable)setMethod(pickupAvailable?'PICKUP':shippingAvailable?'SHIPPING':'PICKUP');if(method==='SHIPPING'&&!shippingAvailable)setMethod(pickupAvailable?'PICKUP':deliveryAvailable?'EVEREST_DELIVERY':'PICKUP');if(method==='PICKUP'&&!pickupAvailable){if(deliveryAvailable)setMethod('EVEREST_DELIVERY');else if(shippingAvailable)setMethod('SHIPPING')}},[deliveryAvailable,pickupAvailable,shippingAvailable,method]);
 async function pay(){if(operationRef.current||refreshing)return;if(hasUnavailableProduct||hasMultipleBusinesses){setError(hasMultipleBusinesses?'Checkout supports products from one business at a time. Remove items from the other business before continuing.':'Remove unavailable products before checking out.');return;}operationRef.current=true;setBusy(true);setError('');try{const result=await checkout(checkoutKey.current,method,method==='PICKUP'?null:address);if(!result.checkoutUrl)throw new Error();if(!(await Linking.canOpenURL(result.checkoutUrl)))throw new Error();await Linking.openURL(result.checkoutUrl)}catch{Alert.alert('Checkout unavailable','Secure checkout could not be started. Please review your cart and try again.')}finally{operationRef.current=false;setBusy(false)}}
 const locked=busy||refreshing;const subtotal=items.reduce((sum,item)=>sum+(cartUnitPrice(item)*item.quantity),0);
 return <SafeAreaView style={s.safe}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load('refresh')} enabled={!busy} tintColor={colors.text}/>} contentContainerStyle={s.page}><Text style={s.eyebrow}>EVEREST LOCAL</Text><Text style={s.title}>Cart</Text>{loading?<ActivityIndicator color={colors.text} style={{marginTop:40}}/>:error&&!items.length?<View style={s.errorBox}><Text style={s.error}>{error}</Text><Pressable onPress={()=>void load()} disabled={locked} style={s.retry}><Text style={s.retryText}>RETRY</Text></Pressable></View>:items.length?<>
 {error?<View style={s.warning}><Text style={s.warningTitle}>Cart update unavailable</Text><Text style={s.warningText}>{error}</Text><Pressable onPress={()=>void load('refresh')} disabled={locked} style={s.warningRetry}><Text style={s.retryText}>{refreshing?'RETRYING…':'RETRY CART'}</Text></Pressable></View>:null}
 {items.map(item=><View style={s.card} key={item.id}><View style={s.row}><View style={{flex:1}}><Text style={s.name}>{item.products?.name??'Product unavailable'}</Text>{item.product_variants?.title?<Text style={s.variant}>{item.product_variants.title}</Text>:null}<Text style={s.meta}>{item.products?`${cartUnitPrice(item).toFixed(2)} AUD each`:'This product is no longer available.'}</Text>{item.product_variants?<Text style={s.variant}>{item.product_variants.title}</Text>:null}{item.products&&item.products.status!=='ACTIVE'&&<Text style={s.unavailable}>Currently unavailable</Text>}</View><Pressable onPress={()=>void remove(item)} disabled={locked}><Text style={s.remove}>Remove</Text></Pressable></View>{item.products?.status==='ACTIVE'&&<View style={s.qty}><Pressable onPress={()=>void change(item,-1)} disabled={locked} style={s.qtyButton}><Text style={s.qtyButtonText}>−</Text></Pressable><Text style={s.qtyText}>{item.quantity}</Text><Pressable onPress={()=>void change(item,1)} disabled={locked||item.quantity>=99} style={[s.qtyButton,item.quantity>=99&&s.disabled]}><Text style={s.qtyButtonText}>+</Text></Pressable></View>}</View>)}
 {hasUnavailableProduct&&<View style={s.warning}><Text style={s.warningTitle}>Cart needs attention</Text><Text style={s.warningText}>One or more products are no longer available. Remove them before continuing to checkout.</Text></View>}{hasMultipleBusinesses&&<View style={s.warning}><Text style={s.warningTitle}>Separate orders required</Text><Text style={s.warningText}>Checkout supports one local business per order. Remove products from the other business, complete this order, then add them again for a separate checkout.</Text></View>}
 <View style={s.total}><Text style={s.totalLabel}>Current subtotal</Text><Text style={s.totalValue}>${subtotal.toFixed(2)} AUD</Text></View>{!hasUnavailableProduct&&!hasMultipleBusinesses&&<><Text style={s.section}>Fulfilment</Text><View style={s.options}>{pickupAvailable&&<Pressable accessibilityRole="radio" accessibilityState={{selected:method==='PICKUP'}} disabled={locked} onPress={()=>setMethod('PICKUP')} style={[s.option,method==='PICKUP'&&s.optionSelected]}><Text style={s.optionTitle}>Pickup</Text><Text style={s.meta}>Collect from the business</Text></Pressable>}{deliveryAvailable&&<Pressable accessibilityRole="radio" accessibilityState={{selected:method==='EVEREST_DELIVERY'}} disabled={locked} onPress={()=>setMethod('EVEREST_DELIVERY')} style={[s.option,method==='EVEREST_DELIVERY'&&s.optionSelected]}><Text style={s.optionTitle}>Everest Delivery</Text><Text style={s.meta}>Local delivery</Text></Pressable>}{shippingAvailable&&<Pressable accessibilityRole="radio" accessibilityState={{selected:method==='SHIPPING'}} disabled={locked} onPress={()=>setMethod('SHIPPING')} style={[s.option,method==='SHIPPING'&&s.optionSelected]}><Text style={s.optionTitle}>Shipping</Text><Text style={s.meta}>Sent by the local business</Text></Pressable>}</View>{method!=='PICKUP'&&<TextInput value={address} onChangeText={setAddress} editable={!locked} placeholder="Delivery address" placeholderTextColor={colors.muted} autoCapitalize="words" style={s.input}/>}</>}
 <Text style={s.note}>Final price, stock, delivery fees and applicable marketplace charges are recalculated securely at checkout.</Text><Pressable disabled={locked||hasUnavailableProduct||hasMultipleBusinesses||method!=='PICKUP'&&!address.trim()} onPress={()=>void pay()} style={[s.button,(locked||hasUnavailableProduct||hasMultipleBusinesses||method!=='PICKUP'&&!address.trim())&&s.disabled]}>{busy?<ActivityIndicator color={colors.onBrand}/>:<Text style={s.buttonText}>SECURE CHECKOUT</Text>}</Pressable></>:<View style={s.empty}><Text style={s.emptyTitle}>Your cart is empty.</Text><Text style={s.meta}>Add real products from verified local businesses to begin.</Text></View>}</ScrollView></SafeAreaView>}

const createStyles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:50,maxWidth:760,width:'100%',alignSelf:'center'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:c.muted},title:{fontSize:31,fontWeight:'900',marginTop:7,marginBottom:22,color:c.text},card:{backgroundColor:c.surface,borderRadius:17,borderWidth:1,borderColor:c.border,padding:16,marginBottom:10},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},name:{fontSize:15,fontWeight:'800',color:c.text},variant:{fontSize:10,fontWeight:'800',color:c.textSecondary,marginTop:5},meta:{fontSize:11,color:c.muted,marginTop:5},unavailable:{fontSize:10,fontWeight:'800',color:c.danger,marginTop:6},remove:{fontSize:10,fontWeight:'800',color:c.text},qty:{flexDirection:'row',alignItems:'center',gap:12,marginTop:14},qtyButton:{width:38,height:38,borderRadius:11,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center'},qtyButtonText:{color:c.text},qtyText:{fontSize:14,fontWeight:'800',color:c.text},warning:{backgroundColor:c.soft,borderRadius:14,borderWidth:1,borderColor:c.border,padding:14,marginTop:8,marginBottom:10},warningTitle:{fontSize:12,fontWeight:'900',color:c.text},warningText:{fontSize:11,color:c.muted,lineHeight:17,marginTop:4},warningRetry:{minHeight:38,alignItems:'center',justifyContent:'center',marginTop:7},total:{marginTop:18,paddingTop:18,borderTopWidth:1,borderTopColor:c.border,flexDirection:'row',justifyContent:'space-between'},totalLabel:{fontSize:13,fontWeight:'700',color:c.text},totalValue:{fontSize:20,fontWeight:'900',color:c.text},section:{fontSize:17,fontWeight:'800',marginTop:24,marginBottom:10,color:c.text},options:{gap:8},option:{backgroundColor:c.surface,borderRadius:14,borderWidth:1,borderColor:c.border,padding:14},optionSelected:{borderColor:c.brand,borderWidth:2},optionTitle:{fontSize:13,fontWeight:'800',color:c.text},input:{height:50,borderRadius:13,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,paddingHorizontal:14,marginTop:10,fontSize:13,color:c.text},note:{fontSize:11,color:c.muted,lineHeight:17,marginTop:12},button:{height:54,borderRadius:15,backgroundColor:c.brand,alignItems:'center',justifyContent:'center',marginTop:18},disabled:{opacity:.45},buttonText:{color:c.onBrand,fontSize:11,fontWeight:'900'},empty:{backgroundColor:c.surface,borderRadius:20,padding:28,alignItems:'center',borderWidth:1,borderColor:c.border},emptyTitle:{fontSize:17,fontWeight:'800',color:c.text},errorBox:{backgroundColor:c.surface,borderRadius:18,borderWidth:1,borderColor:c.border,padding:20},error:{color:c.danger,fontSize:12,lineHeight:18},retry:{marginTop:14,height:42,borderRadius:12,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center'},retryText:{fontSize:10,fontWeight:'900',color:c.text}});