import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { addToCart, getCart, removeFromCart, checkout } from '@/lib/commerce';

type CartProduct={id:string;name:string;price:number;sale_price:number|null;status:string};
type CartItem={id:string;quantity:number;product_id:string;products:CartProduct|null};
export default function Cart(){const [items,setItems]=useState<CartItem[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function load(){try{setError('');setItems((await getCart()) as CartItem[])}catch(e){setError(e instanceof Error?e.message:'Unable to load cart.')}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
 async function remove(id:string){setBusy(true);try{await removeFromCart(id);await load()}catch(e){setError(e instanceof Error?e.message:'Could not remove item.')}finally{setBusy(false)}}
 async function change(item:CartItem,delta:number){const next=item.quantity+delta;if(next<1){await remove(item.id);return;}setBusy(true);try{await addToCart(item.product_id,next);await load()}catch(e){setError(e instanceof Error?e.message:'Could not update quantity.')}finally{setBusy(false)}}
 async function pay(){setBusy(true);setError('');try{const result=await checkout(`cart-${Date.now()}-${Math.random().toString(36).slice(2)}`);if(result.checkoutUrl){const supported=await Linking.canOpenURL(result.checkoutUrl);if(!supported)throw new Error('Secure checkout link could not be opened.');await Linking.openURL(result.checkoutUrl)}else throw new Error('Checkout is not configured yet.')}catch(e){Alert.alert('Checkout unavailable',e instanceof Error?e.message:'Please try again.')}finally{setBusy(false)}}
 const subtotal=items.reduce((sum,item)=>sum+(Number(item.products?.sale_price??item.products?.price??0)*item.quantity),0);
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.eyebrow}>EVEREST LOCAL</Text><Text style={s.title}>Cart</Text>{loading?<ActivityIndicator style={{marginTop:40}}/>:error?<Text style={s.error}>{error}</Text>:items.length?<> {items.map(item=><View style={s.card} key={item.id}><View style={s.row}><View style={{flex:1}}><Text style={s.name}>{item.products?.name??'Product unavailable'}</Text><Text style={s.meta}>${Number(item.products?.sale_price??item.products?.price??0).toFixed(2)} AUD each</Text></View><Pressable onPress={()=>void remove(item.id)} accessibilityLabel={`Remove ${item.products?.name??'item'}`}><Text style={s.remove}>Remove</Text></Pressable></View><View style={s.qty}><Pressable onPress={()=>void change(item,-1)} style={s.qtyButton}><Text>−</Text></Pressable><Text style={s.qtyText}>{item.quantity}</Text><Pressable onPress={()=>void change(item,1)} style={s.qtyButton}><Text>+</Text></Pressable></View></View>)}<View style={s.total}><Text style={s.totalLabel}>Current subtotal</Text><Text style={s.totalValue}>${subtotal.toFixed(2)} AUD</Text></View><Text style={s.note}>Final price, stock, delivery fees and applicable marketplace charges are recalculated securely at checkout.</Text><Pressable disabled={busy} onPress={()=>void pay()} style={s.button}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>SECURE CHECKOUT</Text>}</Pressable></>:<View style={s.empty}><Text style={s.emptyTitle}>Your cart is empty.</Text><Text style={s.meta}>Add real products from verified local businesses to begin.</Text></View>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:50},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:'#777'},title:{fontSize:31,fontWeight:'900',marginTop:7,marginBottom:22},card:{backgroundColor:'#fff',borderRadius:17,borderWidth:1,borderColor:'#e5e2dc',padding:16,marginBottom:10},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},name:{fontSize:15,fontWeight:'800'},meta:{fontSize:11,color:'#777',marginTop:5},remove:{fontSize:10,fontWeight:'800'},qty:{flexDirection:'row',alignItems:'center',gap:12,marginTop:14},qtyButton:{width:38,height:38,borderRadius:11,borderWidth:1,borderColor:'#ddd8cf',alignItems:'center',justifyContent:'center'},qtyText:{fontSize:14,fontWeight:'800'},total:{marginTop:18,paddingTop:18,borderTopWidth:1,borderTopColor:'#e5e2dc',flexDirection:'row',justifyContent:'space-between'},totalLabel:{fontSize:13,fontWeight:'700'},totalValue:{fontSize:20,fontWeight:'900'},note:{fontSize:11,color:'#777',lineHeight:17,marginTop:8},button:{height:54,borderRadius:15,backgroundColor:'#111',alignItems:'center',justifyContent:'center',marginTop:18},buttonText:{color:'#fff',fontSize:11,fontWeight:'900'},empty:{backgroundColor:'#fff',borderRadius:20,padding:28,alignItems:'center'},emptyTitle:{fontSize:17,fontWeight:'800'},error:{color:'#b42318',fontSize:12}});