import {useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Image,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {router} from 'expo-router';
import * as ImagePicker from 'expo-image-picker';
import {createPost,type PostType} from '@/lib/social';
import {uploadPostMedia} from '@/lib/request-post-media';
import {getWorkspaceContext,type BusinessWorkspace} from '@/lib/workspace';
import {supabase} from '@/lib/supabase';
import {type ThemeColors,useAppTheme} from '@/lib/theme';

type Identity={kind:'PERSONAL';id:string;name:string}|{kind:'BUSINESS';id:string;name:string;business:BusinessWorkspace};
type Listing={id:string;name:string};
const personalTypes:PostType[]=['UPDATE','QUESTION','RECOMMENDATION','EXPERIENCE','TIP'];
const businessTypes:PostType[]=['UPDATE','COMPLETED_WORK','BEFORE_AFTER','PROMOTION','ANNOUNCEMENT','OFFER','AVAILABILITY','TIP'];

export default function CreatePost(){
 const {colors}=useAppTheme();const s=useMemo(()=>styles(colors),[colors]);const [identities,setIdentities]=useState<Identity[]>([]);const [identity,setIdentity]=useState<Identity|null>(null);
 const [caption,setCaption]=useState('');const [type,setType]=useState<PostType>('UPDATE');const [visibility,setVisibility]=useState<'PUBLIC'|'FOLLOWERS'>('PUBLIC');const [location,setLocation]=useState('');
 const [photos,setPhotos]=useState<ImagePicker.ImagePickerAsset[]>([]);const [services,setServices]=useState<Listing[]>([]);const [products,setProducts]=useState<Listing[]>([]);const [serviceId,setServiceId]=useState<string|null>(null);const [productId,setProductId]=useState<string|null>(null);
 const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [progress,setProgress]=useState('');const [error,setError]=useState('');
 useEffect(()=>{let active=true;(async()=>{try{const [{data:{user}},ctx,{data:profile}]=await Promise.all([supabase.auth.getUser(),getWorkspaceContext(),supabase.from('profiles').select('full_name').maybeSingle()]);if(!active)return;if(!user){router.replace('/auth');return;}const list:Identity[]=[{kind:'PERSONAL',id:user.id,name:profile?.full_name||'My profile'},...ctx.businesses.map(b=>({kind:'BUSINESS' as const,id:b.id,name:b.name,business:b}))];setIdentities(list);const preferred=ctx.mode==='BUSINESS'&&ctx.active_business_id?list.find(i=>i.kind==='BUSINESS'&&i.id===ctx.active_business_id):list[0];setIdentity(preferred??list[0]);}catch(e){setError(e instanceof Error?e.message:'Post composer could not be opened.')}finally{setLoading(false)}})();return()=>{active=false}},[]);
 useEffect(()=>{let active=true;(async()=>{if(identity?.kind!=='BUSINESS'){setServices([]);setProducts([]);setServiceId(null);setProductId(null);setVisibility(v=>v);return;}const [sr,pr]=await Promise.all([supabase.from('services').select('id,name').eq('business_id',identity.id).eq('active',true).order('name'),supabase.from('products').select('id,name').eq('business_id',identity.id).in('status',['ACTIVE','OUT_OF_STOCK']).order('name')]);if(!active)return;if(!sr.error)setServices((sr.data??[]) as Listing[]);if(!pr.error)setProducts((pr.data??[]) as Listing[]);setVisibility('PUBLIC');})();return()=>{active=false}},[identity]);
 async function pickLibrary(){if(photos.length>=10)return;const p=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!p.granted){setError('Photo access is required to add images.');return;}const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsMultipleSelection:true,selectionLimit:10-photos.length,quality:.84});if(!r.canceled)setPhotos(v=>[...v,...r.assets].slice(0,10));}
 async function takePhoto(){if(photos.length>=10)return;const p=await ImagePicker.requestCameraPermissionsAsync();if(!p.granted){setError('Camera access is required to take a photo.');return;}const r=await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:.84});if(!r.canceled&&r.assets[0])setPhotos(v=>[...v,r.assets[0]].slice(0,10));}
 function move(index:number,delta:number){const to=index+delta;if(to<0||to>=photos.length)return;setPhotos(v=>{const n=[...v];[n[index],n[to]]=[n[to],n[index]];return n;});}
 async function publish(){if(!identity||busy)return;if(!caption.trim()&&!serviceId&&!productId){setError('Add a caption, service or product before publishing.');return;}setBusy(true);setError('');
  try{const id=await createPost({businessId:identity.kind==='BUSINESS'?identity.id:undefined,caption,postType:type,visibility:identity.kind==='BUSINESS'?'PUBLIC':visibility,serviceId:identity.kind==='BUSINESS'?serviceId??undefined:undefined,productId:identity.kind==='BUSINESS'?productId??undefined:undefined,locationLabel:location||undefined});if(photos.length){setProgress(`Uploading 0/${photos.length}`);await uploadPostMedia(id,photos,(d,t)=>setProgress(`Uploading ${d}/${t}`));}router.replace('/social');}catch(e){setError(e instanceof Error?e.message:'Post could not be published.');}finally{setBusy(false);setProgress('');}}
 const availableTypes=identity?.kind==='BUSINESS'?businessTypes:personalTypes;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><View style={s.header}><Pressable onPress={()=>router.back()}><Ionicons name="close" size={26} color={colors.text}/></Pressable><Text style={s.headerTitle}>Create post</Text><Pressable disabled={busy||loading} onPress={()=>void publish()}><Text style={[s.publish,(busy||loading)&&s.dim]}>{busy?'POSTING…':'POST'}</Text></Pressable></View>
 {loading?<ActivityIndicator color={colors.brand} style={{marginTop:50}}/>:<><Text style={s.label}>POSTING AS</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{identities.map(i=><Pressable key={i.kind+i.id} onPress={()=>{setIdentity(i);setType('UPDATE')}} style={[s.identity,identity?.kind===i.kind&&identity.id===i.id&&s.identityActive]}><Ionicons name={i.kind==='BUSINESS'?'business-outline':'person-outline'} size={16} color={colors.text}/><Text style={s.identityText}>{i.name}</Text></Pressable>)}</ScrollView>
 <TextInput value={caption} onChangeText={setCaption} multiline maxLength={3000} autoFocus placeholder={identity?.kind==='BUSINESS'?'Share an update, offer or recent work…':'What’s happening locally?'} placeholderTextColor={colors.muted} style={s.caption}/>
 {photos.length?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.photoRow}>{photos.map((p,i)=><View key={p.assetId??p.uri} style={s.photoWrap}><Image source={{uri:p.uri}} style={s.photo}/><Pressable onPress={()=>setPhotos(v=>v.filter((_,x)=>x!==i))} style={s.remove}><Ionicons name="close" size={14} color="#fff"/></Pressable><View style={s.reorder}>{i>0?<Pressable onPress={()=>move(i,-1)}><Ionicons name="arrow-back-circle" size={22} color="#fff"/></Pressable>:null}{i<photos.length-1?<Pressable onPress={()=>move(i,1)}><Ionicons name="arrow-forward-circle" size={22} color="#fff"/></Pressable>:null}</View></View>)}</ScrollView>:null}
 <View style={s.mediaActions}><Pressable onPress={()=>void pickLibrary()} style={s.mediaButton}><Ionicons name="images-outline" size={18} color={colors.text}/><Text style={s.mediaText}>Photos {photos.length}/10</Text></Pressable><Pressable onPress={()=>void takePhoto()} style={s.mediaButton}><Ionicons name="camera-outline" size={18} color={colors.text}/><Text style={s.mediaText}>Camera</Text></Pressable></View>
 <Text style={s.label}>POST TYPE</Text><View style={s.wrap}>{availableTypes.map(t=><Pressable key={t} onPress={()=>setType(t)} style={[s.pill,type===t&&s.pillActive]}><Text style={s.pillText}>{t.replaceAll('_',' ')}</Text></Pressable>)}</View>
 {identity?.kind==='PERSONAL'?<><Text style={s.label}>WHO CAN SEE IT</Text><View style={s.wrap}><Pressable onPress={()=>setVisibility('PUBLIC')} style={[s.pill,visibility==='PUBLIC'&&s.pillActive]}><Text style={s.pillText}>Public</Text></Pressable><Pressable onPress={()=>setVisibility('FOLLOWERS')} style={[s.pill,visibility==='FOLLOWERS'&&s.pillActive]}><Text style={s.pillText}>Connections</Text></Pressable></View></>:<Text style={s.note}>Business posts are public and remain subject to business verification and moderation.</Text>}
 <Text style={s.label}>LOCATION <Text style={s.optional}>(optional)</Text></Text><TextInput value={location} onChangeText={setLocation} maxLength={120} placeholder="Example: Rooty Hill, NSW" placeholderTextColor={colors.muted} style={s.input}/>
 {identity?.kind==='BUSINESS'?<><Text style={s.label}>LINK A SERVICE <Text style={s.optional}>(optional)</Text></Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}><Pressable onPress={()=>setServiceId(null)} style={[s.pill,!serviceId&&s.pillActive]}><Text style={s.pillText}>None</Text></Pressable>{services.map(x=><Pressable key={x.id} onPress={()=>{setServiceId(x.id);setProductId(null)}} style={[s.pill,serviceId===x.id&&s.pillActive]}><Text style={s.pillText}>{x.name}</Text></Pressable>)}</ScrollView><Text style={s.label}>LINK A PRODUCT <Text style={s.optional}>(optional)</Text></Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}><Pressable onPress={()=>setProductId(null)} style={[s.pill,!productId&&s.pillActive]}><Text style={s.pillText}>None</Text></Pressable>{products.map(x=><Pressable key={x.id} onPress={()=>{setProductId(x.id);setServiceId(null)}} style={[s.pill,productId===x.id&&s.pillActive]}><Text style={s.pillText}>{x.name}</Text></Pressable>)}</ScrollView></>:null}
 {progress?<Text style={s.note}>{progress}</Text>:null}{error?<Text style={s.error}>{error}</Text>:null}<Pressable disabled={busy} onPress={()=>void publish()} style={[s.primary,busy&&s.dim]}>{busy?<ActivityIndicator color={colors.onBrand}/>:<Text style={s.primaryText}>PUBLISH POST</Text>}</Pressable></>}
 </ScrollView></SafeAreaView>;
}
const styles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:50,maxWidth:760,width:'100%',alignSelf:'center'},header:{height:48,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},headerTitle:{fontSize:16,fontWeight:'900',color:c.text},publish:{fontSize:11,fontWeight:'900',color:c.brand},dim:{opacity:.5},label:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:c.muted,marginTop:22,marginBottom:8},optional:{fontWeight:'600',letterSpacing:0},chips:{gap:7,paddingRight:12},identity:{minHeight:43,borderRadius:22,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,paddingHorizontal:13,flexDirection:'row',gap:7,alignItems:'center'},identityActive:{borderColor:c.brand,backgroundColor:c.soft},identityText:{fontSize:11,fontWeight:'800',color:c.text},caption:{minHeight:150,fontSize:18,lineHeight:26,color:c.text,textAlignVertical:'top',paddingVertical:18},photoRow:{gap:9,paddingVertical:8},photoWrap:{width:180,height:180,borderRadius:16,overflow:'hidden',position:'relative'},photo:{width:180,height:180},remove:{position:'absolute',top:8,right:8,width:28,height:28,borderRadius:14,backgroundColor:'rgba(0,0,0,.72)',alignItems:'center',justifyContent:'center'},reorder:{position:'absolute',bottom:8,left:8,right:8,flexDirection:'row',justifyContent:'space-between'},mediaActions:{flexDirection:'row',gap:8,marginTop:9},mediaButton:{minHeight:44,borderWidth:1,borderColor:c.border,borderRadius:13,backgroundColor:c.surface,paddingHorizontal:13,flexDirection:'row',gap:7,alignItems:'center'},mediaText:{fontSize:10,fontWeight:'900',color:c.text},wrap:{flexDirection:'row',flexWrap:'wrap',gap:7},pill:{minHeight:38,borderRadius:19,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,paddingHorizontal:12,alignItems:'center',justifyContent:'center'},pillActive:{borderColor:c.brand,backgroundColor:c.soft},pillText:{fontSize:9,fontWeight:'900',color:c.text},note:{fontSize:11,lineHeight:17,color:c.muted,marginTop:10},input:{minHeight:50,borderWidth:1,borderColor:c.border,borderRadius:13,backgroundColor:c.input,color:c.text,paddingHorizontal:13,fontSize:13},error:{fontSize:12,lineHeight:18,color:c.danger,marginTop:13},primary:{minHeight:52,borderRadius:15,backgroundColor:c.brand,alignItems:'center',justifyContent:'center',marginTop:24},primaryText:{fontSize:10,fontWeight:'900',color:c.onBrand}});
