import {useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Image,Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {router} from 'expo-router';
import * as ImagePicker from 'expo-image-picker';
import {MusicPicker} from '@/components/MusicPicker';
import {ClipPlayer} from '@/components/ClipPlayer';
import {createStory,deleteStory,uploadStoryMedia,type MusicTrack} from '@/lib/social-expansion';
import {getWorkspaceContext,type BusinessWorkspace} from '@/lib/workspace';
import {supabase} from '@/lib/supabase';
import {type ThemeColors,useAppTheme} from '@/lib/theme';
import {haptic} from '@/lib/haptics';

type Identity={kind:'PERSONAL';id:string;name:string}|{kind:'BUSINESS';id:string;name:string;business:BusinessWorkspace};

export default function CreateStory(){
 const {colors}=useAppTheme();const s=useMemo(()=>styles(colors),[colors]);
 const [identities,setIdentities]=useState<Identity[]>([]);const [identity,setIdentity]=useState<Identity|null>(null);
 const [asset,setAsset]=useState<ImagePicker.ImagePickerAsset|null>(null);const [caption,setCaption]=useState('');const [location,setLocation]=useState('');
 const [music,setMusic]=useState<MusicTrack|null>(null);const [musicOpen,setMusicOpen]=useState(false);
 const [visibility,setVisibility]=useState<'PUBLIC'|'FOLLOWERS'>('PUBLIC');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{let active=true;(async()=>{try{const [{data:{user}},ctx,{data:profile}]=await Promise.all([supabase.auth.getUser(),getWorkspaceContext(),supabase.from('profiles').select('full_name,suburb,city,state').maybeSingle()]);if(!user){router.replace('/auth');return}const list:Identity[]=[{kind:'PERSONAL',id:user.id,name:profile?.full_name||'My profile'},...ctx.businesses.map(b=>({kind:'BUSINESS' as const,id:b.id,name:b.name,business:b}))];if(active){setIdentities(list);setIdentity(ctx.mode==='BUSINESS'&&ctx.active_business_id?list.find(i=>i.id===ctx.active_business_id)??list[0]:list[0]);setLocation([profile?.suburb,profile?.city,profile?.state].filter(Boolean).join(', '))}}catch(e){if(active)setError(e instanceof Error?e.message:'Story creator could not be opened.')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
 async function pick(){setError('');if(Platform.OS!=='web'){const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){setError('Photo and video access is required.');return;}}try{const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images','videos'],allowsMultipleSelection:false,quality:.9,videoMaxDuration:60});if(!result.canceled&&result.assets[0]){setAsset(result.assets[0]);void haptic.selection()}}catch(e){setError(e instanceof Error?e.message:'Media could not be opened.')}}
 async function publish(){if(!asset||!identity||busy){if(!asset)setError('Choose a photo or video first.');return}setBusy(true);setError('');let storyId='';try{storyId=await createStory({businessId:identity.kind==='BUSINESS'?identity.id:undefined,caption,visibility:identity.kind==='BUSINESS'?'PUBLIC':visibility,locationLabel:location,musicTrackId:music?.id??null});await uploadStoryMedia(storyId,asset);void haptic.success();router.replace('/social')}catch(e){if(storyId)await deleteStory(storyId).catch(()=>undefined);void haptic.warning();setError(e instanceof Error?e.message:'Story could not be published.')}finally{setBusy(false)}}
 const video=asset&&(asset.type==='video'||String(asset.mimeType).startsWith('video/'));
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled">
  <View style={s.header}><Pressable onPress={()=>router.back()} style={s.round}><Ionicons name="close" size={22} color={colors.text}/></Pressable><Text style={s.title}>Create story</Text><Pressable disabled={busy||!asset} onPress={()=>void publish()}><Text style={[s.share,(busy||!asset)&&{opacity:.4}]}>{busy?'SHARING…':'SHARE'}</Text></Pressable></View>
  {loading?<ActivityIndicator color={colors.brand} style={{marginTop:70}}/>:<>
   <Text style={s.label}>SHARING AS</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.rail}>{identities.map(item=>{const active=item.id===identity?.id&&item.kind===identity?.kind;return <Pressable key={item.kind+item.id} onPress={()=>{setIdentity(item);if(item.kind==='BUSINESS')setVisibility('PUBLIC')}} style={[s.identity,active&&s.identityActive]}><Ionicons name={item.kind==='BUSINESS'?'business-outline':'person-outline'} size={16} color={active?colors.onBrand:colors.text}/><Text style={[s.identityText,active&&{color:colors.onBrand}]}>{item.kind==='PERSONAL'?'My profile':item.name}</Text></Pressable>})}</ScrollView>
   <Pressable onPress={()=>void pick()} style={s.preview}>{asset?(video?<ClipPlayer uri={asset.uri} active/>:<Image source={{uri:asset.uri}} style={s.image}/>):<View style={s.empty}><View style={s.emptyIcon}><Ionicons name="add" size={28} color={colors.brand}/></View><Text style={s.emptyTitle}>Choose photo or video</Text><Text style={s.emptyCopy}>Stories stay public for 24 hours, then move into your private archive.</Text></View>}</Pressable>
   <TextInput value={caption} onChangeText={setCaption} maxLength={1000} placeholder="Add a short caption…" placeholderTextColor={colors.muted} style={s.input}/>
   <Pressable onPress={()=>setMusicOpen(true)} style={s.option}><View style={s.optionIcon}><Ionicons name="musical-notes-outline" size={19} color={colors.text}/></View><View style={{flex:1}}><Text style={s.optionTitle}>{music?music.title:'Add Everest Music'}</Text><Text style={s.optionCopy}>{music?music.artist:'Choose from Everest-owned or licensed tracks'}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted}/></Pressable>
   <View style={s.option}><View style={s.optionIcon}><Ionicons name="location-outline" size={19} color={colors.text}/></View><TextInput value={location} onChangeText={setLocation} placeholder="Location (optional)" placeholderTextColor={colors.muted} style={s.optionInput}/></View>
   {identity?.kind==='PERSONAL'?<Pressable onPress={()=>setVisibility(v=>v==='PUBLIC'?'FOLLOWERS':'PUBLIC')} style={s.option}><View style={s.optionIcon}><Ionicons name={visibility==='PUBLIC'?'globe-outline':'people-outline'} size={19} color={colors.text}/></View><View style={{flex:1}}><Text style={s.optionTitle}>{visibility==='PUBLIC'?'Public story':'Connections only'}</Text><Text style={s.optionCopy}>Tap to change audience</Text></View></Pressable>:null}
   {error?<Text style={s.error}>{error}</Text>:null}
   <Pressable disabled={busy||!asset} onPress={()=>void publish()} style={[s.primary,(busy||!asset)&&{opacity:.45}]}>{busy?<ActivityIndicator color={colors.onBrand}/>:<><Ionicons name="sparkles-outline" size={18} color={colors.onBrand}/><Text style={s.primaryText}>SHARE STORY</Text></>}</Pressable>
  </>}
 </ScrollView><MusicPicker visible={musicOpen} selected={music} onClose={()=>setMusicOpen(false)} onSelect={setMusic}/></SafeAreaView>;
}
const styles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:16,paddingBottom:70,maxWidth:720,width:'100%',alignSelf:'center'},header:{height:62,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},round:{width:40,height:40,borderRadius:20,backgroundColor:c.surface,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center'},title:{fontSize:18,fontWeight:'900',color:c.text},share:{fontSize:10,fontWeight:'900',letterSpacing:.8,color:c.brand},label:{fontSize:8,fontWeight:'900',letterSpacing:1.5,color:c.muted,marginTop:10,marginBottom:9},rail:{gap:8,paddingRight:12},identity:{height:40,borderRadius:20,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:7},identityActive:{backgroundColor:c.brand,borderColor:c.brand},identityText:{fontSize:10,fontWeight:'900',color:c.text},preview:{height:430,borderRadius:28,overflow:'hidden',backgroundColor:c.elevated,borderWidth:1,borderColor:c.border,marginTop:18},image:{width:'100%',height:'100%',resizeMode:'cover'},empty:{flex:1,alignItems:'center',justifyContent:'center',padding:28},emptyIcon:{width:58,height:58,borderRadius:22,backgroundColor:c.soft,alignItems:'center',justifyContent:'center'},emptyTitle:{fontSize:17,fontWeight:'900',color:c.text,marginTop:14},emptyCopy:{fontSize:11,lineHeight:17,color:c.muted,textAlign:'center',marginTop:5,maxWidth:300},input:{minHeight:54,borderRadius:16,borderWidth:1,borderColor:c.border,backgroundColor:c.input,color:c.text,paddingHorizontal:14,marginTop:12},option:{minHeight:62,borderRadius:18,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,padding:11,marginTop:9,flexDirection:'row',alignItems:'center',gap:10},optionIcon:{width:38,height:38,borderRadius:13,backgroundColor:c.soft,alignItems:'center',justifyContent:'center'},optionTitle:{fontSize:12,fontWeight:'900',color:c.text},optionCopy:{fontSize:9,color:c.muted,marginTop:3},optionInput:{flex:1,color:c.text,fontSize:12},error:{fontSize:11,color:c.danger,marginTop:12},primary:{height:54,borderRadius:18,backgroundColor:c.brand,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:17},primaryText:{fontSize:10,fontWeight:'900',letterSpacing:.6,color:c.onBrand}});
