import {useCallback,useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Linking,Platform,Pressable,ScrollView,StyleSheet,Switch,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {router,useLocalSearchParams} from 'expo-router';
import {
 beginCustomerGoogleCalendarOAuth,configureCustomerCalendar,connectDeviceCalendar,disconnectCustomerGoogleCalendar,disconnectDeviceCalendar,
 listCustomerCalendarConnections,syncCustomerCalendar,type CustomerCalendarConnection
} from '@/lib/customer-calendar';
import {type ThemeColors,useAppTheme} from '@/lib/theme';

export default function CustomerCalendar(){
 const {colors}=useAppTheme();const st=useMemo(()=>styles(colors),[colors]);
 const params=useLocalSearchParams<{connected?:string}>();
 const [rows,setRows]=useState<CustomerCalendarConnection[]>([]);const [loading,setLoading]=useState(true);const [working,setWorking]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{setRows(await listCustomerCalendarConnections())}catch(e){setError(e instanceof Error?e.message:'Calendar settings could not load.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(params.connected==='google'){setNotice('Google Calendar connected. Sync once to import your busy time and add eligible Everest bookings.');void load()}},[params.connected,load]);

 async function work(key:string,fn:()=>Promise<unknown>,success?:string){if(working)return;setWorking(key);setError('');setNotice('');try{await fn();if(success)setNotice(success);await load()}catch(e){setError(e instanceof Error?e.message:'That calendar action could not be completed.')}finally{setWorking('')}}
 async function connectGoogle(){await work('google-connect',async()=>{const url=await beginCustomerGoogleCalendarOAuth();await Linking.openURL(url)})}
 async function connectDevice(){await work('device-connect',connectDeviceCalendar,'Device calendar connected and synced.')}
 async function update(row:CustomerCalendarConnection,patch:Partial<Pick<CustomerCalendarConnection,'import_busy_time'|'export_marketplace_bookings'|'allow_ask_everest'>>){const previous=rows;setRows(current=>current.map(x=>x.id===row.id?{...x,...patch}:x));setWorking(row.id);setError('');try{await configureCustomerCalendar(row.id,patch)}catch(e){setRows(previous);setError(e instanceof Error?e.message:'Calendar preference could not be saved.')}finally{setWorking('')}}
 async function disconnect(row:CustomerCalendarConnection){await work('disconnect-'+row.id,()=>row.provider==='GOOGLE_CALENDAR'?disconnectCustomerGoogleCalendar(row.id):disconnectDeviceCalendar(row.id),'Calendar disconnected.')}
 const google=rows.find(x=>x.provider==='GOOGLE_CALENDAR');
 const device=rows.find(x=>x.provider==='APPLE_DEVICE');

 return <SafeAreaView style={st.safe} edges={['top']}><ScrollView contentContainerStyle={st.page}>
  <View style={st.header}><Pressable onPress={()=>router.back()} style={st.back} accessibilityLabel="Go back"><Ionicons name="arrow-back" size={20} color={colors.text}/></Pressable><View style={{flex:1}}><Text style={st.eyebrow}>PERSONAL AVAILABILITY</Text><Text style={st.title}>Calendar & Everest</Text></View></View>
  <View style={st.hero}><View style={st.heroIcon}><Ionicons name="calendar-outline" size={24} color={colors.brand}/></View><View style={{flex:1}}><Text style={st.heroTitle}>Let Everest work around your real schedule</Text><Text style={st.copy}>Connect a calendar to avoid clashes and let Ask Everest reason about when you are free. Everest stores busy time only—not private event names, notes, locations or attendees.</Text></View></View>
  {notice?<View style={st.notice}><Ionicons name="checkmark-circle-outline" size={18} color={colors.brand}/><Text style={st.noticeText}>{notice}</Text></View>:null}
  {error?<View style={st.error}><Ionicons name="alert-circle-outline" size={18} color={colors.danger}/><Text style={st.errorText}>{error}</Text></View>:null}
  {loading?<ActivityIndicator color={colors.brand} style={{marginTop:38}}/>:<>
   <Text style={st.section}>CONNECTED CALENDARS</Text>
   <ProviderCard icon="logo-google" title="Google Calendar" copy="Works across iPhone, Android and web." row={google} working={working} colors={colors}
    onConnect={()=>void connectGoogle()} onSync={row=>void work('sync-'+row.id,()=>syncCustomerCalendar(row),'Google Calendar synced.')} onDisconnect={row=>void disconnect(row)} onUpdate={update}/>
   {Platform.OS!=='web'?<ProviderCard icon="logo-apple" title={Platform.OS==='ios'?'Apple Calendar':'Device Calendar'} copy="Uses the calendars already available on this device." row={device} working={working} colors={colors}
    onConnect={()=>void connectDevice()} onSync={row=>void work('sync-'+row.id,()=>syncCustomerCalendar(row),'Device calendar synced.')} onDisconnect={row=>void disconnect(row)} onUpdate={update}/>:<View style={st.webHint}><Ionicons name="phone-portrait-outline" size={18} color={colors.muted}/><Text style={st.copy}>Apple/device calendar connection appears in the Everest mobile app. Google Calendar can be connected here on web.</Text></View>}
   <Text style={st.section}>HOW ASK EVEREST USES IT</Text>
   <View style={st.infoCard}><Text style={st.infoTitle}>Busy, not private</Text><Text style={st.copy}>Ask Everest can see windows such as “busy 2:00–3:00 PM” only when you enable the setting below. It cannot see what the event is about.</Text><View style={st.example}><Text style={st.exampleText}>“Find me a cleaner next Tuesday when I’m free after 3 PM.”</Text></View><Text style={st.copy}>Everest can compare your busy windows with your marketplace bookings and suggest suitable times. Booking, cancellation or rescheduling still requires an explicit action from you.</Text></View>
  </>}
 </ScrollView></SafeAreaView>;
}

function ProviderCard({icon,title,copy,row,working,colors,onConnect,onSync,onDisconnect,onUpdate}:{icon:keyof typeof Ionicons.glyphMap;title:string;copy:string;row?:CustomerCalendarConnection;working:string;colors:ThemeColors;onConnect:()=>void;onSync:(row:CustomerCalendarConnection)=>void;onDisconnect:(row:CustomerCalendarConnection)=>void;onUpdate:(row:CustomerCalendarConnection,patch:Partial<Pick<CustomerCalendarConnection,'import_busy_time'|'export_marketplace_bookings'|'allow_ask_everest'>>)=>Promise<void>}){
 const s=useMemo(()=>styles(colors),[colors]);const busy=working===row?.id||working==='sync-'+row?.id||working==='disconnect-'+row?.id||working.includes('connect');
 return <View style={s.card}><View style={s.cardHead}><View style={s.providerIcon}><Ionicons name={icon} size={22} color={colors.text}/></View><View style={{flex:1}}><View style={s.titleLine}><Text style={s.cardTitle}>{title}</Text>{row?<View style={s.connected}><Text style={s.connectedText}>{row.status.replaceAll('_',' ')}</Text></View>:null}</View><Text style={s.copy}>{row?.account_label||copy}</Text>{row?.last_synced_at?<Text style={s.meta}>Last synced {new Date(row.last_synced_at).toLocaleString()}</Text>:null}</View></View>
  {row?<><Setting title="Use busy time" copy="Import only anonymous start/end busy windows." value={row.import_busy_time} disabled={busy} onChange={value=>void onUpdate(row,{import_busy_time:value})} colors={colors}/><Setting title="Add Everest bookings" copy="Keep confirmed Everest bookings in this calendar." value={row.export_marketplace_bookings} disabled={busy} onChange={value=>void onUpdate(row,{export_marketplace_bookings:value})} colors={colors}/><Setting title="Use with Ask Everest" copy="Allow the assistant to use anonymous busy windows when helping with timing." value={row.allow_ask_everest} disabled={busy} onChange={value=>void onUpdate(row,{allow_ask_everest:value})} colors={colors}/><View style={s.actions}><Pressable disabled={busy} onPress={()=>onSync(row)} style={s.primary}>{working==='sync-'+row.id?<ActivityIndicator color={colors.onBrand}/>:<><Ionicons name="sync-outline" size={15} color={colors.onBrand}/><Text style={s.primaryText}>SYNC NOW</Text></>}</Pressable><Pressable disabled={busy} onPress={()=>onDisconnect(row)} style={s.secondary}><Text style={s.secondaryText}>DISCONNECT</Text></Pressable></View></>:<Pressable disabled={working.includes('connect')} onPress={onConnect} style={s.primary}>{working.includes('connect')?<ActivityIndicator color={colors.onBrand}/>:<Text style={s.primaryText}>CONNECT</Text>}</Pressable>}
 </View>
}
function Setting({title,copy,value,disabled,onChange,colors}:{title:string;copy:string;value:boolean;disabled:boolean;onChange:(value:boolean)=>void;colors:ThemeColors}){const s=useMemo(()=>styles(colors),[colors]);return <View style={s.setting}><View style={{flex:1}}><Text style={s.settingTitle}>{title}</Text><Text style={s.settingCopy}>{copy}</Text></View><Switch disabled={disabled} value={value} onValueChange={onChange} trackColor={{false:colors.border,true:colors.brand}}/></View>}

const styles=(c:ThemeColors)=>StyleSheet.create({
 safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:70,maxWidth:760,width:'100%',alignSelf:'center'},header:{flexDirection:'row',alignItems:'center',gap:12},back:{width:40,height:40,borderWidth:1,borderColor:c.border,borderRadius:12,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:8,fontWeight:'900',letterSpacing:1.1,color:c.muted},title:{fontSize:28,fontWeight:'900',color:c.text,marginTop:2},
 hero:{marginTop:22,borderWidth:1,borderColor:c.border,borderRadius:19,backgroundColor:c.surface,padding:17,flexDirection:'row',gap:13},heroIcon:{width:44,height:44,borderRadius:14,backgroundColor:c.soft,alignItems:'center',justifyContent:'center'},heroTitle:{fontSize:16,fontWeight:'900',color:c.text},copy:{fontSize:10,lineHeight:16,color:c.muted,marginTop:4},section:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:c.muted,marginTop:25,marginBottom:8},
 card:{borderWidth:1,borderColor:c.border,borderRadius:17,backgroundColor:c.surface,padding:16,marginBottom:12},cardHead:{flexDirection:'row',gap:12,alignItems:'center'},providerIcon:{width:44,height:44,borderRadius:13,backgroundColor:c.soft,alignItems:'center',justifyContent:'center'},titleLine:{flexDirection:'row',alignItems:'center',gap:8,flexWrap:'wrap'},cardTitle:{fontSize:15,fontWeight:'900',color:c.text},connected:{backgroundColor:c.soft,borderRadius:7,paddingHorizontal:7,paddingVertical:4},connectedText:{fontSize:7,fontWeight:'900',color:c.brand},meta:{fontSize:8,color:c.muted,marginTop:5},
 setting:{minHeight:72,borderTopWidth:1,borderTopColor:c.border,flexDirection:'row',alignItems:'center',gap:12,marginTop:12,paddingTop:10},settingTitle:{fontSize:12,fontWeight:'900',color:c.text},settingCopy:{fontSize:9,lineHeight:14,color:c.muted,marginTop:3},actions:{flexDirection:'row',gap:8,marginTop:14,flexWrap:'wrap'},primary:{minHeight:42,backgroundColor:c.brand,borderRadius:11,alignItems:'center',justifyContent:'center',paddingHorizontal:15,flexDirection:'row',gap:7,alignSelf:'flex-start'},primaryText:{fontSize:8,fontWeight:'900',color:c.onBrand},secondary:{minHeight:42,borderWidth:1,borderColor:c.border,borderRadius:11,alignItems:'center',justifyContent:'center',paddingHorizontal:15},secondaryText:{fontSize:8,fontWeight:'900',color:c.text},
 notice:{marginTop:14,borderWidth:1,borderColor:c.border,borderRadius:12,padding:12,flexDirection:'row',gap:9,alignItems:'center',backgroundColor:c.surface},noticeText:{fontSize:10,lineHeight:15,color:c.text,flex:1},error:{marginTop:14,borderWidth:1,borderColor:c.danger,borderRadius:12,padding:12,flexDirection:'row',gap:9,alignItems:'center'},errorText:{fontSize:10,lineHeight:15,color:c.danger,flex:1},webHint:{borderWidth:1,borderColor:c.border,borderRadius:14,padding:14,flexDirection:'row',gap:10,alignItems:'center'},infoCard:{borderWidth:1,borderColor:c.border,borderRadius:17,backgroundColor:c.surface,padding:17},infoTitle:{fontSize:15,fontWeight:'900',color:c.text},example:{marginVertical:13,borderLeftWidth:3,borderLeftColor:c.brand,paddingLeft:12},exampleText:{fontSize:13,lineHeight:20,fontWeight:'700',color:c.text}
});
