import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { supabase } from '@/lib/supabase';
import type { DeliveryStatus } from '@/lib/types';

type Delivery={id:string;order_id:string;status:DeliveryStatus;fee:number;eta:string|null;notes:string|null;customer_location:Record<string,unknown>|null};
type Driver={id:string;full_name:string|null};

function locationLabel(value:Record<string,unknown>|null){if(!value)return '';const parts=['address','address_line','suburb','city','state','postcode'].flatMap(key=>typeof value[key]==='string'?[value[key] as string]:[]);return parts.join(', ');}
function mapsQuery(value:Record<string,unknown>|null){if(!value)return '';if(typeof value.latitude==='number'&&typeof value.longitude==='number')return `${value.latitude},${value.longitude}`;return locationLabel(value);}

export default function Delivery(){
 const [items,setItems]=useState<Delivery[]>([]);const [drivers,setDrivers]=useState<Driver[]>([]);const [isAdmin,setIsAdmin]=useState(false);const [isDriver,setIsDriver]=useState(false);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState('');
 async function load(){try{setError('');const {data:user}=await supabase.auth.getUser();if(!user.user)throw new Error('Authentication required');const {data:profile,error:pe}=await supabase.from('profiles').select('role').eq('id',user.user.id).single();if(pe)throw pe;const admin=profile?.role==='ADMIN';const driver=profile?.role==='DELIVERY_DRIVER';setIsAdmin(admin);setIsDriver(driver);
  const {data,error:e}=await supabase.from('deliveries').select('id,order_id,status,fee,eta,notes,customer_location').order('created_at',{ascending:false});if(e)throw e;setItems((data??[]) as Delivery[]);
  if(admin){const {data:ds,error:de}=await supabase.from('profiles').select('id,full_name').eq('role','DELIVERY_DRIVER').order('full_name');if(de)throw de;setDrivers((ds??[]) as Driver[])}else setDrivers([]);
 }catch{setError('We could not load delivery operations right now.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const next=(status:DeliveryStatus):DeliveryStatus|null=>({PENDING:'ACCEPTED',ACCEPTED:'PREPARING',PREPARING:'READY_FOR_PICKUP',ASSIGNED:'PICKED_UP',PICKED_UP:'OUT_FOR_DELIVERY',OUT_FOR_DELIVERY:'DELIVERED'} as Partial<Record<DeliveryStatus,DeliveryStatus>>)[status]??null;
 const canCancel=(status:DeliveryStatus)=>['PENDING','ACCEPTED','PREPARING','ASSIGNED'].includes(status);
 const canFail=(status:DeliveryStatus)=>status==='OUT_FOR_DELIVERY';
 const earnings=useMemo(()=>items.filter(item=>item.status==='DELIVERED').reduce((sum,item)=>sum+Number(item.fee),0),[items]);
 async function update(d:Delivery,status:DeliveryStatus){setBusy(d.id);setError('');try{const {error:e}=await supabase.rpc('update_delivery_status',{p_delivery_id:d.id,p_status:status});if(e)throw e;await load()}catch(e){setError('That delivery update could not be completed.')}finally{setBusy(null)}}
 async function assign(d:Delivery,driverId:string){setBusy(d.id);setError('');try{const {error:e}=await supabase.rpc('assign_delivery_driver',{p_delivery_id:d.id,p_driver_id:driverId});if(e)throw e;await load()}catch(e){setError('Driver assignment could not be completed.')}finally{setBusy(null)}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
  <Text style={s.eyebrow}>EVEREST DELIVERY</Text><Text style={s.title}>{isDriver?'Driver jobs':'Delivery operations'}</Text>
  {isDriver&&<View style={s.driverSummary}><View><Text style={s.summaryLabel}>ASSIGNED JOBS</Text><Text style={s.summaryValue}>{items.length}</Text></View><View><Text style={s.summaryLabel}>COMPLETED FEES</Text><Text style={s.summaryValue}>${earnings.toFixed(2)}</Text></View><View><Text style={s.summaryLabel}>STATUS</Text><Text style={s.summaryValue}>ACTIVE JOBS</Text></View></View>}
  {!isDriver&&<Text style={s.copy}>Customers and businesses can view only deliveries connected to their orders. Status changes remain server-authorized.</Text>}
  {loading?<ActivityIndicator/>:items.length?items.map(d=><View style={s.card} key={d.id}><Text style={s.order}>ORDER {d.order_id.slice(0,8).toUpperCase()}</Text><Text style={s.status}>{d.status.replaceAll('_',' ')}</Text><Text style={s.meta}>Delivery fee: ${Number(d.fee).toFixed(2)} AUD{d.eta?` · ETA ${new Date(d.eta).toLocaleString()}`:''}</Text>{isDriver&&locationLabel(d.customer_location)&&<><Text style={s.destinationLabel}>CUSTOMER DESTINATION</Text><Text style={s.destination}>{locationLabel(d.customer_location)}</Text><Pressable onPress={()=>{const query=mapsQuery(d.customer_location);if(query)void Linking.openURL(`https://maps.apple.com/?q=${encodeURIComponent(query)}`)}} style={s.outline}><Text style={s.outlineText}>OPEN NAVIGATION</Text></Pressable></>}{isAdmin&&d.status==='READY_FOR_PICKUP'&&<View style={s.assignment}><Text style={s.assignTitle}>Assign delivery driver</Text>{drivers.length?drivers.map(driver=><Pressable key={driver.id} disabled={busy!==null} onPress={()=>void assign(d,driver.id)} style={s.outline}><Text style={s.outlineText}>{driver.full_name||'Delivery driver'}</Text></Pressable>):<Text style={s.meta}>No delivery driver accounts are configured.</Text>}</View>}{next(d.status)&&<Pressable disabled={busy!==null} onPress={()=>void update(d,next(d.status)!)} style={s.button}><Text style={s.buttonText}>{isDriver&&d.status==='ASSIGNED'?'PICK UP ORDER':`ADVANCE TO ${next(d.status)?.replaceAll('_',' ')}`}</Text></Pressable>}{canCancel(d.status)&&<Pressable disabled={busy!==null} onPress={()=>void update(d,'CANCELLED')} style={s.outlineAction}><Text style={s.outlineText}>CANCEL DELIVERY</Text></Pressable>}{canFail(d.status)&&<Pressable disabled={busy!==null} onPress={()=>void update(d,'FAILED')} style={s.outlineAction}><Text style={s.outlineText}>MARK DELIVERY FAILED</Text></Pressable>}</View>):<View style={s.empty}><Text style={s.emptyTitle}>{isDriver?'No delivery jobs yet.':'No active deliveries.'}</Text><Text style={s.meta}>{isDriver?'Assigned deliveries will appear here.':'Deliveries appear here only when a real eligible paid order exists.'}</Text></View>}{!!error&&<Text style={s.error}>{error}</Text>}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:50},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:'#777'},title:{fontSize:31,fontWeight:'900',marginTop:7},copy:{fontSize:13,lineHeight:20,color:'#777',marginTop:8,marginBottom:24},driverSummary:{marginTop:18,backgroundColor:'#151515',borderRadius:20,padding:17,flexDirection:'row',justifyContent:'space-between'},summaryLabel:{fontSize:8,fontWeight:'900',letterSpacing:.8,color:'#aaa'},summaryValue:{fontSize:18,fontWeight:'900',color:'#fff',marginTop:5},card:{backgroundColor:'#fff',borderRadius:17,borderWidth:1,borderColor:'#e5e2dc',padding:17,marginTop:10},order:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#777'},status:{fontSize:17,fontWeight:'900',marginTop:8},meta:{fontSize:11,color:'#777',marginTop:5},destinationLabel:{fontSize:8,fontWeight:'900',letterSpacing:1,color:'#777',marginTop:14},destination:{fontSize:13,fontWeight:'700',lineHeight:18,marginTop:5},assignment:{marginTop:14,paddingTop:12,borderTopWidth:1,borderTopColor:'#eeeae3'},assignTitle:{fontSize:11,fontWeight:'800',marginBottom:8},button:{height:46,borderRadius:12,backgroundColor:'#111',alignItems:'center',justifyContent:'center',marginTop:13},buttonText:{fontSize:9,fontWeight:'900',color:'#fff'},outline:{minHeight:42,borderRadius:11,borderWidth:1,borderColor:'#ddd8cf',alignItems:'center',justifyContent:'center',paddingHorizontal:12,paddingVertical:8,marginTop:9},outlineAction:{height:42,borderRadius:11,borderWidth:1,borderColor:'#ddd8cf',alignItems:'center',justifyContent:'center',marginTop:8},outlineText:{fontSize:9,fontWeight:'800',textAlign:'center'},empty:{backgroundColor:'#fff',borderRadius:19,padding:28,alignItems:'center',marginTop:12},emptyTitle:{fontSize:16,fontWeight:'800'},error:{fontSize:12,color:'#b42318',marginTop:12}});
