import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { supabase } from '@/lib/supabase';
import type { DeliveryStatus } from '@/lib/types';

type Delivery={id:string;order_id:string;status:DeliveryStatus;fee:number;eta:string|null;notes:string|null};
type Driver={id:string;full_name:string|null;phone:string|null};

export default function Delivery(){
 const [items,setItems]=useState<Delivery[]>([]);const [drivers,setDrivers]=useState<Driver[]>([]);const [isAdmin,setIsAdmin]=useState(false);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState('');
 async function load(){try{setError('');const {data:user}=await supabase.auth.getUser();if(!user.user)throw new Error('Authentication required');const {data:profile,error:pe}=await supabase.from('profiles').select('role').eq('id',user.user.id).single();if(pe)throw pe;const admin=profile?.role==='ADMIN';setIsAdmin(admin);const {data,error:e}=await supabase.from('deliveries').select('id,order_id,status,fee,eta,notes').order('created_at',{ascending:false});if(e)throw e;setItems((data??[]) as Delivery[]);if(admin){const {data:ds,error:de}=await supabase.from('profiles').select('id,full_name,phone').eq('role','DELIVERY_DRIVER').order('full_name');if(de)throw de;setDrivers((ds??[]) as Driver[]);}else setDrivers([]);}catch(e){setError(e instanceof Error?e.message:'Unable to load delivery operations.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const next=(status:DeliveryStatus):DeliveryStatus|null=>({PENDING:'ACCEPTED',ACCEPTED:'PREPARING',PREPARING:'READY_FOR_PICKUP',ASSIGNED:'PICKED_UP',PICKED_UP:'OUT_FOR_DELIVERY',OUT_FOR_DELIVERY:'DELIVERED'} as Partial<Record<DeliveryStatus,DeliveryStatus>>)[status]??null;
 async function advance(d:Delivery){const value=next(d.status);if(!value)return;setBusy(d.id);setError('');try{const {error:e}=await supabase.rpc('update_delivery_status',{p_delivery_id:d.id,p_status:value});if(e)throw e;await load()}catch(e){setError(e instanceof Error?e.message:'Delivery status update failed.')}finally{setBusy(null)}}
 async function assign(d:Delivery,driverId:string){setBusy(d.id);setError('');try{const {error:e}=await supabase.rpc('assign_delivery_driver',{p_delivery_id:d.id,p_driver_id:driverId});if(e)throw e;await load()}catch(e){setError(e instanceof Error?e.message:'Driver assignment failed.')}finally{setBusy(null)}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.eyebrow}>EVEREST DELIVERY</Text><Text style={s.title}>Delivery operations</Text><Text style={s.copy}>Customers and businesses can view only deliveries connected to their orders. Status changes are restricted to assigned drivers and admins.</Text>{loading?<ActivityIndicator/>:items.length?items.map(d=><View style={s.card} key={d.id}><Text style={s.order}>ORDER {d.order_id.slice(0,8).toUpperCase()}</Text><Text style={s.status}>{d.status.replaceAll('_',' ')}</Text><Text style={s.meta}>Fee: ${Number(d.fee).toFixed(2)} AUD{d.eta?` · ETA ${new Date(d.eta).toLocaleString()}`:''}</Text>{isAdmin&&d.status==='READY_FOR_PICKUP'&&<View style={s.assignment}><Text style={s.assignTitle}>Assign delivery driver</Text>{drivers.length?drivers.map(driver=><Pressable key={driver.id} disabled={busy!==null} onPress={()=>void assign(d,driver.id)} style={s.outline}><Text style={s.outlineText}>{driver.full_name||'Delivery driver'}{driver.phone?` · ${driver.phone}`:''}</Text></Pressable>):<Text style={s.meta}>No delivery driver accounts are configured.</Text>}</View>}{next(d.status)&&<Pressable disabled={busy!==null} onPress={()=>void advance(d)} style={s.button}><Text style={s.buttonText}>ADVANCE TO {next(d.status)?.replaceAll('_',' ')}</Text></Pressable>}</View>):<View style={s.empty}><Text style={s.emptyTitle}>No active deliveries.</Text><Text style={s.meta}>Deliveries appear here only when a real eligible paid order exists.</Text></View>}{!!error&&<Text style={s.error}>{error}</Text>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:50},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:'#777'},title:{fontSize:31,fontWeight:'900',marginTop:7},copy:{fontSize:13,lineHeight:20,color:'#777',marginTop:8,marginBottom:24},card:{backgroundColor:'#fff',borderRadius:17,borderWidth:1,borderColor:'#e5e2dc',padding:17,marginBottom:10},order:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#777'},status:{fontSize:17,fontWeight:'900',marginTop:8},meta:{fontSize:11,color:'#777',marginTop:5},assignment:{marginTop:14,paddingTop:12,borderTopWidth:1,borderTopColor:'#eeeae3'},assignTitle:{fontSize:11,fontWeight:'800',marginBottom:8},button:{height:46,borderRadius:12,backgroundColor:'#111',alignItems:'center',justifyContent:'center',marginTop:13},buttonText:{fontSize:9,fontWeight:'900',color:'#fff'},outline:{minHeight:42,borderRadius:11,borderWidth:1,borderColor:'#ddd8cf',alignItems:'center',justifyContent:'center',paddingHorizontal:12,paddingVertical:8,marginBottom:7},outlineText:{fontSize:9,fontWeight:'800',textAlign:'center'},empty:{backgroundColor:'#fff',borderRadius:19,padding:28,alignItems:'center'},emptyTitle:{fontSize:16,fontWeight:'800'},error:{fontSize:12,color:'#b42318',marginTop:12}});
