import { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Linking, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { supabase } from '@/lib/supabase';
import { getMyAccessContext } from '@/lib/access';
import { getDriverAvailability, setDriverAvailability, type DriverAvailability } from '@/lib/driver';
import { type ThemeColors, useAppTheme } from '@/lib/theme';
import type { DeliveryStatus } from '@/lib/types';

type Delivery={id:string;order_id:string;status:DeliveryStatus;fee:number;eta:string|null;notes:string|null;customer_location:Record<string,unknown>|null;accepted_at?:string|null};
type Driver={id:string;full_name:string|null};

function locationLabel(value:Record<string,unknown>|null){if(!value)return '';const parts=['address','address_line','suburb','city','state','postcode'].flatMap(key=>typeof value[key]==='string'?[value[key] as string]:[]);return parts.join(', ');}
function mapsQuery(value:Record<string,unknown>|null){if(!value)return '';if(typeof value.latitude==='number'&&typeof value.longitude==='number')return `${value.latitude},${value.longitude}`;return locationLabel(value);}

export default function Delivery(){
 const {colors}=useAppTheme();const s=useMemo(()=>createStyles(colors),[colors]);
 const [items,setItems]=useState<Delivery[]>([]);const [drivers,setDrivers]=useState<Driver[]>([]);const [isAdmin,setIsAdmin]=useState(false);const [isDriver,setIsDriver]=useState(false);const [availability,setAvailability]=useState<DriverAvailability|null>(null);const [radius,setRadius]=useState('10');const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [hasLoaded,setHasLoaded]=useState(false);const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState('');
 const loadRef=useRef(false);const operationRef=useRef(false);const hasLoadedRef=useRef(false);
 async function load(mode:'initial'|'refresh'|'silent'='initial'){if(loadRef.current)return;loadRef.current=true;if(mode==='initial'&&!hasLoadedRef.current)setLoading(true);if(mode==='refresh')setRefreshing(true);setError('');try{const {data:user}=await supabase.auth.getUser();if(!user.user)throw new Error('Authentication required');const access=await getMyAccessContext();const admin=access.is_admin;const driver=access.is_active_driver;let nextAvailability=availability;if(driver){nextAvailability=await getDriverAvailability();}
  const {data,error:e}=await supabase.from('deliveries').select('id,order_id,status,fee,eta,notes,customer_location').order('created_at',{ascending:false});if(e)throw e;let deliveryItems=(data??[]) as Delivery[];if(driver&&deliveryItems.length){const {data:assignments,error:ae}=await supabase.from('delivery_assignments').select('delivery_id,accepted_at').eq('driver_id',user.user.id).in('delivery_id',deliveryItems.map(item=>item.id));if(ae)throw ae;const accepted=new Map((assignments??[]).map(item=>[item.delivery_id,item.accepted_at]));deliveryItems=deliveryItems.map(item=>({...item,accepted_at:accepted.get(item.id)??null}));}
  let nextDrivers:Driver[]=[];if(admin){const {data:apps,error:ae}=await supabase.from('driver_applications').select('user_id').eq('status','APPROVED');if(ae)throw ae;const ids=(apps??[]).map(item=>item.user_id);if(ids.length){const {data:ds,error:de}=await supabase.from('profiles').select('id,full_name').in('id',ids).order('full_name');if(de)throw de;nextDrivers=(ds??[]) as Driver[];}}
  setIsAdmin(admin);setIsDriver(driver);setItems(deliveryItems);setDrivers(nextDrivers);if(driver&&nextAvailability){setAvailability(nextAvailability);setRadius(String(nextAvailability.service_radius_km));}else if(!driver)setAvailability(null);hasLoadedRef.current=true;setHasLoaded(true);
 }catch{setError(hasLoadedRef.current?'Delivery information may be out of date. Retry when you are ready.':'We could not load delivery operations right now.')}finally{loadRef.current=false;setLoading(false);setRefreshing(false)}}
 useEffect(()=>{void load()},[]); // eslint-disable-line react-hooks/exhaustive-deps
 const next=(status:DeliveryStatus):DeliveryStatus|null=>({PENDING:'ACCEPTED',ACCEPTED:'PREPARING',PREPARING:'READY_FOR_PICKUP',ASSIGNED:'PICKED_UP',PICKED_UP:'OUT_FOR_DELIVERY',OUT_FOR_DELIVERY:'DELIVERED'} as Partial<Record<DeliveryStatus,DeliveryStatus>>)[status]??null;
 const canCancel=(status:DeliveryStatus)=>['PENDING','ACCEPTED','PREPARING','ASSIGNED'].includes(status);
 const canFail=(status:DeliveryStatus)=>status==='OUT_FOR_DELIVERY';
 const completedCount=useMemo(()=>items.filter(item=>item.status==='DELIVERED').length,[items]); const activeCount=useMemo(()=>items.filter(item=>!['DELIVERED','CANCELLED','FAILED'].includes(item.status)).length,[items]); const todayCount=useMemo(()=>items.filter(item=>item.eta&&new Date(item.eta).toDateString()===new Date().toDateString()).length,[items]); const earnings=useMemo(()=>items.filter(item=>item.status==='DELIVERED').reduce((sum,item)=>sum+Number(item.fee),0),[items]);
 async function runOperation(id:string,work:()=>Promise<void>,failure:string){if(operationRef.current||loadRef.current)return;operationRef.current=true;setBusy(id);setError('');try{await work();await load('silent')}catch{setError(failure)}finally{operationRef.current=false;setBusy(null)}}
 async function accept(d:Delivery){await runOperation(d.id,async()=>{const {error:e}=await supabase.rpc('accept_delivery_assignment',{p_delivery_id:d.id});if(e)throw e},'That delivery could not be accepted.')}
 async function update(d:Delivery,status:DeliveryStatus){await runOperation(d.id,async()=>{const {error:e}=await supabase.rpc('update_delivery_status',{p_delivery_id:d.id,p_status:status});if(e)throw e},'That delivery update could not be completed.')}
 async function assign(d:Delivery,driverId:string){await runOperation(d.id,async()=>{const {error:e}=await supabase.rpc('assign_delivery_driver',{p_delivery_id:d.id,p_driver_id:driverId});if(e)throw e},'Driver assignment could not be completed.')}
 async function toggleAvailability(){if(!availability||operationRef.current||loadRef.current)return;operationRef.current=true;setBusy('availability');setError('');try{const nextStatus=availability.status==='ONLINE'?'OFFLINE':'ONLINE';const a=await setDriverAvailability(nextStatus,Number(radius));setAvailability(a)}catch{setError('Availability could not be updated right now.')}finally{operationRef.current=false;setBusy(null)}}
 const controlsBusy=busy!==null||refreshing||loading;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} refreshControl={<RefreshControl refreshing={refreshing} enabled={!controlsBusy} tintColor={colors.text} onRefresh={()=>void load('refresh')}/>}>
  <Text style={s.eyebrow}>EVEREST DELIVERY</Text><Text style={s.title}>{isDriver?'Driver jobs':'Delivery operations'}</Text>
  {isDriver&&availability&&<View style={s.availability}><View><Text style={s.availabilityLabel}>AVAILABILITY</Text><Text style={s.availabilityValue}>{availability.busy?'BUSY':availability.status}</Text><Text style={s.meta}>{availability.busy?'Active delivery in progress':`Service radius ${availability.service_radius_km} km`}</Text></View><View style={s.availabilityActions}>{!availability.busy&&<Pressable disabled={controlsBusy} onPress={()=>void toggleAvailability()} style={[s.smallButton,controlsBusy&&s.disabled]}><Text style={s.smallButtonText}>{availability.status==='ONLINE'?'GO OFFLINE':'GO ONLINE'}</Text></Pressable>}</View></View>}
  {isDriver&&<View style={s.driverSummary}><View><Text style={s.summaryLabel}>TODAY</Text><Text style={s.summaryValue}>{todayCount}</Text></View><View><Text style={s.summaryLabel}>ACTIVE</Text><Text style={s.summaryValue}>{activeCount}</Text></View><View><Text style={s.summaryLabel}>DONE</Text><Text style={s.summaryValue}>{completedCount}</Text></View><View><Text style={s.summaryLabel}>EARNED</Text><Text style={s.summaryValue}>${earnings.toFixed(0)}</Text></View></View>}
  {!isDriver&&<Text style={s.copy}>Customers and businesses can view only deliveries connected to their orders. Status changes remain server-authorized.</Text>}
  {loading&&!hasLoaded?<ActivityIndicator color={colors.text} style={{marginTop:32}}/>:items.length?items.map(d=><View style={s.card} key={d.id}><Text style={s.order}>ORDER {d.order_id.slice(0,8).toUpperCase()}</Text><Text style={s.status}>{d.status.replaceAll('_',' ')}</Text><Text style={s.meta}>Delivery fee: ${Number(d.fee).toFixed(2)} AUD{d.eta?` · ETA ${new Date(d.eta).toLocaleString()}`:''}</Text>{isDriver&&locationLabel(d.customer_location)&&<><Text style={s.destinationLabel}>CUSTOMER DESTINATION</Text><Text style={s.destination}>{locationLabel(d.customer_location)}</Text><Pressable disabled={controlsBusy} onPress={()=>{const query=mapsQuery(d.customer_location);if(query)void Linking.openURL(`https://maps.apple.com/?q=${encodeURIComponent(query)}`)}} style={[s.outline,controlsBusy&&s.disabled]}><Text style={s.outlineText}>OPEN NAVIGATION</Text></Pressable></>}{isAdmin&&d.status==='READY_FOR_PICKUP'&&<View style={s.assignment}><Text style={s.assignTitle}>Assign delivery driver</Text>{drivers.length?drivers.map(driver=><Pressable key={driver.id} disabled={controlsBusy} onPress={()=>void assign(d,driver.id)} style={[s.outline,controlsBusy&&s.disabled]}><Text style={s.outlineText}>{driver.full_name||'Delivery driver'}</Text></Pressable>):<Text style={s.meta}>No delivery driver accounts are configured.</Text>}</View>}{isDriver&&d.status==='ASSIGNED'&&!d.accepted_at?<Pressable disabled={controlsBusy} onPress={()=>void accept(d)} style={[s.button,controlsBusy&&s.disabled]}><Text style={s.buttonText}>ACCEPT DELIVERY</Text></Pressable>:next(d.status)&&<Pressable disabled={controlsBusy} onPress={()=>void update(d,next(d.status)!)} style={[s.button,controlsBusy&&s.disabled]}><Text style={s.buttonText}>{isDriver&&d.status==='ASSIGNED'?'PICK UP ORDER':`ADVANCE TO ${next(d.status)?.replaceAll('_',' ')}`}</Text></Pressable>}{canCancel(d.status)&&<Pressable disabled={controlsBusy} onPress={()=>void update(d,'CANCELLED')} style={[s.outlineAction,controlsBusy&&s.disabled]}><Text style={s.outlineText}>CANCEL DELIVERY</Text></Pressable>}{canFail(d.status)&&<Pressable disabled={controlsBusy} onPress={()=>void update(d,'FAILED')} style={[s.outlineAction,controlsBusy&&s.disabled]}><Text style={s.outlineText}>MARK DELIVERY FAILED</Text></Pressable>}</View>):hasLoaded?<View style={s.empty}><Text style={s.emptyTitle}>{isDriver?'No delivery jobs yet.':'No active deliveries.'}</Text><Text style={s.meta}>{isDriver?'Assigned deliveries will appear here.':'Deliveries appear here only when a real eligible paid order exists.'}</Text></View>:null}{!!error&&<View style={s.recovery}><Text style={s.error}>{error}</Text><Pressable disabled={controlsBusy} onPress={()=>void load(hasLoaded?'refresh':'initial')} style={[s.retry,controlsBusy&&s.disabled]}><Text style={s.retryText}>RETRY DELIVERY DATA</Text></Pressable></View>}</ScrollView></SafeAreaView>;
}
const createStyles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:50,maxWidth:760,width:'100%',alignSelf:'center'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:c.muted},title:{fontSize:31,fontWeight:'900',marginTop:7,color:c.text},copy:{fontSize:13,lineHeight:20,color:c.muted,marginTop:8,marginBottom:24},availability:{marginTop:18,backgroundColor:c.surface,borderRadius:18,borderWidth:1,borderColor:c.border,padding:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},availabilityLabel:{fontSize:8,fontWeight:'900',letterSpacing:1,color:c.muted},availabilityValue:{fontSize:19,fontWeight:'900',marginTop:4,color:c.text},availabilityActions:{alignItems:'flex-end'},smallButton:{height:40,borderRadius:11,backgroundColor:c.text,paddingHorizontal:14,alignItems:'center',justifyContent:'center'},smallButtonText:{fontSize:9,fontWeight:'900',color:c.canvas},driverSummary:{marginTop:18,backgroundColor:c.text,borderRadius:20,padding:17,flexDirection:'row',justifyContent:'space-between'},summaryLabel:{fontSize:8,fontWeight:'900',letterSpacing:.8,color:c.canvas,opacity:.7},summaryValue:{fontSize:18,fontWeight:'900',color:c.canvas,marginTop:5},card:{backgroundColor:c.surface,borderRadius:17,borderWidth:1,borderColor:c.border,padding:17,marginTop:10},order:{fontSize:9,fontWeight:'900',letterSpacing:1,color:c.muted},status:{fontSize:17,fontWeight:'900',marginTop:8,color:c.text},meta:{fontSize:11,color:c.muted,marginTop:5},destinationLabel:{fontSize:8,fontWeight:'900',letterSpacing:1,color:c.muted,marginTop:14},destination:{fontSize:13,fontWeight:'700',lineHeight:18,color:c.text},assignment:{marginTop:14,paddingTop:12,borderTopWidth:1,borderTopColor:c.border},assignTitle:{fontSize:11,fontWeight:'800',marginBottom:8,color:c.text},button:{height:46,borderRadius:12,backgroundColor:c.text,alignItems:'center',justifyContent:'center',marginTop:13},buttonText:{fontSize:9,fontWeight:'900',color:c.canvas},outline:{minHeight:42,borderRadius:11,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center',paddingHorizontal:12,paddingVertical:8,marginTop:9},outlineAction:{height:42,borderRadius:11,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center',marginTop:8},outlineText:{fontSize:9,fontWeight:'800',textAlign:'center',color:c.text},empty:{backgroundColor:c.surface,borderRadius:19,padding:28,alignItems:'center',marginTop:12,borderWidth:1,borderColor:c.border},emptyTitle:{fontSize:16,fontWeight:'800',color:c.text},recovery:{backgroundColor:c.soft,borderRadius:15,borderWidth:1,borderColor:c.border,padding:14,marginTop:12},error:{fontSize:12,color:c.text,lineHeight:18},retry:{height:40,borderRadius:10,backgroundColor:c.text,alignItems:'center',justifyContent:'center',marginTop:10},retryText:{fontSize:9,fontWeight:'900',color:c.canvas},disabled:{opacity:.5}});