import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Linking, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { supabase } from '@/lib/supabase';
import { DriverApplication, DriverDocument, DriverCompliance, adminSetDriverApplication, adminSetDriverCredentialDetails, adminSetDriverDocumentStatus, adminSetDriverVehicleVerification, getDriverDocumentSignedUrl } from '@/lib/driver';

type ReviewApplication = DriverApplication & { user_id: string; compliance?: DriverCompliance | null; history?: Array<{action:string;previous_status:string|null;new_status:string|null;reason:string|null;created_at:string}> };

function Pill({ label, good=false }: { label:string; good?:boolean }) { return <View style={[s.pill,good&&s.pillGood]}><Text style={[s.pillText,good&&s.pillGoodText]}>{label}</Text></View>; }
function ReviewRow({ label, value, good }: { label:string; value:string; good?:boolean }) { return <View style={s.reviewRow}><Text style={s.reviewLabel}>{label}</Text><Pill label={value} good={good}/></View>; }

export default function DriverVerificationAdmin(){
 const [applications,setApplications]=useState<ReviewApplication[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState(''); const [reasons,setReasons]=useState<Record<string,string>>({}); const [credentialChecks,setCredentialChecks]=useState<Record<string,{licenceExpiry:string;insuranceProvider:string;insurancePolicyReference:string;insuranceType:''|'ADDITIONAL_MOTOR'|'COMMERCIAL_BUSINESS_USE'|'OTHER';insuranceExpiry:string}>>({}); const [vehicleChecks,setVehicleChecks]=useState<Record<string,{registrationExpiry:string;registrationRestrictions:string;ctpProvider:string;ctpExpiry:string}>>({});
 async function load(){setLoading(true);setError('');try{
  const {data:user}=await supabase.auth.getUser(); if(!user.user)throw new Error('Authentication required');
  const {data:profile,error:pe}=await supabase.from('profiles').select('role').eq('id',user.user.id).single(); if(pe)throw pe; if(profile?.role!=='ADMIN')throw new Error('Admin authorization required');
  const {data:rows,error:ae}=await supabase.from('driver_applications').select('id,user_id,status,legal_first_name,legal_last_name,date_of_birth,address_line,postcode,suburb,city,state,service_area,availability,notes,status_reason,submitted_at,last_submitted_at').order('submitted_at',{ascending:false}).limit(100); if(ae)throw ae;
  const enriched=await Promise.all(((rows??[]) as ReviewApplication[]).map(async app=>{
   const [v,vehicle,docs,complianceResult,historyResult]=await Promise.all([
    supabase.from('driver_verifications').select('identity_status,licence_status,registration_status,insurance_status,verification_method,verification_provider,verification_reference,licence_jurisdiction,licence_number,licence_class,licence_expiry,licence_restrictions,insurance_provider,insurance_policy_reference,insurance_type,insurance_expiry').eq('application_id',app.id).maybeSingle(),
    supabase.from('driver_vehicles').select('id,registration_plate,registration_state,make,model,year,colour,vehicle_type,vin,ownership_status,registration_expiry,registration_restrictions,registration_status,ctp_provider,ctp_expiry,status').eq('application_id',app.id).maybeSingle(),
    supabase.from('driver_documents').select('id,document_type,document_subtype,storage_path,mime_type,size_bytes,status,uploaded_at,expires_at,rejection_reason,document_number,issuing_jurisdiction').eq('application_id',app.id).neq('status','REPLACED').order('uploaded_at',{ascending:false}),
    supabase.rpc('evaluate_driver_compliance',{p_application_id:app.id}),
    supabase.from('driver_status_history').select('action,previous_status,new_status,reason,created_at').eq('application_id',app.id).order('created_at',{ascending:false}).limit(20)
   ]); if(v.error)throw v.error;if(vehicle.error)throw vehicle.error;if(docs.error)throw docs.error;if(complianceResult.error)throw complianceResult.error;if(historyResult.error)throw historyResult.error;
   if(vehicle.data) setVehicleChecks(current=>({...current,[app.id]:{registrationExpiry:vehicle.data?.registration_expiry??'',registrationRestrictions:vehicle.data?.registration_restrictions??'',ctpProvider:vehicle.data?.ctp_provider??'',ctpExpiry:vehicle.data?.ctp_expiry??''}})); if(v.data) setCredentialChecks(current=>({...current,[app.id]:{licenceExpiry:v.data?.licence_expiry??'',insuranceProvider:v.data?.insurance_provider??'',insurancePolicyReference:v.data?.insurance_policy_reference??'',insuranceType:(v.data?.insurance_type??''),insuranceExpiry:v.data?.insurance_expiry??''}})); return {...app,verification:v.data as ReviewApplication['verification'],vehicle:vehicle.data as ReviewApplication['vehicle'],documents:(docs.data??[]) as DriverDocument[],declarations:[],compliance:complianceResult.data as DriverCompliance,history:(historyResult.data??[])};
  })); setApplications(enriched);
 }catch(e){setError(e instanceof Error?e.message:'Unable to load driver verification.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function action(app:ReviewApplication,status:'UNDER_REVIEW'|'MORE_INFORMATION_REQUIRED'|'APPROVED'|'REJECTED'|'SUSPENDED'){
  if(status!=='APPROVED'&&!reasons[app.id]?.trim()){Alert.alert('Reason required','Enter a reason before requesting information, rejecting or suspending a driver.');return;}
  setBusy(app.id);try{await adminSetDriverApplication(app.id,status,reasons[app.id]);await load()}catch(e){setError(e instanceof Error?e.message:'Admin action failed.')}finally{setBusy(null)}}
 async function docAction(doc:DriverDocument,status:'UNDER_REVIEW'|'VERIFIED'|'MORE_INFORMATION_REQUIRED'|'REJECTED'){
  const reason=status==='VERIFIED'?'':reasons[doc.id]??''; if(status!=='VERIFIED'&&!reason.trim()){Alert.alert('Reason required','Enter a reason for this document action.');return;}
  setBusy(doc.id);try{await adminSetDriverDocumentStatus(doc.id,status,reason);await load()}catch(e){setError(e instanceof Error?e.message:'Document review failed.')}finally{setBusy(null)}}
 async function credentialAction(app:ReviewApplication,kind:'LICENCE'|'INSURANCE'){const check=credentialChecks[app.id]??{licenceExpiry:'',insuranceProvider:'',insurancePolicyReference:'',insuranceType:'',insuranceExpiry:''};setBusy(app.id);try{await adminSetDriverCredentialDetails(app.id,{licenceStatus:kind==='LICENCE'?'VERIFIED':(app.verification?.licence_status??'PENDING') as 'PENDING'|'VERIFIED'|'MORE_INFORMATION_REQUIRED'|'REJECTED'|'EXPIRED',licenceExpiry:check.licenceExpiry,insuranceStatus:kind==='INSURANCE'?'VERIFIED':(app.verification?.insurance_status??'NOT_REQUIRED') as 'NOT_REQUIRED'|'PENDING'|'VERIFIED'|'MORE_INFORMATION_REQUIRED'|'REJECTED'|'EXPIRED',insuranceProvider:check.insuranceProvider,insurancePolicyReference:check.insurancePolicyReference,insuranceType:check.insuranceType,insuranceExpiry:check.insuranceExpiry});await load()}catch(e){setError(e instanceof Error?e.message:'Credential verification failed.')}finally{setBusy(null)}}
 async function vehicleAction(app:ReviewApplication){const check=vehicleChecks[app.id]??{registrationExpiry:'',registrationRestrictions:'',ctpProvider:'',ctpExpiry:''};setBusy(app.id);try{await adminSetDriverVehicleVerification(app.id,{registrationStatus:'CURRENT',registrationExpiry:check.registrationExpiry,registrationRestrictions:check.registrationRestrictions,ctpProvider:check.ctpProvider,ctpExpiry:check.ctpExpiry});await load()}catch(e){setError(e instanceof Error?e.message:'Vehicle verification failed.')}finally{setBusy(null)}}
 async function openDocument(doc:DriverDocument){setBusy(doc.id);try{const url=await getDriverDocumentSignedUrl(doc.id);await Linking.openURL(url)}catch(e){setError(e instanceof Error?e.message:'Could not open the secure document.')}finally{setBusy(null)}}
 if(loading)return <SafeAreaView style={s.safe}><ActivityIndicator style={{marginTop:60}}/></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
  <View style={s.top}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.topTitle}>Driver verification</Text><View style={{width:28}}/></View>
  <Text style={s.eyebrow}>ADMIN / SAFETY</Text><Text style={s.title}>Driver applications</Text>
  <Text style={s.copy}>Approval is blocked until the configured identity, licence, registration, vehicle and insurance checklist is complete. Profile roles never grant driver access by themselves.</Text>
  {!!error&&<Text style={s.error}>{error}</Text>}
  {!applications.length&&<View style={s.empty}><Text style={s.emptyTitle}>No driver applications.</Text><Text style={s.copy}>New applications will appear here after submission.</Text></View>}
  {applications.map(app=><View style={s.card} key={app.id}>
   <View style={s.cardHeader}><View style={{flex:1}}><Text style={s.name}>{app.legal_first_name} {app.legal_last_name}</Text><Text style={s.meta}>Application {app.id.slice(0,8).toUpperCase()} · Submitted {new Date(app.submitted_at).toLocaleDateString()}</Text></View><Pill label={app.status.replaceAll('_',' ')} good={app.status==='APPROVED'}/></View>
   <View style={s.identity}><Text style={s.section}>Identity</Text><Text style={s.meta}>{app.date_of_birth || 'DOB not entered'} · {app.address_line || 'Address not entered'}, {app.suburb || ''} {app.postcode || ''}</Text></View>
   <Text style={s.section}>Verification checklist</Text>
   <ReviewRow label="Identity" value={app.verification?.identity_status?.replaceAll('_',' ') ?? 'PENDING'} good={app.verification?.identity_status==='VERIFIED'}/>
   <ReviewRow label="Licence" value={app.verification?.licence_status?.replaceAll('_',' ') ?? 'PENDING'} good={app.verification?.licence_status==='VERIFIED'}/>
   <ReviewRow label="Registration" value={app.verification?.registration_status?.replaceAll('_',' ') ?? 'PENDING'} good={app.verification?.registration_status==='VERIFIED'}/>
   <ReviewRow label="Insurance" value={app.verification?.insurance_status?.replaceAll('_',' ') ?? 'NOT REQUIRED'} good={app.verification?.insurance_status==='VERIFIED'||app.verification?.insurance_status==='NOT_REQUIRED'}/>
   {app.verification&&<View style={s.detailBox}><Text style={s.meta}>Licence: {app.verification.licence_jurisdiction || '—'} · Class {app.verification.licence_class || '—'} · Expiry {app.verification.licence_expiry || '—'}</Text><Text style={s.meta}>Insurance: {app.verification.insurance_provider || '—'} · Expiry {app.verification.insurance_expiry || '—'}</Text><Text style={s.meta}>Verification method: {app.verification.verification_method}</Text><TextInput value={credentialChecks[app.id]?.licenceExpiry??''} onChangeText={value=>setCredentialChecks(current=>({...current,[app.id]:{...(current[app.id]??{licenceExpiry:'',insuranceProvider:'',insurancePolicyReference:'',insuranceExpiry:''}),licenceExpiry:value}}))} placeholder="Official licence expiry YYYY-MM-DD" placeholderTextColor="#aaa69f" style={s.reason}/><Pressable disabled={busy===app.id} onPress={()=>void credentialAction(app,'LICENCE')} style={s.outline}><Text style={s.outlineText}>SAVE OFFICIAL LICENCE CHECK</Text></Pressable><TextInput value={credentialChecks[app.id]?.insuranceProvider??''} onChangeText={value=>setCredentialChecks(current=>({...current,[app.id]:{...(current[app.id]??{licenceExpiry:'',insuranceProvider:'',insurancePolicyReference:'',insuranceExpiry:''}),insuranceProvider:value}}))} placeholder="Insurance provider" placeholderTextColor="#aaa69f" style={s.reason}/><TextInput value={credentialChecks[app.id]?.insurancePolicyReference??''} onChangeText={value=>setCredentialChecks(current=>({...current,[app.id]:{...(current[app.id]??{licenceExpiry:'',insuranceProvider:'',insurancePolicyReference:'',insuranceExpiry:''}),insurancePolicyReference:value}}))} placeholder="Insurance policy reference" placeholderTextColor="#aaa69f" style={s.reason}/><TextInput value={credentialChecks[app.id]?.insuranceExpiry??''} onChangeText={value=>setCredentialChecks(current=>({...current,[app.id]:{...(current[app.id]??{licenceExpiry:'',insuranceProvider:'',insurancePolicyReference:'',insuranceExpiry:''}),insuranceExpiry:value}}))} placeholder="Official insurance expiry YYYY-MM-DD" placeholderTextColor="#aaa69f" style={s.reason}/><Pressable disabled={busy===app.id} onPress={()=>void credentialAction(app,'INSURANCE')} style={s.outline}><Text style={s.outlineText}>SAVE OFFICIAL INSURANCE CHECK</Text></Pressable></View>}
   {app.vehicle&&<View style={s.detailBox}><Text style={s.section}>Vehicle</Text><Text style={s.meta}>{app.vehicle.year || '—'} {app.vehicle.make} {app.vehicle.model} · {app.vehicle.registration_plate}</Text><Text style={s.meta}>{app.vehicle.registration_state} · Current applicant data: {app.vehicle.registration_status} · Expiry {app.vehicle.registration_expiry || '—'}</Text><Text style={s.meta}>CTP: {app.vehicle.ctp_provider || '—'} · Expiry {app.vehicle.ctp_expiry || '—'}</Text><Text style={s.meta}>Use: {app.vehicle.ownership_status.replaceAll('_',' ')}</Text><TextInput value={vehicleChecks[app.id]?.registrationExpiry??''} onChangeText={value=>setVehicleChecks(current=>({...current,[app.id]:{...(current[app.id]??{registrationExpiry:'',ctpProvider:'',ctpExpiry:''}),registrationExpiry:value}}))} placeholder="Official registration expiry YYYY-MM-DD" placeholderTextColor="#aaa69f" style={s.reason}/><TextInput value={vehicleChecks[app.id]?.ctpProvider??''} onChangeText={value=>setVehicleChecks(current=>({...current,[app.id]:{...(current[app.id]??{registrationExpiry:'',ctpProvider:'',ctpExpiry:''}),ctpProvider:value}}))} placeholder="Official CTP provider" placeholderTextColor="#aaa69f" style={s.reason}/><TextInput value={vehicleChecks[app.id]?.ctpExpiry??''} onChangeText={value=>setVehicleChecks(current=>({...current,[app.id]:{...(current[app.id]??{registrationExpiry:'',ctpProvider:'',ctpExpiry:''}),ctpExpiry:value}}))} placeholder="Official CTP expiry YYYY-MM-DD" placeholderTextColor="#aaa69f" style={s.reason}/><Pressable disabled={busy===app.id} onPress={()=>void vehicleAction(app)} style={s.outline}><Text style={s.outlineText}>SAVE OFFICIAL REGO / CTP CHECK</Text></Pressable></View>}
   <Text style={s.section}>Documents</Text>
   {app.documents.map(doc=><View style={s.docRow} key={doc.id}><View style={s.docMain}><Text style={s.docName}>{doc.document_type.replaceAll('_',' ')}</Text><Text style={s.meta}>{doc.status.replaceAll('_',' ')}{doc.expires_at?' · Expires '+doc.expires_at:''}</Text></View><Pressable disabled={busy===doc.id} onPress={()=>void openDocument(doc)} style={s.linkButton}><Text style={s.linkText}>OPEN</Text></Pressable><Pressable disabled={busy===doc.id} onPress={()=>void docAction(doc,'VERIFIED')} style={s.linkButton}><Text style={s.linkText}>VERIFY</Text></Pressable></View>)}
   <TextInput value={reasons[app.id]??''} onChangeText={value=>setReasons(current=>({...current,[app.id]:value}))} placeholder="Reason for more information / rejection / suspension" placeholderTextColor="#aaa69f" style={s.reason}/>
   <View style={s.actions}><Pressable disabled={busy===app.id} onPress={()=>void action(app,'UNDER_REVIEW')} style={s.outline}><Text style={s.outlineText}>UNDER REVIEW</Text></Pressable><Pressable disabled={busy===app.id} onPress={()=>void action(app,'MORE_INFORMATION_REQUIRED')} style={s.outline}><Text style={s.outlineText}>MORE INFO</Text></Pressable><Pressable disabled={busy===app.id} onPress={()=>void action(app,'APPROVED')} style={s.primary}><Text style={s.primaryText}>APPROVE</Text></Pressable></View>
   <View style={s.actions}><Pressable disabled={busy===app.id} onPress={()=>void action(app,'REJECTED')} style={s.outline}><Text style={s.outlineText}>REJECT</Text></Pressable><Pressable disabled={busy===app.id} onPress={()=>void action(app,'SUSPENDED')} style={s.outline}><Text style={s.outlineText}>SUSPEND</Text></Pressable></View>
   <Text style={s.section}>Verification actions</Text>
   <View style={s.actions}><Pressable disabled={busy===app.id} onPress={()=>void adminSetDriverDocumentStatus(e=>setError(e instanceof Error?e.message:'Verification failed'))} style={s.outline}><Text style={s.outlineText}>VERIFY IDENTITY</Text></Pressable><Pressable disabled={busy===app.id} onPress={()=>void adminSetDriverVerification(app.id,{licenceStatus:'VERIFIED'}).then(load).catch(e=>setError(e instanceof Error?e.message:'Verification failed'))} style={s.outline}><Text style={s.outlineText}>VERIFY LICENCE</Text></Pressable><Pressable disabled={busy===app.id} onPress={()=>void adminSetDriverVerification(app.id,{registrationStatus:'VERIFIED'}).then(load).catch(e=>setError(e instanceof Error?e.message:'Verification failed'))} style={s.outline}><Text style={s.outlineText}>VERIFY REGO</Text></Pressable></View>
   <View style={s.actions}><Pressable disabled={busy===app.id} onPress={()=>void adminSetDriverVerification(app.id,{insuranceStatus:'VERIFIED'}).then(load).catch(e=>setError(e instanceof Error?e.message:'Verification failed'))} style={s.outline}><Text style={s.outlineText}>VERIFY INSURANCE</Text></Pressable></View>
  </View>)}
 </ScrollView></SafeAreaView>;
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:60,maxWidth:820,width:'100%',alignSelf:'center'},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:24},back:{fontSize:34,fontWeight:'300'},topTitle:{fontSize:16,fontWeight:'800'},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:2,color:'#777'},title:{fontSize:31,fontWeight:'900',marginTop:7},copy:{fontSize:12,lineHeight:19,color:'#777',marginTop:8,marginBottom:16},card:{backgroundColor:'#fff',borderRadius:20,borderWidth:1,borderColor:'#e5e2dc',padding:18,marginTop:12},cardHeader:{flexDirection:'row',justifyContent:'space-between',gap:10},name:{fontSize:18,fontWeight:'900'},meta:{fontSize:10,lineHeight:16,color:'#777',marginTop:4},pill:{alignSelf:'flex-start',borderRadius:12,paddingHorizontal:9,paddingVertical:6,backgroundColor:'#f3eee4'},pillGood:{backgroundColor:'#e8f3ec'},pillText:{fontSize:7,fontWeight:'900',letterSpacing:.7,color:'#7c632c'},pillGoodText:{color:'#2c6842'},identity:{backgroundColor:'#f8f7f4',borderRadius:13,padding:12,marginTop:14},section:{fontSize:11,fontWeight:'900',marginTop:15,marginBottom:6},reviewRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:7,borderBottomWidth:1,borderBottomColor:'#efede8'},reviewLabel:{fontSize:11,fontWeight:'700'},detailBox:{backgroundColor:'#f8f7f4',borderRadius:13,padding:12,marginTop:10},docRow:{flexDirection:'row',alignItems:'center',gap:6,borderBottomWidth:1,borderBottomColor:'#efede8',paddingVertical:9},docMain:{flex:1},docName:{fontSize:10,fontWeight:'800'},linkButton:{minHeight:34,borderRadius:9,borderWidth:1,borderColor:'#ddd8cf',paddingHorizontal:8,alignItems:'center',justifyContent:'center'},linkText:{fontSize:7,fontWeight:'900'},reason:{minHeight:50,borderRadius:12,borderWidth:1,borderColor:'#ddd8cf',backgroundColor:'#faf9f6',padding:12,fontSize:11,marginTop:14},actions:{flexDirection:'row',gap:7,marginTop:8,flexWrap:'wrap'},primary:{height:42,borderRadius:11,backgroundColor:'#111',paddingHorizontal:13,alignItems:'center',justifyContent:'center'},primaryText:{fontSize:8,fontWeight:'900',color:'#fff'},outline:{height:42,borderRadius:11,borderWidth:1,borderColor:'#d8d3ca',paddingHorizontal:12,alignItems:'center',justifyContent:'center'},outlineText:{fontSize:8,fontWeight:'900'},error:{fontSize:12,color:'#a12820',marginTop:12},empty:{backgroundColor:'#fff',borderRadius:18,padding:28,marginTop:12},emptyTitle:{fontSize:16,fontWeight:'900'}});