import { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { supabase } from '@/lib/supabase';
import { type ThemeColors, useAppTheme } from '@/lib/theme';

type Enquiry = { id:string;status:string;request_id:string;created_at:string;service_requests:{description:string}|{description:string}[]|null;external_quote_responses:{amount:number;message:string;availability:string|null;valid_until:string|null}|{amount:number;message:string;availability:string|null;valid_until:string|null}[]|null };

export default function ExternalQuotes(){
 const {colors}=useAppTheme();const styles=useMemo(()=>createStyles(colors),[colors]);
 const [items,setItems]=useState<Enquiry[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [warning,setWarning]=useState('');const [error,setError]=useState('');const [revokingId,setRevokingId]=useState<string|null>(null);
 const busyRef=useRef(false);const itemsRef=useRef<Enquiry[]>([]);
 function commitItems(next:Enquiry[]){itemsRef.current=next;setItems(next)}
 async function load(refresh=false){if(busyRef.current)return;busyRef.current=true;if(refresh)setRefreshing(true);else if(!itemsRef.current.length)setLoading(true);setError('');setWarning('');
  try{const {data:{user}}=await supabase.auth.getUser();if(!user){if(itemsRef.current.length)setWarning('Sign in again to refresh these enquiries.');else setError('Sign in to view your external enquiries.');return;}
   const {data,error:failure}=await supabase.from('external_enquiries').select('id,status,request_id,created_at,service_requests(description),external_quote_responses(amount,message,availability,valid_until)').eq('customer_id',user.id).order('created_at',{ascending:false}).limit(30);
   if(failure){if(itemsRef.current.length)setWarning('We could not refresh your external enquiries. Showing the last loaded information.');else setError('Unable to load external enquiries right now. Please try again.');return;}commitItems((data??[]) as Enquiry[]);
  }catch{if(itemsRef.current.length)setWarning('We could not refresh your external enquiries. Showing the last loaded information.');else setError('Unable to load external enquiries right now. Please try again.');}finally{setLoading(false);setRefreshing(false);busyRef.current=false;}
 }
 useEffect(()=>{void load()},[]);
 async function revoke(id:string){if(busyRef.current||revokingId)return;busyRef.current=true;setRevokingId(id);setError('');setWarning('');try{const {data,error:failure}=await supabase.rpc('revoke_external_enquiry',{p_enquiry_id:id});if(failure||!data){setWarning('This enquiry could not be revoked. Please try again.');return;}commitItems(itemsRef.current.map(item=>item.id===id?{...item,status:'REVOKED'}:item));}catch{setWarning('This enquiry could not be revoked. Please try again.');}finally{setRevokingId(null);busyRef.current=false;}}
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={colors.brand} progressBackgroundColor={colors.surface}/>}><Text style={styles.title}>External enquiries</Text><Text style={styles.note}>These businesses are not yet on Everest. External quotes are separate from verified Everest quotes, bookings and payments.</Text>
  {loading?<ActivityIndicator style={styles.loader} color={colors.brand}/>:<>{!!error&&<View style={styles.notice}><Text style={styles.noticeTitle}>External enquiries unavailable</Text><Text style={styles.note}>{error}</Text><Pressable accessibilityRole="button" disabled={refreshing||!!revokingId} onPress={()=>void load()}><Text style={styles.link}>Retry</Text></Pressable></View>}{!!warning&&<View style={styles.notice}><Text style={styles.noticeTitle}>Update needed</Text><Text style={styles.note}>{warning}</Text><Pressable accessibilityRole="button" disabled={refreshing||!!revokingId} onPress={()=>void load(true)}><Text style={styles.link}>{refreshing?'Refreshing…':'Retry refresh'}</Text></Pressable></View>}{items.map(item=>{const request=Array.isArray(item.service_requests)?item.service_requests[0]:item.service_requests;const quote=Array.isArray(item.external_quote_responses)?item.external_quote_responses[0]:item.external_quote_responses;const canRevoke=['AUTHORISED','READY','SENT','DELIVERED','OPENED'].includes(item.status);return <View key={item.id} style={styles.card}><Text style={styles.label}>EXTERNAL BUSINESS · NOT YET ON EVEREST</Text><Text style={styles.heading}>{request?.description??'Service request'}</Text><Text style={styles.note}>Enquiry: {item.status.replaceAll('_',' ')}</Text>{quote&&<><Text style={styles.heading}>${Number(quote.amount).toFixed(2)} AUD</Text><Text style={styles.note}>{quote.message}</Text>{!!quote.availability&&<Text style={styles.note}>Availability: {quote.availability}</Text>}{!!quote.valid_until&&<Text style={styles.note}>Valid until: {new Date(quote.valid_until).toLocaleDateString()}</Text>}</>}{canRevoke&&<Pressable accessibilityRole="button" accessibilityLabel="Revoke external enquiry" disabled={!!revokingId||refreshing} onPress={()=>void revoke(item.id)}><Text style={styles.link}>{revokingId===item.id?'Revoking…':'Revoke enquiry'}</Text></Pressable>}</View>})}{!items.length&&!error&&<View style={styles.empty}><Text style={styles.noticeTitle}>No external enquiries yet</Text><Text style={styles.note}>External enquiries you explicitly authorise will appear here.</Text></View>}</>}
 </ScrollView></SafeAreaView>;
}
const createStyles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:50,maxWidth:760,width:'100%',alignSelf:'center'},title:{fontSize:27,fontWeight:'900',color:c.text,marginBottom:10},loader:{marginTop:28},card:{backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:16,padding:18,marginTop:14},notice:{backgroundColor:c.elevated,borderWidth:1,borderColor:c.border,borderRadius:16,padding:16,marginTop:14},empty:{backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:16,padding:22,marginTop:18,alignItems:'center'},noticeTitle:{fontSize:14,fontWeight:'900',color:c.text},label:{fontSize:10,fontWeight:'900',color:c.muted},heading:{fontSize:16,fontWeight:'800',color:c.text,marginTop:10},note:{fontSize:13,lineHeight:20,color:c.textSecondary,marginTop:8},link:{fontSize:13,fontWeight:'800',color:c.brand,marginTop:16}});
