import {useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,Text,TextInput,View} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {router,useLocalSearchParams} from 'expo-router';
import {SafeAreaView} from 'react-native-safe-area-context';
import {supabase} from '@/lib/supabase';
import {useAppTheme} from '@/lib/theme';
type Result={source:'google_places';externalId:string;referenceId:string;name:string;address:string};
export default function ExternalBusinesses(){const {colors:c}=useAppTheme();const params=useLocalSearchParams<{q?:string}>();const [q,setQ]=useState(typeof params.q==='string'?params.q:'');const [items,setItems]=useState<Result[]>([]);const [loading,setLoading]=useState(false);const [enabled,setEnabled]=useState<boolean|null>(null);const [error,setError]=useState('');
 async function search(){const text=q.trim();if(text.length<3)return;setLoading(true);setError('');try{const {data,error:e}=await supabase.functions.invoke('external-discovery',{body:{query:text}});if(e)throw e;setEnabled(data?.enabled===true);setItems(Array.isArray(data?.businesses)?data.businesses:[])}catch(e){setError(e instanceof Error?e.message:'External business search is unavailable.')}finally{setLoading(false)}}
 return <SafeAreaView style={{flex:1,backgroundColor:c.canvas}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:20,paddingBottom:60,maxWidth:760,width:'100%',alignSelf:'center'}}><View style={{flexDirection:'row',alignItems:'center',gap:14}}><Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={23} color={c.text}/></Pressable><Text style={{fontSize:24,fontWeight:'900',color:c.text}}>External businesses</Text></View><Text style={{fontSize:12,lineHeight:18,color:c.muted,marginTop:8}}>Search businesses outside Everest. Results are clearly separated and searching never contacts a business.</Text><View style={{flexDirection:'row',gap:8,marginTop:18}}><TextInput value={q} onChangeText={setQ} onSubmitEditing={()=>void search()} placeholder="Business or service" placeholderTextColor={c.muted} style={{flex:1,minHeight:48,borderRadius:14,borderWidth:1,borderColor:c.border,backgroundColor:c.input,color:c.text,paddingHorizontal:14,fontSize:16}}/><Pressable onPress={()=>void search()} style={{minWidth:48,borderRadius:14,backgroundColor:c.brand,alignItems:'center',justifyContent:'center'}}><Ionicons name="search" size={20} color={c.onBrand}/></Pressable></View>{loading?<ActivityIndicator style={{marginTop:35}} color={c.text}/>:enabled===false?<Text style={{fontSize:12,color:c.muted,marginTop:24}}>External discovery is currently disabled by its production feature gate.</Text>:items.map(x=><View key={x.referenceId} style={{marginTop:10,padding:14,borderRadius:16,borderWidth:1,borderColor:c.border,backgroundColor:c.surface}}><Text style={{fontSize:14,fontWeight:'900',color:c.text}}>{x.name}</Text><Text style={{fontSize:11,lineHeight:17,color:c.muted,marginTop:4}}>{x.address}</Text><Text style={{fontSize:9,fontWeight:'900',color:c.brand,marginTop:8}}>NOT YET ON EVEREST</Text></View>)}{error?<Text style={{fontSize:12,color:c.danger,marginTop:14}}>{error}</Text>:null}</ScrollView></SafeAreaView>}
