import {useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {router} from 'expo-router';
import {createHighlight,deleteHighlight,listHighlights,listMyStoryArchive,type Story,type StoryHighlight} from '@/lib/social-expansion';
import {getWorkspaceContext,type BusinessWorkspace} from '@/lib/workspace';
import {type ThemeColors,useAppTheme} from '@/lib/theme';
import {haptic} from '@/lib/haptics';

type Identity={kind:'PERSONAL';id:string;name:string}|{kind:'BUSINESS';id:string;name:string;business:BusinessWorkspace};
export default function Highlights(){
 const {colors}=useAppTheme();const s=useMemo(()=>styles(colors),[colors]);
 const [identities,setIdentities]=useState<Identity[]>([]);const [identity,setIdentity]=useState<Identity|null>(null);const [items,setItems]=useState<StoryHighlight[]>([]);const [stories,setStories]=useState<Story[]>([]);
 const [title,setTitle]=useState('');const [selected,setSelected]=useState<string[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function load(){setError('');try{const ctx=await getWorkspaceContext();const personalId=(await import('@/lib/supabase')).supabase.auth.getUser().then(r=>r.data.user?.id??'');const uid=await personalId;if(!uid)throw new Error('Sign in to manage Highlights.');const list:Identity[]=[{kind:'PERSONAL',id:uid,name:'My profile'},...ctx.businesses.map(b=>({kind:'BUSINESS' as const,id:b.id,name:b.name,business:b}))];const selectedIdentity=identity??(ctx.mode==='BUSINESS'&&ctx.active_business_id?list.find(x=>x.kind==='BUSINESS'&&x.id===ctx.active_business_id)??list[0]:list[0]);setIdentities(list);setIdentity(selectedIdentity);const [high,archive]=await Promise.all([listHighlights({}),listMyStoryArchive(120)]);setItems(high.filter(h=>selectedIdentity.kind==='BUSINESS'?h.business_id===selectedIdentity.id:h.business_id===null));setStories(archive.filter(st=>selectedIdentity.kind==='BUSINESS'?st.business_id===selectedIdentity.id:st.business_id===null));}catch(e){setError(e instanceof Error?e.message:'Highlights could not be loaded.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function switchIdentity(next:Identity){setIdentity(next);setSelected([]);setLoading(true);try{const [high,archive]=await Promise.all([listHighlights({}),listMyStoryArchive(120)]);setItems(high.filter(h=>next.kind==='BUSINESS'?h.business_id===next.id:h.business_id===null));setStories(archive.filter(st=>next.kind==='BUSINESS'?st.business_id===next.id:st.business_id===null));}finally{setLoading(false)}}
 async function create(){if(!identity||busy)return;if(!title.trim()){setError('Name your Highlight first.');return}if(!selected.length){setError('Choose at least one archived Story.');return}setBusy(true);setError('');try{await createHighlight({title,businessId:identity.kind==='BUSINESS'?identity.id:undefined,storyIds:selected});setTitle('');setSelected([]);void haptic.success();await switchIdentity(identity)}catch(e){setError(e instanceof Error?e.message:'Highlight could not be created.')}finally{setBusy(false)}}
 function remove(item:StoryHighlight){Alert.alert('Delete Highlight?','Stories remain safely in your archive.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{setBusy(true);try{await deleteHighlight(item.id);setItems(v=>v.filter(x=>x.id!==item.id))}finally{setBusy(false)}}}])}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled">
  <View style={s.header}><Pressable onPress={()=>router.back()} style={s.round}><Ionicons name="arrow-back" size={21} color={colors.text}/></Pressable><View style={{flex:1}}><Text style={s.kicker}>PROFILE CURATION</Text><Text style={s.title}>Highlights</Text></View><Pressable onPress={()=>router.push('/archive')}><Ionicons name="archive-outline" size={22} color={colors.text}/></Pressable></View>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.rail}>{identities.map(x=>{const active=x.id===identity?.id&&x.kind===identity?.kind;return <Pressable key={x.kind+x.id} onPress={()=>void switchIdentity(x)} style={[s.identity,active&&s.identityActive]}><Ionicons name={x.kind==='BUSINESS'?'business-outline':'person-outline'} size={15} color={active?colors.onBrand:colors.text}/><Text style={[s.identityText,active&&{color:colors.onBrand}]}>{x.name}</Text></Pressable>})}</ScrollView>
  {loading?<ActivityIndicator color={colors.brand} style={{marginTop:60}}/>:<>
   {items.length?<View style={s.current}>{items.map(item=><View key={item.id} style={s.highlightCard}><View style={s.cover}>{item.coverUrl?null:<Ionicons name="ellipse-outline" size={22} color={colors.brand}/>}</View><View style={{flex:1}}><Text style={s.highlightTitle}>{item.title}</Text><Text style={s.meta}>Visible on profile</Text></View><Pressable onPress={()=>remove(item)} style={s.delete}><Ionicons name="trash-outline" size={17} color={colors.danger}/></Pressable></View>)}</View>:null}
   <View style={s.builder}><Text style={s.builderTitle}>Create Highlight</Text><Text style={s.builderCopy}>Turn expired Stories into a permanent portfolio collection such as Recent Work, Before & After, Offers or Products.</Text><TextInput value={title} onChangeText={setTitle} maxLength={40} placeholder="Highlight name" placeholderTextColor={colors.muted} style={s.input}/>
    <Text style={s.label}>CHOOSE STORIES</Text>{stories.length?<View style={s.storyList}>{stories.map(st=>{const on=selected.includes(st.id);return <Pressable key={st.id} onPress={()=>setSelected(v=>on?v.filter(id=>id!==st.id):[...v,st.id])} style={[s.story,on&&s.storyActive]}><Ionicons name={on?'checkmark-circle':'ellipse-outline'} size={18} color={on?colors.brand:colors.muted}/><View style={{flex:1}}><Text numberOfLines={1} style={s.storyTitle}>{st.caption||'Story'}</Text><Text style={s.meta}>{new Date(st.created_at).toLocaleDateString()}</Text></View></Pressable>})}</View>:<View style={s.empty}><Text style={s.emptyText}>No archived Stories yet. Stories become available here after they expire or are archived.</Text></View>}
    {error?<Text style={s.error}>{error}</Text>:null}<Pressable disabled={busy||!stories.length} onPress={()=>void create()} style={[s.primary,(busy||!stories.length)&&{opacity:.45}]}>{busy?<ActivityIndicator color={colors.onBrand}/>:<Text style={s.primaryText}>CREATE HIGHLIGHT</Text>}</Pressable>
   </View>
  </>}
 </ScrollView></SafeAreaView>;
}
const styles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:18,paddingBottom:60,maxWidth:720,width:'100%',alignSelf:'center'},header:{minHeight:64,flexDirection:'row',alignItems:'center',gap:12},round:{width:42,height:42,borderRadius:21,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,alignItems:'center',justifyContent:'center'},kicker:{fontSize:12,fontWeight:'900',letterSpacing:1.5,color:c.accent},title:{fontSize:25,fontWeight:'900',color:c.text},rail:{gap:8,paddingVertical:14,paddingRight:12},identity:{height:38,borderRadius:19,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,paddingHorizontal:11,flexDirection:'row',alignItems:'center',gap:6},identityActive:{backgroundColor:c.brand,borderColor:c.brand},identityText:{fontSize:12,fontWeight:'900',color:c.text},current:{gap:9,marginBottom:14},highlightCard:{minHeight:68,borderRadius:18,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,padding:10,flexDirection:'row',alignItems:'center',gap:10},cover:{width:46,height:46,borderRadius:23,backgroundColor:c.soft,alignItems:'center',justifyContent:'center'},highlightTitle:{fontSize:13,fontWeight:'900',color:c.text},meta:{fontSize:12,color:c.muted,marginTop:3},delete:{width:38,height:38,borderRadius:19,alignItems:'center',justifyContent:'center'},builder:{borderRadius:23,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,padding:17},builderTitle:{fontSize:18,fontWeight:'900',color:c.text},builderCopy:{fontSize:14,lineHeight:20,color:c.muted,marginTop:5},input:{height:50,borderRadius:15,borderWidth:1,borderColor:c.border,backgroundColor:c.input,color:c.text,paddingHorizontal:13,marginTop:15},label:{fontSize:14,fontWeight:'900',letterSpacing:1.3,color:c.muted,marginTop:17,marginBottom:7},storyList:{gap:7},story:{minHeight:54,borderRadius:15,borderWidth:1,borderColor:c.border,backgroundColor:c.input,paddingHorizontal:11,flexDirection:'row',alignItems:'center',gap:9},storyActive:{borderColor:c.brand,backgroundColor:c.soft},storyTitle:{fontSize:12,fontWeight:'800',color:c.text},empty:{padding:18,borderRadius:15,backgroundColor:c.soft},emptyText:{fontSize:14,lineHeight:20,color:c.muted,textAlign:'center'},error:{fontSize:14,color:c.danger,marginTop:10},primary:{height:50,borderRadius:16,backgroundColor:c.brand,alignItems:'center',justifyContent:'center',marginTop:15},primaryText:{fontSize:14,fontWeight:'900',letterSpacing:.6,color:c.onBrand}});
