import {useCallback,useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {router,useLocalSearchParams} from 'expo-router';
import {resolveCustomerLocality} from '@/lib/customer-location';
import {getInstantSlots,instantBook,type InstantSlot} from '@/lib/retention';
import {useAppTheme,type ThemeColors} from '@/lib/theme';

export default function InstantBook(){
 const {colors}=useAppTheme();const s=useMemo(()=>styles(colors),[colors]);const {serviceId,name}=useLocalSearchParams<{serviceId?:string;name?:string}>();const [slots,setSlots]=useState<InstantSlot[]>([]);const [selected,setSelected]=useState<string>('');const [suburb,setSuburb]=useState('');const [city,setCity]=useState('');const [state,setState]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const load=useCallback(async()=>{if(!serviceId){setError('Service not found.');setLoading(false);return;}setError('');try{const [next,locality]=await Promise.all([getInstantSlots(serviceId),resolveCustomerLocality({requestIfUndetermined:false})]);setSlots(next);setSuburb(locality?.suburb??'');setCity(locality?.city??'');setState(locality?.state??'');}catch(e){setError(e instanceof Error?e.message:'Available slots could not be loaded.');}finally{setLoading(false);}},[serviceId]);useEffect(()=>{void load();},[load]);
 async function confirm(){if(!serviceId||!selected||busy)return;setBusy(true);setError('');try{const bookingId=await instantBook({serviceId,startsAt:selected,suburb,city,state});router.replace('/booking?id='+bookingId);}catch(e){setError(e instanceof Error?e.message:'This slot could not be booked. Please choose another.');await load();}finally{setBusy(false);}}
 const groups=slots.reduce<Record<string,InstantSlot[]>>((all,slot)=>{const key=new Date(slot.starts_at).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});(all[key]??=[]).push(slot);return all;},{});
 return <SafeAreaView style={s.safe} edges={['top']}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}><View style={s.top}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="chevron-back" size={20} color={colors.text}/></Pressable><View><Text style={s.eyebrow}>INSTANT BOOK</Text><Text style={s.title}>{name||'Choose a time'}</Text></View></View><Text style={s.copy}>These slots are checked again at confirmation against business capacity and connected calendar busy time.</Text>{loading?<ActivityIndicator color={colors.brand} style={{marginTop:50}}/>:Object.keys(groups).length?Object.entries(groups).map(([date,daySlots])=><View key={date} style={s.day}><Text style={s.dayTitle}>{date}</Text><View style={s.slotGrid}>{daySlots.map(slot=>{const on=selected===slot.starts_at;return <Pressable key={slot.starts_at} onPress={()=>setSelected(slot.starts_at)} style={[s.slot,on&&s.slotOn]}><Text style={[s.slotText,on&&s.slotTextOn]}>{new Date(slot.starts_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</Text></Pressable>})}</View></View>):<View style={s.empty}><Text style={s.emptyTitle}>No instant slots right now</Text><Text style={s.copy}>You can still request a quote from this business.</Text></View>}<View style={s.location}><Text style={s.dayTitle}>Service location</Text><Text style={s.copy}>We use this only to check the business’s service area.</Text><TextInput value={suburb} onChangeText={setSuburb} placeholder="Suburb" placeholderTextColor={colors.muted} style={s.input}/><TextInput value={city} onChangeText={setCity} placeholder="City" placeholderTextColor={colors.muted} style={s.input}/><TextInput value={state} onChangeText={setState} placeholder="State" placeholderTextColor={colors.muted} style={s.input}/></View><Pressable disabled={!selected||busy} onPress={()=>void confirm()} style={[s.primary,(!selected||busy)&&{opacity:.45}]}><Text style={s.primaryText}>{busy?'RECHECKING…':'CONFIRM INSTANT BOOKING'}</Text></Pressable>{error?<Text style={s.error}>{error}</Text>:null}</ScrollView></SafeAreaView>;
}
const styles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:50,maxWidth:760,width:'100%',alignSelf:'center'},top:{flexDirection:'row',alignItems:'center',gap:12},back:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.4,color:c.brand},title:{fontSize:26,fontWeight:'900',color:c.text,marginTop:2},copy:{fontSize:12,lineHeight:18,color:c.muted,marginTop:12},day:{marginTop:20},dayTitle:{fontSize:13,fontWeight:'900',color:c.text},slotGrid:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:10},slot:{minWidth:86,height:43,paddingHorizontal:10,borderRadius:13,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center'},slotOn:{backgroundColor:c.brand,borderColor:c.brand},slotText:{fontSize:11,fontWeight:'900',color:c.text},slotTextOn:{color:c.onBrand},location:{marginTop:25,padding:15,borderRadius:18,borderWidth:1,borderColor:c.border,backgroundColor:c.surface},input:{height:46,borderRadius:13,borderWidth:1,borderColor:c.border,backgroundColor:c.input,color:c.text,paddingHorizontal:12,marginTop:9},primary:{height:50,borderRadius:15,backgroundColor:c.brand,alignItems:'center',justifyContent:'center',marginTop:18},primaryText:{fontSize:10,fontWeight:'900',color:c.onBrand},empty:{padding:20,marginTop:20,borderWidth:1,borderColor:c.border,borderRadius:18,backgroundColor:c.surface},emptyTitle:{fontSize:16,fontWeight:'900',color:c.text},error:{fontSize:11,color:c.danger,marginTop:14}});
