import {useEffect,useState} from 'react';
import {ActivityIndicator,Image,Pressable,ScrollView,Text,TextInput,View} from 'react-native';
import {router,useLocalSearchParams} from 'expo-router';
import {SafeAreaView} from 'react-native-safe-area-context';
import {conversations,messages,sendMessage} from '@/lib/messaging';
import {currentUser} from '@/lib/marketplace';
import {listPersonalConversations,personalMessages,respondMessageRequest,sendPersonalMessage,type PersonalConversation,type PersonalMessage} from '@/lib/connections';
import {supabase} from '@/lib/supabase';
import {useAppTheme} from '@/lib/theme';

type MarketConversation={id:string;customer_id:string;business_id:string;created_at:string;counterpart_name?:string};
type MarketMessage={id:string;sender_id:string;body:string;created_at:string};

export default function Messages(){
 const {colors:c}=useAppTheme();const params=useLocalSearchParams<{personalId?:string}>();const [tab,setTab]=useState<'CHATS'|'REQUESTS'|'MARKETPLACE'>('CHATS');const [personal,setPersonal]=useState<PersonalConversation[]>([]);const [requests,setRequests]=useState<PersonalConversation[]>([]);const [market,setMarket]=useState<MarketConversation[]>([]);const [selectedPersonal,setSelectedPersonal]=useState<PersonalConversation|null>(null);const [selectedMarket,setSelectedMarket]=useState<MarketConversation|null>(null);const [personalThread,setPersonalThread]=useState<PersonalMessage[]>([]);const [marketThread,setMarketThread]=useState<MarketMessage[]>([]);const [draft,setDraft]=useState('');const [userId,setUserId]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const user=await currentUser();setUserId(user?.id??'');const [p,r,m]=await Promise.all([listPersonalConversations(false),listPersonalConversations(true),conversations()]);setPersonal(p);setRequests(r);const rows=m as MarketConversation[];const ids=[...new Set(rows.map(x=>x.business_id))];const {data}=ids.length?await supabase.from('businesses').select('id,name').in('id',ids):{data:[] as any[]};const names=Object.fromEntries((data??[]).map(x=>[x.id,x.name]));setMarket(rows.map(x=>({...x,counterpart_name:names[x.business_id]??'Marketplace conversation'})));const requested=typeof params.personalId==='string'?params.personalId:'';if(requested){const found=[...p,...r].find(x=>x.id===requested);if(found){setSelectedPersonal(found);setTab(found.status==='REQUEST'&&found.initiated_by!==user?.id?'REQUESTS':'CHATS')}}}catch(e){setError(e instanceof Error?e.message:'Messages could not be loaded.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(selectedPersonal)void personalMessages(selectedPersonal.id).then(setPersonalThread).catch(e=>setError(e instanceof Error?e.message:'Conversation could not be loaded.'))},[selectedPersonal?.id]);
 useEffect(()=>{if(selectedMarket)void messages(selectedMarket.id).then(x=>setMarketThread(x as MarketMessage[])).catch(e=>setError(e instanceof Error?e.message:'Conversation could not be loaded.'))},[selectedMarket?.id]);
 async function submitPersonal(){if(!selectedPersonal||!draft.trim())return;setBusy(true);try{await sendPersonalMessage(selectedPersonal.other_user_id,draft);setDraft('');setPersonalThread(await personalMessages(selectedPersonal.id));await load()}catch(e){setError(e instanceof Error?e.message:'Message could not be sent.')}finally{setBusy(false)}}
 async function submitMarket(){if(!selectedMarket||!draft.trim())return;setBusy(true);try{await sendMessage(selectedMarket.id,draft);setDraft('');setMarketThread(await messages(selectedMarket.id) as MarketMessage[])}catch(e){setError(e instanceof Error?e.message:'Message could not be sent.')}finally{setBusy(false)}}
 if(selectedPersonal)return <SafeAreaView style={{flex:1,backgroundColor:c.canvas}}><View style={{padding:18,borderBottomWidth:1,borderBottomColor:c.border}}><Pressable onPress={()=>{setSelectedPersonal(null);setPersonalThread([])}}><Text style={{fontSize:13,fontWeight:'900',color:c.text}}>‹ Messages</Text></Pressable><Text style={{fontSize:20,fontWeight:'900',color:c.text,marginTop:8}}>{selectedPersonal.display_name??'Everest member'}</Text></View>{selectedPersonal.status==='REQUEST'&&selectedPersonal.initiated_by!==userId?<View style={{padding:14,flexDirection:'row',gap:8}}><Pressable onPress={async()=>{setBusy(true);try{await respondMessageRequest(selectedPersonal.id,true);setSelectedPersonal({...selectedPersonal,status:'ACTIVE'});await load()}finally{setBusy(false)}} style={{paddingHorizontal:16,paddingVertical:10,borderRadius:11,backgroundColor:c.brand}}><Text style={{fontSize:9,fontWeight:'900',color:c.onBrand}}>ACCEPT</Text></Pressable><Pressable onPress={async()=>{setBusy(true);try{await respondMessageRequest(selectedPersonal.id,false);setSelectedPersonal(null);await load()}finally{setBusy(false)}} style={{paddingHorizontal:16,paddingVertical:10,borderRadius:11,borderWidth:1,borderColor:c.border}}><Text style={{fontSize:9,fontWeight:'900',color:c.text}}>DECLINE</Text></Pressable><Pressable onPress={()=>router.push('/public-user?id='+selectedPersonal.other_user_id)} style={{paddingHorizontal:16,paddingVertical:10}}><Text style={{fontSize:9,fontWeight:'900',color:c.muted}}>PROFILE / BLOCK</Text></Pressable></View>:null}<Thread items={personalThread} userId={userId} c={c}/>{selectedPersonal.status==='ACTIVE'?<Composer draft={draft} setDraft={setDraft} busy={busy} submit={()=>void submitPersonal()} c={c}/>:null}</SafeAreaView>;
 if(selectedMarket)return <SafeAreaView style={{flex:1,backgroundColor:c.canvas}}><View style={{padding:18,borderBottomWidth:1,borderBottomColor:c.border}}><Pressable onPress={()=>{setSelectedMarket(null);setMarketThread([])}}><Text style={{fontSize:13,fontWeight:'900',color:c.text}}>‹ Messages</Text></Pressable><Text style={{fontSize:20,fontWeight:'900',color:c.text,marginTop:8}}>{selectedMarket.counterpart_name}</Text><Text style={{fontSize:10,color:c.muted,marginTop:4}}>Marketplace conversation</Text></View><Thread items={marketThread} userId={userId} c={c}/><Composer draft={draft} setDraft={setDraft} busy={busy} submit={()=>void submitMarket()} c={c}/></SafeAreaView>;
 const list=tab==='CHATS'?personal:tab==='REQUESTS'?requests:market;
 return <SafeAreaView style={{flex:1,backgroundColor:c.canvas}}><ScrollView contentContainerStyle={{padding:20,paddingBottom:60,maxWidth:760,width:'100%',alignSelf:'center'}}><Text style={{fontSize:10,fontWeight:'900',letterSpacing:2,color:c.muted}}>EVEREST LOCAL</Text><Text style={{fontSize:30,fontWeight:'900',color:c.text,marginTop:5}}>Messages</Text><View style={{flexDirection:'row',gap:7,marginTop:18,marginBottom:14}}>{(['CHATS','REQUESTS','MARKETPLACE'] as const).map(x=><Pressable key={x} onPress={()=>setTab(x)} style={{paddingHorizontal:13,paddingVertical:9,borderRadius:11,backgroundColor:tab===x?c.brand:c.surface,borderWidth:1,borderColor:tab===x?c.brand:c.border}}><Text style={{fontSize:9,fontWeight:'900',color:tab===x?c.onBrand:c.text}}>{x}{x==='REQUESTS'&&requests.length?' ('+requests.length+')':''}</Text></Pressable>)}</View>{loading?<ActivityIndicator style={{marginTop:40}} color={c.text}/>:list.length?(list as any[]).map(item=>{const personalItem=tab!=='MARKETPLACE';return <Pressable key={item.id} onPress={()=>personalItem?setSelectedPersonal(item as PersonalConversation):setSelectedMarket(item as MarketConversation)} style={{padding:14,borderRadius:16,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,marginBottom:9,flexDirection:'row',alignItems:'center',gap:11}}>{personalItem&&item.avatar_url?<Image source={{uri:item.avatar_url}} style={{width:44,height:44,borderRadius:22}}/>:<View style={{width:44,height:44,borderRadius:22,backgroundColor:c.soft}}/>}<View style={{flex:1}}><Text style={{fontSize:14,fontWeight:'900',color:c.text}}>{personalItem?(item.display_name??'Everest member'):(item.counterpart_name??'Marketplace conversation')}</Text><Text style={{fontSize:10,color:c.muted,marginTop:3}}>{personalItem?(tab==='REQUESTS'?'Message request':'Personal chat'):'Business enquiry / booking chat'}</Text></View></Pressable>}):<View style={{paddingVertical:50,alignItems:'center'}}><Text style={{fontSize:16,fontWeight:'900',color:c.text}}>Nothing here yet</Text><Text style={{fontSize:11,color:c.muted,marginTop:6}}>{tab==='REQUESTS'?'New unsolicited messages will appear here for approval.':'Your conversations will appear here.'}</Text></View>}{error?<Text style={{fontSize:12,color:c.danger,marginTop:12}}>{error}</Text>:null}</ScrollView></SafeAreaView>
}
function Thread({items,userId,c}:{items:Array<{id:string;sender_id:string;body:string;created_at:string}>;userId:string;c:any}){return <ScrollView style={{flex:1}} contentContainerStyle={{padding:18}}>{items.map(m=><View key={m.id} style={{alignSelf:m.sender_id===userId?'flex-end':'flex-start',maxWidth:'84%',backgroundColor:m.sender_id===userId?c.brand:c.surface,borderWidth:m.sender_id===userId?0:1,borderColor:c.border,borderRadius:16,padding:12,marginBottom:8}}><Text style={{fontSize:14,lineHeight:20,color:m.sender_id===userId?c.onBrand:c.text}}>{m.body}</Text><Text style={{fontSize:9,color:c.muted,marginTop:5}}>{new Date(m.created_at).toLocaleString()}</Text></View>)}</ScrollView>}
function Composer({draft,setDraft,busy,submit,c}:{draft:string;setDraft:(v:string)=>void;busy:boolean;submit:()=>void;c:any}){return <View style={{padding:12,borderTopWidth:1,borderTopColor:c.border,backgroundColor:c.surface,flexDirection:'row',gap:8,alignItems:'flex-end'}}><TextInput value={draft} onChangeText={setDraft} placeholder="Write a message…" placeholderTextColor={c.muted} multiline maxLength={5000} style={{flex:1,minHeight:46,maxHeight:120,borderWidth:1,borderColor:c.border,borderRadius:14,paddingHorizontal:14,paddingVertical:10,color:c.text,backgroundColor:c.input}}/><Pressable disabled={busy||!draft.trim()} onPress={submit} style={{height:46,paddingHorizontal:16,borderRadius:13,backgroundColor:c.brand,alignItems:'center',justifyContent:'center',opacity:busy||!draft.trim()?0.5:1}}><Text style={{fontSize:9,fontWeight:'900',color:c.onBrand}}>SEND</Text></Pressable></View>}
