import { useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { supabase } from '@/lib/supabase';

type Notification={id:string;title:string;body:string;read_at:string|null;created_at:string;kind:string;data:Record<string,unknown>|null};
function destination(item:Notification){const data=item.data??{};if(typeof data.route==='string')return data.route;if(item.kind.includes('quote'))return '/quotes';if(item.kind.includes('booking'))return '/bookings';if(item.kind.includes('message'))return '/messages';if(item.kind.includes('order')||item.kind.includes('delivery')||item.kind.includes('payment'))return '/orders';if(item.kind.includes('review'))return '/reviews';if(item.kind.includes('request'))return '/requests';return '/activity';}
export default function Notifications(){
 const [items,setItems]=useState<Notification[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [busyId,setBusyId]=useState<string|null>(null);const [markingAll,setMarkingAll]=useState(false);const [error,setError]=useState('');
 async function load(mode:'initial'|'refresh'='initial'){if(mode==='initial')setLoading(true);else setRefreshing(true);setError('');try{const {data:{user}}=await supabase.auth.getUser();if(!user){setItems([]);return;}const {data,error:e}=await supabase.from('notifications').select('id,title,body,read_at,created_at,kind,data').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100);if(e)throw e;setItems((data??[]) as Notification[])}catch{setError('We could not load notifications right now. Please try again.')}finally{setLoading(false);setRefreshing(false)}}
 useEffect(()=>{void load()},[]);
 async function read(id:string){setBusyId(id);setError('');try{const {error:e}=await supabase.rpc('mark_notification_read',{p_notification_id:id});if(e)throw e;const now=new Date().toISOString();setItems(current=>current.map(item=>item.id===id?{...item,read_at:item.read_at??now}:item));return true;}catch{setError('We could not update that notification. Please try again.');return false;}finally{setBusyId(null)}}
 async function readAll(){const unread=items.filter(item=>!item.read_at);if(!unread.length)return;setMarkingAll(true);setError('');try{const {error:e}=await supabase.rpc('mark_all_notifications_read');if(e)throw e;const now=new Date().toISOString();setItems(current=>current.map(item=>item.read_at?item:{...item,read_at:now}));}catch{setError('We could not mark all notifications as read. Please try again.')}finally{setMarkingAll(false)}}
 async function open(item:Notification){if(busyId||markingAll||refreshing)return;if(!item.read_at){const updated=await read(item.id);if(!updated)return;}router.push(destination(item) as never);}
 const unreadCount=items.filter(item=>!item.read_at).length;const actionsBusy=!!busyId||markingAll||refreshing;
 return <SafeAreaView style={s.safe}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load('refresh')}/>} contentContainerStyle={s.page}><Text style={s.eyebrow}>EVEREST LOCAL</Text><View style={s.header}><View><Text style={s.title}>Notifications</Text>{!loading&&unreadCount>0&&<Text style={s.unreadCount}>{unreadCount} unread</Text>}</View>{!loading&&unreadCount>0&&<Pressable disabled={actionsBusy} onPress={()=>void readAll()} style={s.readAll}><Text style={s.readAllText}>{markingAll?'UPDATING…':'MARK ALL READ'}</Text></Pressable>}</View>{loading?<ActivityIndicator/>:error&&!items.length?<View style={s.empty}><Text style={s.emptyTitle}>We couldn't load notifications.</Text><Text style={s.error}>{error}</Text><Pressable disabled={loading} onPress={()=>void load()} style={s.button}><Text style={s.buttonText}>{loading?'RETRYING…':'RETRY'}</Text></Pressable></View>:items.length?<>{error?<View style={s.warning}><Text style={s.warningText}>We could not refresh notifications. Showing your last loaded updates.</Text><Pressable disabled={refreshing} onPress={()=>void load('refresh')} style={s.warningRetry}><Text style={s.warningRetryText}>RETRY NOTIFICATIONS</Text></Pressable></View>:null}{items.map(n=><Pressable key={n.id} disabled={actionsBusy} onPress={()=>void open(n)} style={[s.card,!n.read_at&&s.unread]}><View style={s.row}><Text style={s.kind}>{n.kind.replaceAll('_',' ')}</Text><Text style={s.time}>{new Date(n.created_at).toLocaleDateString()}</Text></View><Text style={s.cardTitle}>{n.title}</Text><Text style={s.body}>{n.body}</Text><Text style={s.open}>{busyId===n.id?'OPENING…':n.read_at?'OPEN →':'OPEN · NEW →'}</Text></Pressable>)}</>:<View style={s.empty}><Text style={s.emptyTitle}>You’re all caught up.</Text><Text style={s.body}>Marketplace updates will appear here.</Text></View>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:40},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:'#777'},header:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',marginTop:7,marginBottom:22},title:{fontSize:31,fontWeight:'900'},unreadCount:{fontSize:11,color:'#777',marginTop:4},readAll:{height:38,paddingHorizontal:12,borderRadius:11,borderWidth:1,borderColor:'#ddd8cf',alignItems:'center',justifyContent:'center'},readAllText:{fontSize:8,fontWeight:'900'},card:{backgroundColor:'#fff',borderRadius:17,borderWidth:1,borderColor:'#e5e2dc',padding:16,marginBottom:9},unread:{borderColor:'#111'},row:{flexDirection:'row',justifyContent:'space-between'},kind:{fontSize:8,fontWeight:'900',letterSpacing:1},time:{fontSize:10,color:'#777'},cardTitle:{fontSize:14,fontWeight:'800',marginTop:8},body:{fontSize:12,lineHeight:18,color:'#777',marginTop:5},open:{fontSize:9,fontWeight:'900',marginTop:12},empty:{backgroundColor:'#fff',borderRadius:20,padding:28,alignItems:'center',marginTop:20},emptyTitle:{fontSize:16,fontWeight:'800'},button:{height:46,borderRadius:13,backgroundColor:'#111',paddingHorizontal:18,alignItems:'center',justifyContent:'center',marginTop:16},buttonText:{color:'#fff',fontSize:10,fontWeight:'900'},error:{color:'#b42318',fontSize:12,lineHeight:18,marginTop:12},warning:{backgroundColor:'#fff8e8',borderRadius:14,padding:14,marginBottom:12,borderWidth:1,borderColor:'#ead8ae'},warningText:{fontSize:12,lineHeight:18,color:'#6b5424'},warningRetry:{minHeight:38,alignItems:'center',justifyContent:'center',marginTop:8},warningRetryText:{fontSize:10,fontWeight:'900',letterSpacing:.6}});
