import { useEffect,useMemo,useRef,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { supabase } from '@/lib/supabase';
import { type ThemeColors,useAppTheme } from '@/lib/theme';
import { getWorkspaceContext,setWorkspacePreference } from '@/lib/workspace';

type Notification={id:string;title:string;body:string;read_at:string|null;created_at:string;kind:string;data:Record<string,unknown>|null};
type NotificationRoute='/activity'|'/requests'|'/quotes'|'/bookings'|'/messages'|'/orders'|'/reviews';
const allowedRoutes=new Set<NotificationRoute>(['/activity','/requests','/quotes','/bookings','/messages','/orders','/reviews']);
function destination(item:Notification):NotificationRoute{const data=item.data??{};if(typeof data.route==='string'&&allowedRoutes.has(data.route as NotificationRoute))return data.route as NotificationRoute;if(item.kind.includes('quote'))return '/quotes';if(item.kind.includes('booking'))return '/bookings';if(item.kind.includes('message'))return '/messages';if(item.kind.includes('order')||item.kind.includes('delivery')||item.kind.includes('payment'))return '/orders';if(item.kind.includes('review'))return '/reviews';if(item.kind.includes('request'))return '/requests';return '/activity';}
export default function Notifications(){
 const {colors}=useAppTheme();const s=useMemo(()=>createStyles(colors),[colors]);
 const [items,setItems]=useState<Notification[]>([]);const itemsRef=useRef<Notification[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [busyId,setBusyId]=useState<string|null>(null);const [markingAll,setMarkingAll]=useState(false);const [error,setError]=useState('');const loadBusyRef=useRef(false);const actionBusyRef=useRef(false);
 function commitItems(next:Notification[]){itemsRef.current=next;setItems(next)}
 async function load(mode:'initial'|'refresh'='initial'){if(loadBusyRef.current||actionBusyRef.current)return;loadBusyRef.current=true;if(mode==='initial'&&!itemsRef.current.length)setLoading(true);else setRefreshing(true);setError('');try{const {data:{user},error:authError}=await supabase.auth.getUser();if(authError)throw authError;if(!user){commitItems([]);return;}const {data,error:e}=await supabase.from('notifications').select('id,title,body,read_at,created_at,kind,data').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100);if(e)throw e;commitItems((data??[]) as Notification[])}catch{setError('We could not load notifications right now. Please try again.')}finally{setLoading(false);setRefreshing(false);loadBusyRef.current=false}}
 useEffect(()=>{void load()},[]);
 async function read(id:string){if(actionBusyRef.current||loadBusyRef.current)return false;actionBusyRef.current=true;setBusyId(id);setError('');try{const {error:e}=await supabase.rpc('mark_notification_read',{p_notification_id:id});if(e)throw e;const now=new Date().toISOString();commitItems(itemsRef.current.map(item=>item.id===id?{...item,read_at:item.read_at??now}:item));return true;}catch{setError('We could not update that notification. Please try again.');return false;}finally{setBusyId(null);actionBusyRef.current=false}}
 async function readAll(){if(actionBusyRef.current||loadBusyRef.current)return;const unread=itemsRef.current.filter(item=>!item.read_at);if(!unread.length)return;actionBusyRef.current=true;setMarkingAll(true);setError('');try{const {error:e}=await supabase.rpc('mark_all_notifications_read');if(e)throw e;const now=new Date().toISOString();commitItems(itemsRef.current.map(item=>item.read_at?item:{...item,read_at:now}));}catch{setError('We could not mark all notifications as read. Please try again.')}finally{setMarkingAll(false);actionBusyRef.current=false}}
 async function open(item:Notification){if(actionBusyRef.current||loadBusyRef.current)return;if(!item.read_at){const updated=await read(item.id);if(!updated)return;}const businessId=typeof item.data?.business_id==='string'?item.data.business_id:null;if(businessId){try{const ctx=await getWorkspaceContext();if(ctx.businesses.some(b=>b.id===businessId)){await setWorkspacePreference('BUSINESS',businessId);const kind=item.kind.toLowerCase();if(kind.includes('lead')||kind.includes('opportunit')||kind.includes('quote')){router.push('/business-leads');return;}if(kind.includes('booking')||kind.includes('job')){router.push('/business-jobs');return;}if(kind.includes('message')){router.push('/business-inbox');return;}if(kind.includes('order')||kind.includes('payment')||kind.includes('payout')||kind.includes('review')){router.push('/business-control');return;}router.push('/business-today');return;}}catch{setError('');}await setWorkspacePreference('CUSTOMER',null).catch(()=>undefined);router.push(destination(item));}
 const unreadCount=items.filter(item=>!item.read_at).length;const actionsBusy=!!busyId||markingAll||refreshing||loading;
 return <SafeAreaView style={s.safe}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load('refresh')} tintColor={colors.brand} progressBackgroundColor={colors.surface}/>} contentContainerStyle={s.page}><Text style={s.eyebrow}>EVEREST LOCAL</Text><View style={s.header}><View><Text style={s.title}>Notifications</Text>{!loading&&unreadCount>0&&<Text style={s.unreadCount}>{unreadCount} unread</Text>}</View>{!loading&&unreadCount>0&&<Pressable disabled={actionsBusy} onPress={()=>void readAll()} style={[s.readAll,actionsBusy&&s.disabled]}><Text style={s.readAllText}>{markingAll?'UPDATING…':'MARK ALL READ'}</Text></Pressable>}</View>{loading?<ActivityIndicator color={colors.brand}/>:error&&!items.length?<View style={s.empty}><Text style={s.emptyTitle}>We couldn't load notifications.</Text><Text style={s.error}>{error}</Text><Pressable disabled={loading} onPress={()=>void load()} style={s.button}><Text style={s.buttonText}>{loading?'RETRYING…':'RETRY'}</Text></Pressable></View>:items.length?<>{error?<View style={s.warning}><Text style={s.warningText}>We could not refresh notifications. Showing your last loaded updates.</Text><Pressable disabled={refreshing} onPress={()=>void load('refresh')} style={s.warningRetry}><Text style={s.warningRetryText}>{refreshing?'REFRESHING…':'RETRY NOTIFICATIONS'}</Text></Pressable></View>:null}{items.map(n=><Pressable key={n.id} disabled={actionsBusy} onPress={()=>void open(n)} style={[s.card,!n.read_at&&s.unread,actionsBusy&&s.disabled]}><View style={s.row}><Text style={s.kind}>{n.kind.replaceAll('_',' ')}</Text><Text style={s.time}>{new Date(n.created_at).toLocaleDateString()}</Text></View><Text style={s.cardTitle}>{n.title}</Text><Text style={s.body}>{n.body}</Text><Text style={s.open}>{busyId===n.id?'OPENING…':n.read_at?'OPEN →':'OPEN · NEW →'}</Text></Pressable>)}</>:<View style={s.empty}><Text style={s.emptyTitle}>You’re all caught up.</Text><Text style={s.body}>Marketplace updates will appear here.</Text></View>}</ScrollView></SafeAreaView>}
const createStyles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:40,maxWidth:760,width:'100%',alignSelf:'center'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:c.muted},header:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',gap:12,marginTop:7,marginBottom:22},title:{fontSize:31,fontWeight:'900',color:c.text},unreadCount:{fontSize:11,color:c.muted,marginTop:4},readAll:{minHeight:38,paddingHorizontal:12,borderRadius:11,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center',backgroundColor:c.surface},readAllText:{fontSize:8,fontWeight:'900',color:c.text},card:{backgroundColor:c.surface,borderRadius:17,borderWidth:1,borderColor:c.border,padding:16,marginBottom:9},unread:{borderColor:c.brand,backgroundColor:c.elevated},row:{flexDirection:'row',justifyContent:'space-between',gap:12},kind:{fontSize:8,fontWeight:'900',letterSpacing:1,color:c.textSecondary},time:{fontSize:10,color:c.muted},cardTitle:{fontSize:14,fontWeight:'800',marginTop:8,color:c.text},body:{fontSize:12,lineHeight:18,color:c.textSecondary,marginTop:5},open:{fontSize:9,fontWeight:'900',marginTop:12,color:c.brand},empty:{backgroundColor:c.surface,borderRadius:20,padding:28,alignItems:'center',marginTop:20,borderWidth:1,borderColor:c.border},emptyTitle:{fontSize:16,fontWeight:'800',color:c.text,textAlign:'center'},button:{height:46,borderRadius:13,backgroundColor:c.brand,paddingHorizontal:18,alignItems:'center',justifyContent:'center',marginTop:16},buttonText:{color:c.onBrand,fontSize:10,fontWeight:'900'},error:{color:c.danger,fontSize:12,lineHeight:18,marginTop:12,textAlign:'center'},warning:{backgroundColor:c.elevated,borderRadius:14,padding:14,marginBottom:12,borderWidth:1,borderColor:c.border},warningText:{fontSize:12,lineHeight:18,color:c.textSecondary},warningRetry:{minHeight:38,alignItems:'center',justifyContent:'center',marginTop:8},warningRetryText:{fontSize:10,fontWeight:'900',letterSpacing:.6,color:c.brand},disabled:{opacity:.55}});
