import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { supabase } from '@/lib/supabase';

export default function Opportunities(){const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [quoteId,setQuoteId]=useState<string|null>(null);const [price,setPrice]=useState('');const [description,setDescription]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function load(){try{const {data,error}=await supabase.from('opportunities').select('id,request_id,status,expires_at,service_requests(description,suburb,city,state,preferred_date,preferred_time,budget)').eq('status','OPEN').order('created_at',{ascending:false});if(error)throw error;setItems(data??[]);}catch(e){setError(e instanceof Error?e.message:'Unable to load opportunities.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function sendQuote(requestId:string){if(!price||Number(price)<0||!description.trim()){setMessage('Add a valid price and quote description.');return;}setBusy(true);setMessage('');try{const {data,error}=await supabase.rpc('send_quote',{p_request_id:requestId,p_service_id:null,p_description:description,p_line_items:[],p_price:Number(price),p_deposit:0,p_total:Number(price),p_proposed_date:null,p_proposed_time:null,p_valid_until:null,p_terms:null});if(error)throw error;setMessage(`Quote sent: ${data}`);setQuoteId(null);setPrice('');setDescription('');load();}catch(e){setMessage(e instanceof Error?e.message:'Quote could not be sent.')}finally{setBusy(false)}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.eyebrow}>EVEREST LOCAL</Text><Text style={s.title}>Opportunities</Text><Text style={s.copy}>Only requests matched to your business are shown. Customer identity and private details stay protected until authorized by the marketplace flow.</Text>{loading?<ActivityIndicator/>:error?<Text style={s.error}>{error}</Text>:items.length?items.map(o=><View style={s.card} key={o.id}><Text style={s.status}>OPEN OPPORTUNITY</Text><Text style={s.cardTitle}>{o.service_requests?.description}</Text><Text style={s.meta}>{[o.service_requests?.suburb,o.service_requests?.city,o.service_requests?.state].filter(Boolean).join(', ')}</Text>{o.service_requests?.preferred_date&&<Text style={s.meta}>Preferred: {o.service_requests.preferred_date}{o.service_requests.preferred_time?` at ${o.service_requests.preferred_time}`:''}</Text>}{o.service_requests?.budget!=null&&<Text style={s.meta}>Customer budget: ${Number(o.service_requests.budget).toFixed(2)} AUD</Text>}{quoteId===o.request_id?<View><TextInput value={description} onChangeText={setDescription} placeholder="Quote description" style={s.input}/><TextInput value={price} onChangeText={setPrice} placeholder="Total AUD" keyboardType="decimal-pad" style={s.input}/><Pressable disabled={busy} onPress={()=>sendQuote(o.request_id)} style={s.button}><Text style={s.buttonText}>{busy?'SENDING…':'SEND QUOTE'}</Text></Pressable></View>:<Pressable onPress={()=>setQuoteId(o.request_id)} style={s.outline}><Text style={s.outlineText}>RESPOND WITH QUOTE</Text></Pressable>}</View>):<View style={s.empty}><Text style={s.emptyTitle}>No open opportunities.</Text><Text style={s.meta}>New matched requests will appear here when your business is eligible.</Text></View>}{!!message&&<Text style={s.message}>{message}</Text>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:50},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:'#777'},title:{fontSize:31,fontWeight:'900',letterSpacing:-1,marginTop:7},copy:{fontSize:13,lineHeight:20,color:'#777',marginTop:8,marginBottom:24},card:{backgroundColor:'#fff',borderRadius:19,borderWidth:1,borderColor:'#e5e2dc',padding:17,marginBottom:11},status:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#777'},cardTitle:{fontSize:16,fontWeight:'800',marginTop:8,lineHeight:21},meta:{fontSize:12,color:'#777',marginTop:6,lineHeight:18},outline:{height:46,borderRadius:13,borderWidth:1,borderColor:'#d8d3ca',alignItems:'center',justifyContent:'center',marginTop:15},outlineText:{fontSize:10,fontWeight:'900'},input:{height:50,borderWidth:1,borderColor:'#dfdcd5',backgroundColor:'#fff',borderRadius:13,paddingHorizontal:14,fontSize:13,marginTop:10},button:{height:50,borderRadius:13,backgroundColor:'#111',alignItems:'center',justifyContent:'center',marginTop:10},buttonText:{color:'#fff',fontSize:10,fontWeight:'900'},empty:{backgroundColor:'#fff',borderRadius:19,padding:26,alignItems:'center',marginTop:10},emptyTitle:{fontSize:16,fontWeight:'800'},error:{color:'#b42318'},message:{fontSize:12,color:'#333',marginTop:12}});