import { useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { supabase } from '@/lib/supabase';
import { myOrders } from '@/lib/commerce';
import type { Order } from '@/lib/types';
type Delivery={order_id:string;status:string;eta:string|null};
export default function Orders(){const [orders,setOrders]=useState<Order[]>([]);const [deliveries,setDeliveries]=useState<Record<string,Delivery>>({});const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState('');const [deliveryError,setDeliveryError]=useState('');const [deliveryLoading,setDeliveryLoading]=useState(false);
 async function loadDeliveries(data:Order[]){if(!data.length){setDeliveries({});setDeliveryError('');return}setDeliveryLoading(true);setDeliveryError('');try{const {data:ds,error:e}=await supabase.from('deliveries').select('order_id,status,eta').in('order_id',data.map(o=>o.id));if(e)throw e;setDeliveries(Object.fromEntries(((ds??[]) as Delivery[]).map(d=>[d.order_id,d])))}catch{setDeliveryError('Delivery updates are temporarily unavailable. Your order details are still available below.')}finally{setDeliveryLoading(false)}}
 async function load(mode:'initial'|'refresh'='initial'){if(mode==='initial')setLoading(true);else setRefreshing(true);setError('');try{const data=await myOrders();setOrders(data);await loadDeliveries(data)}catch{setError('We could not load your orders right now. Please try again.')}finally{setLoading(false);setRefreshing(false)}}useEffect(()=>{void load()},[]);
 return <SafeAreaView style={s.safe}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load('refresh')}/>} contentContainerStyle={s.page}><View style={s.top}><Pressable onPress={()=>router.back()} accessibilityLabel="Go back"><Text style={s.back}>‹</Text></Pressable><Text style={s.topTitle}>Orders</Text><View style={{width:28}}/></View>{loading?<ActivityIndicator style={{marginTop:50}}/>:error&&!orders.length?<><Text style={s.error}>{error}</Text><Pressable onPress={()=>void load()} style={s.retry}><Text>RETRY</Text></Pressable></>:orders.length?<>{error?<View style={s.warning}><Text style={s.warningText}>We could not refresh your orders. Showing your last loaded order information.</Text><Pressable disabled={refreshing} onPress={()=>void load('refresh')} style={s.deliveryRetry}><Text style={s.retryText}>RETRY ORDERS</Text></Pressable></View>:null}{deliveryError?<View style={s.warning}><Text style={s.warningText}>{deliveryError}</Text><Pressable disabled={deliveryLoading} onPress={()=>void loadDeliveries(orders)} style={s.deliveryRetry}>{deliveryLoading?<ActivityIndicator/>:<Text style={s.retryText}>RETRY DELIVERY UPDATES</Text>}</Pressable></View>:null}{orders.map(o=>{const delivery=deliveries[o.id];return <View style={s.card} key={o.id}><View style={s.row}><Text style={s.number}>{o.order_number}</Text><Text style={s.status}>{o.status.replaceAll('_',' ')}</Text></View><Text style={s.amount}>${Number(o.total).toFixed(2)} AUD</Text><Text style={s.meta}>{new Date(o.created_at).toLocaleDateString()} · {o.payment_status.replaceAll('_',' ')}</Text>{delivery&&<View style={s.delivery}><Text style={s.deliveryTitle}>EVEREST DELIVERY</Text><Text style={s.deliveryStatus}>{delivery.status.replaceAll('_',' ')}</Text>{delivery.eta&&<Text style={s.meta}>ETA {new Date(delivery.eta).toLocaleString()}</Text>}</View>}</View>})}</>:<View style={s.emptyBox}><Text style={s.emptyTitle}>You haven’t placed an order yet.</Text><Text style={s.empty}>Products from verified local businesses will appear here after a real purchase.</Text></View>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:25},back:{fontSize:34,fontWeight:'300'},topTitle:{fontSize:16,fontWeight:'800'},card:{backgroundColor:'#fff',borderRadius:17,borderWidth:1,borderColor:'#e5e2dc',padding:17,marginBottom:10},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},number:{fontSize:14,fontWeight:'900'},status:{fontSize:9,fontWeight:'900',letterSpacing:.7},amount:{fontSize:22,fontWeight:'900',marginTop:12},meta:{fontSize:11,color:'#777',marginTop:5},delivery:{marginTop:13,paddingTop:12,borderTopWidth:1,borderTopColor:'#eeeae3'},deliveryTitle:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#777'},deliveryStatus:{fontSize:15,fontWeight:'800',marginTop:5},emptyBox:{backgroundColor:'#fff',borderRadius:20,padding:28,alignItems:'center',marginTop:20},emptyTitle:{fontSize:16,fontWeight:'800',textAlign:'center'},empty:{fontSize:13,color:'#777',lineHeight:20,textAlign:'center',marginTop:7},error:{fontSize:12,color:'#b42318',textAlign:'center'},retry:{height:44,borderRadius:12,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',marginTop:12},warning:{backgroundColor:'#fff8e8',borderRadius:14,padding:14,marginBottom:12,borderWidth:1,borderColor:'#ead8ae'},warningText:{fontSize:12,lineHeight:18,color:'#6b5424'},deliveryRetry:{minHeight:38,alignItems:'center',justifyContent:'center',marginTop:8},retryText:{fontSize:10,fontWeight:'900',letterSpacing:.6}});