import {ScrollView,Text,View} from 'react-native';import {SafeAreaView} from 'react-native-safe-area-context';import {useAppTheme} from '@/lib/theme';
export default function Privacy(){const{colors:c}=useAppTheme();const s={safe:{flex:1,backgroundColor:c.canvas},page:{padding:24,paddingBottom:60,maxWidth:760,width:'100%' as const,alignSelf:'center' as const},eyebrow:{fontSize:10,fontWeight:'900' as const,letterSpacing:2,color:c.muted},title:{fontSize:34,fontWeight:'900' as const,marginTop:8,color:c.text},updated:{fontSize:12,color:c.muted,marginTop:7}};return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.eyebrow}>EVEREST LOCAL</Text><Text style={s.title}>Privacy Policy</Text><Text style={s.updated}>Effective 26 September 2026</Text>
<Section title="Information we handle">Everest Local processes account information, profile details you provide, service requests, quotes, bookings, messages, reviews, products, orders, delivery and fulfilment information, support requests, and security/audit records needed to operate the marketplace.</Section>
<Section title="Payments">Payments are processed through Stripe. Everest Local does not store full payment-card numbers in its application database. Stripe processes payment and transaction information under its own privacy terms.</Section>
<Section title="Location, photos, camera and calendar">Everest Local requests device access only when you use a feature that needs it. Location can be used to confirm where a local service is needed. Photo-library or camera access can be used when you choose media for profiles, requests, posts, products or verification. Calendar access can be used when you choose to check availability or add confirmed bookings. These permissions can be declined or changed in device settings.</Section>
<Section title="Use and sharing">Information is used to authenticate accounts, operate and secure the marketplace, match customers and businesses, process transactions, provide support and deliver features you request. Information may be shared with marketplace participants where required for a transaction and with service providers that operate Everest Local infrastructure and payments. Everest Local does not intentionally sell personal information for advertising.</Section>
<Section title="AI and integrations">When enabled, Ask Everest may process your prompt and permitted marketplace context using the configured AI provider. Optional calendar, email, CRM and other integrations process data only when connected or used and remain subject to the relevant provider's terms and privacy practices.</Section>
<Section title="External business discovery">When external discovery is enabled, search text may be sent to Google Maps Platform to return current business results. Provider Place IDs may be retained for reference. An external enquiry is not sent merely because a result is viewed; sharing request or contact information requires the applicable user action.</Section>
<Section title="Retention and account deletion">You can request account deletion from Settings. Where records must be retained for transaction history, payments, disputes, fraud prevention, security, audit or legal obligations, Everest Local may retain those records and restrict them to those purposes rather than destroying required history. If automated hard deletion is unavailable because retained records exist, contact support through the app to request account closure and deletion or de-identification of eligible data.</Section>
<Section title="Security">Everest Local uses authenticated sessions, row-level database controls and server-authorized operations for sensitive marketplace actions. No internet service can guarantee absolute security.</Section>
<Section title="Children">Everest Local is not directed to children under 13. Users must also meet any higher minimum age required by applicable law or distribution-platform rules.</Section>
<Section title="Contact and changes">Privacy or account requests can be submitted through Settings → Help & support. We may update this policy when the service or legal requirements change; the effective date above identifies the current version.</Section>
</ScrollView></SafeAreaView>}
function Section({title,children}:{title:string;children:string}){const{colors:c}=useAppTheme();return <View style={{marginTop:24}}><Text style={{fontSize:16,fontWeight:'900',marginBottom:7,color:c.text}}>{title}</Text><Text style={{fontSize:14,lineHeight:22,color:c.textSecondary}}>{children}</Text></View>}
