import {useCallback,useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Image,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {router} from 'expo-router';
import {myBusiness,setProductStatus} from '@/lib/catalog';
import {signedProductMedia} from '@/lib/product-commerce';
import {supabase} from '@/lib/supabase';
import {type ThemeColors,useAppTheme} from '@/lib/theme';
type Row={id:string;name:string;price:number;sale_price:number|null;status:string;listing_quality:number;created_at:string;product_images:{storage_path:string|null;url:string;is_primary:boolean;sort_order:number}[];inventory:{stock_quantity:number;reserved_quantity:number}|null;imageUrl?:string|null};
const FILTERS=['ALL','ACTIVE','DRAFT','OUT_OF_STOCK','ARCHIVED'] as const;
export default function Products(){
 const {colors:c}=useAppTheme();const s=useMemo(()=>styles(c),[c]);const [business,setBusiness]=useState<{id:string;name:string}|null>(null);const [rows,setRows]=useState<Row[]>([]);const [filter,setFilter]=useState<(typeof FILTERS)[number]>('ALL');const [q,setQ]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=useCallback(async()=>{try{setLoading(true);setError('');const b=await myBusiness();if(!b){setBusiness(null);setRows([]);return}setBusiness({id:b.id,name:b.name});let query=supabase.from('products').select('id,name,price,sale_price,status,listing_quality,created_at,product_images(storage_path,url,is_primary,sort_order),inventory(stock_quantity,reserved_quantity)').eq('business_id',b.id).order('created_at',{ascending:false});if(filter!=='ALL')query=query.eq('status',filter);if(q.trim())query=query.ilike('name','%'+q.trim()+'%');const {data,error:e}=await query;if(e)throw e;const normalized=await Promise.all((data??[]).map(async(raw:any)=>{const inv=Array.isArray(raw.inventory)?raw.inventory[0]??null:raw.inventory;const imgs=[...(raw.product_images??[])].sort((a,b)=>Number(b.is_primary)-Number(a.is_primary)||a.sort_order-b.sort_order);return {...raw,inventory:inv,product_images:imgs,imageUrl:await signedProductMedia(imgs[0]?.storage_path||imgs[0]?.url||null,1800)} as Row}));setRows(normalized)}catch{setError('Products could not be loaded.')}finally{setLoading(false)}},[filter,q]);
 useEffect(()=>{const t=setTimeout(()=>void load(),q?250:0);return()=>clearTimeout(t)},[load,q]);
 async function archive(id:string){try{await setProductStatus(id,'ARCHIVED');await load()}catch{setError('Product could not be archived.')}}
 async function duplicate(row:Row){router.push(('/product-editor?duplicate='+row.id) as never)}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} showsVerticalScrollIndicator={false}>
  <View style={s.header}><View><Text style={s.eyebrow}>BUSINESS</Text><Text style={s.title}>Products</Text><Text style={s.sub}>{business?.name||'Your catalog'}</Text></View><Pressable onPress={()=>router.push('/product-editor')} style={s.add}><Ionicons name="add" size={19} color={c.onBrand}/><Text style={s.addText}>ADD PRODUCT</Text></Pressable></View>
  <View style={s.search}><Ionicons name="search" size={18} color={c.muted}/><TextInput value={q} onChangeText={setQ} placeholder="Search products" placeholderTextColor={c.muted} style={s.input}/></View>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{FILTERS.map(x=><Pressable key={x} onPress={()=>setFilter(x)} style={[s.filter,filter===x&&s.filterOn]}><Text style={s.filterText}>{x.replaceAll('_',' ')}</Text></Pressable>)}</ScrollView>
  {loading?<View style={s.center}><ActivityIndicator color={c.text}/></View>:!business?<View style={s.empty}><Text style={s.emptyTitle}>Business profile required.</Text><Text style={s.copy}>Create or select your business before managing products.</Text></View>:error?<View style={s.empty}><Text style={s.emptyTitle}>{error}</Text><Pressable onPress={()=>void load()} style={s.retry}><Text style={s.retryText}>TRY AGAIN</Text></Pressable></View>:rows.length?rows.map(row=>{const available=Math.max(0,(row.inventory?.stock_quantity??0)-(row.inventory?.reserved_quantity??0));return <View key={row.id} style={s.card}><Pressable onPress={()=>router.push(('/product-editor?id='+row.id) as never)} style={s.cardMain}>{row.imageUrl?<Image source={{uri:row.imageUrl}} style={s.image}/>:<View style={[s.image,s.fallback]}><Ionicons name="image-outline" size={22} color={c.muted}/></View>}<View style={{flex:1}}><View style={s.nameRow}><Text numberOfLines={1} style={s.name}>{row.name}</Text><Text style={s.status}>{row.status}</Text></View><Text style={s.price}>{'$'+Number(row.sale_price??row.price).toFixed(2)}</Text><Text style={s.meta}>{available} available · Listing quality {row.listing_quality??0}%</Text></View><Ionicons name="chevron-forward" size={18} color={c.muted}/></Pressable><View style={s.actions}><Pressable onPress={()=>router.push(('/product-editor?id='+row.id) as never)} style={s.action}><Text style={s.actionText}>Edit</Text></Pressable><Pressable onPress={()=>router.push(('/product?id='+row.id) as never)} style={s.action}><Text style={s.actionText}>View as customer</Text></Pressable><Pressable onPress={()=>duplicate(row)} style={s.action}><Text style={s.actionText}>Duplicate</Text></Pressable>{row.status!=='ARCHIVED'?<Pressable onPress={()=>void archive(row.id)} style={s.action}><Text style={[s.actionText,{color:c.danger}]}>Archive</Text></Pressable>:null}</View></View>}):<View style={s.empty}><Ionicons name="cube-outline" size={28} color={c.muted}/><Text style={s.emptyTitle}>No products here yet.</Text><Text style={s.copy}>Create a draft, add real photos, preview it, then publish.</Text><Pressable onPress={()=>router.push('/product-editor')} style={s.retry}><Text style={s.retryText}>ADD PRODUCT</Text></Pressable></View>}
  <View style={{height:30}}/>
 </ScrollView></SafeAreaView>
}
const styles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:18,paddingBottom:40,maxWidth:820,width:'100%',alignSelf:'center'},header:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',gap:12},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.6,color:c.brand},title:{fontSize:31,fontWeight:'900',letterSpacing:-.9,color:c.text,marginTop:4},sub:{fontSize:11,color:c.muted,marginTop:4},add:{height:44,borderRadius:14,paddingHorizontal:13,backgroundColor:c.brand,flexDirection:'row',alignItems:'center',gap:5},addText:{fontSize:8,fontWeight:'900',color:c.onBrand},search:{height:50,borderRadius:16,backgroundColor:c.surface,borderWidth:1,borderColor:c.border,flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:12,marginTop:18},input:{flex:1,color:c.text,fontSize:13},filters:{gap:7,paddingVertical:13,paddingRight:8},filter:{height:36,borderRadius:12,paddingHorizontal:12,backgroundColor:c.surface,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center'},filterOn:{borderColor:c.brand,backgroundColor:c.elevated},filterText:{fontSize:8,fontWeight:'900',color:c.text},center:{paddingVertical:70},card:{borderRadius:18,backgroundColor:c.surface,borderWidth:1,borderColor:c.border,marginBottom:10,overflow:'hidden'},cardMain:{padding:11,flexDirection:'row',alignItems:'center',gap:11},image:{width:72,height:72,borderRadius:14,backgroundColor:c.soft},fallback:{alignItems:'center',justifyContent:'center'},nameRow:{flexDirection:'row',alignItems:'center',gap:8},name:{fontSize:13,fontWeight:'900',color:c.text,flex:1},status:{fontSize:7,fontWeight:'900',color:c.muted},price:{fontSize:14,fontWeight:'900',color:c.text,marginTop:6},meta:{fontSize:9,color:c.muted,marginTop:4},actions:{flexDirection:'row',flexWrap:'wrap',gap:7,padding:10,borderTopWidth:1,borderTopColor:c.border},action:{height:34,borderRadius:10,paddingHorizontal:10,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center'},actionText:{fontSize:8,fontWeight:'900',color:c.text},empty:{paddingVertical:55,alignItems:'center'},emptyTitle:{fontSize:15,fontWeight:'900',color:c.text,marginTop:9,textAlign:'center'},copy:{fontSize:10,lineHeight:16,color:c.muted,textAlign:'center',marginTop:5},retry:{height:42,borderRadius:12,paddingHorizontal:16,backgroundColor:c.text,alignItems:'center',justifyContent:'center',marginTop:13},retryText:{fontSize:8,fontWeight:'900',color:c.canvas}});
