import {useEffect,useState} from 'react';
import {ActivityIndicator,Alert,Image,Pressable,ScrollView,Text,TextInput,View} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {router,useLocalSearchParams} from 'expo-router';
import {SafeAreaView} from 'react-native-safe-area-context';
import {blockUser,cancelConnectionRequest,getPublicUserProfile,publicPostsForUser,removeConnection,sendConnectionRequest,sendPersonalMessage,type PublicUserProfile} from '@/lib/connections';
import {useAppTheme} from '@/lib/theme';

export default function PublicUser(){
 const {colors:c}=useAppTheme(); const {id}=useLocalSearchParams<{id?:string}>(); const userId=typeof id==='string'?id:'';
 const [p,setP]=useState<PublicUserProfile|null>(null); const [posts,setPosts]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
 async function load(){if(!userId)return;setLoading(true);setError('');try{const [profile,content]=await Promise.all([getPublicUserProfile(userId),publicPostsForUser(userId)]);setP(profile);setPosts(content)}catch(e){setError(e instanceof Error?e.message:'Profile could not be loaded.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[userId]);
 async function connect(){if(!p)return;setBusy(true);try{if(p.connection_state==='NONE')await sendConnectionRequest(p.id);else if(p.connection_state==='OUTGOING')await cancelConnectionRequest(p.id);else if(p.connection_state==='CONNECTED')await removeConnection(p.id);await load()}catch(e){setError(e instanceof Error?e.message:'Connection action failed.')}finally{setBusy(false)}}
 async function send(){if(!p||!message.trim())return;setBusy(true);try{const conversationId=await sendPersonalMessage(p.id,message);setMessage('');router.push('/messages?personalId='+conversationId)}catch(e){setError(e instanceof Error?e.message:'Message could not be sent.')}finally{setBusy(false)}}
 function doBlock(){if(!p)return;Alert.alert('Block user','They will no longer be able to find, connect with or message you.',[{text:'Cancel',style:'cancel'},{text:'Block',style:'destructive',onPress:async()=>{setBusy(true);try{await blockUser(p.id);router.back()}finally{setBusy(false)}}}])}
 if(loading)return <SafeAreaView style={{flex:1,backgroundColor:c.canvas}}><ActivityIndicator style={{marginTop:80}} color={c.text}/></SafeAreaView>;
 return <SafeAreaView style={{flex:1,backgroundColor:c.canvas}}><ScrollView contentContainerStyle={{padding:20,paddingBottom:60,maxWidth:760,width:'100%',alignSelf:'center'}}>
  <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={23} color={c.text}/></Pressable><Text style={{fontSize:16,fontWeight:'800',color:c.text}}>Profile</Text><Pressable onPress={doBlock} disabled={!p||busy}><Ionicons name="ellipsis-horizontal" size={22} color={c.text}/></Pressable></View>
  {!p?<View style={{paddingVertical:70,alignItems:'center'}}><Text style={{fontSize:18,fontWeight:'900',color:c.text}}>Profile unavailable</Text><Text style={{fontSize:12,color:c.muted,marginTop:8}}>This profile may be private or unavailable to you.</Text></View>:<>
   <View style={{alignItems:'center',marginTop:28}}>{p.avatar_url?<Image source={{uri:p.avatar_url}} style={{width:94,height:94,borderRadius:47}}/>:<View style={{width:94,height:94,borderRadius:47,backgroundColor:c.soft,alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:30,fontWeight:'900',color:c.text}}>{(p.display_name??'E')[0]?.toUpperCase()}</Text></View>}
    <Text style={{fontSize:24,fontWeight:'900',color:c.text,marginTop:13}}>{p.display_name??'Everest member'}</Text>{p.username?<Text style={{fontSize:12,color:c.muted,marginTop:3}}>@{p.username}</Text>:null}
    {p.bio?<Text style={{fontSize:13,lineHeight:20,color:c.textSecondary,textAlign:'center',marginTop:10,maxWidth:420}}>{p.bio}</Text>:null}{p.suburb?<Text style={{fontSize:11,color:c.muted,marginTop:6}}>{p.suburb}</Text>:null}
    <Pressable onPress={()=>router.push('/connections?userId='+p.id)} style={{marginTop:16}}><Text style={{fontSize:13,fontWeight:'800',color:c.text}}>{p.connection_count} Connections{p.mutual_count?' · '+p.mutual_count+' mutual':''}</Text></Pressable>
    <View style={{flexDirection:'row',gap:8,marginTop:18}}>{p.connection_state!=='SELF'&&p.connection_state!=='UNAVAILABLE'&&p.connection_state!=='BLOCKED'?<Pressable disabled={busy||p.connection_state==='INCOMING'} onPress={()=>void connect()} style={{minHeight:44,paddingHorizontal:18,borderRadius:13,backgroundColor:c.brand,alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:10,fontWeight:'900',color:c.onBrand}}>{p.connection_state==='CONNECTED'?'REMOVE':p.connection_state==='OUTGOING'?'CANCEL REQUEST':p.connection_state==='INCOMING'?'REQUEST RECEIVED':'CONNECT'}</Text></Pressable>:null}</View>
   </View>
   <View style={{marginTop:28,borderRadius:18,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,padding:14}}><Text style={{fontSize:11,fontWeight:'900',color:c.text,marginBottom:8}}>Message</Text><TextInput value={message} onChangeText={setMessage} placeholder="Write a message…" placeholderTextColor={c.muted} multiline maxLength={5000} style={{minHeight:74,borderRadius:13,backgroundColor:c.input,color:c.text,padding:12,textAlignVertical:'top'}}/><Pressable disabled={busy||!message.trim()} onPress={()=>void send()} style={{alignSelf:'flex-end',marginTop:8,minHeight:40,paddingHorizontal:16,borderRadius:12,backgroundColor:c.brand,alignItems:'center',justifyContent:'center',opacity:busy||!message.trim()?.5:1}}><Text style={{fontSize:10,fontWeight:'900',color:c.onBrand}}>SEND</Text></Pressable></View>
   <Text style={{fontSize:15,fontWeight:'900',color:c.text,marginTop:28,marginBottom:10}}>Posts & media</Text>{posts.length?posts.map(item=><View key={item.id} style={{borderRadius:16,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,padding:14,marginBottom:10}}><Text style={{fontSize:13,lineHeight:19,color:c.text}}>{item.caption||String(item.post_type).replaceAll('_',' ')}</Text><Text style={{fontSize:10,color:c.muted,marginTop:7}}>{new Date(item.created_at).toLocaleDateString()}</Text></View>):<Text style={{fontSize:12,color:c.muted}}>No public posts yet.</Text>}
  </>}
  {error?<Text style={{fontSize:12,color:c.danger,marginTop:14}}>{error}</Text>:null}
 </ScrollView></SafeAreaView>
}