import { useCallback,useEffect,useMemo,useRef,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { router,useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { acceptQuote,myQuotes } from '@/lib/marketplace';
import { getOrCreateConversation } from '@/lib/messaging';
import { type ThemeColors,useAppTheme } from '@/lib/theme';
import type { Quote } from '@/lib/types';

export default function Quotes(){
 const {requestId}=useLocalSearchParams<{requestId?:string}>();const {colors}=useAppTheme();const s=useMemo(()=>createStyles(colors),[colors]);
 const [quotes,setQuotes]=useState<Quote[]>([]);const quotesRef=useRef<Quote[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [loadedOnce,setLoadedOnce]=useState(false);const [accepting,setAccepting]=useState<string|null>(null);const [messaging,setMessaging]=useState<string|null>(null);const [error,setError]=useState('');const loadActiveRef=useRef(false);const operationActiveRef=useRef(false);
 const load=useCallback(async(mode:'initial'|'refresh'='initial')=>{if(loadActiveRef.current||operationActiveRef.current)return;loadActiveRef.current=true;if(mode==='refresh')setRefreshing(true);else if(!quotesRef.current.length)setLoading(true);try{setError('');const data=await myQuotes(requestId);quotesRef.current=data;setQuotes(data);setLoadedOnce(true)}catch{setError(quotesRef.current.length?"We couldn't refresh your quotes. Showing the last successfully loaded quotes.":"We couldn't load your quotes right now. Please try again.")}finally{loadActiveRef.current=false;setLoading(false);setRefreshing(false)}},[requestId]);
 useEffect(()=>{void load('initial')},[load]);
 async function runOperation(key:string,kind:'accept'|'message',action:()=>Promise<void>){if(operationActiveRef.current||loadActiveRef.current)return;operationActiveRef.current=true;setError('');if(kind==='accept')setAccepting(key);else setMessaging(key);try{await action()}finally{operationActiveRef.current=false;if(kind==='accept')setAccepting(null);else setMessaging(null)}}
 async function accept(id:string){await runOperation(id,'accept',async()=>{try{await acceptQuote(id);router.replace('/bookings')}catch{setError('Quote could not be accepted. Please check that it is still available and try again.')}})}
 async function messageBusiness(q:Quote){await runOperation(q.id,'message',async()=>{try{const id=await getOrCreateConversation({requestId:q.request_id,businessId:q.business_id,quoteId:q.id});router.push({pathname:'/messages',params:{conversationId:id}})}catch{setError('Conversation could not be opened. Please try again.')}})}
 const operationActive=!!accepting||!!messaging;const hasQuotes=quotes.length>0;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} refreshControl={<RefreshControl refreshing={refreshing} enabled={!operationActive} tintColor={colors.text} onRefresh={()=>void load('refresh')}/>}><Text style={s.eyebrow}>EVEREST LOCAL</Text><View style={s.header}><Text style={s.title}>{requestId?'Quotes for request':'Quotes'}</Text>{requestId&&<Pressable disabled={refreshing||operationActive} onPress={()=>router.back()} style={[s.back,(refreshing||operationActive)&&s.disabled]}><Text style={s.backText}>BACK</Text></Pressable>}</View>{loading&&!loadedOnce?<ActivityIndicator color={colors.text} style={{marginTop:20}}/>:error&&!loadedOnce&&!hasQuotes?<View style={s.empty}><Text style={s.emptyTitle}>We couldn't load quotes.</Text><Text style={s.meta}>Your quotes are still safe. Try again.</Text><Pressable disabled={refreshing||operationActive} onPress={()=>void load('initial')} style={s.button}><Text style={s.buttonText}>RETRY QUOTES</Text></Pressable></View>:<>{!!error&&loadedOnce&&<View style={s.warning}><Text style={s.warningTitle}>Quotes may be out of date.</Text><Text style={s.meta}>{error}</Text><Pressable disabled={refreshing||operationActive} onPress={()=>void load('refresh')} style={s.retry}><Text style={s.retryText}>{refreshing?'REFRESHING…':'RETRY QUOTES'}</Text></Pressable></View>}{hasQuotes?quotes.map(q=><View style={s.card} key={q.id}><View style={s.row}><Text style={s.status}>{q.status.replaceAll('_',' ')}</Text><Text style={s.amount}>${Number(q.total).toFixed(2)} AUD</Text></View><Text style={s.description}>{q.description}</Text>{q.proposed_date&&<Text style={s.meta}>Proposed: {q.proposed_date}{q.proposed_time?` at ${q.proposed_time}`:''}</Text>}{q.valid_until&&<Text style={s.meta}>Valid until {new Date(q.valid_until).toLocaleString()}</Text>}{q.status==='SENT'||q.status==='VIEWED'?<Pressable disabled={refreshing||operationActive} onPress={()=>void accept(q.id)} style={[s.button,(refreshing||operationActive)&&s.disabled]}><Text style={s.buttonText}>{accepting===q.id?'ACCEPTING…':'ACCEPT QUOTE'}</Text></Pressable>:null}<Pressable disabled={refreshing||operationActive} onPress={()=>void messageBusiness(q)} style={[s.outline,(refreshing||operationActive)&&s.disabled]}><Text style={s.outlineText}>{messaging===q.id?'OPENING…':'MESSAGE BUSINESS'}</Text></Pressable></View>):!error&&<View style={s.empty}><Text style={s.emptyTitle}>{requestId?'No quotes have arrived yet.':'No quotes yet.'}</Text><Text style={s.meta}>{requestId?'Matched businesses will appear here when they send a quote.':'Quotes from real matched businesses will appear here.'}</Text>{requestId&&<Pressable onPress={()=>router.back()} style={s.button}><Text style={s.buttonText}>BACK TO REQUESTS</Text></Pressable>}</View>}</>}</ScrollView></SafeAreaView>}
const createStyles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:50,maxWidth:760,width:'100%',alignSelf:'center'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:c.muted},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12,marginTop:7,marginBottom:4},title:{fontSize:31,fontWeight:'900',color:c.text,flexShrink:1},back:{minHeight:38,paddingHorizontal:14,borderRadius:12,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center'},backText:{fontSize:9,fontWeight:'900',color:c.text},card:{backgroundColor:c.surface,borderRadius:17,borderWidth:1,borderColor:c.border,padding:17,marginTop:10},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},status:{fontSize:9,fontWeight:'900',color:c.text},amount:{fontSize:20,fontWeight:'900',color:c.text},description:{fontSize:14,fontWeight:'700',lineHeight:20,marginTop:12,color:c.text},meta:{fontSize:11,color:c.muted,marginTop:6,lineHeight:17},button:{minHeight:48,borderRadius:13,backgroundColor:c.text,alignItems:'center',justifyContent:'center',marginTop:14,paddingHorizontal:16},buttonText:{color:c.canvas,fontSize:10,fontWeight:'900'},outline:{minHeight:46,borderRadius:13,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center',marginTop:10},outlineText:{fontSize:10,fontWeight:'900',color:c.text},empty:{backgroundColor:c.surface,borderRadius:19,padding:28,alignItems:'center',marginTop:18,borderWidth:1,borderColor:c.border},emptyTitle:{fontSize:16,fontWeight:'800',textAlign:'center',color:c.text},warning:{backgroundColor:c.soft,borderRadius:17,borderWidth:1,borderColor:c.border,padding:16,marginTop:14},warningTitle:{fontSize:13,fontWeight:'900',color:c.text},retry:{alignSelf:'flex-start',marginTop:10,minHeight:40,paddingHorizontal:12,borderRadius:10,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center'},retryText:{fontSize:9,fontWeight:'900',color:c.text},disabled:{opacity:.5}});