import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { router,useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { acceptQuote,myQuotes } from '@/lib/marketplace';
import { getOrCreateConversation } from '@/lib/messaging';
import { userFacingError } from '@/lib/errors';
import type { Quote } from '@/lib/types';

export default function Quotes(){const {requestId}=useLocalSearchParams<{requestId?:string}>();const [quotes,setQuotes]=useState<Quote[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [loadedOnce,setLoadedOnce]=useState(false);const [accepting,setAccepting]=useState<string|null>(null);const [messaging,setMessaging]=useState<string|null>(null);const [error,setError]=useState('');
const load=useCallback(async(mode:'initial'|'refresh'='initial')=>{if(mode==='refresh')setRefreshing(true);else if(!loadedOnce)setLoading(true);try{setError('');const data=await myQuotes(requestId);setQuotes(data);setLoadedOnce(true)}catch(e){setError(userFacingError(e,"We couldn't refresh your quotes. Please try again."))}finally{setLoading(false);setRefreshing(false)}},[loadedOnce,requestId]);useEffect(()=>{void load('initial')},[load]);
async function accept(id:string){if(accepting||messaging)return;setAccepting(id);setError('');try{await acceptQuote(id);router.replace('/bookings')}catch(e){setError(userFacingError(e,'Quote could not be accepted. Please try again.'));void load('refresh')}finally{setAccepting(null)}}
async function messageBusiness(q:Quote){if(accepting||messaging)return;setMessaging(q.id);setError('');try{const id=await getOrCreateConversation({requestId:q.request_id,businessId:q.business_id,quoteId:q.id});router.push({pathname:'/messages',params:{conversationId:id}})}catch(e){setError(userFacingError(e,'Conversation could not be opened. Please try again.'))}finally{setMessaging(null)}}
const hasQuotes=quotes.length>0;return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load('refresh')}/>}><Text style={s.eyebrow}>EVEREST LOCAL</Text><View style={s.header}><Text style={s.title}>{requestId?'Quotes for request':'Quotes'}</Text>{requestId&&<Pressable disabled={refreshing||!!accepting||!!messaging} onPress={()=>router.back()} style={s.back}><Text style={s.backText}>BACK</Text></Pressable>}</View>{loading&&!loadedOnce?<ActivityIndicator style={{marginTop:20}}/>:error&&!loadedOnce&&!hasQuotes?<View style={s.empty}><Text style={s.emptyTitle}>We couldn't load quotes.</Text><Text style={s.meta}>Your quotes are still safe. Try again.</Text><Pressable onPress={()=>void load('initial')} style={s.button}><Text style={s.buttonText}>RETRY QUOTES</Text></Pressable></View>:<>{!!error&&loadedOnce&&<View style={s.warning}><Text style={s.warningTitle}>Quotes may be out of date.</Text><Text style={s.meta}>We kept your last loaded quotes while the refresh failed.</Text><Pressable disabled={refreshing} onPress={()=>void load('refresh')} style={s.retry}><Text style={s.retryText}>{refreshing?'REFRESHING…':'RETRY QUOTES'}</Text></Pressable></View>}{hasQuotes?quotes.map(q=><View style={s.card} key={q.id}><View style={s.row}><Text style={s.status}>{q.status.replaceAll('_',' ')}</Text><Text style={s.amount}>${Number(q.total).toFixed(2)} AUD</Text></View><Text style={s.description}>{q.description}</Text>{q.proposed_date&&<Text style={s.meta}>Proposed: {q.proposed_date}{q.proposed_time?` at ${q.proposed_time}`:''}</Text>}{q.valid_until&&<Text style={s.meta}>Valid until {new Date(q.valid_until).toLocaleString()}</Text>}{q.status==='SENT'||q.status==='VIEWED'?<Pressable disabled={refreshing||!!accepting||!!messaging} onPress={()=>void accept(q.id)} style={s.button}><Text style={s.buttonText}>{accepting===q.id?'ACCEPTING…':'ACCEPT QUOTE'}</Text></Pressable>:null}<Pressable disabled={refreshing||!!accepting||!!messaging} onPress={()=>void messageBusiness(q)} style={s.outline}><Text style={s.outlineText}>{messaging===q.id?'OPENING…':'MESSAGE BUSINESS'}</Text></Pressable></View>):!error&&<View style={s.empty}><Text style={s.emptyTitle}>{requestId?'No quotes have arrived yet.':'No quotes yet.'}</Text><Text style={s.meta}>{requestId?'Matched businesses will appear here when they send a quote.':'Quotes from real matched businesses will appear here.'}</Text>{requestId&&<Pressable onPress={()=>router.back()} style={s.button}><Text style={s.buttonText}>BACK TO REQUESTS</Text></Pressable>}</View>}</>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:50},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:'#777'},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:7},title:{fontSize:31,fontWeight:'900'},back:{height:38,paddingHorizontal:14,borderRadius:12,borderWidth:1,borderColor:'#ddd8cf',alignItems:'center',justifyContent:'center'},backText:{fontSize:9,fontWeight:'900'},card:{backgroundColor:'#fff',borderRadius:17,borderWidth:1,borderColor:'#e5e2dc',padding:17,marginTop:10},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},status:{fontSize:9,fontWeight:'900'},amount:{fontSize:20,fontWeight:'900'},description:{fontSize:14,fontWeight:'700',lineHeight:20,marginTop:12},meta:{fontSize:11,color:'#777',marginTop:6},button:{height:48,borderRadius:13,backgroundColor:'#111',alignItems:'center',justifyContent:'center',marginTop:14,paddingHorizontal:16},buttonText:{color:'#fff',fontSize:10,fontWeight:'900'},outline:{height:46,borderRadius:13,borderWidth:1,borderColor:'#d8d3ca',alignItems:'center',justifyContent:'center',marginTop:10},outlineText:{fontSize:10,fontWeight:'900'},empty:{backgroundColor:'#fff',borderRadius:19,padding:28,alignItems:'center',marginTop:18},emptyTitle:{fontSize:16,fontWeight:'800',textAlign:'center'},warning:{backgroundColor:'#fff',borderRadius:17,borderWidth:1,borderColor:'#e5e2dc',padding:16,marginTop:14},warningTitle:{fontSize:13,fontWeight:'900'},retry:{alignSelf:'flex-start',marginTop:10,paddingVertical:8,paddingHorizontal:10,borderRadius:10,borderWidth:1,borderColor:'#d8d3ca'},retryText:{fontSize:9,fontWeight:'900'}});