import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { acceptQuote, myQuotes } from '@/lib/marketplace';
import { getOrCreateConversation } from '@/lib/messaging';
import type { Quote } from '@/lib/types';

export default function Quotes(){
 const [quotes,setQuotes]=useState<Quote[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [messaging,setMessaging]=useState<string|null>(null);const [error,setError]=useState('');
 async function load(){try{setError('');setQuotes(await myQuotes())}catch(e){setError(e instanceof Error?e.message:'Unable to load quotes.')}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
 async function accept(id:string){setBusy(true);setError('');try{await acceptQuote(id);await load()}catch(e){setError(e instanceof Error?e.message:'Quote could not be accepted.')}finally{setBusy(false)}}
 async function messageBusiness(q:Quote){setMessaging(q.id);setError('');try{const id=await getOrCreateConversation({requestId:q.request_id,businessId:q.business_id,quoteId:q.id});router.push({pathname:'/messages',params:{conversationId:id}})}catch(e){setError(e instanceof Error?e.message:'Conversation could not be opened.')}finally{setMessaging(null)}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.eyebrow}>EVEREST LOCAL</Text><Text style={s.title}>Quotes</Text>{loading?<ActivityIndicator/>:quotes.length?quotes.map(q=><View style={s.card} key={q.id}><View style={s.row}><Text style={s.status}>{q.status}</Text><Text style={s.amount}>${Number(q.total).toFixed(2)} AUD</Text></View><Text style={s.description}>{q.description}</Text>{q.proposed_date&&<Text style={s.meta}>Proposed: {q.proposed_date}{q.proposed_time?` at ${q.proposed_time}`:''}</Text>}{q.valid_until&&<Text style={s.meta}>Valid until {new Date(q.valid_until).toLocaleString()}</Text>}{q.status==='SENT'||q.status==='VIEWED'?<Pressable disabled={busy} onPress={()=>void accept(q.id)} style={s.button}><Text style={s.buttonText}>ACCEPT QUOTE</Text></Pressable>:null}<Pressable disabled={messaging===q.id} onPress={()=>void messageBusiness(q)} style={s.outline}><Text style={s.outlineText}>{messaging===q.id?'OPENING…':'MESSAGE BUSINESS'}</Text></Pressable></View>):<View style={s.empty}><Text style={s.emptyTitle}>No quotes yet.</Text><Text style={s.meta}>Quotes from real matched businesses will appear here.</Text></View>}{!!error&&<Text style={s.error}>{error}</Text>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:50},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:'#777'},title:{fontSize:31,fontWeight:'900',marginTop:7,marginBottom:22},card:{backgroundColor:'#fff',borderRadius:17,borderWidth:1,borderColor:'#e5e2dc',padding:17,marginBottom:10},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},status:{fontSize:9,fontWeight:'900'},amount:{fontSize:20,fontWeight:'900'},description:{fontSize:14,fontWeight:'700',lineHeight:20,marginTop:12},meta:{fontSize:11,color:'#777',marginTop:6},button:{height:48,borderRadius:13,backgroundColor:'#111',alignItems:'center',justifyContent:'center',marginTop:14},buttonText:{color:'#fff',fontSize:10,fontWeight:'900'},outline:{height:46,borderRadius:13,borderWidth:1,borderColor:'#d8d3ca',alignItems:'center',justifyContent:'center',marginTop:10},outlineText:{fontSize:10,fontWeight:'900'},empty:{backgroundColor:'#fff',borderRadius:19,padding:28,alignItems:'center'},emptyTitle:{fontSize:16,fontWeight:'800'},error:{fontSize:12,color:'#b42318',marginTop:12}});