import { useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router,useLocalSearchParams } from 'expo-router';
import { createServiceRequest } from '@/lib/marketplace';
import { supabase } from '@/lib/supabase';
import { userFacingError } from '@/lib/errors';
import { captureCurrentWebLocation,setServiceRequestLocation,type SharedLocation } from '@/lib/service-dispatch';
import type { DeliveryMode } from '@/lib/taxonomy';

export default function Request(){
 const params=useLocalSearchParams<{serviceId?:string;mode?:string}>();
 const serviceId=typeof params.serviceId==='string'?params.serviceId:'';
 const [step,setStep]=useState(1);const [description,setDescription]=useState('');const [suburb,setSuburb]=useState('');const [date,setDate]=useState('');const [time,setTime]=useState('');const [budget,setBudget]=useState('');const [mode,setMode]=useState<DeliveryMode>((params.mode==='REMOTE'||params.mode==='BOTH'||params.mode==='LOCAL')?params.mode:'LOCAL');const [serviceName,setServiceName]=useState('');const [serviceMode,setServiceMode]=useState<DeliveryMode|null>(null);const [busy,setBusy]=useState(false);const [locating,setLocating]=useState(false);const [location,setLocation]=useState<SharedLocation|null>(null);const [error,setError]=useState('');const [success,setSuccess]=useState(false);const [successNote,setSuccessNote]=useState('');
 useEffect(()=>{let active=true;(async()=>{if(!serviceId)return;const {data,error:e}=await supabase.from('services').select('name,delivery_mode').eq('id',serviceId).eq('active',true).maybeSingle();if(e){if(active)setError('Could not load the selected service.');return;}if(active&&data){setServiceName(data.name);setServiceMode(data.delivery_mode as DeliveryMode);if(data.delivery_mode==='REMOTE')setMode('REMOTE');else if(data.delivery_mode==='LOCAL')setMode('LOCAL');}})();return()=>{active=false}},[serviceId]);
 const effectiveMode=serviceMode==='BOTH'?mode:(serviceMode??mode);
 function next(){setError('');if(step===1&&description.trim().length<5){setError('Tell businesses what you need in at least a few words.');return;}if(step===2&&effectiveMode==='LOCAL'&&!suburb.trim()){setError('Add the suburb where the work will happen.');return;}if(step===3&&budget&&(!Number.isFinite(Number(budget))||Number(budget)<0)){setError('Budget must be a valid positive amount.');return;}setStep(value=>Math.min(4,value+1));}
 function back(){setError('');setStep(value=>Math.max(1,value-1));}
 async function shareLocation(){setError('');setLocating(true);try{setLocation(await captureCurrentWebLocation())}catch(e){setError(userFacingError(e,'We could not access your location. Check browser permission and try again.'))}finally{setLocating(false)}}
 async function submit(){if(busy)return;setError('');setBusy(true);try{const requestId=await createServiceRequest({serviceId:serviceId||undefined,description,suburb:effectiveMode==='REMOTE'?undefined:suburb,city:effectiveMode==='REMOTE'?undefined:'Sydney',state:effectiveMode==='REMOTE'?undefined:'NSW',preferredDate:date||undefined,preferredTime:time||undefined,budget:budget?Number(budget):undefined,deliveryMode:effectiveMode});if(effectiveMode==='LOCAL'&&location){try{await setServiceRequestLocation(requestId,location)}catch{setSuccessNote('Your request was created, but its precise location could not be saved. Instant provider dispatch will remain unavailable for this request.')}}setSuccess(true);}catch(e){setError(userFacingError(e,'We could not submit your request. Please retry.'))}finally{setBusy(false)}}
 if(success)return <SafeAreaView style={s.safe}><View style={s.success}><View style={s.check}><Text style={{fontSize:28}}>✓</Text></View><Text style={s.title}>Request received.</Text><Text style={s.copy}>Everest will match your request against eligible verified businesses that support {effectiveMode==='REMOTE'?'remote delivery':effectiveMode==='LOCAL'?'local delivery':'the requested delivery mode'}.</Text>{!!successNote&&<Text accessibilityRole="alert" style={s.error}>{successNote}</Text>}<Pressable onPress={()=>router.replace('/activity')} style={s.button}><Text style={s.buttonText}>VIEW ACTIVITY</Text></Pressable></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
  <View style={s.top}><Pressable onPress={()=>step>1?back():router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.topTitle}>Post a request</Text><Text style={s.step}>{step}/4</Text></View><View style={s.progress}><View style={[s.progressFill,{width:`${step*25}%`}]}/></View>
  {!!serviceName&&<View style={s.selected}><Text style={s.selectedLabel}>SELECTED SERVICE</Text><Text style={s.selectedName}>{serviceName}</Text><Text style={s.meta}>{serviceMode==='REMOTE'?'Remote':serviceMode==='BOTH'?'Local + remote':'Local'}</Text></View>}
  {step===1&&<Step title="What do you need?" copy="Start with the job. Everest uses your description and selected service to match eligible businesses." label="YOUR NEED" value={description} onChange={setDescription} placeholder="Example: I need a responsive website for my business." multiline/>}
  {step===2&&<>{serviceMode==='BOTH'&&<><Text style={s.title}>How should it be delivered?</Text><Text style={s.copy}>Choose whether you want the provider to work locally or remotely.</Text><View style={s.modeRow}>{(['LOCAL','REMOTE'] as DeliveryMode[]).map(item=><Pressable key={item} onPress={()=>setMode(item)} style={[s.mode,mode===item&&s.modeActive]}><Text style={[s.modeText,mode===item&&s.modeTextActive]}>{item}</Text></Pressable>)}</View></>}{effectiveMode==='LOCAL'?<><Text style={s.title}>Where is the job?</Text><Text style={s.copy}>Use the suburb where the work will happen.</Text><Text style={s.label}>SUBURB</Text><TextInput value={suburb} onChangeText={setSuburb} placeholder="e.g. Greystanes" style={s.input}/><View style={s.locationCard}><Text style={s.locationTitle}>{location?'LOCATION SHARED':'PRECISE LOCATION (OPTIONAL)'}</Text><Text style={s.meta}>{location?'Saved locally and shared only when this request is posted.':'Required only if you later use instant provider dispatch. Your browser will ask permission.'}</Text><Pressable disabled={locating} onPress={()=>void shareLocation()} style={s.locationButton}><Text style={s.locationButtonText}>{locating?'LOCATING…':location?'UPDATE LOCATION':'SHARE CURRENT LOCATION'}</Text></Pressable></View></>:<View><Text style={s.title}>Remote service</Text><Text style={s.copy}>No local service area is required. Your request will be matched to providers who support remote work.</Text></View>}</>}
  {step===3&&<><Text style={s.title}>When do you need it?</Text><Text style={s.copy}>Dates and times are preferences, not guaranteed availability.</Text><Text style={s.label}>PREFERRED DATE</Text><TextInput value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" style={s.input}/><Text style={s.label}>PREFERRED TIME</Text><TextInput value={time} onChangeText={setTime} placeholder="e.g. 10:00" style={s.input}/><Text style={s.label}>BUDGET (OPTIONAL)</Text><TextInput value={budget} onChangeText={setBudget} placeholder="AUD" keyboardType="decimal-pad" style={s.input}/></>}
  {step===4&&<><Text style={s.title}>Check your request</Text><Text style={s.copy}>Nothing is submitted until you press Post request.</Text><Summary label="Service" value={serviceName||'General service request'}/><Summary label="Delivery" value={effectiveMode==='REMOTE'?'Remote / online':effectiveMode==='BOTH'?'Local + remote':'Local'}/><Summary label="Where" value={effectiveMode==='REMOTE'?'Remote — no local area required':suburb+', Sydney, NSW'}/>{effectiveMode==='LOCAL'&&<Summary label="Instant dispatch" value={location?'Location ready':'Unavailable until a precise location is provided'}/>}<Summary label="When" value={date||(time?'Flexible · '+time:'Flexible')}/><Summary label="Budget" value={budget?'$'+Number(budget).toFixed(2)+' AUD':'Not specified'}/></>}
  {!!error&&<Text style={s.error}>{error}</Text>}<View style={s.actions}>{step>1&&<Pressable disabled={busy} onPress={back} style={s.outline}><Text style={s.outlineText}>BACK</Text></Pressable>}{step<4?<Pressable onPress={next} style={[s.button,{flex:1}]}><Text style={s.buttonText}>CONTINUE</Text></Pressable>:<Pressable disabled={busy} onPress={()=>void submit()} style={[s.button,{flex:1}]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>POST REQUEST</Text>}</Pressable>}</View>
 </ScrollView></SafeAreaView>;
}
function Step({title,copy,label,value,onChange,placeholder,multiline}:{title:string;copy:string;label:string;value:string;onChange:(v:string)=>void;placeholder:string;multiline?:boolean}){return <><Text style={s.title}>{title}</Text><Text style={s.copy}>{copy}</Text><Text style={s.label}>{label}</Text><TextInput multiline={multiline} value={value} onChangeText={onChange} placeholder={placeholder} style={[s.input,multiline&&s.area]} maxLength={5000}/></>}
function Summary({label,value}:{label:string;value:string}){return <View style={s.summary}><Text style={s.summaryLabel}>{label}</Text><Text style={s.summaryValue}>{value}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:50},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},back:{fontSize:34,fontWeight:'300'},topTitle:{fontSize:16,fontWeight:'800'},step:{fontSize:10,fontWeight:'900',color:'#777'},progress:{height:5,borderRadius:5,backgroundColor:'#e3e0d9',overflow:'hidden'},progressFill:{height:5,backgroundColor:'#111'},selected:{backgroundColor:'#eeece7',borderRadius:16,padding:14,marginTop:16},selectedLabel:{fontSize:8,fontWeight:'900',letterSpacing:1.1,color:'#777'},selectedName:{fontSize:15,fontWeight:'800',marginTop:5},title:{fontSize:30,fontWeight:'900',letterSpacing:-1,marginTop:28},copy:{fontSize:13,lineHeight:20,color:'#777',marginTop:8,marginBottom:25},label:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:'#777',marginTop:15,marginBottom:7},input:{height:54,borderWidth:1,borderColor:'#dfdcd5',backgroundColor:'#fff',borderRadius:15,paddingHorizontal:15,fontSize:16},area:{height:150,paddingTop:15,textAlignVertical:'top'},modeRow:{flexDirection:'row',gap:8,marginTop:12},mode:{flex:1,height:48,borderRadius:13,borderWidth:1,borderColor:'#ddd8cf',alignItems:'center',justifyContent:'center'},modeActive:{backgroundColor:'#111',borderColor:'#111'},modeText:{fontSize:10,fontWeight:'900',color:'#666'},modeTextActive:{color:'#fff'},meta:{fontSize:11,color:'#777',marginTop:4,lineHeight:17},locationCard:{backgroundColor:'#eeece7',borderRadius:15,padding:15,marginTop:14},locationTitle:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#555'},locationButton:{minHeight:44,borderRadius:12,borderWidth:1,borderColor:'#cfcac1',alignItems:'center',justifyContent:'center',marginTop:12},locationButtonText:{fontSize:9,fontWeight:'900'},error:{color:'#b42318',fontSize:12,lineHeight:18,marginTop:12},actions:{flexDirection:'row',gap:10,marginTop:24},button:{height:54,borderRadius:15,backgroundColor:'#111',alignItems:'center',justifyContent:'center',marginTop:0,paddingHorizontal:18},buttonText:{color:'#fff',fontSize:11,fontWeight:'900',letterSpacing:.7},outline:{height:54,borderRadius:15,borderWidth:1,borderColor:'#d8d3ca',alignItems:'center',justifyContent:'center',paddingHorizontal:20},outlineText:{fontSize:10,fontWeight:'900'},summary:{backgroundColor:'#fff',borderRadius:15,borderWidth:1,borderColor:'#e5e2dc',padding:15,marginBottom:9},summaryLabel:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#777'},summaryValue:{fontSize:14,fontWeight:'700',marginTop:5,lineHeight:20},success:{flex:1,padding:28,justifyContent:'center',alignItems:'center'},check:{width:64,height:64,borderRadius:32,backgroundColor:'#e9e7e1',alignItems:'center',justifyContent:'center'}});
