import { useEffect,useMemo,useRef,useState } from 'react';
import { ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router,useLocalSearchParams } from 'expo-router';
import { createServiceRequest } from '@/lib/marketplace';
import { supabase } from '@/lib/supabase';
import { userFacingError } from '@/lib/errors';
import type { DeliveryMode } from '@/lib/taxonomy';
import { type ThemeColors,useAppTheme } from '@/lib/theme';

const DATE_RE=/^\d{4}-\d{2}-\d{2}$/;
const TIME_RE=/^([01]\d|2[0-3]):[0-5]\d$/;
function validDate(value:string){if(!DATE_RE.test(value))return false;const [y,m,d]=value.split('-').map(Number);const parsed=new Date(Date.UTC(y,m-1,d));return parsed.getUTCFullYear()===y&&parsed.getUTCMonth()===m-1&&parsed.getUTCDate()===d;}

export default function Request(){
 const {colors}=useAppTheme();const s=useMemo(()=>createStyles(colors),[colors]);
 const params=useLocalSearchParams<{serviceId?:string;mode?:string;description?:string}>();
 const serviceId=typeof params.serviceId==='string'?params.serviceId:'';
 const initialDescription=typeof params.description==='string'?params.description.trim().slice(0,5000):'';
 const [step,setStep]=useState(1);const [description,setDescription]=useState(initialDescription);const [suburb,setSuburb]=useState('');const [date,setDate]=useState('');const [time,setTime]=useState('');const [budget,setBudget]=useState('');const [mode,setMode]=useState<DeliveryMode>((params.mode==='REMOTE'||params.mode==='BOTH'||params.mode==='LOCAL')?params.mode:'LOCAL');const [serviceName,setServiceName]=useState('');const [serviceMode,setServiceMode]=useState<DeliveryMode|null>(null);const [serviceLoading,setServiceLoading]=useState(Boolean(serviceId));const [serviceValid,setServiceValid]=useState(!serviceId);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState(false);const submitRef=useRef(false);
 useEffect(()=>{let active=true;(async()=>{if(!serviceId){setServiceLoading(false);setServiceValid(true);return;}setServiceLoading(true);setServiceValid(false);const {data,error:e}=await supabase.from('services').select('name,delivery_mode').eq('id',serviceId).eq('active',true).maybeSingle();if(!active)return;if(e||!data){setError('The selected service is no longer available. Choose another service and try again.');setServiceLoading(false);return;}setServiceName(data.name);setServiceMode(data.delivery_mode as DeliveryMode);setServiceValid(true);setServiceLoading(false);if(data.delivery_mode==='REMOTE')setMode('REMOTE');else if(data.delivery_mode==='LOCAL')setMode('LOCAL');})().catch(()=>{if(active){setError('Could not load the selected service. Please try again.');setServiceLoading(false);}});return()=>{active=false}},[serviceId]);
 const effectiveMode=serviceMode==='BOTH'?mode:(serviceMode??mode);
 function next(){setError('');if(serviceId&&!serviceValid){setError('The selected service is unavailable. Go back and choose another service.');return;}if(step===1&&description.trim().length<5){setError('Tell businesses what you need in at least a few words.');return;}if(step===2&&effectiveMode==='LOCAL'&&!suburb.trim()){setError('Add the suburb where the work will happen.');return;}if(step===3){if(date&&!validDate(date)){setError('Use a valid date in YYYY-MM-DD format.');return;}if(time&&!TIME_RE.test(time)){setError('Use a valid 24-hour time in HH:MM format.');return;}if(budget&&(!Number.isFinite(Number(budget))||Number(budget)<0)){setError('Budget must be a valid non-negative amount.');return;}}setStep(value=>Math.min(4,value+1));}
 function back(){if(busy)return;setError('');setStep(value=>Math.max(1,value-1));}
 async function submit(){if(submitRef.current||busy||serviceLoading)return;if(serviceId&&!serviceValid){setError('The selected service is unavailable. Go back and choose another service.');return;}submitRef.current=true;setError('');setBusy(true);try{await createServiceRequest({serviceId:serviceId||undefined,description:description.trim(),suburb:effectiveMode==='REMOTE'?undefined:suburb.trim(),city:effectiveMode==='REMOTE'?undefined:'Sydney',state:effectiveMode==='REMOTE'?undefined:'NSW',preferredDate:date||undefined,preferredTime:time||undefined,budget:budget?Number(budget):undefined,deliveryMode:effectiveMode});setSuccess(true);}catch(e){setError(userFacingError(e,'We could not submit your request. Please retry.'))}finally{submitRef.current=false;setBusy(false)}}
 if(success)return <SafeAreaView style={s.safe}><View style={s.success}><View style={s.check}><Text style={{fontSize:28}}>✓</Text></View><Text style={s.title}>Request received.</Text><Text style={s.copy}>Everest will match your request against eligible verified businesses that support {effectiveMode==='REMOTE'?'remote delivery':effectiveMode==='LOCAL'?'local delivery':'the requested delivery mode'}.</Text><Pressable onPress={()=>router.replace('/activity')} style={s.button}><Text style={s.buttonText}>VIEW ACTIVITY</Text></Pressable></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled">
  <View style={s.top}><Pressable disabled={busy} onPress={()=>step>1?back():router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.topTitle}>Post a request</Text><Text style={s.step}>{step}/4</Text></View><View style={s.progress}><View style={[s.progressFill,{width:`${step*25}%`}]}/></View>
  {serviceLoading&&<View style={s.selected}><ActivityIndicator color={colors.brand}/><Text style={s.meta}>Loading selected service…</Text></View>}{!!serviceName&&!serviceLoading&&<View style={s.selected}><Text style={s.selectedLabel}>SELECTED SERVICE</Text><Text style={s.selectedName}>{serviceName}</Text><Text style={s.meta}>{serviceMode==='REMOTE'?'Remote':serviceMode==='BOTH'?'Local + remote':'Local'}</Text></View>}
  {step===1&&<Step title="What do you need?" copy="Start with the job. Everest uses your description and selected service to match eligible businesses." label="YOUR NEED" value={description} onChange={setDescription} placeholder="Example: I need a responsive website for my business." multiline/>}
  {step===2&&<>{serviceMode==='BOTH'&&<><Text style={s.title}>How should it be delivered?</Text><Text style={s.copy}>Choose whether you want the provider to work locally or remotely.</Text><View style={s.modeRow}>{(['LOCAL','REMOTE'] as DeliveryMode[]).map(item=><Pressable key={item} onPress={()=>setMode(item)} style={[s.mode,mode===item&&s.modeActive]}><Text style={[s.modeText,mode===item&&s.modeTextActive]}>{item}</Text></Pressable>)}</View></>}{effectiveMode==='LOCAL'?<><Text style={s.title}>Where is the job?</Text><Text style={s.copy}>Use the suburb where the work will happen.</Text><Text style={s.label}>SUBURB</Text><TextInput placeholderTextColor={colors.muted} value={suburb} onChangeText={setSuburb} placeholder="e.g. Greystanes" style={s.input} maxLength={120}/></>:<View><Text style={s.title}>Remote service</Text><Text style={s.copy}>No local service area is required. Your request will be matched to providers who support remote work.</Text></View>}</>}
  {step===3&&<><Text style={s.title}>When do you need it?</Text><Text style={s.copy}>Dates and times are preferences, not guaranteed availability.</Text><Text style={s.label}>PREFERRED DATE</Text><TextInput placeholderTextColor={colors.muted} value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" style={s.input} maxLength={10}/><Text style={s.label}>PREFERRED TIME</Text><TextInput placeholderTextColor={colors.muted} value={time} onChangeText={setTime} placeholder="e.g. 10:00" style={s.input} maxLength={5}/><Text style={s.label}>BUDGET (OPTIONAL)</Text><TextInput placeholderTextColor={colors.muted} value={budget} onChangeText={setBudget} placeholder="AUD" keyboardType="decimal-pad" style={s.input} maxLength={12}/></>}
  {step===4&&<><Text style={s.title}>Check your request</Text><Text style={s.copy}>Nothing is submitted until you press Post request.</Text><Summary label="Service" value={serviceName||'General service request'}/><Summary label="Delivery" value={effectiveMode==='REMOTE'?'Remote / online':effectiveMode==='BOTH'?'Local + remote':'Local'}/><Summary label="Where" value={effectiveMode==='REMOTE'?'Remote — no local area required':suburb.trim()+', Sydney, NSW'}/><Summary label="When" value={date?(date+(time?' · '+time:'')):(time?'Flexible · '+time:'Flexible')}/><Summary label="Budget" value={budget?'$'+Number(budget).toFixed(2)+' AUD':'Not specified'}/></>}
  {!!error&&<Text style={s.error}>{error}</Text>}<View style={s.actions}>{step>1&&<Pressable disabled={busy} onPress={back} style={[s.outline,busy&&s.disabled]}><Text style={s.outlineText}>BACK</Text></Pressable>}{step<4?<Pressable disabled={serviceLoading||busy} onPress={next} style={[s.button,{flex:1},(serviceLoading||busy)&&s.disabled]}><Text style={s.buttonText}>CONTINUE</Text></Pressable>:<Pressable disabled={busy||serviceLoading||!serviceValid} onPress={()=>void submit()} style={[s.button,{flex:1},(busy||serviceLoading||!serviceValid)&&s.disabled]}>{busy?<ActivityIndicator color={colors.onBrand}/>:<Text style={s.buttonText}>POST REQUEST</Text>}</Pressable>}</View>
 </ScrollView></SafeAreaView>;
}
function Step({title,copy,label,value,onChange,placeholder,multiline}:{title:string;copy:string;label:string;value:string;onChange:(v:string)=>void;placeholder:string;multiline?:boolean}){const {colors}=useAppTheme();const s=createStyles(colors);return <><Text style={s.title}>{title}</Text><Text style={s.copy}>{copy}</Text><Text style={s.label}>{label}</Text><TextInput placeholderTextColor={colors.muted} multiline={multiline} value={value} onChangeText={onChange} placeholder={placeholder} style={[s.input,multiline&&s.area]} maxLength={5000}/></>}
function Summary({label,value}:{label:string;value:string}){const {colors}=useAppTheme();const s=createStyles(colors);return <View style={s.summary}><Text style={s.summaryLabel}>{label}</Text><Text style={s.summaryValue}>{value}</Text></View>}
const createStyles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.canvas},page:{padding:20,paddingBottom:50,maxWidth:760,width:'100%',alignSelf:'center'},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},back:{fontSize:34,fontWeight:'300',color:c.text},topTitle:{fontSize:16,fontWeight:'800',color:c.text},step:{fontSize:10,fontWeight:'900',color:c.muted},progress:{height:5,borderRadius:5,backgroundColor:c.border,overflow:'hidden'},progressFill:{height:5,backgroundColor:c.brand},selected:{backgroundColor:c.soft,borderRadius:16,padding:14,marginTop:16,alignItems:'flex-start'},selectedLabel:{fontSize:8,fontWeight:'900',letterSpacing:1.1,color:c.muted},selectedName:{fontSize:15,fontWeight:'800',marginTop:5,color:c.text},title:{fontSize:30,fontWeight:'900',letterSpacing:-1,marginTop:28,color:c.text},copy:{fontSize:13,lineHeight:20,color:c.textSecondary,marginTop:8,marginBottom:25},label:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:c.muted,marginTop:15,marginBottom:7},input:{height:54,borderWidth:1,borderColor:c.border,backgroundColor:c.input,color:c.text,borderRadius:15,paddingHorizontal:15,fontSize:14},area:{height:150,paddingTop:15,textAlignVertical:'top'},modeRow:{flexDirection:'row',gap:8,marginTop:12},mode:{flex:1,height:48,borderRadius:13,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center'},modeActive:{backgroundColor:c.brand,borderColor:c.brand},modeText:{fontSize:10,fontWeight:'900',color:c.muted},modeTextActive:{color:c.onBrand},meta:{fontSize:11,color:c.muted,marginTop:4},error:{color:c.danger,fontSize:12,lineHeight:18,marginTop:12},actions:{flexDirection:'row',gap:10,marginTop:24},button:{height:54,borderRadius:15,backgroundColor:c.brand,alignItems:'center',justifyContent:'center',marginTop:0,paddingHorizontal:18},buttonText:{color:c.onBrand,fontSize:11,fontWeight:'900',letterSpacing:.7},outline:{height:54,borderRadius:15,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center',paddingHorizontal:20},outlineText:{fontSize:10,fontWeight:'900',color:c.text},disabled:{opacity:.5},summary:{backgroundColor:c.surface,borderRadius:15,borderWidth:1,borderColor:c.border,padding:15,marginBottom:9},summaryLabel:{fontSize:9,fontWeight:'900',letterSpacing:1,color:c.muted},summaryValue:{fontSize:14,fontWeight:'700',marginTop:5,lineHeight:20,color:c.text},success:{flex:1,padding:28,justifyContent:'center',alignItems:'center'},check:{width:64,height:64,borderRadius:32,backgroundColor:c.soft,alignItems:'center',justifyContent:'center'}});
