import { useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';

export default function Request(){
 const [step,setStep]=useState(1);const [description,setDescription]=useState('');const [suburb,setSuburb]=useState('');const [date,setDate]=useState('');const [time,setTime]=useState('');const [budget,setBudget]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState(false);
 function next(){setError('');if(step===1&&description.trim().length<5){setError('Tell businesses what you need in at least a few words.');return;}if(step===2&&!suburb.trim()){setError('Add your suburb so Everest can match local businesses.');return;}if(step===3&&budget&&(!Number.isFinite(Number(budget))||Number(budget)<0)){setError('Budget must be a valid positive amount.');return;}setStep(value=>Math.min(4,value+1));}
 function back(){setError('');setStep(value=>Math.max(1,value-1));}
 async function submit(){setError('');setBusy(true);try{const {createServiceRequest}=await import('@/lib/marketplace');await createServiceRequest({description,suburb,city:'Sydney',state:'NSW',preferredDate:date||undefined,preferredTime:time||undefined,budget:budget?Number(budget):undefined});setSuccess(true);}catch(e){setError(e instanceof Error?e.message:'We could not submit your request. Please retry.')}finally{setBusy(false)}}
 if(success)return <SafeAreaView style={s.safe}><View style={s.success}><View style={s.check}><Text style={{fontSize:28}}>✓</Text></View><Text style={s.title}>Request received.</Text><Text style={s.copy}>Everest will match your request against eligible verified businesses. You’ll see real opportunities and quotes when businesses respond.</Text><Pressable onPress={()=>router.replace('/activity')} style={s.button}><Text style={s.buttonText}>VIEW ACTIVITY</Text></Pressable></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
  <View style={s.top}><Pressable onPress={()=>step>1?back():router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.topTitle}>Post a request</Text><Text style={s.step}>{step}/4</Text></View>
  <View style={s.progress}><View style={[s.progressFill,{width:`${step*25}%`}]}/></View>
  {step===1&&<Step title="What do you need?" copy="Start with the job. Everest uses your description to match eligible businesses." label="YOUR NEED" value={description} onChange={setDescription} placeholder="Example: Full interior and exterior car detail for a BMW." multiline/>}
  {step===2&&<Step title="Where is the job?" copy="Use the suburb where the work will happen." label="SUBURB" value={suburb} onChange={setSuburb} placeholder="e.g. Rooty Hill"/>}
  {step===3&&<><Text style={s.title}>When do you need it?</Text><Text style={s.copy}>Dates and times are preferences, not guaranteed availability.</Text><Text style={s.label}>PREFERRED DATE</Text><TextInput value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" style={s.input}/><Text style={s.label}>PREFERRED TIME</Text><TextInput value={time} onChangeText={setTime} placeholder="e.g. 10:00" style={s.input}/><Text style={s.label}>BUDGET (OPTIONAL)</Text><TextInput value={budget} onChangeText={setBudget} placeholder="AUD" keyboardType="decimal-pad" style={s.input}/></>}
  {step===4&&<><Text style={s.title}>Check your request</Text><Text style={s.copy}>Nothing is submitted until you press Post request.</Text><Summary label="What" value={description}/><Summary label="Where" value={suburb+', Sydney, NSW'}/><Summary label="When" value={date||'Flexible' + (time?' · '+time:'')}/><Summary label="Budget" value={budget?'$'+Number(budget).toFixed(2)+' AUD':'Not specified'}/><View style={s.mediaNote}><Text style={s.mediaTitle}>Photos or video</Text><Text style={s.mediaCopy}>Media attachments are not enabled until the secure private storage layer is configured. No fake upload control is shown.</Text></View></>}
  {!!error&&<Text style={s.error}>{error}</Text>}
  <View style={s.actions}>{step>1&&<Pressable disabled={busy} onPress={back} style={s.outline}><Text style={s.outlineText}>BACK</Text></Pressable>}{step<4?<Pressable onPress={next} style={[s.button,{flex:1}]}><Text style={s.buttonText}>CONTINUE</Text></Pressable>:<Pressable disabled={busy} onPress={()=>void submit()} style={[s.button,{flex:1}]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>POST REQUEST</Text>}</Pressable>}</View>
 </ScrollView></SafeAreaView>;
}
function Step({title,copy,label,value,onChange,placeholder,multiline}:{title:string;copy:string;label:string;value:string;onChange:(v:string)=>void;placeholder:string;multiline?:boolean}){return <><Text style={s.title}>{title}</Text><Text style={s.copy}>{copy}</Text><Text style={s.label}>{label}</Text><TextInput multiline={multiline} value={value} onChangeText={onChange} placeholder={placeholder} style={[s.input,multiline&&s.area]} maxLength={5000}/></>}
function Summary({label,value}:{label:string;value:string}){return <View style={s.summary}><Text style={s.summaryLabel}>{label}</Text><Text style={s.summaryValue}>{value}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:50},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},back:{fontSize:34,fontWeight:'300'},topTitle:{fontSize:16,fontWeight:'800'},step:{fontSize:10,fontWeight:'900',color:'#777'},progress:{height:5,borderRadius:5,backgroundColor:'#e3e0d9',overflow:'hidden'},progressFill:{height:5,backgroundColor:'#111'},title:{fontSize:30,fontWeight:'900',letterSpacing:-1,marginTop:28},copy:{fontSize:13,lineHeight:20,color:'#777',marginTop:8,marginBottom:25},label:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:'#777',marginTop:15,marginBottom:7},input:{height:54,borderWidth:1,borderColor:'#dfdcd5',backgroundColor:'#fff',borderRadius:15,paddingHorizontal:15,fontSize:14},area:{height:150,paddingTop:15,textAlignVertical:'top'},error:{color:'#b42318',fontSize:12,lineHeight:18,marginTop:12},actions:{flexDirection:'row',gap:10,marginTop:24},button:{height:54,borderRadius:15,backgroundColor:'#111',alignItems:'center',justifyContent:'center',marginTop:0,paddingHorizontal:18},buttonText:{color:'#fff',fontSize:11,fontWeight:'900',letterSpacing:.7},outline:{height:54,borderRadius:15,borderWidth:1,borderColor:'#d8d3ca',alignItems:'center',justifyContent:'center',paddingHorizontal:20},outlineText:{fontSize:10,fontWeight:'900'},summary:{backgroundColor:'#fff',borderRadius:15,borderWidth:1,borderColor:'#e5e2dc',padding:15,marginBottom:9},summaryLabel:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#777'},summaryValue:{fontSize:14,fontWeight:'700',marginTop:5,lineHeight:20},mediaNote:{marginTop:8,backgroundColor:'#efede8',borderRadius:15,padding:15},mediaTitle:{fontSize:12,fontWeight:'800'},mediaCopy:{fontSize:11,lineHeight:17,color:'#777',marginTop:4},success:{flex:1,padding:28,justifyContent:'center',alignItems:'center'},check:{width:64,height:64,borderRadius:32,backgroundColor:'#e9e7e1',alignItems:'center',justifyContent:'center'}});
