import { useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import type { ServiceRequest } from '@/lib/types';
import { userFacingError } from '@/lib/errors';
export default function Requests(){const [items,setItems]=useState<ServiceRequest[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [hasLoaded,setHasLoaded]=useState(false);const [error,setError]=useState('');
async function load(refresh=false){if(refresh)setRefreshing(true);else if(!hasLoaded)setLoading(true);try{setError('');const {myRequests}=await import('@/lib/marketplace');setItems(await myRequests());setHasLoaded(true)}catch(e){setError(userFacingError(e,'We could not load your requests right now. Please try again.'))}finally{setLoading(false);setRefreshing(false)}}
useEffect(()=>{void load()},[]);
const stale=Boolean(error&&hasLoaded);
return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)}/>}><Text style={s.eyebrow}>EVEREST LOCAL</Text><View style={s.header}><Text style={s.title}>Requests</Text><Pressable disabled={refreshing} onPress={()=>router.push('/request')} style={[s.add,refreshing&&s.disabled]}><Text style={s.addText}>NEW</Text></Pressable></View>{stale&&<View style={s.warning}><Text style={s.warningTitle}>Your requests may be out of date.</Text><Text style={s.meta}>We couldn’t refresh them, so the last successfully loaded requests are still shown.</Text><Pressable style={s.retry} disabled={refreshing} onPress={()=>void load(true)}><Text style={s.retryText}>{refreshing?'REFRESHING…':'RETRY REQUESTS'}</Text></Pressable></View>}{loading?<ActivityIndicator style={{marginTop:20}}/>:error&&!hasLoaded?<View style={s.empty}><Text style={s.emptyTitle}>We couldn't load your requests.</Text><Text style={s.meta}>Your requests are still safe. Try again.</Text><Pressable style={s.button} onPress={()=>void load()}><Text style={s.buttonText}>RETRY</Text></Pressable></View>:items.length?items.map(r=><View style={s.card} key={r.id}><View style={s.row}><Text style={s.status}>{r.status.replaceAll('_',' ')}</Text><Text style={s.date}>{new Date(r.created_at).toLocaleDateString()}</Text></View><Text style={s.description}>{r.description}</Text><Text style={s.meta}>{[r.suburb,r.city,r.state].filter(Boolean).join(', ')}</Text>{r.preferred_date&&<Text style={s.meta}>Preferred: {r.preferred_date}{r.preferred_time?` at ${r.preferred_time}`:''}</Text>}{r.status==='QUOTING'&&<Pressable disabled={refreshing} style={[s.button,refreshing&&s.disabled]} onPress={()=>router.push({pathname:'/quotes',params:{requestId:r.id}})}><Text style={s.buttonText}>VIEW QUOTES</Text></Pressable>}</View>):<View style={s.empty}><Text style={s.emptyTitle}>You haven’t requested a service yet.</Text><Text style={s.meta}>Create a request and Everest will match eligible verified businesses.</Text><Pressable disabled={refreshing} style={[s.button,refreshing&&s.disabled]} onPress={()=>router.push('/request')}><Text style={s.buttonText}>REQUEST A SERVICE</Text></Pressable></View>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:50},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:'#777'},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:7},title:{fontSize:31,fontWeight:'900'},add:{height:38,paddingHorizontal:14,borderRadius:12,backgroundColor:'#111',alignItems:'center',justifyContent:'center'},addText:{color:'#fff',fontSize:9,fontWeight:'900'},card:{backgroundColor:'#fff',borderRadius:17,borderWidth:1,borderColor:'#e5e2dc',padding:17,marginTop:10},row:{flexDirection:'row',justifyContent:'space-between'},status:{fontSize:9,fontWeight:'900'},date:{fontSize:10,color:'#777'},description:{fontSize:14,fontWeight:'800',lineHeight:20,marginTop:11},meta:{fontSize:11,color:'#777',marginTop:5},button:{height:46,borderRadius:13,backgroundColor:'#111',paddingHorizontal:18,alignItems:'center',justifyContent:'center',marginTop:14},buttonText:{color:'#fff',fontSize:10,fontWeight:'900'},empty:{backgroundColor:'#fff',borderRadius:20,padding:28,alignItems:'center',marginTop:18},emptyTitle:{fontSize:16,fontWeight:'800',textAlign:'center'},warning:{backgroundColor:'#fff8e8',borderWidth:1,borderColor:'#ead9ae',borderRadius:16,padding:15,marginTop:14},warningTitle:{fontSize:13,fontWeight:'900',color:'#6b4d00'},retry:{alignSelf:'flex-start',marginTop:10,paddingVertical:7,paddingHorizontal:10,borderRadius:9,backgroundColor:'#111'},retryText:{color:'#fff',fontSize:9,fontWeight:'900'},disabled:{opacity:.55}});