import { useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { createReview,reviewTargets,type ReviewTarget } from '@/lib/reviews';

export default function Reviews(){
 const [targets,setTargets]=useState<ReviewTarget[]>([]);const [loading,setLoading]=useState(true);const [selected,setSelected]=useState<ReviewTarget|null>(null);const [rating,setRating]=useState(5);const [body,setBody]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');
 async function load(){setLoading(true);setError('');try{setTargets(await reviewTargets())}catch(e){setError(e instanceof Error?e.message:'Unable to load review opportunities.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function submit(){if(!selected||busy)return;setBusy(true);setError('');setSuccess('');try{await createReview({businessId:selected.businessId,bookingId:selected.kind==='SERVICE'?selected.referenceId:undefined,orderId:selected.kind==='PRODUCT'?selected.referenceId:undefined,productId:selected.productId,rating,body});setSuccess('Review submitted and linked to your completed transaction.');setSelected(null);setBody('');await load()}catch(e){setError(e instanceof Error?e.message:'Review could not be submitted.')}finally{setBusy(false)}}
 if(selected)return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Pressable onPress={()=>setSelected(null)}><Text style={s.back}>‹ Reviews</Text></Pressable><Text style={s.title}>Leave a review</Text><Text style={s.meta}>{selected.kind==='SERVICE'?'Service booking':'Product purchase'} · {selected.businessName}</Text><Text style={s.label}>Rating</Text><View style={s.stars}>{[1,2,3,4,5].map(value=><Pressable key={value} onPress={()=>setRating(value)} accessibilityLabel={`${value} stars`}><Text style={[s.star,rating>=value&&s.starActive]}>★</Text></Pressable>)}</View><Text style={s.label}>Optional feedback</Text><TextInput value={body} onChangeText={setBody} placeholder="Tell other customers about your experience…" multiline maxLength={2000} style={s.input}/><Pressable disabled={busy} onPress={()=>void submit()} style={s.button}><Text style={s.buttonText}>{busy?'SUBMITTING…':'SUBMIT REVIEW'}</Text></Pressable>{!!error&&<Text style={s.error}>{error}</Text>}</ScrollView></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.eyebrow}>EVEREST LOCAL</Text><Text style={s.title}>Reviews</Text><Text style={s.copy}>Reviews can only be submitted for completed transactions.</Text>{success&&<Text style={s.success}>{success}</Text>}{loading?<ActivityIndicator/>:error?<Text style={s.error}>{error}</Text>:targets.length?targets.map(target=><View style={s.card} key={target.id}><Text style={s.cardTitle}>{target.kind==='SERVICE'?'Completed service':'Completed product purchase'}</Text><Text style={s.meta}>{target.businessName}</Text>{target.reviewed?<Text style={s.done}>REVIEW SUBMITTED</Text>:<Pressable onPress={()=>setSelected(target)} style={s.outline}><Text style={s.outlineText}>LEAVE REVIEW</Text></Pressable>}</View>):<View style={s.empty}><Text style={s.emptyTitle}>Nothing to review yet.</Text><Text style={s.meta}>Completed bookings and product purchases will appear here.</Text></View>}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:50},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:2,color:'#777'},back:{fontSize:14,fontWeight:'800',marginBottom:18},title:{fontSize:31,fontWeight:'900',marginBottom:8},copy:{fontSize:13,lineHeight:20,color:'#777',marginBottom:20},meta:{fontSize:11,color:'#777',marginTop:5},label:{fontSize:11,fontWeight:'900',marginTop:24,marginBottom:8},stars:{flexDirection:'row',gap:8},star:{fontSize:34,color:'#d8d3ca'},starActive:{color:'#111'},input:{minHeight:120,borderWidth:1,borderColor:'#dfdcd5',borderRadius:15,padding:14,fontSize:14,textAlignVertical:'top',backgroundColor:'#fff'},button:{height:48,borderRadius:13,backgroundColor:'#111',alignItems:'center',justifyContent:'center',marginTop:14},buttonText:{color:'#fff',fontSize:10,fontWeight:'900'},card:{backgroundColor:'#fff',borderRadius:17,borderWidth:1,borderColor:'#e5e2dc',padding:17,marginBottom:10},cardTitle:{fontSize:14,fontWeight:'800'},outline:{height:44,borderRadius:12,borderWidth:1,borderColor:'#d8d3ca',alignItems:'center',justifyContent:'center',marginTop:13},outlineText:{fontSize:9,fontWeight:'900'},done:{fontSize:9,fontWeight:'900',marginTop:13},empty:{backgroundColor:'#fff',borderRadius:19,padding:28,alignItems:'center'},emptyTitle:{fontSize:16,fontWeight:'800'},error:{fontSize:12,color:'#b42318',marginTop:12},success:{fontSize:12,marginBottom:15}});