import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import type { MarketplaceBusiness, Product } from '@/lib/types';
import { mySavedBusinesses, mySavedProducts, setBusinessSaved, setProductSaved } from '@/lib/marketplace';

export default function Saved(){
 const [businesses,setBusinesses]=useState<MarketplaceBusiness[]>([]);
 const [products,setProducts]=useState<Product[]>([]);
 const [loading,setLoading]=useState(true);
 const [refreshing,setRefreshing]=useState(false);
 const [error,setError]=useState('');
 const [busy,setBusy]=useState<string|null>(null);

 const load=useCallback(async()=>{setError('');try{const [nextBusinesses,nextProducts]=await Promise.all([mySavedBusinesses(),mySavedProducts()]);setBusinesses(nextBusinesses);setProducts(nextProducts);}catch(e){setError(e instanceof Error?e.message:'We could not load your saved items. Please try again.');}finally{setLoading(false);setRefreshing(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const refresh=()=>{setRefreshing(true);void load();};
 const removeBusiness=async(id:string)=>{setBusy(id);setError('');try{await setBusinessSaved(id,false);setBusinesses(items=>items.filter(item=>item.id!==id));}catch(e){setError(e instanceof Error?e.message:'Could not remove that saved business.');}finally{setBusy(null);}};
 const removeProduct=async(id:string)=>{setBusy(id);setError('');try{await setProductSaved(id,false);setProducts(items=>items.filter(item=>item.id!==id));}catch(e){setError(e instanceof Error?e.message:'Could not remove that saved product.');}finally{setBusy(null);}};
 const empty=!businesses.length&&!products.length;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>}> 
   <View style={s.header}><Pressable onPress={()=>router.back()} accessibilityLabel="Go back"><Ionicons name="arrow-back" size={23}/></Pressable><View style={s.headerCopy}><Text style={s.title}>Saved</Text><Text style={s.subtitle}>Your businesses and products, kept in one place.</Text></View><View style={{width:23}}/></View>
   {loading?<ActivityIndicator style={{marginTop:60}}/>:<>
     {error?<View style={s.errorCard}><Text style={s.errorTitle}>Couldn’t load saved items</Text><Text style={s.errorText}>{error}</Text><Pressable style={s.retry} onPress={()=>{setLoading(true);void load();}}><Text style={s.retryText}>TRY AGAIN</Text></Pressable></View>:null}
     {!error&&empty?<View style={s.empty}><View style={s.emptyIcon}><Ionicons name="bookmark-outline" size={28}/></View><Text style={s.emptyTitle}>Nothing saved yet</Text><Text style={s.emptyText}>Save a business or product while browsing and it will appear here.</Text><Pressable style={s.primary} onPress={()=>router.replace('/')}><Text style={s.primaryText}>START EXPLORING</Text></Pressable></View>:null}
     {businesses.length>0?<Section title="Businesses" icon="storefront-outline">{businesses.map(item=><View style={s.card} key={item.id}><Pressable style={s.cardMain} onPress={()=>router.push({pathname:'/business-profile',params:{id:item.id}})}><View style={s.icon}><Ionicons name="storefront-outline" size={21}/></View><View style={s.cardCopy}><Text style={s.cardTitle}>{item.name}</Text><Text style={s.cardMeta}>{item.suburb||item.city||'Local business'}{item.verification_status==='VERIFIED'?' · Verified':''}</Text>{item.description?<Text numberOfLines={2} style={s.description}>{item.description}</Text>:null}</View></Pressable><Pressable style={s.remove} disabled={busy===item.id} onPress={()=>void removeBusiness(item.id)} accessibilityLabel={`Remove ${item.name} from saved businesses`}>{busy===item.id?<ActivityIndicator size="small"/>:<Ionicons name="bookmark" size={20}/>}</Pressable></View>)}</Section>:null}
     {products.length>0?<Section title="Products" icon="bag-handle-outline">{products.map(item=><View style={s.card} key={item.id}><Pressable style={s.cardMain} onPress={()=>router.push({pathname:'/product',params:{id:item.id}})}><View style={s.icon}><Ionicons name="bag-handle-outline" size={21}/></View><View style={s.cardCopy}><Text style={s.cardTitle}>{item.name}</Text><Text style={s.cardMeta}>{item.sale_price??item.price>0?`$${(item.sale_price??item.price).toFixed(2)}`:'Price unavailable'}{item.status==='OUT_OF_STOCK'?' · Out of stock':''}</Text>{item.description?<Text numberOfLines={2} style={s.description}>{item.description}</Text>:null}</View></Pressable><Pressable style={s.remove} disabled={busy===item.id} onPress={()=>void removeProduct(item.id)} accessibilityLabel={`Remove ${item.name} from saved products`}>{busy===item.id?<ActivityIndicator size="small"/>:<Ionicons name="bookmark" size={20}/>}</Pressable></View>)}</Section>:null}
   </>}
 </ScrollView></SafeAreaView>;
}
function Section({title,icon,children}:{title:string;icon:'storefront-outline'|'bag-handle-outline';children:React.ReactNode}){return <View style={s.section}><View style={s.sectionHeader}><Ionicons name={icon} size={19}/><Text style={s.sectionTitle}>{title}</Text></View>{children}</View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20,paddingBottom:50},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},headerCopy:{alignItems:'center',flex:1,paddingHorizontal:14},title:{fontSize:21,fontWeight:'900'},subtitle:{fontSize:11,color:'#777',marginTop:4,textAlign:'center'},section:{marginTop:28},sectionHeader:{flexDirection:'row',alignItems:'center',gap:8,marginBottom:9},sectionTitle:{fontSize:18,fontWeight:'900'},card:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e5e2dc',borderRadius:17,padding:13,marginTop:9,flexDirection:'row',alignItems:'center'},cardMain:{flex:1,flexDirection:'row',alignItems:'center',minWidth:0},icon:{width:44,height:44,borderRadius:14,backgroundColor:'#f0eee9',alignItems:'center',justifyContent:'center'},cardCopy:{flex:1,marginLeft:12,minWidth:0},cardTitle:{fontSize:14,fontWeight:'800'},cardMeta:{fontSize:11,color:'#666',marginTop:3},description:{fontSize:11,color:'#888',lineHeight:16,marginTop:5},remove:{width:40,height:40,alignItems:'center',justifyContent:'center',marginLeft:6},empty:{alignItems:'center',paddingHorizontal:20,paddingTop:90},emptyIcon:{width:64,height:64,borderRadius:22,backgroundColor:'#e9e6df',alignItems:'center',justifyContent:'center'},emptyTitle:{fontSize:20,fontWeight:'900',marginTop:18},emptyText:{fontSize:12,color:'#777',lineHeight:19,textAlign:'center',marginTop:7,maxWidth:320},primary:{backgroundColor:'#151515',borderRadius:14,paddingVertical:13,paddingHorizontal:18,marginTop:20},primaryText:{color:'#fff',fontSize:10,fontWeight:'900',letterSpacing:.7},errorCard:{backgroundColor:'#fff0ed',borderWidth:1,borderColor:'#f2c8c1',borderRadius:16,padding:16,marginTop:22},errorTitle:{fontSize:14,fontWeight:'900'},errorText:{fontSize:12,color:'#7a3b34',lineHeight:18,marginTop:5},retry:{alignSelf:'flex-start',marginTop:12,borderWidth:1,borderColor:'#b75b4f',borderRadius:10,paddingVertical:9,paddingHorizontal:12},retryText:{fontSize:10,fontWeight:'900'}});
