import { useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { searchBusinesses, searchProducts } from '@/lib/marketplace';
import type { MarketplaceBusiness, Product } from '@/lib/types';
export default function Search(){const [q,setQ]=useState('');const [businesses,setBusinesses]=useState<MarketplaceBusiness[]>([]);const [products,setProducts]=useState<Product[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{const timer=setTimeout(()=>{void runSearch()},300);return()=>clearTimeout(timer)},[q]);
 async function runSearch(){setLoading(true);setError('');try{const [b,p]=await Promise.all([searchBusinesses(q),searchProducts(q)]);setBusinesses(b);setProducts(p)}catch(e){setError(e instanceof Error?e.message:'Search is temporarily unavailable.')}finally{setLoading(false)}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.eyebrow}>EVEREST LOCAL</Text><Text style={s.title}>Search local</Text><View style={s.search}><Ionicons name="search" size={20} color="#777"/><TextInput autoFocus value={q} onChangeText={setQ} placeholder="Services, businesses or products" placeholderTextColor="#888" style={s.input} returnKeyType="search" onSubmitEditing={()=>void runSearch()}/></View>{loading?<ActivityIndicator style={{marginTop:35}}/>:error?<View style={s.empty}><Text style={s.emptyTitle}>Search unavailable</Text><Text style={s.emptyCopy}>{error}</Text></View>:<><Text style={s.heading}>Businesses {businesses.length>0?`(${businesses.length})`:''}</Text>{businesses.length?businesses.map(b=><View style={s.result} key={b.id}><View style={s.icon}><Ionicons name="business-outline" size={22}/></View><View style={{flex:1}}><Text style={s.resultTitle}>{b.name}</Text><Text style={s.resultCopy}>{[b.suburb,b.city,b.state].filter(Boolean).join(', ')||'Local business'}</Text>{b.verification_status==='VERIFIED'&&<Text style={s.verified}>✓ VERIFIED</Text>}</View></View>):<Text style={s.muted}>No verified businesses found in this area yet.</Text>}<Text style={s.heading}>Products {products.length?`(${products.length})`:''}</Text>{products.length?products.map(p=><View style={s.result} key={p.id}><View style={s.icon}><Ionicons name="cube-outline" size={22}/></View><View style={{flex:1}}><Text style={s.resultTitle}>{p.name}</Text><Text style={s.resultCopy}>${Number(p.sale_price??p.price).toFixed(2)} AUD</Text></View></View>):<Text style={s.muted}>No products are available here yet.</Text>}</>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7f4'},page:{padding:20},eyebrow:{fontSize:10,fontWeight:'800',letterSpacing:2,color:'#777'},title:{fontSize:30,fontWeight:'800',marginTop:5,marginBottom:20},search:{height:58,borderRadius:17,backgroundColor:'#fff',borderWidth:1,borderColor:'#e5e2dc',paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:10},input:{flex:1,fontSize:15,color:'#111'},heading:{fontSize:19,fontWeight:'800',marginTop:30,marginBottom:12},empty:{backgroundColor:'#fff',borderRadius:20,borderWidth:1,borderColor:'#e5e2dc',padding:30,alignItems:'center'},emptyTitle:{fontSize:16,fontWeight:'800'},emptyCopy:{fontSize:13,lineHeight:20,color:'#777',textAlign:'center',marginTop:7},result:{backgroundColor:'#fff',borderRadius:17,borderWidth:1,borderColor:'#e5e2dc',padding:14,flexDirection:'row',alignItems:'center',gap:12,marginBottom:9},icon:{width:48,height:48,borderRadius:14,backgroundColor:'#f0eee9',alignItems:'center',justifyContent:'center'},resultTitle:{fontSize:14,fontWeight:'800'},resultCopy:{fontSize:12,color:'#777',marginTop:4},verified:{fontSize:9,fontWeight:'900',letterSpacing:.7,marginTop:5},muted:{fontSize:13,color:'#777',lineHeight:20}});