import {useEffect,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,Switch,Text,View} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {router} from 'expo-router';
import {SafeAreaView} from 'react-native-safe-area-context';
import {getSocialPreferences,setSocialPreferences,type SocialPreferences} from '@/lib/connections';
import {type ThemeColors,useAppTheme} from '@/lib/theme';

const options={profile_visibility:['PUBLIC','LIMITED','PRIVATE'],connection_requests:['EVERYONE','MUTUALS','NOBODY'],message_requests:['EVERYONE','CONNECTIONS','NOBODY'],connection_list_visibility:['EVERYONE','CONNECTIONS','ONLY_ME']} as const;
export default function SocialPrivacy(){const {colors:c}=useAppTheme();const [v,setV]=useState<SocialPreferences|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{void getSocialPreferences().then(setV).catch(e=>setError(e instanceof Error?e.message:'Privacy settings could not be loaded.'))},[]);
 async function save(next:SocialPreferences){setV(next);setBusy(true);setError('');try{await setSocialPreferences(next)}catch(e){setError(e instanceof Error?e.message:'Privacy settings could not be saved.')}finally{setBusy(false)}}
 if(!v)return <SafeAreaView style={{flex:1,backgroundColor:c.canvas}}><ActivityIndicator style={{marginTop:80}} color={c.text}/></SafeAreaView>;
 const segmented=(key:'profile_visibility'|'connection_requests'|'message_requests'|'connection_list_visibility',title:string)=><View style={{marginTop:22}}><Text style={{fontSize:12,fontWeight:'900',color:c.text,marginBottom:9}}>{title}</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:7}}>{options[key].map(o=><Pressable key={o} onPress={()=>void save({...v,[key]:o} as SocialPreferences)} style={{paddingHorizontal:12,paddingVertical:9,borderRadius:11,borderWidth:1,borderColor:v[key]===o?c.brand:c.border,backgroundColor:v[key]===o?c.brand:c.surface}}><Text style={{fontSize:9,fontWeight:'900',color:v[key]===o?c.onBrand:c.text}}>{o.replaceAll('_',' ')}</Text></Pressable>)}</View></View>;
 return <SafeAreaView style={{flex:1,backgroundColor:c.canvas}}><ScrollView contentContainerStyle={{padding:20,paddingBottom:60,maxWidth:760,width:'100%',alignSelf:'center'}}><View style={{flexDirection:'row',alignItems:'center',gap:14}}><Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={23} color={c.text}/></Pressable><Text style={{fontSize:24,fontWeight:'900',color:c.text}}>Social privacy</Text></View><Text style={{fontSize:12,lineHeight:18,color:c.muted,marginTop:8}}>These controls are enforced by database RPCs and discovery queries, not just hidden in the UI.</Text>{segmented('profile_visibility','Profile visibility')}{segmented('connection_requests','Who can send connection requests')}{segmented('message_requests','Who can send message requests')}{segmented('connection_list_visibility','Who can see your connections')}<Row title="Appear in People search" value={v.search_visible} onChange={x=>void save({...v,search_visible:x})} c={c}/><Row title="Show suburb on public profile" value={v.show_location} onChange={x=>void save({...v,show_location:x})} c={c}/>{busy?<Text style={{fontSize:10,color:c.muted,marginTop:12}}>Saving…</Text>:null}{error?<Text style={{fontSize:12,color:c.danger,marginTop:12}}>{error}</Text>:null}</ScrollView></SafeAreaView>}
function Row({title,value,onChange,c}:{title:string;value:boolean;onChange:(v:boolean)=>void;c:ThemeColors}){return <View style={{marginTop:22,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:14}}><Text style={{fontSize:12,fontWeight:'800',color:c.text,flex:1}}>{title}</Text><Switch value={value} onValueChange={onChange}/></View>}
