import {ScrollView,Text,View} from 'react-native';import {SafeAreaView} from 'react-native-safe-area-context';import {useAppTheme} from '@/lib/theme';
export default function Terms(){const{colors:c}=useAppTheme();const s={safe:{flex:1,backgroundColor:c.canvas},page:{padding:24,paddingBottom:60,maxWidth:760,width:'100%' as const,alignSelf:'center' as const},eyebrow:{fontSize:10,fontWeight:'900' as const,letterSpacing:2,color:c.muted},title:{fontSize:34,fontWeight:'900' as const,marginTop:8,color:c.text},updated:{fontSize:12,color:c.muted,marginTop:7}};return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.eyebrow}>EVEREST LOCAL</Text><Text style={s.title}>Terms of Service</Text><Text style={s.updated}>Effective 26 September 2026</Text>
<Section title="1. Marketplace role">Everest Local provides software that helps customers discover and transact with participating businesses and sellers. Unless expressly stated for a transaction, the business or seller—not Everest Local—is responsible for the service or product supplied.</Section>
<Section title="2. Accounts">You must provide accurate information, protect access to your account and use Everest Local lawfully. You must not impersonate others, misuse another account, manipulate marketplace systems or use the service for fraud or abuse.</Section>
<Section title="3. Businesses and drivers">Businesses are responsible for accurate listings, pricing, availability, fulfilment, licensing and compliance with applicable consumer laws. Drivers must maintain the credentials and eligibility required for delivery access. Everest verification is an operational marketplace control, not a guarantee of performance.</Section>
<Section title="4. Quotes, bookings, orders and payments">Authoritative prices, inventory, booking state and payment state are determined by Everest Local's server-side records and payment processing. Reaching a checkout or confirmation screen does not by itself prove that payment or a booking has completed.</Section>
<Section title="5. Cancellations, refunds and disputes">Cancellation, refund and dispute outcomes depend on the transaction state, applicable business terms, payment-provider rules and Australian consumer-law rights. Nothing in these terms excludes rights that cannot lawfully be excluded.</Section>
<Section title="6. Delivery">Delivery is available only for eligible orders and supported areas. Delivery status is controlled by authorized marketplace workflows. A delivery failure does not automatically mean a payment has been refunded.</Section>
<Section title="7. Messaging, posts and reviews">Do not publish unlawful, abusive, fraudulent, infringing or misleading content. Reviews should reflect genuine experiences. Everest Local may moderate content and retain records reasonably required for safety, disputes and marketplace integrity.</Section>
<Section title="8. Offers, memberships and loyalty">Businesses may provide offers, recurring memberships, packages, loyalty benefits or referral rewards. Eligibility, limits, expiry and payment terms shown for the relevant program apply. Benefits do not replace rights available under applicable consumer law.</Section>
<Section title="9. Availability and integrations">Business availability, inventory and response times can change. Optional AI, calendar, email and CRM integrations do not override authoritative marketplace, payment, booking or permission state.</Section>
<Section title="10. Account closure">You can initiate deletion from Settings. Records required for transactions, payments, disputes, fraud prevention, security, audit or legal obligations may be retained for those purposes. Support can assist where automated hard deletion is unavailable.</Section>
<Section title="11. Changes and support">These terms may be updated as Everest Local changes. The effective date above identifies the current version. Support requests can be submitted through Settings → Help & support.</Section>
</ScrollView></SafeAreaView>}
function Section({title,children}:{title:string;children:string}){const{colors:c}=useAppTheme();return <View style={{marginTop:24}}><Text style={{fontSize:16,fontWeight:'900',marginBottom:7,color:c.text}}>{title}</Text><Text style={{fontSize:14,lineHeight:22,color:c.textSecondary}}>{children}</Text></View>}
