import { Ionicons } from '@expo/vector-icons';
import { Pressable,Text,View } from 'react-native';
import { useAppTheme } from '@/lib/theme';
import {useExperience} from '@/lib/experience';

export function SettingsRow({icon,title,detail,onPress,danger=false,disabled=false}:{icon:keyof typeof Ionicons.glyphMap;title:string;detail?:string;onPress:()=>void;danger?:boolean;disabled?:boolean}){
 const {colors}=useAppTheme();const {tokens:t,mode}=useExperience();return <Pressable accessibilityRole="button" accessibilityLabel={detail?`${title}. ${detail}`:title} disabled={disabled} onPress={onPress} style={({pressed})=>({minHeight:Math.max(58,t.controls.minHeight+10),paddingHorizontal:t.spacing.card,paddingVertical:mode==='CLASSIC'?13:10,flexDirection:'row',alignItems:'center',gap:t.spacing.controlGap+2,opacity:disabled?.5:pressed?.65:1})}><View style={{width:mode==='CLASSIC'?38:32,height:mode==='CLASSIC'?38:32,borderRadius:t.shape.small,backgroundColor:colors.soft,alignItems:'center',justifyContent:'center'}}><Ionicons name={icon} size={mode==='CLASSIC'?19:17} color={danger?colors.danger:colors.text}/></View><View style={{flex:1}}><Text style={{fontSize:mode==='CLASSIC'?16:14,fontWeight:'700',color:danger?colors.danger:colors.text}}>{title}</Text>{detail?<Text numberOfLines={mode==='CLASSIC'?3:2} style={{fontSize:t.typography.caption+1,lineHeight:(t.typography.caption+1)*1.45,color:colors.muted,marginTop:2}}>{detail}</Text>:null}</View><Ionicons name="chevron-forward" size={mode==='CLASSIC'?20:17} color={colors.muted}/></Pressable>
}
export function SettingsGroup({title,children}:{title:string;children:React.ReactNode}){const {colors}=useAppTheme();const {tokens:t}=useExperience();return <View style={{marginTop:t.spacing.section}}><Text style={{fontSize:t.typography.caption,fontWeight:'900',letterSpacing:1.3,color:colors.muted,marginBottom:8,marginLeft:4}}>{title}</Text><View style={{backgroundColor:colors.surface,borderRadius:t.shape.medium,borderWidth:t.surfaces.borderWidth,borderColor:colors.border,overflow:'hidden'}}>{children}</View></View>}
