import { userFacingError } from './errors';
import { supabase,requireSupabaseConfig } from './supabase';
import type { Product } from './types';
import { getWorkspaceContext } from './workspace';
export interface BusinessSummary{id:string;name:string;slug:string;description:string|null;logo_url:string|null;status:string;verification_status:string;suburb:string|null;city:string|null;state:string|null;abn?:string|null;}
export async function createProduct(input:{businessId:string;name:string;description:string;categoryId?:string;price:number;salePrice?:number;sku?:string;deliveryEligible:boolean;pickupAvailable:boolean;stock:number}){requireSupabaseConfig();if(!Number.isFinite(input.price)||input.price<0)throw new Error('Invalid price.');if(input.salePrice!==undefined&&(!Number.isFinite(input.salePrice)||input.salePrice<0||input.salePrice>input.price))throw new Error('Sale price must be between $0 and the regular price.');if(!Number.isInteger(input.stock)||input.stock<0)throw new Error('Invalid inventory quantity.');const {data,error}=await supabase.rpc('create_product',{p_business_id:input.businessId,p_name:input.name.trim(),p_description:input.description.trim(),p_category_id:input.categoryId??null,p_price:input.price,p_sale_price:input.salePrice??null,p_sku:input.sku?.trim()||null,p_delivery_eligible:input.deliveryEligible,p_pickup_available:input.pickupAvailable,p_stock:input.stock});if(error)throw new Error(userFacingError(error,'Product could not be created. Please try again.'));return data as string;}
export async function updateProduct(input:{productId:string;name:string;description:string;categoryId?:string;price:number;salePrice?:number;sku?:string;deliveryEligible:boolean;pickupAvailable:boolean}){requireSupabaseConfig();if(!Number.isFinite(input.price)||input.price<0)throw new Error('Invalid price.');if(input.salePrice!==undefined&&(!Number.isFinite(input.salePrice)||input.salePrice<0||input.salePrice>input.price))throw new Error('Sale price must be between $0 and the regular price.');const {data,error}=await supabase.rpc('update_product',{p_product_id:input.productId,p_name:input.name.trim(),p_description:input.description.trim(),p_category_id:input.categoryId??null,p_price:input.price,p_sale_price:input.salePrice??null,p_sku:input.sku?.trim()||null,p_delivery_eligible:input.deliveryEligible,p_pickup_available:input.pickupAvailable});if(error)throw new Error(userFacingError(error,'Product could not be updated. Please try again.'));return Boolean(data);}
export async function setProductStatus(productId:string,status:Product['status']){requireSupabaseConfig();const {data,error}=await supabase.rpc('set_product_status',{p_product_id:productId,p_status:status});if(error)throw new Error(userFacingError(error,'Product status could not be changed. Please try again.'));return Boolean(data);}
export async function adjustInventory(productId:string,delta:number){requireSupabaseConfig();if(!Number.isInteger(delta))throw new Error('Inventory adjustment must be a whole number.');const {data,error}=await supabase.rpc('adjust_inventory',{p_product_id:productId,p_delta:delta});if(error)throw new Error(userFacingError(error,'Inventory could not be updated. Please try again.'));return Boolean(data);}
export async function myBusiness():Promise<BusinessSummary|null>{requireSupabaseConfig();const context=await getWorkspaceContext();const businessId=context.active_business_id??context.businesses[0]?.id??null;if(!businessId)return null;const {data,error}=await supabase.from('businesses').select('id,name,slug,description,logo_url,status,verification_status,suburb,city,state,abn').eq('id',businessId).maybeSingle();if(error)throw new Error(userFacingError(error,'Business details could not be loaded. Please try again.'));return data as BusinessSummary|null;}
export { submitBusinessVerification } from './business-verification';
