import { supabase,requireSupabaseConfig } from './supabase';
import type { Product } from './types';
export interface BusinessSummary{id:string;name:string;slug:string;description:string|null;status:string;verification_status:string;suburb:string|null;city:string|null;state:string|null;abn?:string|null;}
export async function createProduct(input:{businessId:string;name:string;description:string;categoryId?:string;price:number;salePrice?:number;sku?:string;deliveryEligible:boolean;pickupAvailable:boolean;stock:number}){requireSupabaseConfig();if(!Number.isFinite(input.price)||input.price<0)throw new Error('Invalid price.');if(input.salePrice!==undefined&&(!Number.isFinite(input.salePrice)||input.salePrice<0||input.salePrice>input.price))throw new Error('Sale price must be between $0 and the regular price.');if(!Number.isInteger(input.stock)||input.stock<0)throw new Error('Invalid inventory quantity.');const {data,error}=await supabase.rpc('create_product',{p_business_id:input.businessId,p_name:input.name.trim(),p_description:input.description.trim(),p_category_id:input.categoryId??null,p_price:input.price,p_sale_price:input.salePrice??null,p_sku:input.sku?.trim()||null,p_delivery_eligible:input.deliveryEligible,p_pickup_available:input.pickupAvailable,p_stock:input.stock});if(error)throw new Error(error.message);return data as string;}
export async function updateProduct(input:{productId:string;name:string;description:string;categoryId?:string;price:number;salePrice?:number;sku?:string;deliveryEligible:boolean;pickupAvailable:boolean}){requireSupabaseConfig();if(!Number.isFinite(input.price)||input.price<0)throw new Error('Invalid price.');if(input.salePrice!==undefined&&(!Number.isFinite(input.salePrice)||input.salePrice<0||input.salePrice>input.price))throw new Error('Sale price must be between $0 and the regular price.');const {data,error}=await supabase.rpc('update_product',{p_product_id:input.productId,p_name:input.name.trim(),p_description:input.description.trim(),p_category_id:input.categoryId??null,p_price:input.price,p_sale_price:input.salePrice??null,p_sku:input.sku?.trim()||null,p_delivery_eligible:input.deliveryEligible,p_pickup_available:input.pickupAvailable});if(error)throw new Error(error.message);return Boolean(data);}
export async function setProductStatus(productId:string,status:Product['status']){requireSupabaseConfig();const {data,error}=await supabase.rpc('set_product_status',{p_product_id:productId,p_status:status});if(error)throw new Error(error.message);return Boolean(data);}
export async function adjustInventory(productId:string,delta:number){requireSupabaseConfig();if(!Number.isInteger(delta))throw new Error('Inventory adjustment must be a whole number.');const {data,error}=await supabase.rpc('adjust_inventory',{p_product_id:productId,p_delta:delta});if(error)throw new Error(error.message);return Boolean(data);}
export async function myBusiness():Promise<BusinessSummary|null>{requireSupabaseConfig();const {data:{user}}=await supabase.auth.getUser();if(!user)return null;const {data,error}=await supabase.from('business_members').select('business_id,businesses(id,name,slug,description,status,verification_status,suburb,city,state,abn)').eq('user_id',user.id).eq('member_role','OWNER').limit(1).maybeSingle();if(error)throw new Error(error.message);if(!data)return null;const related=data.businesses as unknown as BusinessSummary[]|BusinessSummary|null;return Array.isArray(related)?related[0]??null:related;}
export async function submitBusinessVerification(businessId:string,abn:string){requireSupabaseConfig();const {data,error}=await supabase.rpc('submit_business_verification',{p_business_id:businessId,p_abn:abn.trim()||null,p_documents:[]});if(error)throw new Error(error.message);return data as string;}
