import { supabase,requireSupabaseConfig } from './supabase';
import type { Order } from './types';
type CartProduct={id:string;name:string;price:number;sale_price:number|null;status:string;business_id:string;delivery_eligible:boolean;pickup_available:boolean};export interface CartItem{id:string;quantity:number;product_id:string;products:CartProduct|null};
export type ProductDeliveryMethod='PICKUP'|'EVEREST_DELIVERY'|'SAME_DAY';
type CheckoutResult={orderId:string;orderNumber:string;total:number;checkoutUrl:string|null;reused:boolean};
function commerceError(fallback:string){return new Error(fallback);}
function validStripeCheckoutUrl(value:unknown):value is string{if(typeof value!=='string'||!value)return false;try{const url=new URL(value);return url.protocol==='https:'&&url.hostname==='checkout.stripe.com'&&url.username===''&&url.password==='';}catch{return false;}}
function parseCheckoutResult(value:unknown):CheckoutResult{if(!value||typeof value!=='object')throw commerceError('Checkout returned an invalid response. Please try again.');const result=value as Record<string,unknown>;if(typeof result.orderId!=='string'||!result.orderId||typeof result.orderNumber!=='string'||!result.orderNumber||typeof result.total!=='number'||!Number.isFinite(result.total)||result.total<0||typeof result.reused!=='boolean'||(result.checkoutUrl!==null&&!validStripeCheckoutUrl(result.checkoutUrl)))throw commerceError('Checkout returned an invalid response. Please try again.');return {orderId:result.orderId,orderNumber:result.orderNumber,total:result.total,checkoutUrl:result.checkoutUrl as string|null,reused:result.reused};}
export async function getOrCreateCart(){requireSupabaseConfig();const {data,error}=await supabase.rpc('get_or_create_cart');if(error)throw commerceError('Unable to load your cart right now.');if(typeof data!=='string'||!data)throw commerceError('Unable to load your cart right now.');return data;}
async function setCartItem(productId:string,quantity:number){requireSupabaseConfig();if(!productId||!Number.isInteger(quantity)||quantity<0||quantity>99)throw commerceError('Invalid cart quantity.');const {error}=await supabase.rpc('set_my_cart_item',{p_product_id:productId,p_quantity:quantity});if(error)throw commerceError(quantity===0?'Unable to remove this item from your cart right now.':'Unable to update your cart. Check availability and try again.');}
export async function addToCart(productId:string,quantity=1){if(!Number.isInteger(quantity)||quantity<1)throw commerceError('Invalid quantity.');await setCartItem(productId,quantity);return true;}
export async function getCart():Promise<CartItem[]>{const cartId=await getOrCreateCart();const {data,error}=await supabase.from('cart_items').select('id,quantity,product_id,products(id,name,price,sale_price,status,business_id,delivery_eligible,pickup_available)').eq('cart_id',cartId);if(error)throw commerceError('Unable to load your cart right now.');return (data??[]).map(item=>{const raw=item.products as unknown as CartProduct[]|CartProduct|null;return {...item,products:Array.isArray(raw)?raw[0]??null:raw} as CartItem;});}
export async function removeFromCart(productId:string){await setCartItem(productId,0);}
export async function checkout(idempotencyKey:string,deliveryMethod:ProductDeliveryMethod='PICKUP',deliveryAddress:string|null=null):Promise<CheckoutResult>{requireSupabaseConfig();if(idempotencyKey.length<16)throw new Error('Invalid checkout idempotency key.');const address=deliveryAddress?.trim()||null;if(deliveryMethod!=='PICKUP'&&(!address||address.length<5))throw new Error('Enter a valid delivery address.');const {data,error}=await supabase.functions.invoke('checkout',{body:{delivery_method:deliveryMethod,delivery_address:address?{address_line:address}:null},headers:{'Idempotency-Key':idempotencyKey}});if(error)throw commerceError('Checkout is temporarily unavailable. Please try again.');if(data?.error)throw commerceError('Checkout could not be completed. Please review your cart and try again.');return parseCheckoutResult(data);}
export async function myOrders():Promise<Order[]>{const {data:{user}}=await supabase.auth.getUser();if(!user)return[];const {data,error}=await supabase.from('orders').select('id,order_number,status,payment_status,total,created_at,delivery_method').eq('customer_id',user.id).order('created_at',{ascending:false});if(error)throw commerceError('Unable to load your orders right now.');return (data??[]) as Order[];}
