import { supabase,requireSupabaseConfig } from './supabase';
import type { Order } from './types';
type CartProduct={id:string;name:string;price:number;sale_price:number|null;status:string;business_id:string;delivery_eligible:boolean;pickup_available:boolean};export interface CartItem{id:string;quantity:number;product_id:string;products:CartProduct|null};
export type ProductDeliveryMethod='PICKUP'|'EVEREST_DELIVERY'|'SAME_DAY';
export async function getOrCreateCart(){requireSupabaseConfig();const {data,error}=await supabase.rpc('get_or_create_cart');if(error)throw new Error(error.message);if(typeof data!=='string'||!data)throw new Error('Unable to create cart.');return data;}
export async function addToCart(productId:string,quantity=1){if(!Number.isInteger(quantity)||quantity<1)throw new Error('Invalid quantity');const cartId=await getOrCreateCart();const {data,error}=await supabase.from('cart_items').upsert({cart_id:cartId,product_id:productId,quantity},{onConflict:'cart_id,product_id'}).select().single();if(error)throw new Error(error.message);return data;}
export async function getCart():Promise<CartItem[]>{const cartId=await getOrCreateCart();const {data,error}=await supabase.from('cart_items').select('id,quantity,product_id,products(id,name,price,sale_price,status,business_id,delivery_eligible,pickup_available)').eq('cart_id',cartId);if(error)throw new Error(error.message);return (data??[]).map(item=>{const raw=item.products as unknown as CartProduct[]|CartProduct|null;return {...item,products:Array.isArray(raw)?raw[0]??null:raw} as CartItem;});}
export async function removeFromCart(itemId:string){const {error}=await supabase.from('cart_items').delete().eq('id',itemId);if(error)throw new Error(error.message);}
export async function checkout(idempotencyKey:string,deliveryMethod:ProductDeliveryMethod='PICKUP',deliveryAddress:string|null=null){requireSupabaseConfig();if(idempotencyKey.length<16)throw new Error('Invalid checkout idempotency key.');const address=deliveryAddress?.trim()||null;if(deliveryMethod!=='PICKUP'&&(!address||address.length<5))throw new Error('Enter a valid delivery address.');const {data,error}=await supabase.functions.invoke('checkout',{body:{delivery_method:deliveryMethod,delivery_address:address?{address_line:address}:null},headers:{'Idempotency-Key':idempotencyKey}});if(error)throw new Error(error.message);if(data?.error)throw new Error(data.error);return data as {orderId:string;orderNumber:string;total:number;checkoutUrl:string|null;reused:boolean};}
export async function myOrders():Promise<Order[]>{const {data:{user}}=await supabase.auth.getUser();if(!user)return[];const {data,error}=await supabase.from('orders').select('id,order_number,status,payment_status,total,created_at,delivery_method').eq('customer_id',user.id).order('created_at',{ascending:false});if(error)throw new Error(error.message);return (data??[]) as Order[];}
