import { requireSupabaseConfig,supabase } from './supabase';

export type ConnectionState='SELF'|'NONE'|'OUTGOING'|'INCOMING'|'CONNECTED'|'BLOCKED'|'UNAVAILABLE';
export type SocialPreferences={
 profile_visibility:'PUBLIC'|'LIMITED'|'PRIVATE';
 connection_requests:'EVERYONE'|'MUTUALS'|'NOBODY';
 message_requests:'EVERYONE'|'CONNECTIONS'|'NOBODY';
 connection_list_visibility:'EVERYONE'|'CONNECTIONS'|'ONLY_ME';
 search_visible:boolean;
 show_location:boolean;
};
export type PublicUserProfile={id:string;display_name:string|null;username:string|null;avatar_url:string|null;bio:string|null;suburb:string|null;joined_at:string|null;connection_count:number;mutual_count:number;connection_state:ConnectionState};
export type ConnectionPerson={id:string;display_name:string|null;avatar_url:string|null;bio:string|null;mutual_count:number};
export type ConnectionRequest={id:string;requester_id:string;display_name:string|null;avatar_url:string|null;bio:string|null;mutual_count:number;created_at:string};
export type PersonalConversation={id:string;other_user_id:string;display_name:string|null;avatar_url:string|null;status:'REQUEST'|'ACTIVE'|'DECLINED';initiated_by:string;updated_at:string;latest_message:string|null;latest_message_at:string|null;unread_count:number};
export type MessageReaction={reaction:'❤️'|'👍'|'😂'|'😮'|'😢'|'🔥';count:number;mine:boolean};
export type PersonalMessage={id:string;conversation_id:string;sender_id:string;body:string;read_at:string|null;created_at:string;deleted_for_everyone:boolean;edited_at:string|null;reply_to_message_id:string|null;reply_sender_id:string|null;reply_preview:string|null;reactions:MessageReaction[];sending?:boolean;failed?:boolean};

export async function getPublicUserProfile(userId:string):Promise<PublicUserProfile|null>{requireSupabaseConfig();const {data,error}=await supabase.rpc('get_public_user_profile',{p_user:userId});if(error)throw new Error(error.message);return data as PublicUserProfile|null}
export async function getConnectionState(userId:string):Promise<ConnectionState>{requireSupabaseConfig();const {data,error}=await supabase.rpc('get_connection_state',{p_other:userId});if(error)throw new Error(error.message);return data as ConnectionState}
export async function sendConnectionRequest(userId:string){requireSupabaseConfig();const {data,error}=await supabase.rpc('send_connection_request',{p_recipient:userId});if(error)throw new Error(error.message);return data as string}
export async function cancelConnectionRequest(userId:string){requireSupabaseConfig();const {data,error}=await supabase.rpc('cancel_connection_request',{p_recipient:userId});if(error)throw new Error(error.message);return Boolean(data)}
export async function respondConnectionRequest(requestId:string,accept:boolean){requireSupabaseConfig();const {data,error}=await supabase.rpc('respond_connection_request',{p_request:requestId,p_accept:accept});if(error)throw new Error(error.message);return Boolean(data)}
export async function removeConnection(userId:string){requireSupabaseConfig();const {data,error}=await supabase.rpc('remove_connection',{p_other:userId});if(error)throw new Error(error.message);return Boolean(data)}
export async function blockUser(userId:string){requireSupabaseConfig();const {data,error}=await supabase.rpc('block_user',{p_other:userId});if(error)throw new Error(error.message);return Boolean(data)}
export async function reportUser(userId:string,reason:'SPAM'|'HARASSMENT'|'IMPERSONATION'|'INAPPROPRIATE'|'OTHER'='OTHER',details?:string){requireSupabaseConfig();const {data,error}=await supabase.rpc('report_user',{p_other:userId,p_reason:reason,p_details:details?.trim()||null});if(error)throw new Error(error.message);return data as string}
export async function unblockUser(userId:string){requireSupabaseConfig();const {data,error}=await supabase.rpc('unblock_user',{p_other:userId});if(error)throw new Error(error.message);return Boolean(data)}
export async function listConnections(userId?:string):Promise<ConnectionPerson[]>{requireSupabaseConfig();const {data,error}=await supabase.rpc('list_connections',{p_user:userId??null});if(error)throw new Error(error.message);return (data??[]) as ConnectionPerson[]}
export async function listConnectionRequests():Promise<ConnectionRequest[]>{requireSupabaseConfig();const {data,error}=await supabase.rpc('list_connection_requests');if(error)throw new Error(error.message);return (data??[]) as ConnectionRequest[]}
export async function getSocialPreferences():Promise<SocialPreferences>{requireSupabaseConfig();const {data,error}=await supabase.rpc('get_social_preferences');if(error)throw new Error(error.message);return data as SocialPreferences}
export async function setSocialPreferences(value:SocialPreferences){requireSupabaseConfig();const {data,error}=await supabase.rpc('set_social_preferences',{p_profile_visibility:value.profile_visibility,p_connection_requests:value.connection_requests,p_message_requests:value.message_requests,p_connection_list_visibility:value.connection_list_visibility,p_search_visible:value.search_visible,p_show_location:value.show_location});if(error)throw new Error(error.message);return Boolean(data)}
export async function sendPersonalMessageDetailed(recipientId:string,body:string,replyTo:string|null=null){requireSupabaseConfig();const {data,error}=await supabase.rpc('send_personal_message_v2',{p_recipient:recipientId,p_body:body,p_reply_to:replyTo});if(error)throw new Error('Couldn’t send message. Try again.');return data as {conversation_id:string;message_id:string;created_at:string;status:'REQUEST'|'ACTIVE'}}
export async function sendPersonalMessage(recipientId:string,body:string){const result=await sendPersonalMessageDetailed(recipientId,body,null);return result.conversation_id}
export async function respondMessageRequest(conversationId:string,accept:boolean){requireSupabaseConfig();const {data,error}=await supabase.rpc('respond_message_request',{p_conversation:conversationId,p_accept:accept});if(error)throw new Error(error.message);return Boolean(data)}
export async function listPersonalConversations(requests=false):Promise<PersonalConversation[]>{requireSupabaseConfig();const {data,error}=await supabase.rpc('list_personal_conversations_v2',{p_requests:requests});if(error)throw new Error('Messages could not be loaded.');return (data??[]).map((row:Record<string,unknown>)=>({...row,unread_count:Number(row.unread_count??0)})) as PersonalConversation[]}
export async function hidePersonalConversation(conversationId:string){requireSupabaseConfig();const {data,error}=await supabase.rpc('hide_personal_conversation',{p_conversation:conversationId});if(error)throw new Error('Conversation could not be removed.');return Boolean(data)}
export async function personalMessages(conversationId:string,before:string|null=null,limit=40):Promise<PersonalMessage[]>{requireSupabaseConfig();const {data,error}=await supabase.rpc('list_personal_messages_v2',{p_conversation:conversationId,p_before:before,p_limit:limit});if(error)throw new Error('Conversation could not be loaded.');return (data??[]).map((row:Record<string,unknown>)=>({...row,reactions:Array.isArray(row.reactions)?row.reactions:[]})) as PersonalMessage[]}
export async function deletePersonalMessageForMe(messageId:string){requireSupabaseConfig();const {data,error}=await supabase.rpc('delete_personal_message_for_me',{p_message:messageId});if(error)throw new Error(error.message);return Boolean(data)}
export async function deletePersonalMessageForEveryone(messageId:string){requireSupabaseConfig();const {data,error}=await supabase.rpc('delete_personal_message_for_everyone_v2',{p_message:messageId});if(error)throw new Error('Message could not be deleted for everyone.');return data as {message_id:string;conversation_id:string;deleted_at:string;placeholder:string}}
export async function markPersonalMessageRead(messageId:string){requireSupabaseConfig();const {data,error}=await supabase.rpc('mark_personal_message_read',{p_message:messageId});if(error)throw new Error('Message could not be marked as read.');return Boolean(data)}
export async function markPersonalConversationRead(conversationId:string){requireSupabaseConfig();const {data,error}=await supabase.rpc('mark_personal_conversation_read',{p_conversation:conversationId});if(error)throw new Error('Conversation could not be marked as read.');return Number(data??0)}
export async function editPersonalMessage(messageId:string,body:string){requireSupabaseConfig();const {data,error}=await supabase.rpc('edit_personal_message',{p_message:messageId,p_body:body});if(error)throw new Error('This message could not be edited.');return data as string}
export async function togglePersonalMessageReaction(messageId:string,reaction:MessageReaction['reaction']){requireSupabaseConfig();const {data,error}=await supabase.rpc('toggle_personal_message_reaction',{p_message:messageId,p_reaction:reaction});if(error)throw new Error('Reaction could not be updated.');return Boolean(data)}
export async function publicPostsForUser(userId:string){requireSupabaseConfig();const {data,error}=await supabase.from('posts').select('id,author_id,business_id,caption,post_type,visibility,status,created_at,post_media(id,media_type,storage_path,sort_order)').eq('author_id',userId).eq('status','PUBLISHED').eq('visibility','PUBLIC').order('created_at',{ascending:false}).limit(40);if(error)throw new Error(error.message);return data??[]}
