import { supabase, requireSupabaseConfig } from './supabase';
import { userFacingError } from './errors';
import type { MarketplaceBusiness, Product, Quote, ServiceRequest, Profile } from './types';

export type SavedBusiness={id:string;name:string;suburb:string|null;city:string|null;state:string|null;verified:boolean};
export type SavedProduct={id:string;name:string;price:number;salePrice:number|null;businessName:string|null};

type SavedBusinessRow={business_id:string;businesses:Pick<MarketplaceBusiness,'id'|'name'|'suburb'|'city'|'state'|'verification_status'>|Array<Pick<MarketplaceBusiness,'id'|'name'|'suburb'|'city'|'state'|'verification_status'>>|null};
type SavedProductRow={product_id:string;products:(Pick<Product,'id'|'name'|'price'|'sale_price'> & {businesses:Pick<MarketplaceBusiness,'name'>|Array<Pick<MarketplaceBusiness,'name'>>|null})|Array<Pick<Product,'id'|'name'|'price'|'sale_price'> & {businesses:Pick<MarketplaceBusiness,'name'>|Array<Pick<MarketplaceBusiness,'name'>>|null}>|null};

function safeBackendError(error:{message:string},fallback:string){return new Error(userFacingError(new Error(error.message),fallback));}

export async function currentUser(){requireSupabaseConfig();const {data,error}=await supabase.auth.getUser();if(error)throw safeBackendError(error,'Your session could not be verified. Please sign in again.');return data.user;}
export async function getProfile():Promise<Profile|null>{const user=await currentUser();if(!user)return null;const {data,error}=await supabase.from('profiles').select('*').eq('id',user.id).single();if(error)throw safeBackendError(error,'Your profile could not be loaded. Please try again.');return data as Profile;}
export async function searchBusinesses(query:string,suburb?:string):Promise<MarketplaceBusiness[]>{requireSupabaseConfig();let request=supabase.from('businesses').select('id,name,slug,description,logo_url,category_id,verification_status,suburb,city,state').eq('status','ACTIVE').eq('verification_status','VERIFIED').limit(30);if(query.trim())request=request.ilike('name',`%${query.trim()}%`);if(suburb?.trim())request=request.ilike('suburb',suburb.trim());const {data,error}=await request;if(error)throw safeBackendError(error,'Businesses could not be loaded. Please try again.');return (data??[]) as MarketplaceBusiness[];}
export async function searchProducts(query:string):Promise<Product[]>{requireSupabaseConfig();const text=query.trim();if(!text){const {data,error}=await supabase.from('products').select('id,business_id,category_id,name,slug,description,price,sale_price,status,delivery_eligible,pickup_available').eq('status','ACTIVE').limit(30);if(error)throw safeBackendError(error,'Products could not be loaded. Please try again.');return (data??[]) as Product[];}const pattern=`%${text}%`;const [byName,byDescription]=await Promise.all([supabase.from('products').select('id,business_id,category_id,name,slug,description,price,sale_price,status,delivery_eligible,pickup_available').eq('status','ACTIVE').ilike('name',pattern).limit(30),supabase.from('products').select('id,business_id,category_id,name,slug,description,price,sale_price,status,delivery_eligible,pickup_available').eq('status','ACTIVE').ilike('description',pattern).limit(30)]);if(byName.error)throw safeBackendError(byName.error,'Products could not be loaded. Please try again.');if(byDescription.error)throw safeBackendError(byDescription.error,'Products could not be loaded. Please try again.');const merged=new Map<string,Product>();for(const item of [...(byName.data??[]),...(byDescription.data??[])])merged.set(item.id,item as Product);return [...merged.values()].slice(0,30);}
export async function getSavedItems(){const user=await currentUser();if(!user)return{businesses:[] as SavedBusiness[],products:[] as SavedProduct[]};const [businessResult,productResult]=await Promise.all([supabase.from('saved_businesses').select('business_id,businesses(id,name,suburb,city,state,verification_status)').eq('customer_id',user.id).order('created_at',{ascending:false}),supabase.from('saved_products').select('product_id,products(id,name,price,sale_price,businesses(name))').eq('customer_id',user.id).order('created_at',{ascending:false})]);if(businessResult.error)throw safeBackendError(businessResult.error,'Saved businesses could not be loaded. Please try again.');if(productResult.error)throw safeBackendError(productResult.error,'Saved products could not be loaded. Please try again.');const businesses=((businessResult.data??[]) as SavedBusinessRow[]).map(row=>{const item=Array.isArray(row.businesses)?row.businesses[0]:row.businesses;return{id:item?.id??row.business_id,name:item?.name??'Business',suburb:item?.suburb??null,city:item?.city??null,state:item?.state??null,verified:item?.verification_status==='VERIFIED'}}).filter(item=>item.id);const products=((productResult.data??[]) as SavedProductRow[]).map(row=>{const item=Array.isArray(row.products)?row.products[0]:row.products;const business=Array.isArray(item?.businesses)?item?.businesses[0]:item?.businesses;return{id:item?.id??row.product_id,name:item?.name??'Product',price:Number(item?.price??0),salePrice:item?.sale_price==null?null:Number(item.sale_price),businessName:business?.name??null}}).filter(item=>item.id);return{businesses,products};}
export async function isBusinessSaved(businessId:string){const user=await currentUser();if(!user)return false;const {data,error}=await supabase.from('saved_businesses').select('business_id').eq('customer_id',user.id).eq('business_id',businessId).maybeSingle();if(error)throw safeBackendError(error,'Saved status could not be loaded. Please try again.');return !!data;}
export async function isProductSaved(productId:string){const user=await currentUser();if(!user)return false;const {data,error}=await supabase.from('saved_products').select('product_id').eq('customer_id',user.id).eq('product_id',productId).maybeSingle();if(error)throw safeBackendError(error,'Saved status could not be loaded. Please try again.');return !!data;}
export async function toggleSavedBusiness(businessId:string,saved:boolean){const user=await currentUser();if(!user)throw new Error('Please sign in to save businesses.');if(!businessId.trim())throw new Error('Business reference is required.');const result=saved?await supabase.from('saved_businesses').upsert({customer_id:user.id,business_id:businessId},{onConflict:'customer_id,business_id'}):await supabase.from('saved_businesses').delete().eq('customer_id',user.id).eq('business_id',businessId);if(result.error)throw safeBackendError(result.error,'Saved businesses could not be updated. Please try again.');}
export async function toggleSavedProduct(productId:string,saved:boolean){const user=await currentUser();if(!user)throw new Error('Please sign in to save products.');if(!productId.trim())throw new Error('Product reference is required.');const result=saved?await supabase.from('saved_products').upsert({customer_id:user.id,product_id:productId},{onConflict:'customer_id,product_id'}):await supabase.from('saved_products').delete().eq('customer_id',user.id).eq('product_id',productId);if(result.error)throw safeBackendError(result.error,'Saved products could not be updated. Please try again.');}
export async function createServiceRequest(input:{categoryId?:string;serviceId?:string;description:string;suburb?:string;city?:string;state?:string;preferredDate?:string;preferredTime?:string;budget?:number;mediaUrls?:string[];deliveryMode?:'LOCAL'|'REMOTE'|'BOTH'}){requireSupabaseConfig();const description=input.description.trim();if(description.length<5||description.length>5000)throw new Error('Service description must be between 5 and 5000 characters.');if(input.budget!==undefined&&(!Number.isFinite(input.budget)||input.budget<0))throw new Error('Budget must be a valid non-negative amount.');const {data,error}=await supabase.rpc('create_service_request',{p_category_id:input.categoryId??null,p_service_id:input.serviceId??null,p_description:description,p_suburb:input.suburb?.trim()||null,p_city:input.city?.trim()||null,p_state:input.state?.trim()||null,p_preferred_date:input.preferredDate??null,p_preferred_time:input.preferredTime??null,p_budget:input.budget??null,p_media_urls:input.mediaUrls??[],p_delivery_mode:input.deliveryMode??null});if(error)throw safeBackendError(error,'Your service request could not be created. Please try again.');return data as string;}
export async function myRequests():Promise<ServiceRequest[]>{const user=await currentUser();if(!user)return[];const {data,error}=await supabase.from('service_requests').select('*').eq('customer_id',user.id).order('created_at',{ascending:false});if(error)throw safeBackendError(error,'Your service requests could not be loaded. Please try again.');return (data??[]) as ServiceRequest[];}
export async function myQuotes(requestId?:string):Promise<Quote[]>{const user=await currentUser();if(!user)return[];let query=supabase.from('quotes').select('*').eq('customer_id',user.id).order('created_at',{ascending:false});if(requestId?.trim())query=query.eq('request_id',requestId.trim());const {data,error}=await query;if(error)throw safeBackendError(error,'Your quotes could not be loaded. Please try again.');return (data??[]) as Quote[];}
export async function acceptQuote(quoteId:string){requireSupabaseConfig();if(!quoteId.trim())throw new Error('Quote reference is required.');const {data,error}=await supabase.rpc('accept_quote',{p_quote_id:quoteId});if(error)throw safeBackendError(error,'This quote could not be accepted. Please refresh and try again.');return data as string;}
export async function updateBookingStatus(bookingId:string,nextStatus:'REQUESTED'|'PENDING_PAYMENT'|'CONFIRMED'|'UPCOMING'|'IN_PROGRESS'|'COMPLETED'|'CANCELLED'|'DISPUTED'){requireSupabaseConfig();const {data,error}=await supabase.rpc('update_booking_status',{p_booking_id:bookingId,p_next:nextStatus});if(error)throw safeBackendError(error,'The booking could not be updated. Please refresh and try again.');return Boolean(data);}
export async function getOrCreateBookingConversation(input:{requestId:string;businessId:string;bookingId:string}){requireSupabaseConfig();if(!input.requestId.trim()||!input.businessId.trim()||!input.bookingId.trim())throw new Error('Booking conversation references are required.');const {data,error}=await supabase.rpc('get_or_create_conversation',{p_request_id:input.requestId,p_business_id:input.businessId,p_quote_id:null,p_booking_id:input.bookingId});if(error)throw safeBackendError(error,'Conversation could not be opened.');if(typeof data!=='string'||!data)throw new Error('Conversation could not be opened.');return data;}
