import { Platform } from 'react-native';
import { requireSupabaseConfig, supabase } from './supabase';

export type DispatchOffer={id:string;job_id:string;status:string;expires_at:string;eta_seconds:number;expected_job_value:number|null;estimated_duration_minutes:number|null};
export type DispatchJob={id:string;request_id:string;status:string;claimed_provider_id:string|null;created_at:string;updated_at:string};
export type CapabilityService={id:string;name:string;enabled:boolean};
export type DispatchAssignment={id:string;job_id:string;service_request_id:string;booking_id:string;scheduled_start_at:string|null;scheduled_end_at:string|null;started_at:string|null;completed_at:string|null;created_at:string};
export type SharedLocation={latitude:number;longitude:number;accuracy:number|null;recordedAt:string};

export async function captureCurrentWebLocation():Promise<SharedLocation>{
 if(Platform.OS!=='web'||typeof navigator==='undefined'||!navigator.geolocation)throw new Error('Location sharing is currently available in the web app.');
 const position=await new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:0}));
 return{latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy:Number.isFinite(position.coords.accuracy)?position.coords.accuracy:null,recordedAt:new Date(position.timestamp).toISOString()};
}

export async function setServiceRequestLocation(requestId:string,location:SharedLocation){requireSupabaseConfig();const {error}=await supabase.rpc('set_service_request_location',{p_request_id:requestId,p_latitude:location.latitude,p_longitude:location.longitude});if(error)throw new Error(error.message);}

export async function startServiceDispatch(requestId:string){requireSupabaseConfig();const {data,error}=await supabase.rpc('start_service_dispatch',{p_request_id:requestId});if(error)throw new Error(error.message);if(typeof data!=='string')throw new Error('Dispatch did not return a job reference.');return data;}
export async function getMyDispatchJobs(requestIds?:string[]){requireSupabaseConfig();if(requestIds&&requestIds.length===0)return[];let query=supabase.from('service_dispatch_jobs').select('id,request_id,status,claimed_provider_id,created_at,updated_at').order('created_at',{ascending:false});if(requestIds)query=query.in('request_id',requestIds);const {data,error}=await query;if(error)throw new Error(error.message);return (data??[]) as DispatchJob[];}
export async function getMyDispatchOffers(){requireSupabaseConfig();const {data,error}=await supabase.from('service_dispatch_offers').select('id,job_id,status,expires_at,eta_seconds,expected_job_value,estimated_duration_minutes').eq('status','OFFERED').order('offered_at',{ascending:false});if(error)throw new Error(error.message);return (data??[]) as DispatchOffer[];}
export async function getMyDispatchAssignments(){requireSupabaseConfig();const {data,error}=await supabase.from('service_dispatch_assignments').select('id,job_id,service_request_id,booking_id,scheduled_start_at,scheduled_end_at,started_at,completed_at,created_at').is('completed_at',null).order('created_at',{ascending:false});if(error)throw new Error(error.message);return (data??[]) as DispatchAssignment[];}
export async function respondToDispatchOffer(offerId:string,response:'ACCEPT'|'DECLINE'){requireSupabaseConfig();const {data,error}=await supabase.rpc('respond_service_dispatch_offer',{p_offer_id:offerId,p_response:response});if(error)throw new Error(error.message);return data as {ok:boolean;code:string;job_id?:string;assignment_id?:string};}
export async function updateDispatchAssignment(assignmentId:string,action:'START'|'COMPLETE'){requireSupabaseConfig();const {data,error}=await supabase.rpc('update_my_service_dispatch_assignment',{p_assignment_id:assignmentId,p_action:action});if(error)throw new Error(error.message);return data as {ok:boolean;code:string};}
export async function getCapabilityServices(){requireSupabaseConfig();const {data:{user}}=await supabase.auth.getUser();if(!user)return[];const {data:members,error:memberError}=await supabase.from('business_members').select('business_id,businesses(status,verification_status)').eq('user_id',user.id);if(memberError)throw new Error(memberError.message);const businessIds=(members??[]).filter(row=>{const business=Array.isArray(row.businesses)?row.businesses[0]:row.businesses;return business?.status==='ACTIVE'&&business?.verification_status==='VERIFIED'}).map(row=>row.business_id);if(!businessIds.length)return[];const [servicesResult,capabilityResult]=await Promise.all([supabase.from('services').select('id,name').in('business_id',businessIds).eq('active',true).order('name'),supabase.from('service_provider_capabilities').select('service_id').eq('provider_id',user.id)]);if(servicesResult.error)throw new Error(servicesResult.error.message);if(capabilityResult.error)throw new Error(capabilityResult.error.message);const enabled=new Set((capabilityResult.data??[]).map(row=>row.service_id));return (servicesResult.data??[]).map(row=>({id:row.id,name:row.name,enabled:enabled.has(row.id)})) as CapabilityService[];}
export async function setCapability(serviceId:string,enabled:boolean){requireSupabaseConfig();const {error}=await supabase.rpc('set_service_provider_capability',{p_service_id:serviceId,p_enabled:enabled});if(error)throw new Error(error.message);}
export async function updateCurrentProviderLocation(){requireSupabaseConfig();const location=await captureCurrentWebLocation();const {error}=await supabase.rpc('update_provider_location',{p_latitude:location.latitude,p_longitude:location.longitude,p_accuracy_m:location.accuracy,p_recorded_at:location.recordedAt});if(error)throw new Error(error.message);return location.accuracy;}
