export type AppRole='CUSTOMER'|'BUSINESS'|'ADMIN'|'DELIVERY_DRIVER';
export type VerificationStatus='UNVERIFIED'|'PENDING'|'VERIFIED'|'REJECTED'|'SUSPENDED';
export type DriverVerificationStatus='DRAFT'|'SUBMITTED'|'UNDER_REVIEW'|'MORE_INFORMATION_REQUIRED'|'APPROVED'|'REJECTED'|'SUSPENDED'|'EXPIRED';
export type RequestStatus='OPEN'|'MATCHING'|'QUOTING'|'BOOKED'|'COMPLETED'|'CANCELLED';
export type QuoteStatus='DRAFT'|'SENT'|'VIEWED'|'ACCEPTED'|'DECLINED'|'EXPIRED'|'CANCELLED';
export type BookingStatus='REQUESTED'|'PENDING_PAYMENT'|'CONFIRMED'|'UPCOMING'|'IN_PROGRESS'|'COMPLETED'|'CANCELLED'|'DISPUTED';
export type ProductStatus='DRAFT'|'ACTIVE'|'OUT_OF_STOCK'|'PAUSED'|'ARCHIVED';
export type OrderStatus='PENDING'|'PAYMENT_CONFIRMED'|'ACCEPTED'|'PREPARING'|'READY_FOR_PICKUP'|'OUT_FOR_DELIVERY'|'DELIVERED'|'COMPLETED'|'CANCELLED'|'REFUNDED';
export type PaymentStatus='PENDING'|'REQUIRES_ACTION'|'SUCCEEDED'|'FAILED'|'REFUNDED'|'PARTIALLY_REFUNDED';
export type DeliveryStatus='PENDING'|'ACCEPTED'|'PREPARING'|'READY_FOR_PICKUP'|'ASSIGNED'|'PICKED_UP'|'OUT_FOR_DELIVERY'|'DELIVERED'|'FAILED'|'CANCELLED';
export type ServiceDeliveryMode='LOCAL'|'REMOTE'|'BOTH';

export interface Profile{id:string;email?:string|null;full_name:string|null;phone:string|null;role:AppRole;suburb:string|null;city:string|null;state:string|null;country?:string|null;avatar_url:string|null;bio:string|null;created_at:string;updated_at:string;}
export interface MarketplaceBusiness{id:string;name:string;slug:string;description:string|null;logo_url:string|null;category_id:string|null;verification_status:VerificationStatus;suburb:string|null;city:string|null;state:string|null;}
export interface ServiceRequest{id:string;customer_id:string;category_id:string|null;service_id:string|null;delivery_mode:ServiceDeliveryMode;description:string;suburb:string|null;city:string|null;state:string|null;latitude?:number|null;longitude?:number|null;location_source?:string|null;location_accuracy_m?:number|null;location_confirmed?:boolean;preferred_date:string|null;preferred_time:string|null;timing_mode?:'ASAP'|'FLEXIBLE'|'TIME_WINDOW'|'EXACT_TIME';time_window_start?:string|null;time_window_end?:string|null;budget:number|null;budget_min?:number|null;budget_max?:number|null;status:RequestStatus;created_at:string;}
export interface Quote{id:string;request_id:string;business_id:string;customer_id:string;description:string;line_items:unknown[];price:number;deposit:number;total:number;proposed_date:string|null;proposed_time:string|null;valid_until:string|null;terms:string|null;status:QuoteStatus;created_at:string;}
export interface Product{id:string;business_id:string;category_id:string|null;name:string;slug:string;description:string|null;price:number;sale_price:number|null;status:ProductStatus;delivery_eligible:boolean;pickup_available:boolean;}
export interface Conversation{id:string;business_id:string;request_id:string|null;booking_id:string|null;quote_id:string|null;created_at:string;}
export interface Opportunity{id:string;request_id:string;status:'OPEN'|'RESPONDED'|'DECLINED'|'EXPIRED';expires_at:string|null;service_requests?:Pick<ServiceRequest,'description'|'suburb'|'city'|'state'|'preferred_date'|'preferred_time'|'budget'>|null;}
export interface Order{id:string;order_number:string;status:OrderStatus;payment_status:PaymentStatus;total:number;created_at:string;delivery_method:string|null;}
