revoke execute on function public.guard_delivery_assignment_provider_conflict() from public;
revoke execute on function public.guard_service_dispatch_provider_conflict() from public;
revoke execute on function public.respond_service_dispatch_offer(uuid, text) from public;
revoke execute on function public.start_service_dispatch(uuid) from public;
revoke execute on function public.update_provider_location(numeric, numeric, numeric, timestamptz) from public;
grant execute on function public.guard_delivery_assignment_provider_conflict() to authenticated;
grant execute on function public.guard_service_dispatch_provider_conflict() to authenticated;
grant execute on function public.respond_service_dispatch_offer(uuid, text) to authenticated;
grant execute on function public.start_service_dispatch(uuid) to authenticated;
grant execute on function public.update_provider_location(numeric, numeric, numeric, timestamptz) to authenticated;
